In [1]:
import os
import random
import skimage.data
from skimage import io
import skimage.transform
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf
from tqdm import tqdm
from keras.utils import to_categorical

Using TensorFlow backend.


In [2]:
def get_train_data_batch(num, pic_dir, label_dir):
    data = [0,1,2,3,4]
    data = np.array(data)
    one_hots = to_categorical(data)
    
    train_txt = os.path.join(label_dir,"label.txt")
    count = len(open(train_txt,'r').readlines())    
    idx = np.arange(0, count)      
    np.random.shuffle(idx)                
    data_idx = idx[:num]        
    
    labels = []
    images = []
    
    for i in range(num):
        with open(train_txt,'r') as file:
            s = file.readlines()
            img = skimage.data.imread(os.path.join(pic_dir, s[data_idx[i]].split(";")[0]))
            images.append(img)
            label = int(s[data_idx[i]].split(";")[1])
            labels.append(one_hots[label])
    return np.asarray(images),np.asarray(labels)
train_label_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/00"
train_pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/00/picture"

num = 4
train_images, train_labels = get_train_data_batch(num,train_pic_dir,train_label_dir)
print(np.shape(train_images))
print(np.shape(train_labels))
print(type(train_labels))


(4, 896, 896, 3)
(4, 5)
<class 'numpy.ndarray'>


In [3]:
def load_test_data(pic_dir,label_dir):
    data = [0,1,2,3,4]
    data = np.array(data)
    one_hots = to_categorical(data)
    
    train_txt = os.path.join(label_dir,"label.txt")
    labels = []
    images = []
    with open(train_txt,'r') as f:
        all_file_name = [x.strip() for x in f.readlines()]
        for fil in all_file_name:
            img = skimage.data.imread(os.path.join(pic_dir,fil.split(";")[0]))
            images.append(img)
            label = int([fil.split(";")[-1]][0])
            labels.append(one_hots[label])
    return np.asarray(images), np.asarray(labels)

test_label_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/01"
test_pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/01/picture"

test_images, test_labels = load_test_data(test_pic_dir,test_label_dir)
print(np.shape(test_images))
print(np.shape(test_labels))
print(type(test_labels[0]))

(88, 896, 896, 3)
(88, 5)
<class 'numpy.ndarray'>


In [4]:
def get_test_batch(num, data, labels):
    idx = np.arange(0 , len(data))
    np.random.shuffle(idx)
    idx = idx[:num]
    data_shuffle = [data[i] for i in idx]
    labels_shuffle = [labels[i] for i in idx]
    return np.asarray(data_shuffle), np.asarray(labels_shuffle)

X, Y = get_test_batch(10, test_images, test_labels)
print(Y)
print(np.shape(X))
print(np.shape(Y))

[[0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]
(10, 896, 896, 3)
(10, 5)


In [5]:
with tf.name_scope("input"):
    input_image = tf.placeholder("float", [None, 896, 896, 3],name='input_image')
    y_ = tf.placeholder("float", [None, 5],name='y_') 

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape = shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding="SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")

#第0层卷积层
#参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度

W_conv0 = weight_variable([7, 7, 3, 64])
b_conv0 = bias_variable([64])

h_conv0 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv0, strides=[1,2,2,1], padding="SAME") + b_conv0)
h_pool0 = max_pool_2x2(h_conv0)   #输出变成224*224*64 [None,224,224,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度

W_conv1 = weight_variable([7, 7, 64, 64])
b_conv1 = bias_variable([64])

h_conv1 = tf.nn.relu(conv2d(h_pool0, W_conv1) + b_conv1)
# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1, strides=[1,2,2,1], padding="SAME") + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64   [None,112,112,64]

#第二层卷积层
W_conv2 = weight_variable([3, 3, 64, 192])
b_conv2 = bias_variable([192])

h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)  #输出变为56*56*192  [4,56,56,192]

#第三层卷积层
W_conv3 = weight_variable([3, 3, 192, 128])
b_conv3 = bias_variable([128])

h_conv3 = tf.nn.relu(conv2d(h_pool2, W_conv3) + b_conv3)
h_pool3 = max_pool_2x2(h_conv3)   #输出为28*28*128  [4,28,28,192]


#第四层卷积层
W_conv4 = weight_variable([3, 3, 128, 64])
b_conv4 = bias_variable([64])

h_conv4 = tf.nn.relu(conv2d(h_pool3, W_conv4) + b_conv4)
h_pool4 = max_pool_2x2(h_conv4)   #输出变为14*14*64 [None, 14,14,64]

#密集连接层1
W_fc1 = weight_variable([14*14*64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool4, [-1, 14*14*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)   #输出为[None,1024]

keep_prob = tf.placeholder("float")
#relu函数作用是求出max(h_fc1,0)
h_fc1_drop1 = tf.nn.dropout(h_fc1, keep_prob)   #输出为[None, 1024]

#密集连接层2
W_fc2 = weight_variable([1024, 512])
b_fc2 = bias_variable([512])

h_fc2 = tf.nn.relu(tf.matmul(h_fc1_drop1, W_fc2) + b_fc2)   #输出为[None,512]
#relu函数作用是求出max(h_fc1,0)
h_fc1_drop2 = tf.nn.dropout(h_fc2, keep_prob)

#输出层softmax层
W_fc3 = weight_variable([512, 5])
b_fc3 = bias_variable([5])

y_conv = tf.matmul(h_fc1_drop2, W_fc3) + b_fc3

# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
#     batch_x,batch_y = get_train_data_batch(4, train_pic_dir, train_label_dir)
#     print(batch_x.shape)
#     print(sess.run(tf.shape(y_conv),feed_dict={input_image:batch_x, y_:batch_y, keep_prob:1.0}))
    
starter_learning_rate = 0.01
steps_per_decay = 1000
decay_factor = 0.96
 
global_step = tf.Variable(0, trainable=False)
learning_rate = tf.train.exponential_decay(learning_rate = starter_learning_rate,
                                           global_step = global_step,
                                           decay_steps = steps_per_decay,
                                           decay_rate = decay_factor,
                                           staircase = True,#If `True` decay the learning rate at discrete intervals
                                           #staircase = False,change learning rate at every step
                                           )

# cross_entropy = tf.reduce_sum(tf.square(y_-y_conv)) 
# cross_entropy = -tf.reduce_sum(y_*tf.log(y_conv))
cross_entropy = tf.reduce_sum(tf.nn.softmax_cross_entropy_with_logits_v2(labels=y_, logits=y_conv))
tf.summary.scalar("cross_entropy",cross_entropy)

# train_step = tf.train.AdamOptimizer(learning_rate).minimize(cross_entropy)
train_step = tf.train.AdadeltaOptimizer(learning_rate).minimize(cross_entropy)
correct_prediction = tf.equal(tf.argmax(y_conv, 1), tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
tf.summary.scalar("accuracy",accuracy)
merged = tf.summary.merge_all()

batch_size = 4
                
checkpointsPath = "./896_classs_checkpoints/"
reload = True

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #保存训练好的模型一遍下次使用
    saver = tf.train.Saver()
    writer = tf.summary.FileWriter("logs_dir/", sess.graph)
    
    if not os.path.exists(checkpointsPath):
        os.mkdir(checkpointsPath)
    
    if reload:
        checkPoint = tf.train.get_checkpoint_state(checkpointsPath)
        if checkPoint and checkPoint.model_checkpoint_path:
            saver.restore(sess,checkPoint.model_checkpoint_path)
            print("restored %s" % checkPoint.model_checkpoint_path)
        else:
            print("no checkpoint found!")
        
    for i in tqdm(range(20000)):
        batch_x,batch_y = get_train_data_batch(batch_size, train_pic_dir, train_label_dir)
        summary,_ = sess.run([merged,train_step],feed_dict={input_image:batch_x, y_:batch_y, 
                                                            keep_prob:0.8,global_step:i})
        writer.add_summary(summary, i)
        if (i % 100) == 0 & (i != 0):
            print("save model")
            saver.save(sess, os.path.join(checkpointsPath,"saved_net.ckpt"), global_step=i)
            print("loss is:",sess.run(cross_entropy,feed_dict={input_image:batch_x, y_:batch_y, keep_prob:1.0}))
            test_batch_x,test_batch_y = get_test_batch(30, test_images, test_labels)
            print("learning_rate is:",sess.run(learning_rate,feed_dict = {global_step:i}))
            print("test accuraracy: %.5f" %accuracy.eval(feed_dict={input_image:test_batch_x,
                                                                    y_:test_batch_y,
                                                                    keep_prob:1.0}))
    print("done!")


  0%|          | 0/20000 [00:00<?, ?it/s]

no checkpoint found!
save model
loss is: 192924.9
learning_rate is: 0.01


  0%|          | 1/20000 [00:10<57:41:14, 10.38s/it]

test accuraracy: 0.30000


  0%|          | 100/20000 [00:37<1:24:25,  3.93it/s]

save model
loss is: 77345.7
learning_rate is: 0.01


  1%|          | 101/20000 [00:38<2:33:23,  2.16it/s]

test accuraracy: 0.30000


  1%|          | 200/20000 [01:04<1:19:02,  4.17it/s]

save model
loss is: 112365.16
learning_rate is: 0.01


  1%|          | 201/20000 [01:05<2:28:14,  2.23it/s]

test accuraracy: 0.40000


  2%|▏         | 300/20000 [01:31<1:40:26,  3.27it/s]

save model
loss is: 55824.25
learning_rate is: 0.01


  2%|▏         | 301/20000 [01:31<2:43:30,  2.01it/s]

test accuraracy: 0.43333


  2%|▏         | 400/20000 [01:58<1:23:38,  3.91it/s]

save model
loss is: 57401.227
learning_rate is: 0.01


  2%|▏         | 401/20000 [01:59<2:30:27,  2.17it/s]

test accuraracy: 0.36667


  2%|▎         | 500/20000 [02:25<1:20:40,  4.03it/s]

save model
loss is: 55053.805
learning_rate is: 0.01


  3%|▎         | 501/20000 [02:26<2:30:00,  2.17it/s]

test accuraracy: 0.43333


  3%|▎         | 600/20000 [02:51<1:20:41,  4.01it/s]

save model
loss is: 51607.28
learning_rate is: 0.01


  3%|▎         | 601/20000 [02:52<2:27:06,  2.20it/s]

test accuraracy: 0.40000


  4%|▎         | 700/20000 [03:17<1:17:47,  4.14it/s]

save model
loss is: 20429.438
learning_rate is: 0.01


  4%|▎         | 701/20000 [03:18<2:25:57,  2.20it/s]

test accuraracy: 0.40000


  4%|▍         | 800/20000 [03:43<1:17:59,  4.10it/s]

save model
loss is: 20446.734
learning_rate is: 0.01


  4%|▍         | 801/20000 [03:44<2:27:56,  2.16it/s]

test accuraracy: 0.50000


  4%|▍         | 900/20000 [04:09<1:15:17,  4.23it/s]

save model
loss is: 21466.25
learning_rate is: 0.01


  5%|▍         | 901/20000 [04:10<2:36:29,  2.03it/s]

test accuraracy: 0.33333


  5%|▌         | 1000/20000 [04:35<1:14:11,  4.27it/s]

save model
loss is: 25998.785
learning_rate is: 0.0095999995


  5%|▌         | 1001/20000 [04:36<2:21:58,  2.23it/s]

test accuraracy: 0.53333


  6%|▌         | 1100/20000 [05:01<1:15:46,  4.16it/s]

save model
loss is: 4184.051
learning_rate is: 0.0095999995


  6%|▌         | 1101/20000 [05:02<2:23:22,  2.20it/s]

test accuraracy: 0.53333


  6%|▌         | 1200/20000 [05:27<1:15:43,  4.14it/s]

save model
loss is: 0.0
learning_rate is: 0.0095999995


  6%|▌         | 1201/20000 [05:28<2:23:00,  2.19it/s]

test accuraracy: 0.63333


  6%|▋         | 1300/20000 [05:53<1:23:51,  3.72it/s]

save model
loss is: 3215.1328
learning_rate is: 0.0095999995


  7%|▋         | 1301/20000 [05:54<2:26:43,  2.12it/s]

test accuraracy: 0.60000


  7%|▋         | 1400/20000 [06:18<1:13:49,  4.20it/s]

save model
loss is: 0.0
learning_rate is: 0.0095999995


  7%|▋         | 1401/20000 [06:19<2:18:41,  2.24it/s]

test accuraracy: 0.56667


  8%|▊         | 1500/20000 [06:44<1:13:39,  4.19it/s]

save model
loss is: 20692.11
learning_rate is: 0.0095999995


  8%|▊         | 1501/20000 [06:45<2:19:03,  2.22it/s]

test accuraracy: 0.53333


  8%|▊         | 1600/20000 [07:10<1:14:18,  4.13it/s]

save model
loss is: 888.5156
learning_rate is: 0.0095999995


  8%|▊         | 1601/20000 [07:11<2:18:03,  2.22it/s]

test accuraracy: 0.50000


  8%|▊         | 1700/20000 [07:35<1:13:45,  4.14it/s]

save model
loss is: 17974.967
learning_rate is: 0.0095999995


  9%|▊         | 1701/20000 [07:36<2:18:41,  2.20it/s]

test accuraracy: 0.70000


  9%|▉         | 1800/20000 [08:00<1:12:42,  4.17it/s]

save model
loss is: 0.0
learning_rate is: 0.0095999995


  9%|▉         | 1801/20000 [08:01<2:16:06,  2.23it/s]

test accuraracy: 0.40000


 10%|▉         | 1900/20000 [08:26<1:16:27,  3.95it/s]

save model
loss is: 0.0
learning_rate is: 0.0095999995


 10%|▉         | 1901/20000 [08:27<2:18:31,  2.18it/s]

test accuraracy: 0.66667


 10%|█         | 2000/20000 [08:51<1:09:22,  4.32it/s]

save model
loss is: 0.0
learning_rate is: 0.009215999


 10%|█         | 2001/20000 [08:52<2:13:13,  2.25it/s]

test accuraracy: 0.43333


 10%|█         | 2100/20000 [09:16<1:08:09,  4.38it/s]

save model
loss is: 4540.7246
learning_rate is: 0.009215999


 11%|█         | 2101/20000 [09:17<2:11:11,  2.27it/s]

test accuraracy: 0.56667


 11%|█         | 2200/20000 [09:41<1:09:29,  4.27it/s]

save model
loss is: 8362.986
learning_rate is: 0.009215999


 11%|█         | 2201/20000 [09:42<2:13:53,  2.22it/s]

test accuraracy: 0.43333


 12%|█▏        | 2300/20000 [10:06<1:07:09,  4.39it/s]

save model
loss is: 15379.639
learning_rate is: 0.009215999


 12%|█▏        | 2301/20000 [10:07<2:11:14,  2.25it/s]

test accuraracy: 0.66667


 12%|█▏        | 2400/20000 [10:30<1:07:04,  4.37it/s]

save model
loss is: 1615.9805
learning_rate is: 0.009215999


 12%|█▏        | 2401/20000 [10:31<2:10:17,  2.25it/s]

test accuraracy: 0.50000


 12%|█▎        | 2500/20000 [10:55<1:05:25,  4.46it/s]

save model
loss is: 4486.0
learning_rate is: 0.009215999


 13%|█▎        | 2501/20000 [10:56<2:08:33,  2.27it/s]

test accuraracy: 0.50000


 13%|█▎        | 2600/20000 [11:20<1:07:13,  4.31it/s]

save model
loss is: 6260.8105
learning_rate is: 0.009215999


 13%|█▎        | 2601/20000 [11:21<2:11:15,  2.21it/s]

test accuraracy: 0.73333


 14%|█▎        | 2700/20000 [11:44<1:05:43,  4.39it/s]

save model
loss is: 16074.865
learning_rate is: 0.009215999


 14%|█▎        | 2701/20000 [11:45<2:08:03,  2.25it/s]

test accuraracy: 0.60000


 14%|█▍        | 2800/20000 [12:09<1:10:14,  4.08it/s]

save model
loss is: 5874.998
learning_rate is: 0.009215999


 14%|█▍        | 2801/20000 [12:09<2:10:48,  2.19it/s]

test accuraracy: 0.56667


 14%|█▍        | 2900/20000 [12:33<1:05:16,  4.37it/s]

save model
loss is: 0.0
learning_rate is: 0.009215999


 15%|█▍        | 2901/20000 [12:34<2:04:53,  2.28it/s]

test accuraracy: 0.53333


 15%|█▌        | 3000/20000 [12:57<1:04:50,  4.37it/s]

save model
loss is: 8558.24
learning_rate is: 0.008847359


 15%|█▌        | 3001/20000 [12:58<2:04:08,  2.28it/s]

test accuraracy: 0.70000


 16%|█▌        | 3100/20000 [13:22<1:07:35,  4.17it/s]

save model
loss is: 0.0
learning_rate is: 0.008847359


 16%|█▌        | 3101/20000 [13:23<2:06:22,  2.23it/s]

test accuraracy: 0.46667


 16%|█▌        | 3200/20000 [13:47<1:07:56,  4.12it/s]

save model
loss is: 3613.7344
learning_rate is: 0.008847359


 16%|█▌        | 3201/20000 [13:48<2:06:16,  2.22it/s]

test accuraracy: 0.63333


 16%|█▋        | 3300/20000 [14:11<1:03:30,  4.38it/s]

save model
loss is: 1078.1328
learning_rate is: 0.008847359


 17%|█▋        | 3301/20000 [14:12<2:01:55,  2.28it/s]

test accuraracy: 0.56667


 17%|█▋        | 3400/20000 [14:35<1:04:26,  4.29it/s]

save model
loss is: 2211.5137
learning_rate is: 0.008847359


 17%|█▋        | 3401/20000 [14:36<2:04:16,  2.23it/s]

test accuraracy: 0.63333


 18%|█▊        | 3500/20000 [15:00<1:02:28,  4.40it/s]

save model
loss is: 0.0
learning_rate is: 0.008847359


 18%|█▊        | 3501/20000 [15:00<2:00:17,  2.29it/s]

test accuraracy: 0.60000


 18%|█▊        | 3600/20000 [15:24<1:03:42,  4.29it/s]

save model
loss is: 0.0
learning_rate is: 0.008847359


 18%|█▊        | 3601/20000 [15:25<2:00:35,  2.27it/s]

test accuraracy: 0.56667


 18%|█▊        | 3700/20000 [15:48<1:02:31,  4.34it/s]

save model
loss is: 0.0
learning_rate is: 0.008847359


 19%|█▊        | 3701/20000 [15:49<1:59:16,  2.28it/s]

test accuraracy: 0.63333


 19%|█▉        | 3800/20000 [16:12<1:00:55,  4.43it/s]

save model
loss is: 0.0
learning_rate is: 0.008847359


 19%|█▉        | 3801/20000 [16:13<1:59:57,  2.25it/s]

test accuraracy: 0.63333


 20%|█▉        | 3900/20000 [16:36<1:00:38,  4.42it/s]

save model
loss is: 0.0
learning_rate is: 0.008847359


 20%|█▉        | 3901/20000 [16:37<1:57:26,  2.28it/s]

test accuraracy: 0.53333


 20%|██        | 4000/20000 [17:00<59:29,  4.48it/s]  

save model
loss is: 0.0
learning_rate is: 0.008493464


 20%|██        | 4001/20000 [17:01<1:56:52,  2.28it/s]

test accuraracy: 0.56667


 20%|██        | 4100/20000 [17:24<1:00:48,  4.36it/s]

save model
loss is: 0.0
learning_rate is: 0.008493464


 21%|██        | 4101/20000 [17:25<1:56:36,  2.27it/s]

test accuraracy: 0.73333


 21%|██        | 4200/20000 [17:47<1:01:08,  4.31it/s]

save model
loss is: 7241.214
learning_rate is: 0.008493464


 21%|██        | 4201/20000 [17:48<1:56:52,  2.25it/s]

test accuraracy: 0.70000


 22%|██▏       | 4300/20000 [18:11<58:23,  4.48it/s]  

save model
loss is: 0.0
learning_rate is: 0.008493464


 22%|██▏       | 4301/20000 [18:12<1:53:40,  2.30it/s]

test accuraracy: 0.66667


 22%|██▏       | 4400/20000 [18:35<57:20,  4.53it/s]  

save model
loss is: 0.0
learning_rate is: 0.008493464


 22%|██▏       | 4401/20000 [18:36<1:52:06,  2.32it/s]

test accuraracy: 0.56667


 22%|██▎       | 4500/20000 [18:58<57:29,  4.49it/s]  

save model
loss is: 0.0
learning_rate is: 0.008493464


 23%|██▎       | 4501/20000 [18:59<1:52:18,  2.30it/s]

test accuraracy: 0.66667


 23%|██▎       | 4600/20000 [19:22<56:39,  4.53it/s]  

save model
loss is: 2108.8154
learning_rate is: 0.008493464


 23%|██▎       | 4601/20000 [19:23<1:50:59,  2.31it/s]

test accuraracy: 0.66667


 24%|██▎       | 4700/20000 [19:45<56:28,  4.52it/s]  

save model
loss is: 0.0
learning_rate is: 0.008493464


 24%|██▎       | 4701/20000 [19:46<1:50:35,  2.31it/s]

test accuraracy: 0.43333


 24%|██▍       | 4800/20000 [20:09<56:25,  4.49it/s]  

save model
loss is: 0.0
learning_rate is: 0.008493464


 24%|██▍       | 4801/20000 [20:10<1:51:33,  2.27it/s]

test accuraracy: 0.63333


 24%|██▍       | 4900/20000 [20:33<55:11,  4.56it/s]  

save model
loss is: 1595.1396
learning_rate is: 0.008493464


 25%|██▍       | 4901/20000 [20:34<1:48:29,  2.32it/s]

test accuraracy: 0.70000


 25%|██▌       | 5000/20000 [20:56<55:43,  4.49it/s]  

save model
loss is: 0.0
learning_rate is: 0.008153725


 25%|██▌       | 5001/20000 [20:57<1:48:26,  2.31it/s]

test accuraracy: 0.66667


 26%|██▌       | 5100/20000 [21:20<58:14,  4.26it/s]  

save model
loss is: 382.24023
learning_rate is: 0.008153725


 26%|██▌       | 5101/20000 [21:21<1:50:34,  2.25it/s]

test accuraracy: 0.80000


 26%|██▌       | 5200/20000 [21:43<55:06,  4.48it/s]  

save model
loss is: 0.0
learning_rate is: 0.008153725


 26%|██▌       | 5201/20000 [21:44<1:46:49,  2.31it/s]

test accuraracy: 0.66667


 26%|██▋       | 5300/20000 [22:07<53:49,  4.55it/s]  

save model
loss is: 155.4248
learning_rate is: 0.008153725


 27%|██▋       | 5301/20000 [22:08<1:45:30,  2.32it/s]

test accuraracy: 0.60000


 27%|██▋       | 5400/20000 [22:30<53:51,  4.52it/s]  

save model
loss is: 2390.958
learning_rate is: 0.008153725


 27%|██▋       | 5401/20000 [22:31<1:44:58,  2.32it/s]

test accuraracy: 0.70000


 28%|██▊       | 5500/20000 [22:54<54:22,  4.44it/s]  

save model
loss is: 0.0
learning_rate is: 0.008153725


 28%|██▊       | 5501/20000 [22:55<1:45:21,  2.29it/s]

test accuraracy: 0.40000


 28%|██▊       | 5600/20000 [23:17<52:39,  4.56it/s]  

save model
loss is: 0.0
learning_rate is: 0.008153725


 28%|██▊       | 5601/20000 [23:18<1:44:54,  2.29it/s]

test accuraracy: 0.63333


 28%|██▊       | 5700/20000 [23:40<53:49,  4.43it/s]  

save model
loss is: 0.0
learning_rate is: 0.008153725


 29%|██▊       | 5701/20000 [23:41<1:44:17,  2.29it/s]

test accuraracy: 0.56667


 29%|██▉       | 5800/20000 [24:04<53:04,  4.46it/s]  

save model
loss is: 0.0
learning_rate is: 0.008153725


 29%|██▉       | 5801/20000 [24:04<1:43:38,  2.28it/s]

test accuraracy: 0.80000


 30%|██▉       | 5900/20000 [24:27<51:33,  4.56it/s]  

save model
loss is: 921.3613
learning_rate is: 0.008153725


 30%|██▉       | 5901/20000 [24:28<1:41:04,  2.32it/s]

test accuraracy: 0.70000


 30%|███       | 6000/20000 [24:50<51:51,  4.50it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 30%|███       | 6001/20000 [24:51<1:41:33,  2.30it/s]

test accuraracy: 0.70000


 30%|███       | 6100/20000 [25:13<50:33,  4.58it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 31%|███       | 6101/20000 [25:14<1:40:58,  2.29it/s]

test accuraracy: 0.83333


 31%|███       | 6200/20000 [25:37<51:25,  4.47it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 31%|███       | 6201/20000 [25:38<1:39:58,  2.30it/s]

test accuraracy: 0.86667


 32%|███▏      | 6300/20000 [26:01<52:54,  4.32it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 32%|███▏      | 6301/20000 [26:01<1:41:33,  2.25it/s]

test accuraracy: 0.53333


 32%|███▏      | 6400/20000 [26:24<49:38,  4.57it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 32%|███▏      | 6401/20000 [26:25<1:37:52,  2.32it/s]

test accuraracy: 0.66667


 32%|███▎      | 6500/20000 [26:47<49:18,  4.56it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 33%|███▎      | 6501/20000 [26:48<1:37:17,  2.31it/s]

test accuraracy: 0.73333


 33%|███▎      | 6600/20000 [27:10<50:29,  4.42it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 33%|███▎      | 6601/20000 [27:11<1:38:05,  2.28it/s]

test accuraracy: 0.83333


 34%|███▎      | 6700/20000 [27:33<50:39,  4.38it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 34%|███▎      | 6701/20000 [27:34<1:37:20,  2.28it/s]

test accuraracy: 0.86667


 34%|███▍      | 6800/20000 [27:57<48:26,  4.54it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 34%|███▍      | 6801/20000 [27:57<1:35:02,  2.31it/s]

test accuraracy: 0.73333


 34%|███▍      | 6900/20000 [28:20<47:52,  4.56it/s]  

save model
loss is: 0.0
learning_rate is: 0.007827576


 35%|███▍      | 6901/20000 [28:21<1:34:24,  2.31it/s]

test accuraracy: 0.76667


 35%|███▌      | 7000/20000 [28:43<47:13,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 35%|███▌      | 7001/20000 [28:44<1:33:14,  2.32it/s]

test accuraracy: 0.76667


 36%|███▌      | 7100/20000 [29:06<46:48,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 36%|███▌      | 7101/20000 [29:07<1:32:50,  2.32it/s]

test accuraracy: 0.93333


 36%|███▌      | 7200/20000 [29:29<47:32,  4.49it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 36%|███▌      | 7201/20000 [29:30<1:32:13,  2.31it/s]

test accuraracy: 0.83333


 36%|███▋      | 7300/20000 [29:53<47:08,  4.49it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 37%|███▋      | 7301/20000 [29:54<1:32:08,  2.30it/s]

test accuraracy: 0.70000


 37%|███▋      | 7400/20000 [30:16<46:45,  4.49it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 37%|███▋      | 7401/20000 [30:16<1:31:12,  2.30it/s]

test accuraracy: 0.80000


 38%|███▊      | 7500/20000 [30:39<45:36,  4.57it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 38%|███▊      | 7501/20000 [30:40<1:31:57,  2.27it/s]

test accuraracy: 0.73333


 38%|███▊      | 7600/20000 [31:02<45:05,  4.58it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 38%|███▊      | 7601/20000 [31:03<1:29:07,  2.32it/s]

test accuraracy: 0.80000


 38%|███▊      | 7700/20000 [31:25<45:15,  4.53it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 39%|███▊      | 7701/20000 [31:26<1:29:50,  2.28it/s]

test accuraracy: 0.73333


 39%|███▉      | 7800/20000 [31:48<44:56,  4.52it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 39%|███▉      | 7801/20000 [31:49<1:27:47,  2.32it/s]

test accuraracy: 0.80000


 40%|███▉      | 7900/20000 [32:11<44:18,  4.55it/s]  

save model
loss is: 0.0
learning_rate is: 0.007514473


 40%|███▉      | 7901/20000 [32:12<1:27:22,  2.31it/s]

test accuraracy: 0.76667


 40%|████      | 8000/20000 [32:33<43:34,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 40%|████      | 8001/20000 [32:34<1:26:44,  2.31it/s]

test accuraracy: 0.83333


 40%|████      | 8100/20000 [32:56<43:56,  4.51it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 41%|████      | 8101/20000 [32:57<1:26:02,  2.31it/s]

test accuraracy: 0.80000


 41%|████      | 8200/20000 [33:19<43:03,  4.57it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 41%|████      | 8201/20000 [33:20<1:24:45,  2.32it/s]

test accuraracy: 0.70000


 42%|████▏     | 8300/20000 [33:42<42:35,  4.58it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 42%|████▏     | 8301/20000 [33:43<1:24:37,  2.30it/s]

test accuraracy: 0.83333


 42%|████▏     | 8400/20000 [34:05<42:23,  4.56it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 42%|████▏     | 8401/20000 [34:06<1:23:18,  2.32it/s]

test accuraracy: 0.73333


 42%|████▎     | 8500/20000 [34:28<42:02,  4.56it/s]  

save model
loss is: 669.01465
learning_rate is: 0.0072138947


 43%|████▎     | 8501/20000 [34:29<1:22:39,  2.32it/s]

test accuraracy: 0.86667


 43%|████▎     | 8600/20000 [34:51<41:26,  4.58it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 43%|████▎     | 8601/20000 [34:51<1:21:55,  2.32it/s]

test accuraracy: 0.80000


 44%|████▎     | 8700/20000 [35:14<41:35,  4.53it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 44%|████▎     | 8701/20000 [35:15<1:21:38,  2.31it/s]

test accuraracy: 0.83333


 44%|████▍     | 8800/20000 [35:37<42:38,  4.38it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 44%|████▍     | 8801/20000 [35:38<1:22:07,  2.27it/s]

test accuraracy: 0.66667


 44%|████▍     | 8900/20000 [36:00<40:16,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0072138947


 45%|████▍     | 8901/20000 [36:01<1:20:36,  2.29it/s]

test accuraracy: 0.80000


 45%|████▌     | 9000/20000 [36:23<39:51,  4.60it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 45%|████▌     | 9001/20000 [36:23<1:18:57,  2.32it/s]

test accuraracy: 0.86667


 46%|████▌     | 9100/20000 [36:45<39:55,  4.55it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 46%|████▌     | 9101/20000 [36:46<1:18:55,  2.30it/s]

test accuraracy: 0.66667


 46%|████▌     | 9200/20000 [37:08<39:26,  4.56it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 46%|████▌     | 9201/20000 [37:09<1:17:28,  2.32it/s]

test accuraracy: 0.86667


 46%|████▋     | 9300/20000 [37:31<39:18,  4.54it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 47%|████▋     | 9301/20000 [37:32<1:16:52,  2.32it/s]

test accuraracy: 0.83333


 47%|████▋     | 9400/20000 [37:53<38:41,  4.57it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 47%|████▋     | 9401/20000 [37:54<1:16:18,  2.32it/s]

test accuraracy: 0.80000


 48%|████▊     | 9500/20000 [38:17<38:17,  4.57it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 48%|████▊     | 9501/20000 [38:17<1:15:34,  2.32it/s]

test accuraracy: 0.80000


 48%|████▊     | 9600/20000 [38:39<38:01,  4.56it/s]  

save model
loss is: 139.02441
learning_rate is: 0.0069253384


 48%|████▊     | 9601/20000 [38:40<1:15:34,  2.29it/s]

test accuraracy: 0.80000


 48%|████▊     | 9700/20000 [39:02<37:41,  4.55it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 49%|████▊     | 9701/20000 [39:03<1:14:02,  2.32it/s]

test accuraracy: 0.76667


 49%|████▉     | 9800/20000 [39:24<37:00,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0069253384


 49%|████▉     | 9801/20000 [39:25<1:13:12,  2.32it/s]

test accuraracy: 0.80000


 50%|████▉     | 9900/20000 [39:48<36:43,  4.58it/s]  

save model
loss is: 32.648438
learning_rate is: 0.0069253384


 50%|████▉     | 9901/20000 [39:49<1:12:47,  2.31it/s]

test accuraracy: 0.83333


 50%|█████     | 10000/20000 [40:11<37:13,  4.48it/s] 

save model
loss is: 0.0
learning_rate is: 0.0066483244


 50%|█████     | 10001/20000 [40:11<1:12:15,  2.31it/s]

test accuraracy: 0.80000


 50%|█████     | 10100/20000 [40:33<35:55,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 51%|█████     | 10101/20000 [40:34<1:11:07,  2.32it/s]

test accuraracy: 0.83333


 51%|█████     | 10200/20000 [40:56<35:34,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 51%|█████     | 10201/20000 [40:57<1:10:33,  2.31it/s]

test accuraracy: 0.76667


 52%|█████▏    | 10300/20000 [41:19<35:12,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 52%|█████▏    | 10301/20000 [41:20<1:09:41,  2.32it/s]

test accuraracy: 0.80000


 52%|█████▏    | 10400/20000 [41:41<34:59,  4.57it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 52%|█████▏    | 10401/20000 [41:42<1:09:02,  2.32it/s]

test accuraracy: 0.80000


 52%|█████▎    | 10500/20000 [42:04<34:43,  4.56it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 53%|█████▎    | 10501/20000 [42:05<1:08:36,  2.31it/s]

test accuraracy: 0.90000


 53%|█████▎    | 10600/20000 [42:28<34:09,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 53%|█████▎    | 10601/20000 [42:29<1:07:19,  2.33it/s]

test accuraracy: 0.83333


 54%|█████▎    | 10700/20000 [42:50<33:44,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 54%|█████▎    | 10701/20000 [42:51<1:06:44,  2.32it/s]

test accuraracy: 0.83333


 54%|█████▍    | 10800/20000 [43:13<33:34,  4.57it/s]  

save model
loss is: 0.0
learning_rate is: 0.0066483244


 54%|█████▍    | 10801/20000 [43:14<1:06:03,  2.32it/s]

test accuraracy: 0.83333


 55%|█████▍    | 10900/20000 [43:35<33:32,  4.52it/s]  

save model
loss is: 932.86084
learning_rate is: 0.0066483244


 55%|█████▍    | 10901/20000 [43:36<1:05:31,  2.31it/s]

test accuraracy: 0.80000


 55%|█████▌    | 11000/20000 [43:59<32:38,  4.60it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 55%|█████▌    | 11001/20000 [44:00<1:04:47,  2.31it/s]

test accuraracy: 0.70000


 56%|█████▌    | 11100/20000 [44:22<32:46,  4.52it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 56%|█████▌    | 11101/20000 [44:22<1:04:03,  2.32it/s]

test accuraracy: 0.86667


 56%|█████▌    | 11200/20000 [44:44<31:56,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 56%|█████▌    | 11201/20000 [44:45<1:03:02,  2.33it/s]

test accuraracy: 0.76667


 56%|█████▋    | 11300/20000 [45:07<31:32,  4.60it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 57%|█████▋    | 11301/20000 [45:08<1:02:12,  2.33it/s]

test accuraracy: 0.83333


 57%|█████▋    | 11400/20000 [45:30<31:11,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 57%|█████▋    | 11401/20000 [45:31<1:01:51,  2.32it/s]

test accuraracy: 0.80000


 57%|█████▊    | 11500/20000 [45:52<30:49,  4.60it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 58%|█████▊    | 11501/20000 [45:53<1:01:45,  2.29it/s]

test accuraracy: 0.83333


 58%|█████▊    | 11600/20000 [46:15<30:31,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 58%|█████▊    | 11601/20000 [46:16<1:00:12,  2.33it/s]

test accuraracy: 0.83333


 58%|█████▊    | 11700/20000 [46:37<30:09,  4.59it/s]  

save model
loss is: 0.0
learning_rate is: 0.006382392


 59%|█████▊    | 11701/20000 [46:38<59:36,  2.32it/s]

test accuraracy: 0.86667


 59%|█████▉    | 11800/20000 [47:00<30:12,  4.52it/s]

save model
loss is: 0.0
learning_rate is: 0.006382392


 59%|█████▉    | 11801/20000 [47:01<59:21,  2.30it/s]

test accuraracy: 0.73333


 60%|█████▉    | 11900/20000 [47:23<29:21,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.006382392


 60%|█████▉    | 11901/20000 [47:24<58:08,  2.32it/s]

test accuraracy: 0.80000


 60%|██████    | 12000/20000 [47:45<29:02,  4.59it/s]

save model
loss is: 1955.916
learning_rate is: 0.006127096


 60%|██████    | 12001/20000 [47:46<57:33,  2.32it/s]

test accuraracy: 0.90000


 60%|██████    | 12100/20000 [48:08<28:38,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 61%|██████    | 12101/20000 [48:09<56:41,  2.32it/s]

test accuraracy: 0.76667


 61%|██████    | 12200/20000 [48:31<28:24,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 61%|██████    | 12201/20000 [48:32<56:00,  2.32it/s]

test accuraracy: 0.80000


 62%|██████▏   | 12300/20000 [48:54<27:59,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 62%|██████▏   | 12301/20000 [48:55<55:07,  2.33it/s]

test accuraracy: 0.86667


 62%|██████▏   | 12400/20000 [49:16<28:02,  4.52it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 62%|██████▏   | 12401/20000 [49:17<54:49,  2.31it/s]

test accuraracy: 0.70000


 62%|██████▎   | 12500/20000 [49:39<27:19,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 63%|██████▎   | 12501/20000 [49:40<54:48,  2.28it/s]

test accuraracy: 0.90000


 63%|██████▎   | 12600/20000 [50:01<26:49,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 63%|██████▎   | 12601/20000 [50:02<53:13,  2.32it/s]

test accuraracy: 0.73333


 64%|██████▎   | 12700/20000 [50:25<26:35,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 64%|██████▎   | 12701/20000 [50:26<52:24,  2.32it/s]

test accuraracy: 0.86667


 64%|██████▍   | 12800/20000 [50:47<26:08,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 64%|██████▍   | 12801/20000 [50:48<51:50,  2.31it/s]

test accuraracy: 0.83333


 64%|██████▍   | 12900/20000 [51:10<26:12,  4.52it/s]

save model
loss is: 0.0
learning_rate is: 0.006127096


 65%|██████▍   | 12901/20000 [51:11<51:28,  2.30it/s]

test accuraracy: 0.90000


 65%|██████▌   | 13000/20000 [51:32<25:37,  4.55it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 65%|██████▌   | 13001/20000 [51:33<50:15,  2.32it/s]

test accuraracy: 0.90000


 66%|██████▌   | 13100/20000 [51:55<25:07,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 66%|██████▌   | 13101/20000 [51:56<49:42,  2.31it/s]

test accuraracy: 0.86667


 66%|██████▌   | 13200/20000 [52:17<24:42,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 66%|██████▌   | 13201/20000 [52:18<48:46,  2.32it/s]

test accuraracy: 0.93333


 66%|██████▋   | 13300/20000 [52:40<24:47,  4.50it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 67%|██████▋   | 13301/20000 [52:41<48:31,  2.30it/s]

test accuraracy: 0.93333


 67%|██████▋   | 13400/20000 [53:03<24:00,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 67%|██████▋   | 13401/20000 [53:04<47:53,  2.30it/s]

test accuraracy: 0.86667


 68%|██████▊   | 13500/20000 [53:26<23:35,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 68%|██████▊   | 13501/20000 [53:27<46:39,  2.32it/s]

test accuraracy: 0.86667


 68%|██████▊   | 13600/20000 [53:49<23:12,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 68%|██████▊   | 13601/20000 [53:50<45:54,  2.32it/s]

test accuraracy: 0.83333


 68%|██████▊   | 13700/20000 [54:11<22:57,  4.57it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 69%|██████▊   | 13701/20000 [54:12<45:14,  2.32it/s]

test accuraracy: 0.86667


 69%|██████▉   | 13800/20000 [54:34<22:30,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 69%|██████▉   | 13801/20000 [54:35<45:01,  2.29it/s]

test accuraracy: 0.73333


 70%|██████▉   | 13900/20000 [54:57<22:11,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.005882012


 70%|██████▉   | 13901/20000 [54:58<43:58,  2.31it/s]

test accuraracy: 0.83333


 70%|███████   | 14000/20000 [55:19<21:52,  4.57it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 70%|███████   | 14001/20000 [55:20<43:07,  2.32it/s]

test accuraracy: 0.93333


 70%|███████   | 14100/20000 [55:42<21:26,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 71%|███████   | 14101/20000 [55:43<42:21,  2.32it/s]

test accuraracy: 0.73333


 71%|███████   | 14200/20000 [56:04<21:04,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 71%|███████   | 14201/20000 [56:05<41:41,  2.32it/s]

test accuraracy: 0.83333


 72%|███████▏  | 14300/20000 [56:27<20:39,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 72%|███████▏  | 14301/20000 [56:28<41:01,  2.32it/s]

test accuraracy: 0.76667


 72%|███████▏  | 14400/20000 [56:50<20:21,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 72%|███████▏  | 14401/20000 [56:51<40:09,  2.32it/s]

test accuraracy: 0.90000


 72%|███████▎  | 14500/20000 [57:12<20:00,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 73%|███████▎  | 14501/20000 [57:13<39:25,  2.32it/s]

test accuraracy: 0.83333


 73%|███████▎  | 14600/20000 [57:35<19:38,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 73%|███████▎  | 14601/20000 [57:36<38:48,  2.32it/s]

test accuraracy: 0.80000


 74%|███████▎  | 14700/20000 [57:57<19:14,  4.59it/s]

save model
loss is: 2246.622
learning_rate is: 0.0056467312


 74%|███████▎  | 14701/20000 [57:58<38:07,  2.32it/s]

test accuraracy: 0.83333


 74%|███████▍  | 14800/20000 [58:20<18:52,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 74%|███████▍  | 14801/20000 [58:21<37:24,  2.32it/s]

test accuraracy: 0.83333


 74%|███████▍  | 14900/20000 [58:42<18:43,  4.54it/s]

save model
loss is: 0.0
learning_rate is: 0.0056467312


 75%|███████▍  | 14901/20000 [58:43<36:54,  2.30it/s]

test accuraracy: 0.83333


 75%|███████▌  | 15000/20000 [59:05<18:06,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 75%|███████▌  | 15001/20000 [59:06<35:59,  2.32it/s]

test accuraracy: 0.83333


 76%|███████▌  | 15100/20000 [59:27<17:53,  4.56it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 76%|███████▌  | 15101/20000 [59:28<35:25,  2.30it/s]

test accuraracy: 0.90000


 76%|███████▌  | 15200/20000 [59:50<17:24,  4.60it/s]

save model
loss is: 1610.6592
learning_rate is: 0.0054208618


 76%|███████▌  | 15201/20000 [59:51<34:24,  2.32it/s]

test accuraracy: 0.83333


 76%|███████▋  | 15300/20000 [1:00:12<17:06,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 77%|███████▋  | 15301/20000 [1:00:13<33:43,  2.32it/s]

test accuraracy: 0.76667


 77%|███████▋  | 15400/20000 [1:00:35<16:41,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 77%|███████▋  | 15401/20000 [1:00:36<33:00,  2.32it/s]

test accuraracy: 0.86667


 78%|███████▊  | 15500/20000 [1:00:58<16:20,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 78%|███████▊  | 15501/20000 [1:00:58<32:14,  2.33it/s]

test accuraracy: 0.80000


 78%|███████▊  | 15600/20000 [1:01:20<15:58,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 78%|███████▊  | 15601/20000 [1:01:21<31:35,  2.32it/s]

test accuraracy: 0.80000


 78%|███████▊  | 15700/20000 [1:01:43<15:34,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 79%|███████▊  | 15701/20000 [1:01:44<30:57,  2.31it/s]

test accuraracy: 0.80000


 79%|███████▉  | 15800/20000 [1:02:06<15:15,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 79%|███████▉  | 15801/20000 [1:02:07<30:11,  2.32it/s]

test accuraracy: 0.96667


 80%|███████▉  | 15900/20000 [1:02:29<14:53,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0054208618


 80%|███████▉  | 15901/20000 [1:02:30<29:27,  2.32it/s]

test accuraracy: 0.83333


 80%|████████  | 16000/20000 [1:02:51<14:35,  4.57it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 80%|████████  | 16001/20000 [1:02:52<28:41,  2.32it/s]

test accuraracy: 0.76667


 80%|████████  | 16100/20000 [1:03:14<14:08,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 81%|████████  | 16101/20000 [1:03:15<27:59,  2.32it/s]

test accuraracy: 0.83333


 81%|████████  | 16200/20000 [1:03:36<13:48,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 81%|████████  | 16201/20000 [1:03:37<27:27,  2.31it/s]

test accuraracy: 0.86667


 82%|████████▏ | 16300/20000 [1:03:59<13:27,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 82%|████████▏ | 16301/20000 [1:04:00<26:38,  2.31it/s]

test accuraracy: 0.93333


 82%|████████▏ | 16400/20000 [1:04:21<13:05,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 82%|████████▏ | 16401/20000 [1:04:22<25:56,  2.31it/s]

test accuraracy: 0.73333


 82%|████████▎ | 16500/20000 [1:04:44<12:43,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 83%|████████▎ | 16501/20000 [1:04:45<25:12,  2.31it/s]

test accuraracy: 0.96667


 83%|████████▎ | 16600/20000 [1:05:06<12:21,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 83%|████████▎ | 16601/20000 [1:05:07<24:29,  2.31it/s]

test accuraracy: 0.86667


 84%|████████▎ | 16700/20000 [1:05:29<12:02,  4.57it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 84%|████████▎ | 16701/20000 [1:05:30<23:49,  2.31it/s]

test accuraracy: 0.80000


 84%|████████▍ | 16800/20000 [1:05:52<11:36,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 84%|████████▍ | 16801/20000 [1:05:53<23:02,  2.31it/s]

test accuraracy: 0.76667


 84%|████████▍ | 16900/20000 [1:06:14<11:15,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.005204027


 85%|████████▍ | 16901/20000 [1:06:15<22:21,  2.31it/s]

test accuraracy: 0.86667


 85%|████████▌ | 17000/20000 [1:06:37<10:52,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 85%|████████▌ | 17001/20000 [1:06:38<21:35,  2.32it/s]

test accuraracy: 0.86667


 86%|████████▌ | 17100/20000 [1:06:59<10:30,  4.60it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 86%|████████▌ | 17101/20000 [1:07:00<20:56,  2.31it/s]

test accuraracy: 0.90000


 86%|████████▌ | 17200/20000 [1:07:22<10:10,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 86%|████████▌ | 17201/20000 [1:07:23<20:11,  2.31it/s]

test accuraracy: 0.86667


 86%|████████▋ | 17300/20000 [1:07:45<09:49,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 87%|████████▋ | 17301/20000 [1:07:46<19:22,  2.32it/s]

test accuraracy: 0.93333


 87%|████████▋ | 17400/20000 [1:08:07<09:26,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 87%|████████▋ | 17401/20000 [1:08:08<18:44,  2.31it/s]

test accuraracy: 0.90000


 88%|████████▊ | 17500/20000 [1:08:30<09:05,  4.58it/s]

save model
loss is: 1589.3774
learning_rate is: 0.0049958657


 88%|████████▊ | 17501/20000 [1:08:31<17:56,  2.32it/s]

test accuraracy: 0.76667


 88%|████████▊ | 17600/20000 [1:08:52<08:43,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 88%|████████▊ | 17601/20000 [1:08:53<17:17,  2.31it/s]

test accuraracy: 0.83333


 88%|████████▊ | 17700/20000 [1:09:15<08:20,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 89%|████████▊ | 17701/20000 [1:09:16<16:28,  2.32it/s]

test accuraracy: 0.83333


 89%|████████▉ | 17800/20000 [1:09:37<08:01,  4.57it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 89%|████████▉ | 17801/20000 [1:09:38<15:48,  2.32it/s]

test accuraracy: 0.70000


 90%|████████▉ | 17900/20000 [1:10:00<07:38,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0049958657


 90%|████████▉ | 17901/20000 [1:10:01<15:07,  2.31it/s]

test accuraracy: 0.80000


 90%|█████████ | 18000/20000 [1:10:22<07:16,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 90%|█████████ | 18001/20000 [1:10:23<14:24,  2.31it/s]

test accuraracy: 0.90000


 90%|█████████ | 18100/20000 [1:10:45<06:54,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 91%|█████████ | 18101/20000 [1:10:46<13:38,  2.32it/s]

test accuraracy: 0.86667


 91%|█████████ | 18200/20000 [1:11:07<06:33,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 91%|█████████ | 18201/20000 [1:11:08<12:56,  2.32it/s]

test accuraracy: 0.83333


 92%|█████████▏| 18300/20000 [1:11:30<06:10,  4.59it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 92%|█████████▏| 18301/20000 [1:11:31<12:11,  2.32it/s]

test accuraracy: 0.83333


 92%|█████████▏| 18400/20000 [1:11:53<05:58,  4.46it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 92%|█████████▏| 18401/20000 [1:11:54<11:55,  2.24it/s]

test accuraracy: 0.80000


 92%|█████████▎| 18500/20000 [1:12:16<05:40,  4.41it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 93%|█████████▎| 18501/20000 [1:12:17<11:01,  2.27it/s]

test accuraracy: 0.90000


 93%|█████████▎| 18600/20000 [1:12:39<05:05,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 93%|█████████▎| 18601/20000 [1:12:40<10:05,  2.31it/s]

test accuraracy: 0.90000


 94%|█████████▎| 18700/20000 [1:13:02<04:44,  4.56it/s]

save model
loss is: 3748.5972
learning_rate is: 0.0047960314


 94%|█████████▎| 18701/20000 [1:13:03<09:21,  2.32it/s]

test accuraracy: 0.93333


 94%|█████████▍| 18800/20000 [1:13:24<04:23,  4.56it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 94%|█████████▍| 18801/20000 [1:13:25<08:36,  2.32it/s]

test accuraracy: 0.76667


 94%|█████████▍| 18900/20000 [1:13:47<04:00,  4.57it/s]

save model
loss is: 0.0
learning_rate is: 0.0047960314


 95%|█████████▍| 18901/20000 [1:13:48<07:53,  2.32it/s]

test accuraracy: 0.86667


 95%|█████████▌| 19000/20000 [1:14:09<03:38,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 95%|█████████▌| 19001/20000 [1:14:10<07:12,  2.31it/s]

test accuraracy: 0.93333


 96%|█████████▌| 19100/20000 [1:14:32<03:18,  4.53it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 96%|█████████▌| 19101/20000 [1:14:33<06:30,  2.30it/s]

test accuraracy: 0.83333


 96%|█████████▌| 19200/20000 [1:14:54<02:54,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 96%|█████████▌| 19201/20000 [1:14:55<05:46,  2.31it/s]

test accuraracy: 0.80000


 96%|█████████▋| 19300/20000 [1:15:17<02:32,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 97%|█████████▋| 19301/20000 [1:15:18<05:03,  2.30it/s]

test accuraracy: 0.93333


 97%|█████████▋| 19400/20000 [1:15:40<02:11,  4.56it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 97%|█████████▋| 19401/20000 [1:15:41<04:19,  2.31it/s]

test accuraracy: 0.86667


 98%|█████████▊| 19500/20000 [1:16:02<01:49,  4.57it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 98%|█████████▊| 19501/20000 [1:16:03<03:36,  2.31it/s]

test accuraracy: 0.86667


 98%|█████████▊| 19600/20000 [1:16:25<01:28,  4.54it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 98%|█████████▊| 19601/20000 [1:16:26<02:54,  2.29it/s]

test accuraracy: 0.90000


 98%|█████████▊| 19700/20000 [1:16:47<01:05,  4.59it/s]

save model
loss is: 346.1338
learning_rate is: 0.0046041897


 99%|█████████▊| 19701/20000 [1:16:48<02:08,  2.32it/s]

test accuraracy: 0.83333


 99%|█████████▉| 19800/20000 [1:17:10<00:43,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


 99%|█████████▉| 19801/20000 [1:17:11<01:26,  2.31it/s]

test accuraracy: 0.76667


100%|█████████▉| 19900/20000 [1:17:33<00:21,  4.58it/s]

save model
loss is: 0.0
learning_rate is: 0.0046041897


100%|█████████▉| 19901/20000 [1:17:33<00:42,  2.32it/s]

test accuraracy: 0.96667


100%|██████████| 20000/20000 [1:17:55<00:00,  4.57it/s]

done!
