In [1]:
import os
import random
import skimage.data
from skimage import io
import skimage.transform as skt
import numpy as np
import tensorflow as tf
from tqdm import tqdm
import sys
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
import cv2

In [2]:
# submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression/submap"
# pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression/picture"

# # for i in range(4):
# i = 1
# submap1 = cv2.imread(os.path.join(submap_dir,str(0) + '.pgm'))
# submap1 = cv2.resize(submap1,(448,448))
# submap1 = cv2.transpose(submap1)
# submap1 = cv2.flip(submap1, 1)
# # submap1 = np.rot90(submap1)
# cv2.imshow("submap",submap1)


# pic1 = cv2.imread(os.path.join(pic_dir, '00000.jpg'))
# cv2.imshow("pic",pic1)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# print(np.shape(submap1))

In [3]:
label_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression"
pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression/picture"
submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression/submap"

train_txt = os.path.join(label_dir, "label.txt")
count = len(open(train_txt, 'r').readlines())
print(count)
file = open(train_txt, 'r')
s = file.readlines()
all_images = []
all_labels = []

for i in range(0, count-2):
    image1 = skimage.data.imread(os.path.join(pic_dir, s[i].split(";")[0]))
    submap1 = cv2.imread(os.path.join(submap_dir,str(i) + '.pgm'))
    submap1 = cv2.resize(submap1,(448,448))
    submap1 = cv2.transpose(submap1)
    submap1 = cv2.flip(submap1, 1)
    
    image2 = skimage.data.imread(os.path.join(pic_dir, s[i+1].split(";")[0]))
    submap2 = cv2.imread(os.path.join(submap_dir,str(i+1) + '.pgm'))
    submap2 = cv2.resize(submap2,(448,448))
    submap2 = cv2.transpose(submap2)
    submap2 = cv2.flip(submap2, 1)
    
    label = s[i].split(";")[1:3]
    label = list(map(float,label))
#     image2 = skimage.data.imread(os.path.join(pic_dir, s[i].split(";")[0]))
#     image3 = skimage.data.imread(os.path.join(pic_dir, s[i+1].split(";")[0]))
#     image4 = skimage.data.imread(os.path.join(pic_dir, s[i+2].split(";")[0]))
    img = cv2.merge([submap1,image1,image2,submap2])
#     img = cv2.merge([image1,image2,image3,image4])

    all_images.append(img)
    all_labels.append(label)
    
print(np.shape(all_images))
print(np.shape(all_labels))

4026
(4024, 448, 448, 12)
(4024, 2)


In [4]:
def get_train_data_batch(num):
    idx = np.arange(0, count-2)
    np.random.shuffle(idx)
    data_idx = idx[:num]

    labels = []
    images = []

    for i in range(num):
        images.append(all_images[data_idx[i]])
        labels.append(all_labels[data_idx[i]])

    return np.asarray(images), np.asarray(labels)
X,Y = get_train_data_batch(10)
print(Y)
print(np.shape(X))
print(np.shape(Y))

[[ 31.11121215  -5.85223187]
 [ 21.8258767   -9.10912608]
 [  7.15754183   0.3714195 ]
 [ 17.70421116  -9.3766028 ]
 [ 24.08184946   0.87288413]
 [-14.96184401  -5.25396523]
 [ -3.10579622  -0.46758396]
 [ 12.36987907  -3.08969176]
 [ -5.20160946  -1.7571838 ]
 [-29.09674194  -7.2445275 ]]
(10, 448, 448, 12)
(10, 2)


In [5]:
with tf.name_scope("input"):
    input_image = tf.placeholder("float", [None, 448,448,12],name='input_image')
#     input_image = tf.pad(image,np.array([[0, 0], [3, 3], [3, 3], [0, 0]]))
    y_ = tf.placeholder("float", [None, 2],name='y_') 

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape = shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding="SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")


W_conv0 = weight_variable([7, 7, 12, 64])
b_conv0 = bias_variable([64])

h_conv0 = tf.nn.leaky_relu(tf.nn.conv2d(input_image, W_conv0, strides=[1,1,1,1], padding="SAME") + b_conv0)
h_pool0 = max_pool_2x2(h_conv0)   #输出变成224*224*64 [None,224,224,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度

W_conv1 = weight_variable([7, 7, 64, 64])
b_conv1 = bias_variable([64])

h_conv1 = tf.nn.leaky_relu(conv2d(h_pool0, W_conv1) + b_conv1)
# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1, strides=[1,2,2,1], padding="SAME") + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64   [None,112,112,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度
# W_conv1 = weight_variable([7, 7, 6, 64])
# b_conv1 = bias_variable([64])

# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1,strides=[1,2,2,1],padding="SAME") + b_conv1)
# h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64

#第二层卷积层
W_conv2 = weight_variable([3, 3, 64, 192])
b_conv2 = bias_variable([192])

h_conv2 = tf.nn.leaky_relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)  #输出变为56*56*192


#第三层卷积层
W_conv3 = weight_variable([3, 3, 192, 128])
b_conv3 = bias_variable([128])

h_conv3 = tf.nn.leaky_relu(conv2d(h_pool2, W_conv3) + b_conv3)
h_pool3 = max_pool_2x2(h_conv3)   #输出为28*28*128


#第四层卷积层
W_conv4 = weight_variable([3, 3, 128, 64])
b_conv4 = bias_variable([64])

h_conv4 = tf.nn.leaky_relu(conv2d(h_pool3, W_conv4) + b_conv4)
h_pool4 = max_pool_2x2(h_conv4)   #输出变为14*14*64


#密集连接层1
W_fc1 = weight_variable([14*14*64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool4, [-1, 14*14*64])
h_fc1 = tf.nn.leaky_relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)   #输出为96*1024

keep_prob = tf.placeholder("float")
#relu函数作用是求出max(h_fc1,0)
h_fc1_drop1 = tf.nn.dropout(h_fc1, keep_prob)   #输出为96*1024


#密集连接层2
W_fc2 = weight_variable([1024, 512])
b_fc2 = bias_variable([512])

h_fc2 = tf.nn.leaky_relu(tf.matmul(h_fc1_drop1, W_fc2) + b_fc2)

#relu函数作用是求出max(h_fc1,0)
h_fc1_drop2 = tf.nn.dropout(h_fc2, keep_prob)

#输出层softmax层
W_fc3 = weight_variable([512, 2])

y_conv = tf.matmul(h_fc1_drop2, W_fc3)
# tf.summary.histogram('y_conv',y_conv)

# batch_x = images[1:3]
# batch_y = labels[1:3]
# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
#     print("shape of outputs is:",sess.run(tf.shape(y_conv),feed_dict={input_image:batch_x, 
#                                                                            y_:batch_y,keep_prob:1.0}))
#         print("learning rate is :",sess.run(learning_rate,feed_dict = {global_step:i}))


starter_learning_rate = 0.0003
steps_per_decay = 3000
decay_factor = 0.96
 
global_step = tf.Variable(tf.constant(0))
learning_rate = tf.train.exponential_decay(learning_rate = starter_learning_rate,
                                           global_step = global_step,
                                           decay_steps = steps_per_decay,
                                           decay_rate = decay_factor,
                                           staircase = True
                                           )
delta=tf.constant(1.25)
#huber损失函数
loss = tf.reduce_mean(tf.multiply(tf.square(delta),
                                          tf.sqrt(1. + tf.square((y_ - y_conv)/delta)) - 1.))

# cross_entropy = tf.reduce_sum(tf.square(y_-y_conv)) 
tf.summary.scalar("loss",loss)

train_step = tf.train.AdamOptimizer(learning_rate).minimize(loss)
# train_step = tf.train.AdadeltaOptimizer(learning_rate).minimize(cross_entropy)
# train_step = tf.train.RMSPropOptimizer(learning_rate).minimize(cross_entropy)

# correct_prediction = tf.equal(tf.argmax(y_conv, 1), tf.argmax(y_, 1))
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
# tf.summary.scalar("accuracy", accuracy)
merged = tf.summary.merge_all()

batch_size = 4          
checkpointsPath = "./checkpoints/"
reload = False

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #保存训练好的模型一遍下次使用
    saver = tf.train.Saver()
    writer = tf.summary.FileWriter("logs_dir/", sess.graph)
    
    if not os.path.exists(checkpointsPath):
        os.mkdir(checkpointsPath)
    
    if reload:
        checkPoint = tf.train.get_checkpoint_state(checkpointsPath)
        if checkPoint and checkPoint.model_checkpoint_path:
            saver.restore(sess,checkPoint.model_checkpoint_path)
            print("restored %s" % checkPoint.model_checkpoint_path)
        else:
            print("no checkpoint found!")
        
    for i in tqdm(range(100000)):
        batch_x,batch_y = get_train_data_batch(batch_size)
        batch_y = batch_y*1000
        summary,_ = sess.run([merged,train_step],feed_dict={global_step:i,
                                                            input_image:batch_x, 
                                                            y_:batch_y, 
                                                            keep_prob:0.8})
        writer.add_summary(summary, i)
        if (i % 1000) == 0 & (i != 0):
            print("save model")
            print("learning_rate is:\n",sess.run(learning_rate,feed_dict = {global_step:i}))
            print("real location is:\n",batch_y)
            print("prediction is:\n",sess.run(y_conv,feed_dict={input_image:batch_x, y_:batch_y,keep_prob:1.0}))
#             saver.save(sess, os.path.join(checkpointsPath,"saved_net.ckpt"), global_step=i)
            print("loss is:",sess.run(loss,feed_dict={input_image:batch_x, y_:batch_y, keep_prob:1.0}))
    print("done!")


  0%|          | 0/100000 [00:00<?, ?it/s]

save model
learning_rate is:
 0.0003
real location is:
 [[ 12572.3698636   -5501.42692179]
 [-20599.2884466   -5452.05586943]
 [ 10781.5764829   -9733.88958679]
 [ 15868.7874756   -9424.61705883]]
prediction is:
 [[-573125.9   849638.94]
 [-557779.3   851805.4 ]
 [-561823.5   858014.3 ]
 [-553050.6   871639.1 ]]


  0%|          | 1/100000 [00:02<59:22:01,  2.14s/it]

loss is: 894625.44


  1%|          | 1001/100000 [03:37<7:22:41,  3.73it/s]

save model
learning_rate is:
 0.0003
real location is:
 [[  1343.2168769     132.57276714]
 [ -5917.28330488  -6781.86981111]
 [-29803.419945     -305.2856513 ]
 [ 16251.9665643     770.03771143]]
prediction is:
 [[  5395.136    1310.8015]
 [  2010.292   -1135.3997]
 [-33101.008   -5555.947 ]
 [ 13219.6      1972.2167]]
loss is: 4933.905


  2%|▏         | 2001/100000 [07:13<7:16:24,  3.74it/s]

save model
learning_rate is:
 0.0003
real location is:
 [[-21767.6848754   -7076.11305675]
 [ -1371.53434336 -10389.106756  ]
 [ 13449.1604628   -9721.4223685 ]
 [-24506.6872358   -5720.63125974]]
prediction is:
 [[-22180.352   -5044.455 ]
 [  9752.102   -6744.6875]
 [ 15646.185   -2760.1697]
 [-20728.273   -4458.4434]]
loss is: 4906.4473


  3%|▎         | 3001/100000 [10:48<7:12:44,  3.74it/s]

save model
learning_rate is:
 0.000288
real location is:
 [[ 31123.7124128   -5559.573766  ]
 [ 14712.6979818     688.96051373]
 [-29925.7242434    1756.7816944 ]
 [-29016.1954328  -12452.2471895 ]]
prediction is:
 [[ 15991.138   -6601.7646]
 [ 19220.336    3705.153 ]
 [-30277.883   -6540.0776]
 [-17612.18    -9424.771 ]]
loss is: 7307.674


  4%|▍         | 4001/100000 [14:24<7:08:13,  3.74it/s]

save model
learning_rate is:
 0.000288
real location is:
 [[ 29662.6483107   -8713.57842574]
 [ 11961.0793949   -9606.64828928]
 [ 19801.3443317   -9207.70500417]
 [-27244.150828    -7412.69307272]]
prediction is:
 [[  8697.242   -6749.6743]
 [  6049.916   -5210.4453]
 [ 10135.495   -6339.4688]
 [-18005.973   -7450.7734]]
loss is: 8599.539


  5%|▌         | 5001/100000 [17:59<7:03:22,  3.74it/s]

save model
learning_rate is:
 0.000288
real location is:
 [[-13009.382904    -6882.93501692]
 [  2654.25073338   -169.03501212]
 [ 12262.6524722   -1225.57979251]
 [  2612.83682904 -10284.7873048 ]]
prediction is:
 [[-15969.689   -4537.915 ]
 [  7617.583   -3114.263 ]
 [ 11776.026   -2494.3167]
 [ 10930.664   -5773.331 ]]
loss is: 4341.959


  6%|▌         | 6001/100000 [21:35<6:58:56,  3.74it/s]

save model
learning_rate is:
 0.00027648
real location is:
 [[-17614.155769    -6993.76093295]
 [-27904.783105    -7685.22924773]
 [-30677.584894     9461.96553902]
 [  9176.84848962  -9874.38857878]]
prediction is:
 [[-25291.7     -4856.8867]
 [-28201.46    -8848.339 ]
 [-39652.49     7855.4375]
 [ 14854.654   -6754.5625]]
loss is: 4788.0117


  7%|▋         | 7001/100000 [25:10<6:54:16,  3.74it/s]

save model
learning_rate is:
 0.00027648
real location is:
 [[-23477.8073042   -7276.741412  ]
 [ 30728.7326945   -2138.94763323]
 [-30787.6364246    8951.65441413]
 [-30757.9805778   10714.3050711 ]]
prediction is:
 [[-19878.219   -6022.2983]
 [ 33951.414   -7620.1504]
 [-26593.871    6934.796 ]
 [-39895.336   10648.712 ]]
loss is: 4525.2344


  8%|▊         | 8001/100000 [28:46<6:50:19,  3.74it/s]

save model
learning_rate is:
 0.00027648
real location is:
 [[  6129.59260186    343.30222573]
 [-28864.8289223  -14364.4437825 ]
 [-13550.4621144   -6891.91757118]
 [-29790.5113281   -1410.61413634]]
prediction is:
 [[  8210.24      2010.9688 ]
 [-21570.457    -4811.527  ]
 [-13771.817    -7164.161  ]
 [-28910.516      459.20987]]
loss is: 3723.2861


  9%|▉         | 9001/100000 [32:21<6:45:22,  3.74it/s]

save model
learning_rate is:
 0.00026542076
real location is:
 [[ 27083.4511559   -8759.57492206]
 [-27875.5953827   -7617.93260658]
 [  -343.68865711 -10467.0611573 ]
 [  5358.66148417    322.4943599 ]]
prediction is:
 [[ 20194.938   -7388.921 ]
 [-16198.168   -5143.9023]
 [  6537.1133  -8621.187 ]
 [  4282.7793  -1377.9215]]
loss is: 5297.4385


 10%|█         | 10001/100000 [35:56<6:41:06,  3.74it/s]

save model
learning_rate is:
 0.00026542076
real location is:
 [[  7307.27324347    -40.21035325]
 [-30269.2362559    8742.33270425]
 [-16109.690939    -6900.62828367]
 [ 12420.8343537   -3426.91759638]]
prediction is:
 [[  8224.671    -715.0708]
 [-32820.984    7253.755 ]
 [-25404.04    -6245.302 ]
 [ 13348.788   -5128.738 ]]
loss is: 2844.0684


 11%|█         | 11001/100000 [39:32<6:37:20,  3.73it/s]

save model
learning_rate is:
 0.00026542076
real location is:
 [[-29206.3067977   -9192.0396599 ]
 [-25460.2002684   -7142.49109085]
 [-20390.7341149   -7025.74408383]
 [  2330.57948839 -10661.9041325 ]]
prediction is:
 [[-24986.902   -10298.655  ]
 [-25719.516    -7810.124  ]
 [-19140.738    -7299.4443 ]
 [   986.89655  -7049.1514 ]]
loss is: 1987.9856


 12%|█▏        | 12001/100000 [43:07<6:32:17,  3.74it/s]

save model
learning_rate is:
 0.00025480395
real location is:
 [[ 12569.3258787   -8005.94853471]
 [ 12891.7629309   -3219.16530998]
 [-30834.6631334   11913.6475601 ]
 [ 12383.2906688   -2572.38182695]]
prediction is:
 [[ 12936.829   -3316.5615]
 [  9353.634   -3627.322 ]
 [-27936.953    9576.346 ]
 [ 13399.711   -1779.1619]]
loss is: 2505.9116


 13%|█▎        | 13001/100000 [46:43<6:27:42,  3.74it/s]

save model
learning_rate is:
 0.00025480395
real location is:
 [[ 30398.8211467   -8480.00741932]
 [-15790.2080269   -6958.97142555]
 [-30206.0970139    4186.70585648]
 [-31119.3715946    9060.87127083]]
prediction is:
 [[ 17799.73     -5240.647  ]
 [-15527.457    -6716.902  ]
 [-32650.527     3067.6462 ]
 [-25389.84      -730.55725]]
loss is: 5534.02


 14%|█▍        | 14001/100000 [50:18<6:23:13,  3.74it/s]

save model
learning_rate is:
 0.00025480395
real location is:
 [[-30705.5220211    6400.1387927 ]
 [ 11071.6676967   -9777.09336426]
 [-12977.8232657   -6876.32105867]
 [ -5096.01222236  -8419.20479073]]
prediction is:
 [[-25302.799    1819.4076]
 [ 10197.267   -8936.886 ]
 [-12798.893   -6991.5938]
 [ -2472.358   -9335.543 ]]
loss is: 2425.355


 15%|█▌        | 15001/100000 [53:54<6:18:56,  3.74it/s]

save model
learning_rate is:
 0.0002446118
real location is:
 [[ 26859.6211705   -9037.96793838]
 [ 11480.9347521   -9680.47765424]
 [-29140.5059595  -11965.8330191 ]
 [  2541.56437373 -10684.142326  ]]
prediction is:
 [[ 27407.555   -7572.513 ]
 [ 13773.711   -9323.107 ]
 [-33182.16   -15963.023 ]
 [  4764.9775 -10231.004 ]]
loss is: 2401.3965


 16%|█▌        | 16001/100000 [57:29<6:14:30,  3.74it/s]

save model
learning_rate is:
 0.0002446118
real location is:
 [[-17350.3965416   -6999.81761156]
 [-29564.2970485   -4671.86529298]
 [  1683.10481143 -10212.0811334 ]
 [-18730.9364266   -5369.92726987]]
prediction is:
 [[-17724.227   -6938.9697]
 [-27918.977   -7987.2656]
 [  2700.2515  -9036.316 ]
 [-17946.23    -5586.629 ]]
loss is: 1340.5841


 17%|█▋        | 17001/100000 [1:01:04<6:10:03,  3.74it/s]

save model
learning_rate is:
 0.0002446118
real location is:
 [[ 12553.9923948   -3045.07687064]
 [-14160.3068784   -6874.06491979]
 [-30685.5641828    9030.94650982]
 [ -5305.61637438  -8316.68236731]]
prediction is:
 [[ 10228.311  -2757.019]
 [-15388.275  -6402.579]
 [-35934.863  13506.396]
 [ -5967.092  -8572.449]]
loss is: 2335.1865


 18%|█▊        | 18001/100000 [1:04:40<6:05:45,  3.74it/s]

save model
learning_rate is:
 0.0002348273
real location is:
 [[-29988.6558814    1283.51617929]
 [  4370.35453796   -159.72236328]
 [ 12521.5389905   -5008.5767523 ]
 [ 30683.5067163   -2185.68746184]]
prediction is:
 [[-25589.426    5126.207 ]
 [  8508.904   -1808.4401]
 [ 11241.984   -5828.97  ]
 [ 27911.754     -35.3479]]
loss is: 3287.6926


 19%|█▉        | 19001/100000 [1:08:15<6:01:09,  3.74it/s]

save model
learning_rate is:
 0.0002348273
real location is:
 [[ 11408.4693769   -9681.42423995]
 [ 12411.5993765   -1267.77109931]
 [-28926.0440763  -13836.59128   ]
 [ 16163.6039585   -9562.70399705]]
prediction is:
 [[ 10365.641    -8227.545  ]
 [  5562.4014      26.25653]
 [-25914.316   -15351.391  ]
 [ 15807.697    -8345.441  ]]
loss is: 2614.0059


 20%|██        | 20001/100000 [1:11:51<5:56:49,  3.74it/s]

save model
learning_rate is:
 0.0002348273
real location is:
 [[-23172.5036554   -5761.24417067]
 [  1965.80541184 -10321.8702847 ]
 [ 12352.6917107   -2648.57281095]
 [-29271.5516128  -17114.9485818 ]]
prediction is:
 [[-23248.172   -6822.9424]
 [  1715.9902  -9760.361 ]
 [ 12042.615   -1895.9105]
 [-29468.988  -15062.293 ]]
loss is: 820.554


 21%|██        | 21001/100000 [1:15:26<5:52:33,  3.73it/s]

save model
learning_rate is:
 0.00022543421
real location is:
 [[ 12941.1882022   -6998.69597296]
 [-22472.3926767   -7234.58164396]
 [ 16426.3275506   -9565.44802409]
 [-28711.8612071  -17240.2827022 ]]
prediction is:
 [[ 12346.826   -6964.8154]
 [-22457.21    -7390.3955]
 [ 15654.596   -7800.1606]
 [-26561.762  -16532.83  ]]
loss is: 966.2336


 22%|██▏       | 22001/100000 [1:19:02<5:48:02,  3.74it/s]

save model
learning_rate is:
 0.00022543421
real location is:
 [[ 25509.922839    -9042.40073149]
 [ 30841.886167    -6941.69624729]
 [  1209.54702199 -10348.4311145 ]
 [-29993.8068123    1567.04985204]]
prediction is:
 [[ 24116.453    -9753.277  ]
 [ 29034.35     -6862.209  ]
 [ -3748.1968   -8596.641  ]
 [-30297.17       272.62152]]
loss is: 1920.1111


 23%|██▎       | 23001/100000 [1:22:37<5:44:03,  3.73it/s]

save model
learning_rate is:
 0.00022543421
real location is:
 [[-28747.728406   -18119.8248212 ]
 [ 12105.666224     -509.98649421]
 [ 24583.3692373    1063.56440969]
 [-16637.1927806   -5351.49512553]]
prediction is:
 [[-24370.176   -13733.387  ]
 [  8847.733     -181.91258]
 [ 23427.281     1304.0184 ]
 [-16553.332    -5366.716  ]]
loss is: 2161.8264


 24%|██▍       | 24001/100000 [1:26:13<5:39:24,  3.73it/s]

save model
learning_rate is:
 0.00021641685
real location is:
 [[  4483.46065695    306.73588728]
 [ -8624.19048991  -4807.30134417]
 [ 12546.1984639   -2600.68908351]
 [-28225.7382063   -5942.97434259]]
prediction is:
 [[  6958.8022  -1614.3394]
 [ -7529.0176  -4700.8564]
 [ 12123.611   -4726.535 ]
 [-24183.346   -5941.1104]]
loss is: 1903.2994


 25%|██▌       | 25001/100000 [1:29:49<5:34:52,  3.73it/s]

save model
learning_rate is:
 0.00021641685
real location is:
 [[-25525.772926    -7252.28358518]
 [  8638.62208562  -9913.58450618]
 [-12677.2641662   -5302.28191849]
 [ 11869.700337      581.41889336]]
prediction is:
 [[-26229.566    -6584.4287 ]
 [ 11932.898    -9245.615  ]
 [-13044.04     -5297.045  ]
 [ 12373.166     -402.09943]]
loss is: 1122.3508


 26%|██▌       | 26001/100000 [1:33:24<5:29:55,  3.74it/s]

save model
learning_rate is:
 0.00021641685
real location is:
 [[-31119.3715946    9060.87127083]
 [-29168.7779149  -11443.4928658 ]
 [  4058.12687875 -10153.8663522 ]
 [  4570.57731278   -159.26052566]]
prediction is:
 [[-27528.494    5043.4053]
 [-25477.656  -11983.568 ]
 [  3154.8784  -9432.556 ]
 [  4692.656   -1212.3042]]
loss is: 2285.8174


 27%|██▋       | 27001/100000 [1:37:00<5:25:30,  3.74it/s]

save model
learning_rate is:
 0.00020776017
real location is:
 [[ 29250.1694061    1068.70721342]
 [-20135.4613924   -5660.73452174]
 [-30750.9203197   12320.5995513 ]
 [-28897.9138774  -15801.509078  ]]
prediction is:
 [[ 27278.936     943.9916]
 [-19814.426   -6381.1665]
 [-33195.574   12590.944 ]
 [-28890.402  -16706.531 ]]
loss is: 1055.4795


 28%|██▊       | 28001/100000 [1:40:36<5:21:32,  3.73it/s]

save model
learning_rate is:
 0.00020776017
real location is:
 [[ 27713.1826946   -8772.57124039]
 [ -5180.60522229  -6034.55851386]
 [-23528.8599012   -5831.36841423]
 [ 30929.3752576   -5298.02953536]]
prediction is:
 [[ 27474.031   -8230.698 ]
 [ -6567.873   -5499.609 ]
 [-25127.137   -4914.55  ]
 [ 31829.195   -6168.8164]]
loss is: 1090.462


 29%|██▉       | 29001/100000 [1:44:11<5:17:34,  3.73it/s]

save model
learning_rate is:
 0.00020776017
real location is:
 [[12395.231555   -2784.38217401]
 [-5042.565398   -1809.88959908]
 [10558.1903528    798.99322222]
 [ 6556.74837222   398.64090362]]
prediction is:
 [[12603.27    -3739.6553 ]
 [-6072.1523  -1616.4065 ]
 [ 8541.117   -1121.2874 ]
 [ 6083.0366   -283.12378]]
loss is: 1167.0664


 30%|███       | 30001/100000 [1:47:47<5:12:41,  3.73it/s]

save model
learning_rate is:
 0.00019944976
real location is:
 [[ -5031.5992594   -7217.98559905]
 [ 29660.3093495    1242.23705739]
 [-30269.2362559    8742.33270425]
 [-30480.5996448    9488.77559654]]
prediction is:
 [[ -7712.627   -4949.075 ]
 [ 31579.77    -1073.0793]
 [-27698.549    6200.497 ]
 [-31017.164    9369.074 ]]
loss is: 2334.9243


 31%|███       | 31001/100000 [1:51:23<5:07:43,  3.74it/s]

save model
learning_rate is:
 0.00019944976
real location is:
 [[  8215.91671408 -10024.8000292 ]
 [ 24188.0295483    1034.23475106]
 [  6714.07035732    617.5574281 ]
 [-29759.3189949   -1618.1425804 ]]
prediction is:
 [[  8490.475    -9343.918  ]
 [ 21530.82       913.11304]
 [  9138.851     1405.227  ]
 [-27298.426     -440.87277]]
loss is: 1652.2493


 32%|███▏      | 32001/100000 [1:54:59<5:03:33,  3.73it/s]

save model
learning_rate is:
 0.00019944976
real location is:
 [[ -2438.78005972   -605.95651387]
 [ 18896.8068837   -9325.28204327]
 [  3308.13596797 -10117.5071717 ]
 [  9302.19857586  -9856.9493507 ]]
prediction is:
 [[ -4248.1265  -1201.1268]
 [ 18664.682   -8818.273 ]
 [  1908.9097 -11892.768 ]
 [  8366.026  -10146.557 ]]
loss is: 1177.1763


 33%|███▎      | 33001/100000 [1:58:34<4:59:14,  3.73it/s]

save model
learning_rate is:
 0.00019147177
real location is:
 [[ -4690.89068299  -8968.58107626]
 [-18331.0587178   -5334.21660203]
 [   144.45686532 -10352.28097   ]
 [ 19549.4103015   -9252.03834969]]
prediction is:
 [[ -5301.1953  -10886.127  ]
 [-18105.516    -5230.829  ]
 [  -353.60547 -12007.479  ]
 [ 18929.395   -11150.232  ]]
loss is: 1174.7292


 34%|███▍      | 34001/100000 [2:02:10<4:54:46,  3.73it/s]

save model
learning_rate is:
 0.00019147177
real location is:
 [[-18233.7907779   -5660.02700514]
 [ -8182.27124436  -6696.1167925 ]
 [-29894.0883032    1373.53235936]
 [ 13586.9940289     621.95824293]]
prediction is:
 [[-17108.594   -6304.9404]
 [ -7490.293   -6460.9453]
 [-30053.367    1561.4268]
 [ 11944.742    -343.9696]]
loss is: 881.66113


 35%|███▌      | 35001/100000 [2:05:46<4:50:07,  3.73it/s]

save model
learning_rate is:
 0.00019147177
real location is:
 [[30398.8211467  -8480.00741932]
 [14910.5338207    696.18821519]
 [ 8770.44787438    65.4782334 ]
 [-9228.27560548 -4919.26969403]]
prediction is:
 [[27730.746   -7483.295  ]
 [14128.919     974.4303 ]
 [ 8273.799     143.15735]
 [-8461.832   -4632.7686 ]]
loss is: 990.92773


 36%|███▌      | 36001/100000 [2:09:21<4:45:50,  3.73it/s]

save model
learning_rate is:
 0.00018381288
real location is:
 [[31111.2121452  -5852.23186814]
 [29872.8354793   1055.55705521]
 [-5151.11521669 -1583.92454563]
 [29662.1258041  -8645.59119809]]
prediction is:
 [[29431.238  -5791.4565]
 [23902.16    2033.8198]
 [-4471.477  -1629.0663]
 [28594.164  -8593.824 ]]
loss is: 1644.4131


 37%|███▋      | 37001/100000 [2:12:57<4:41:13,  3.73it/s]

save model
learning_rate is:
 0.00018381288
real location is:
 [[ 12556.9926933   -6751.82925317]
 [ 26055.8517075    1146.83003697]
 [-27875.5953827   -7617.93260658]
 [ 18875.6020009   -9308.4579838 ]]
prediction is:
 [[ 14531.352    -7108.2754 ]
 [ 23597.146      446.93915]
 [-27274.979    -7494.198  ]
 [ 20373.469    -9537.975  ]]
loss is: 1239.2424


 38%|███▊      | 38001/100000 [2:16:33<4:36:42,  3.73it/s]

save model
learning_rate is:
 0.00018381288
real location is:
 [[-29141.5151466  -20081.0014867 ]
 [-29061.464835   -11568.4234134 ]
 [ 17848.9663707     823.36152453]
 [ 15262.2479392   -9497.3768507 ]]
prediction is:
 [[-29346.148   -18994.145  ]
 [-30293.645   -12749.351  ]
 [ 15653.9375    -793.47034]
 [ 16495.031    -9732.455  ]]
loss is: 1402.239


 39%|███▉      | 39001/100000 [2:20:08<4:32:12,  3.73it/s]

save model
learning_rate is:
 0.00017646038
real location is:
 [[  6034.28365388 -10068.0324882 ]
 [  3857.85233059    273.39851033]
 [  3245.39655976 -10269.8206277 ]
 [ 26930.550749     1034.05942224]]
prediction is:
 [[  6769.07      -9329.8955  ]
 [  3549.4883       25.407536]
 [  3267.3262   -11029.379   ]
 [ 25010.559       336.88074 ]]
loss is: 846.5598


 40%|████      | 40001/100000 [2:23:44<4:27:45,  3.73it/s]

save model
learning_rate is:
 0.00017646038
real location is:
 [[ 24781.2772243    1076.54131853]
 [-15853.3001113   -5206.60910442]
 [ -1832.02561348   -339.75808657]
 [ -1155.02137404 -10658.2105988 ]]
prediction is:
 [[ 21866.492      601.6825 ]
 [-14979.447    -5001.6377 ]
 [ -2019.4637    -438.62704]
 [ -1249.9738  -10382.82   ]]
loss is: 799.2418


 41%|████      | 41001/100000 [2:27:20<4:23:24,  3.73it/s]

save model
learning_rate is:
 0.00017646038
real location is:
 [[-21020.14159     -6996.10244546]
 [ -1507.93531373   -278.85925874]
 [-17815.4532405   -7026.2158966 ]
 [  2985.16102206    159.26496747]]
prediction is:
 [[-20501.164    -6951.006  ]
 [ -1358.3977    -613.9026 ]
 [-19078.934    -7454.967  ]
 [  2488.768     -159.88593]]
loss is: 554.13477


 42%|████▏     | 42001/100000 [2:30:55<4:19:07,  3.73it/s]

save model
learning_rate is:
 0.00016940194
real location is:
 [[-5.82600795e+02  7.89026194e+00]
 [ 1.25112691e+04 -4.67902660e+03]
 [-2.13263361e+04 -7.20952710e+03]
 [-2.98972792e+04  1.15069627e+03]]
prediction is:
 [[ -1561.0508     217.83188]
 [ 12341.805    -4464.667  ]
 [-19701.717    -6855.6914 ]
 [-28558.896     2215.7698 ]]
loss is: 928.7726


 43%|████▎     | 43001/100000 [2:34:31<4:14:20,  3.74it/s]

save model
learning_rate is:
 0.00016940194
real location is:
 [[ 30467.6021397     418.16211457]
 [-16276.1672677   -6867.87414686]
 [  3028.17419652    238.70009312]
 [   -31.77604498    -74.65322548]]
prediction is:
 [[ 25097.062      990.70447]
 [-13914.776    -5579.043  ]
 [  3453.792      181.89754]
 [  1463.1191     594.53534]]
loss is: 1910.9104


 44%|████▍     | 44001/100000 [2:38:07<4:09:59,  3.73it/s]

save model
learning_rate is:
 0.00016940194
real location is:
 [[-30501.1401177    6887.4692978 ]
 [ 12352.6917107   -2648.57281095]
 [-28729.6074417  -18636.0246104 ]
 [-25937.1676178   -5810.5789173 ]]
prediction is:
 [[-33505.945    7602.9536]
 [ 13657.732   -1530.4187]
 [-26049.164  -17644.89  ]
 [-27579.943   -6410.545 ]]
loss is: 1882.4702


 45%|████▌     | 45001/100000 [2:41:42<4:05:50,  3.73it/s]

save model
learning_rate is:
 0.00016262586
real location is:
 [[-29199.4643152   -9616.90350313]
 [ 29104.500054    -8819.10035641]
 [-20952.064961    -5615.56460775]
 [-29991.5135566    2090.27682882]]
prediction is:
 [[-26557.95    -9217.8955]
 [ 27997.902   -9331.791 ]
 [-18574.156   -5157.039 ]
 [-27159.566    1972.7761]]
loss is: 1630.5791


 46%|████▌     | 46001/100000 [2:45:18<4:01:02,  3.73it/s]

save model
learning_rate is:
 0.00016262586
real location is:
 [[-30127.4396166    4534.47075521]
 [-29530.4586037   -5211.24679096]
 [-29279.4933539  -12285.6225828 ]
 [ -5229.19587908  -1762.62166266]]
prediction is:
 [[-28999.648    4962.5264]
 [-27423.164   -3993.791 ]
 [-26421.719  -11773.988 ]
 [ -5690.3516  -1722.8674]]
loss is: 1365.7725


 47%|████▋     | 47001/100000 [2:48:53<3:56:52,  3.73it/s]

save model
learning_rate is:
 0.00016262586
real location is:
 [[ -4964.92900505  -8602.32805921]
 [ 30169.2034664   -8517.2607292 ]
 [    57.61526554 -10311.7413207 ]
 [ 23428.2733558   -8978.0291082 ]]
prediction is:
 [[ -4349.5923   -8983.442  ]
 [ 32585.566    -8222.543  ]
 [  -515.98645 -10325.983  ]
 [ 22155.912    -9019.25   ]]
loss is: 874.85


 48%|████▊     | 48001/100000 [2:52:29<3:52:07,  3.73it/s]

save model
learning_rate is:
 0.00015612082
real location is:
 [[ 30477.4671216     -76.2811414 ]
 [-10094.733186    -6707.82526739]
 [ -4660.31832037  -9797.11346798]
 [ 11125.8267434     842.85389371]]
prediction is:
 [[ 31249.082        55.844055]
 [ -9940.172     -6306.179   ]
 [ -4038.5403   -10832.827   ]
 [  9883.98        212.56438 ]]
loss is: 778.0615


 49%|████▉     | 49001/100000 [2:56:05<3:47:41,  3.73it/s]

save model
learning_rate is:
 0.00015612082
real location is:
 [[ 25322.1333693   -8861.28617801]
 [-30420.8578592   11610.5940904 ]
 [-30075.023501     2711.98359767]
 [ 12511.2690563   -4679.02659871]]
prediction is:
 [[ 26002.9     -8733.473 ]
 [-33602.234   10774.627 ]
 [-29342.006    2910.452 ]
 [ 12853.707   -5458.7607]]
loss is: 1073.3749


 50%|█████     | 50001/100000 [2:59:40<3:43:21,  3.73it/s]

save model
learning_rate is:
 0.00015612082
real location is:
 [[-11337.6840687   -4971.23277927]
 [  7154.27762798  -9985.43325226]
 [ 16780.6956087   -9415.33991254]
 [ -5100.19487078  -2018.35647075]]
prediction is:
 [[-11114.963   -5220.0986]
 [  7532.6543 -10437.78  ]
 [ 17521.998   -9211.869 ]
 [ -6200.3496  -2203.2734]]
loss is: 550.33984


 51%|█████     | 51001/100000 [3:03:16<3:38:38,  3.74it/s]

save model
learning_rate is:
 0.00014987598
real location is:
 [[ 30661.2322964   -3856.90360885]
 [ -7223.38453637  -4721.74609399]
 [-30249.731594     5121.28463575]
 [ 12869.8268283     734.48830604]]
prediction is:
 [[ 28975.363    -4121.3394 ]
 [ -7854.3477   -4268.6626 ]
 [-29195.555     4610.653  ]
 [ 13044.645      409.28296]]
loss is: 795.1873


 52%|█████▏    | 52001/100000 [3:06:52<3:34:26,  3.73it/s]

save model
learning_rate is:
 0.00014987598
real location is:
 [[-30407.6588526   11179.8603862 ]
 [-20610.4175045   -7034.36133386]
 [ 20894.5008468     994.10191082]
 [  5180.43129989    160.93060094]]
prediction is:
 [[-29464.71     12310.238  ]
 [-19542.012    -7016.214  ]
 [ 20127.059      890.52344]
 [  5090.2095    -560.5842 ]]
loss is: 755.1092


 53%|█████▎    | 53001/100000 [3:10:27<3:29:48,  3.73it/s]

save model
learning_rate is:
 0.00014987598
real location is:
 [[ 30796.0843408   -2964.61423798]
 [ 12840.759286    -4241.35815758]
 [-11175.3426439   -6790.96039436]
 [ -5060.03859484  -1399.30462462]]
prediction is:
 [[ 29778.787   -3213.512 ]
 [ 11910.472   -3358.4019]
 [-11114.225   -6842.615 ]
 [ -5883.4946  -1418.5383]]
loss is: 628.90265


 54%|█████▍    | 54001/100000 [3:14:03<3:25:25,  3.73it/s]

save model
learning_rate is:
 0.00014388096
real location is:
 [[ 25749.5993801   -8910.75748128]
 [-27322.5967292   -7436.9433612 ]
 [ 29358.336979     1141.94410277]
 [-30501.1401177    6887.4692978 ]]
prediction is:
 [[ 24518.535   -9043.791 ]
 [-28051.814   -6859.0396]
 [ 25977.58     1292.0627]
 [-30370.969    6528.535 ]]
loss is: 1043.9412


 55%|█████▌    | 55001/100000 [3:17:39<3:20:44,  3.74it/s]

save model
learning_rate is:
 0.00014388096
real location is:
 [[ 14484.6663024     676.29374312]
 [-24241.5187791   -5823.93363253]
 [  8195.43249466    427.25768816]
 [  3052.79326594 -10699.8861156 ]]
prediction is:
 [[ 13759.107     592.0447]
 [-21164.115   -5489.299 ]
 [  7679.118    1069.0386]
 [  3128.856  -11055.588 ]]
loss is: 906.5211


 56%|█████▌    | 56001/100000 [3:21:14<3:16:29,  3.73it/s]

save model
learning_rate is:
 0.00014388096
real location is:
 [[   601.79136707 -10602.6685067 ]
 [ 17341.2401245   -9480.63564177]
 [ 22318.9053538    1036.13254139]
 [  1442.75498049 -10638.158425  ]]
prediction is:
 [[ 1262.0732  -9361.951  ]
 [16019.377   -9285.886  ]
 [21953.473     712.65015]
 [ 1071.1204  -9798.715  ]]
loss is: 829.3158


 57%|█████▋    | 57001/100000 [3:24:50<3:11:54,  3.73it/s]

save model
learning_rate is:
 0.0001381257
real location is:
 [[-20390.4167788   -5444.7038805 ]
 [-29181.774962    -9279.3454456 ]
 [  8018.22785067  -9931.56648653]
 [ 26710.4151817    1041.68859016]]
prediction is:
 [[-21033.52    -6114.443 ]
 [-28770.72    -9543.959 ]
 [  7544.2495  -8798.668 ]
 [ 26927.32      800.3562]]
loss is: 631.81885


 58%|█████▊    | 58001/100000 [3:28:26<3:07:38,  3.73it/s]

save model
learning_rate is:
 0.0001381257
real location is:
 [[   280.48424862    104.69442132]
 [-30191.4281922    7601.44873904]
 [ 17704.2111629   -9376.60279717]
 [  1684.75169246 -10307.9703553 ]]
prediction is:
 [[  -134.7242      -62.804367]
 [-28884.426      7184.465   ]
 [ 16601.004     -9027.039   ]
 [  2273.0464    -9982.678   ]]
loss is: 728.6042


 59%|█████▉    | 59001/100000 [3:32:02<3:03:04,  3.73it/s]

save model
learning_rate is:
 0.0001381257
real location is:
 [[-19353.6184211   -5400.78543921]
 [-30389.2941322    8035.05288489]
 [ 12302.7053687   -1554.0459474 ]
 [ -4652.3932684   -9476.09644289]]
prediction is:
 [[-19442.004   -5806.3057]
 [-31454.266    9448.939 ]
 [ 12665.355   -1123.5562]
 [ -2112.4995  -9358.191 ]]
loss is: 1002.1444


 60%|██████    | 60001/100000 [3:35:37<2:58:38,  3.73it/s]

save model
learning_rate is:
 0.00013260067
real location is:
 [[  3025.32278707    258.21599277]
 [-29711.4662268   -1482.93414557]
 [ 15027.1666518   -9501.50167837]
 [-23250.3074945   -7238.37746652]]
prediction is:
 [[  2906.2139     214.77512]
 [-29295.96     -1851.209  ]
 [ 15483.635    -9396.617  ]
 [-23570.043    -7308.4395 ]]
loss is: 294.92697


 61%|██████    | 61001/100000 [3:39:13<2:54:13,  3.73it/s]

save model
learning_rate is:
 0.00013260067
real location is:
 [[ -3672.72564133 -10538.392087  ]
 [ -7940.68969557  -4833.03370147]
 [-26145.3071511   -5824.04251926]
 [-23146.0651117   -7126.22270179]]
prediction is:
 [[  -577.0957 -10320.471 ]
 [ -7479.2007  -4207.129 ]
 [-27571.664   -5588.0923]
 [-24209.836   -6640.698 ]]
loss is: 1187.9001


 62%|██████▏   | 62001/100000 [3:42:49<2:49:32,  3.74it/s]

save model
learning_rate is:
 0.00013260067
real location is:
 [[-22427.7810182   -7288.33440806]
 [ 11176.9503908      57.13066678]
 [ 23166.7235138    1016.74336885]
 [-29759.6707326   -2589.89232669]]
prediction is:
 [[-21309.658   -7174.332 ]
 [ 10406.0625   -268.9016]
 [ 24155.605    1243.7072]
 [-32675.629   -4255.4697]]
loss is: 1268.1945


 63%|██████▎   | 63001/100000 [3:46:25<2:45:33,  3.72it/s]

save model
learning_rate is:
 0.00012729665
real location is:
 [[ -4561.80314098  -9966.5951992 ]
 [-11488.4078358   -6764.47933359]
 [ -5794.92854558  -6935.61315491]
 [-16717.4831616   -6921.27762584]]
prediction is:
 [[ -4182.3125 -10141.645 ]
 [-12398.887   -6636.958 ]
 [ -4690.6865  -6487.739 ]
 [-16329.023   -6883.1924]]
loss is: 556.4438


 64%|██████▍   | 64001/100000 [3:50:01<2:41:03,  3.73it/s]

save model
learning_rate is:
 0.00012729665
real location is:
 [[ 23722.343086     1070.01137691]
 [  9302.19857586  -9856.9493507 ]
 [ -4234.4903562  -10287.0426399 ]
 [ -5416.20674026  -3119.36368491]]
prediction is:
 [[ 22990.8      1346.8682]
 [  9255.436   -9530.131 ]
 [ -3688.0999 -10346.998 ]
 [ -5755.955   -3139.5498]]
loss is: 365.36554


 65%|██████▌   | 65001/100000 [3:53:37<2:36:15,  3.73it/s]

save model
learning_rate is:
 0.00012729665
real location is:
 [[-22227.9250108   -7222.26066819]
 [-29765.211207    -1854.44784258]
 [-16157.6928873   -5299.20660518]
 [ 12334.3988621   -2416.86255671]]
prediction is:
 [[-22910.793   -7601.203 ]
 [-29937.377   -2423.5557]
 [-16382.547   -5406.3887]
 [ 13233.5625  -2527.945 ]]
loss is: 489.9052


 66%|██████▌   | 66001/100000 [3:57:12<2:32:01,  3.73it/s]

save model
learning_rate is:
 0.00012220477
real location is:
 [[12589.1079588  -8439.26158318]
 [13449.1604628  -9721.4223685 ]
 [30393.2401716  -8460.91751612]
 [30987.4331496  -6319.93406572]]
prediction is:
 [[11317.576  -8864.6   ]
 [11841.24   -9161.671 ]
 [29183.547  -8632.579 ]
 [31238.82   -6068.3574]]
loss is: 896.69934


 67%|██████▋   | 67001/100000 [4:00:48<2:27:33,  3.73it/s]

save model
learning_rate is:
 0.00012220477
real location is:
 [[-3.07028506e+04  7.00363462e+03]
 [ 1.25720364e+04 -8.07107700e+02]
 [ 9.55225468e+03 -1.03313992e+04]
 [ 1.04867687e+03 -3.56241426e+00]]
prediction is:
 [[-32224.383     7361.5273 ]
 [ 13390.133    -1034.1575 ]
 [ 10171.43    -11837.801  ]
 [   759.59656   -263.12097]]
loss is: 873.2503


 68%|██████▊   | 68001/100000 [4:04:24<2:22:57,  3.73it/s]

save model
learning_rate is:
 0.00012220477
real location is:
 [[11869.700337     581.41889336]
 [21480.3181603   1034.78814948]
 [20634.3362108   1034.40064077]
 [ 7293.07804212   397.17435325]]
prediction is:
 [[10646.226     321.80795]
 [19831.98      728.5679 ]
 [19247.615     828.7092 ]
 [ 5937.551     416.08984]]
loss is: 999.1487


 69%|██████▉   | 69001/100000 [4:08:00<2:18:34,  3.73it/s]

save model
learning_rate is:
 0.00011731658
real location is:
 [[-4786.40204455 -9034.20002206]
 [16994.3115963  -9400.15814947]
 [10014.9204621  -9800.80191998]
 [17570.6984951    761.4157144 ]]
prediction is:
 [[ -3349.217   -8861.935 ]
 [ 18375.715  -10171.23  ]
 [ 10082.518  -10272.67  ]
 [ 18344.426    1103.5226]]
loss is: 844.8823


 70%|███████   | 70001/100000 [4:11:36<2:14:00,  3.73it/s]

save model
learning_rate is:
 0.00011731658
real location is:
 [[ 27479.8810018   -8782.24686484]
 [ 30881.4857178   -7978.78944599]
 [ 24703.2284008     895.64625107]
 [-29540.6280539   -3245.87839309]]
prediction is:
 [[ 26491.54     -8950.739  ]
 [ 29184.36     -8236.708  ]
 [ 23967.104      244.56827]
 [-28557.865    -2944.9775 ]]
loss is: 901.994


 71%|███████   | 71001/100000 [4:15:12<2:09:33,  3.73it/s]

save model
learning_rate is:
 0.00011731658
real location is:
 [[ 15893.95112      1055.11654862]
 [-21988.1572465   -7249.91601078]
 [-13977.3846954   -5129.28746709]
 [  -170.38257695     60.5485252 ]]
prediction is:
 [[ 13999.5625     829.3366 ]
 [-20278.426    -7319.847  ]
 [-13263.476    -5457.513  ]
 [   194.80476    138.49023]]
loss is: 839.8637


 72%|███████▏  | 72001/100000 [4:18:47<2:05:00,  3.73it/s]

save model
learning_rate is:
 0.000112623915
real location is:
 [[-19660.7294264   -5541.024327  ]
 [ -4513.43525569 -10385.6166698 ]
 [  2802.4454729     118.58654497]
 [ 16525.4694539    1047.14020461]]
prediction is:
 [[-19262.992    -5734.424  ]
 [ -3669.622    -9918.752  ]
 [  3067.0063     -75.26758]
 [ 16354.121     1328.262  ]]
loss is: 437.92502


 73%|███████▎  | 73001/100000 [4:22:23<2:00:33,  3.73it/s]

save model
learning_rate is:
 0.000112623915
real location is:
 [[ 26997.8546613   -8770.94336172]
 [-28798.6922113  -15800.8550838 ]
 [-29529.2884774   -3569.5575498 ]
 [ 24655.4377133   -8906.35548394]]
prediction is:
 [[ 26182.43    -8883.916 ]
 [-27914.18   -15902.473 ]
 [-29876.438   -5102.3896]
 [ 23634.02    -8682.65  ]]
loss is: 785.8835


 74%|███████▍  | 74001/100000 [4:25:59<1:56:10,  3.73it/s]

save model
learning_rate is:
 0.000112623915
real location is:
 [[ 12420.8343537   -3426.91759638]
 [   703.35531394 -10385.9668865 ]
 [-29256.7656794  -18307.5531633 ]
 [-25766.6578535   -5939.71173317]]
prediction is:
 [[ 12728.707    -3921.1606 ]
 [   432.85425 -10193.146  ]
 [-27789.227   -17333.172  ]
 [-25818.695    -5663.787  ]]
loss is: 628.9608


 75%|███████▌  | 75001/100000 [4:29:34<1:51:46,  3.73it/s]

save model
learning_rate is:
 0.00010811896
real location is:
 [[-4726.95851582 -1072.81157511]
 [30846.0156817  -3817.87652243]
 [12696.6890065  -6969.98147289]
 [24703.2284008    895.64625107]]
prediction is:
 [[-4688.3765   -884.54224]
 [30653.184   -3684.3242 ]
 [11662.      -6280.3438 ]
 [23611.258     612.83386]]
loss is: 569.12274


 76%|███████▌  | 76001/100000 [4:33:10<1:47:07,  3.73it/s]

save model
learning_rate is:
 0.00010811896
real location is:
 [[ 3.04927951e+04 -3.42849965e+02]
 [ 2.35363782e+04  8.79710911e+02]
 [-9.66309438e+03 -4.93721152e+03]
 [-2.37118483e+01 -1.05949636e+04]]
prediction is:
 [[29208.639      34.43586]
 [22693.79      867.37067]
 [-8933.96    -4809.529  ]
 [ -275.80307 -9847.891  ]]
loss is: 681.63007


 77%|███████▋  | 77001/100000 [4:36:46<1:42:56,  3.72it/s]

save model
learning_rate is:
 0.00010811896
real location is:
 [[12435.1008282  -2183.35371682]
 [28483.8275659  -8686.65445081]
 [ 5881.52716875 -9972.6477548 ]
 [14864.5571272    748.16562399]]
prediction is:
 [[11984.66   -1736.3518]
 [26325.473  -7203.951 ]
 [ 5564.043  -9815.58  ]
 [13815.918   1134.231 ]]
loss is: 1005.9018


 78%|███████▊  | 78001/100000 [4:40:21<1:38:11,  3.73it/s]

save model
learning_rate is:
 0.000103794206
real location is:
 [[ 10381.1119804   -9815.36862324]
 [ 10271.6130446      45.74259194]
 [-27986.5118309   -5949.48697318]
 [-18638.052383    -7064.83696167]]
prediction is:
 [[ 9.2801836e+03 -1.0020100e+04]
 [ 8.4864707e+03 -5.0412292e+00]
 [-2.6583211e+04 -6.0925537e+03]
 [-1.9391340e+04 -7.2424639e+03]]
loss is: 876.3907


 79%|███████▉  | 79001/100000 [4:43:57<1:33:46,  3.73it/s]

save model
learning_rate is:
 0.000103794206
real location is:
 [[  2803.74066451    225.44058723]
 [-29471.6910329   -5997.08934384]
 [   111.30921951     32.95018092]
 [ 15522.373163    -9545.86561279]]
prediction is:
 [[  2981.953      374.6203 ]
 [-25683.736    -6494.4814 ]
 [  1226.8157    -322.80078]
 [ 13199.865    -8746.262  ]]
loss is: 1436.8943


 80%|████████  | 80001/100000 [4:47:33<1:30:15,  3.69it/s]

save model
learning_rate is:
 0.000103794206
real location is:
 [[  2179.65996126    181.77257257]
 [ 30427.8883183     544.77608437]
 [-29204.1253073   -9865.27582453]
 [-30328.6701242    6979.02827197]]
prediction is:
 [[  1600.4824     262.40723]
 [ 28197.75       975.62286]
 [-28883.59     -9290.182  ]
 [-30114.547     5579.0283 ]]
loss is: 909.46423


 81%|████████  | 81001/100000 [4:51:08<1:24:49,  3.73it/s]

save model
learning_rate is:
 9.964243e-05
real location is:
 [[-30868.1034646   12895.9680607 ]
 [-29241.3640796   -5668.20859614]
 [-19074.3325287   -5642.43623541]
 [ 17314.3763252     824.11002157]]
prediction is:
 [[-31481.139   11537.117 ]
 [-29882.172   -6874.396 ]
 [-19617.965   -5656.551 ]
 [ 17427.75      922.6872]]
loss is: 715.4148


 82%|████████▏ | 82001/100000 [4:54:44<1:20:26,  3.73it/s]

save model
learning_rate is:
 9.964243e-05
real location is:
 [[-30813.6137069   11514.5375498 ]
 [-29615.444632    -4065.78189884]
 [-25461.0355292   -7492.53886784]
 [ 22513.6317284     962.34879534]]
prediction is:
 [[-31402.8      10563.705  ]
 [-28542.066    -4223.5205 ]
 [-25795.098    -7714.777  ]
 [ 21517.27       313.54565]]
loss is: 775.409


 83%|████████▎ | 83001/100000 [4:58:20<1:16:03,  3.73it/s]

save model
learning_rate is:
 9.964243e-05
real location is:
 [[ 20236.6537885    1031.20842644]
 [-29065.8364884  -13464.4376541 ]
 [  9306.30164505  -9822.33682688]
 [  6451.13713598    586.81644311]]
prediction is:
 [[ 20200.594     851.8351]
 [-30887.316  -14531.409 ]
 [  9169.414  -10037.658 ]
 [  6158.7188    317.6316]]
loss is: 626.2095


 84%|████████▍ | 84001/100000 [5:01:56<1:11:34,  3.73it/s]

save model
learning_rate is:
 9.565673e-05
real location is:
 [[ 13544.8455235     784.20774984]
 [ 30987.4331496   -6319.93406572]
 [-30979.9280767    9734.45033758]
 [ -2038.34168273 -10475.534123  ]]
prediction is:
 [[ 12744.872    1164.8728]
 [ 30526.695   -6036.21  ]
 [-32687.135    8859.858 ]
 [ -2627.7761 -10690.991 ]]
loss is: 828.4071


 85%|████████▌ | 85001/100000 [5:05:32<1:07:13,  3.72it/s]

save model
learning_rate is:
 9.565673e-05
real location is:
 [[-16955.3092323   -6992.37765227]
 [  6247.1989924  -10128.4037451 ]
 [-29394.939355    -5284.33278955]
 [  1931.09787291     63.62001778]]
prediction is:
 [[-16745.662    -7584.6475 ]
 [  5211.1465   -9969.326  ]
 [-29692.297    -5179.7476 ]
 [  2254.125     -141.74748]]
loss is: 455.84546


 86%|████████▌ | 86001/100000 [5:09:07<1:02:36,  3.73it/s]

save model
learning_rate is:
 9.565673e-05
real location is:
 [[-16022.9327118   -5527.64530531]
 [ 17349.9006637     754.30309323]
 [ 12537.2793342   -2155.55460707]
 [-30436.8488221    8853.02160979]]
prediction is:
 [[-15732.18    -6126.3706]
 [ 16719.562     707.1122]
 [ 11854.753   -1846.3123]
 [-30084.898    9208.002 ]]
loss is: 508.70895


 87%|████████▋ | 87001/100000 [5:12:43<58:05,  3.73it/s]  

save model
learning_rate is:
 9.183046e-05
real location is:
 [[ 12713.5813604   -9557.20360071]
 [-28715.6385987  -22181.4723055 ]
 [  -762.79924974 -10431.8720669 ]
 [-19074.3325287   -5642.43623541]]
prediction is:
 [[ 11703.356   -8708.976 ]
 [-28161.062  -19360.719 ]
 [  -686.0248  -9913.597 ]
 [-18057.035   -5402.0776]]
loss is: 1105.7042


 88%|████████▊ | 88001/100000 [5:16:19<53:40,  3.73it/s]

save model
learning_rate is:
 9.183046e-05
real location is:
 [[ 11480.9347521   -9680.47765424]
 [ -5698.40934563  -7074.41237495]
 [-29172.5447501  -19584.9415763 ]
 [-23889.7635521   -5802.14591831]]
prediction is:
 [[ 11252.945  -9951.533]
 [ -5705.291  -6860.461]
 [-29478.363 -19038.652]
 [-24286.527  -6086.733]]
loss is: 350.54184


 89%|████████▉ | 89001/100000 [5:19:55<49:10,  3.73it/s]

save model
learning_rate is:
 9.183046e-05
real location is:
 [[-28637.1899605  -20692.3924593 ]
 [ -4661.24849729  -9901.12718688]
 [ -9681.75747609  -4931.55708297]
 [-26056.1157328   -5896.0559459 ]]
prediction is:
 [[-28638.805  -21010.5   ]
 [ -4903.8022  -9752.5625]
 [ -9903.746   -4842.9536]
 [-24575.629   -5971.3193]]
loss is: 401.19427


 90%|█████████ | 90001/100000 [5:23:31<45:04,  3.70it/s]

save model
learning_rate is:
 8.8157234e-05
real location is:
 [[  1448.81987509 -10325.0480137 ]
 [-15840.3265125   -5204.44608678]
 [  5881.52716875  -9972.6477548 ]
 [ 31002.363549    -7569.88310936]]
prediction is:
 [[  2013.3525 -10542.412 ]
 [-15885.783   -5516.1924]
 [  5903.9     -9885.1875]
 [ 30955.498   -7439.7266]]
loss is: 221.25716


 91%|█████████ | 91001/100000 [5:27:07<40:16,  3.72it/s]

save model
learning_rate is:
 8.8157234e-05
real location is:
 [[-31031.0199394    8228.29150766]
 [  7523.01731874 -10065.2040854 ]
 [  9405.83471051    453.69998776]
 [ -4906.04537202  -1344.8223196 ]]
prediction is:
 [[-31259.512     8915.481  ]
 [  6949.7217  -10155.732  ]
 [ 10200.557      492.79694]
 [ -4802.872    -1192.0463 ]]
loss is: 415.51898


 92%|█████████▏| 92001/100000 [5:30:42<35:45,  3.73it/s]

save model
learning_rate is:
 8.8157234e-05
real location is:
 [[-29513.9989582   -5474.1922535 ]
 [ 11891.3133447     810.13378081]
 [ 15548.3077954   -9596.25860394]
 [ 12548.3267714   -6840.82972716]]
prediction is:
 [[-29316.727    -5600.0107 ]
 [ 10590.467      855.63794]
 [ 14347.855    -9247.08   ]
 [ 11733.029    -6398.3774 ]]
loss is: 697.94617


 93%|█████████▎| 93001/100000 [5:34:18<31:15,  3.73it/s]

save model
learning_rate is:
 8.463095e-05
real location is:
 [[-30750.9203197   12320.5995513 ]
 [ 12941.1882022   -6998.69597296]
 [ 28832.9174795   -8843.24236342]
 [-28194.8132005   -7490.41554238]]
prediction is:
 [[-30434.07    12144.038 ]
 [ 13096.818   -7036.631 ]
 [ 28583.629   -8542.986 ]
 [-27598.059   -7406.4746]]
loss is: 298.01013


 94%|█████████▍| 94001/100000 [5:37:54<26:49,  3.73it/s]

save model
learning_rate is:
 8.463095e-05
real location is:
 [[-5342.64946834 -2904.32257151]
 [23438.4652528  -9209.19809144]
 [12517.6878792  -5883.00702855]
 [10742.0433507     56.84400079]]
prediction is:
 [[ -5372.909    -2956.2292 ]
 [ 23705.672   -10034.523  ]
 [ 11609.105    -5962.55   ]
 [ 10340.689     -191.41287]]
loss is: 437.8898


 95%|█████████▌| 95001/100000 [5:41:30<22:20,  3.73it/s]

save model
learning_rate is:
 8.463095e-05
real location is:
 [[28718.731847    1268.97999944]
 [27700.8718495  -9025.52851212]
 [30716.5696086  -8913.08326086]
 [ 3279.98219707   169.73346549]]
prediction is:
 [[ 2.7790051e+04  1.2812952e+03]
 [ 2.6964398e+04 -8.4310762e+03]
 [ 3.0248203e+04 -8.5752480e+03]
 [ 2.9669248e+03  1.5357269e+01]]
loss is: 552.44305


 96%|█████████▌| 96001/100000 [5:45:06<17:51,  3.73it/s]

save model
learning_rate is:
 8.124571e-05
real location is:
 [[ 12798.5330501   -7003.03089492]
 [ 24583.3692373    1063.56440969]
 [ 10440.1358628     551.25194786]
 [-30182.7687585    1428.84759737]]
prediction is:
 [[ 13622.275    -6419.635  ]
 [ 23950.5        798.7259 ]
 [ 10483.006      -93.76813]
 [-29490.607     1354.1708 ]]
loss is: 585.87695


 97%|█████████▋| 97001/100000 [5:48:41<13:23,  3.73it/s]

save model
learning_rate is:
 8.124571e-05
real location is:
 [[  6942.83872864    365.8634137 ]
 [ 12446.3809605   -3088.82518079]
 [-27803.6636604   -5931.7443907 ]
 [ 12620.0885856   -4139.73885561]]
prediction is:
 [[  6770.961      186.11336]
 [ 11686.279    -3138.0122 ]
 [-27855.195    -5697.76   ]
 [ 12511.293    -4208.7803 ]]
loss is: 252.2395


 98%|█████████▊| 98001/100000 [5:52:17<08:56,  3.73it/s]

save model
learning_rate is:
 8.124571e-05
real location is:
 [[ 21475.8974596     819.27056934]
 [ 26785.2213558   -8782.14402546]
 [-29921.6101513    1603.67889109]
 [ 12325.7668003   -1754.82568197]]
prediction is:
 [[ 21294.709     856.7885]
 [ 27062.46    -9623.092 ]
 [-30929.723    1676.2853]
 [ 12388.461   -1828.8538]]
loss is: 397.56244


 99%|█████████▉| 99001/100000 [5:55:53<04:28,  3.73it/s]

save model
learning_rate is:
 7.799588e-05
real location is:
 [[-29673.4742628   -1365.46088637]
 [-15654.7564288   -5200.49509483]
 [ 10440.1358628     551.25194786]
 [-29132.2781132  -11548.3667222 ]]
prediction is:
 [[-29239.703    -1642.502  ]
 [-15241.91     -5033.1763 ]
 [ 10282.718      584.36993]
 [-29334.14    -11608.693  ]]
loss is: 270.90002


100%|██████████| 100000/100000 [5:59:28<00:00,  4.64it/s]

done!
