In [1]:
import os
import random
import skimage.data
from skimage import io
import skimage.transform as skt
import numpy as np
import tensorflow as tf
from tqdm import tqdm
import sys
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
import cv2

In [2]:
# submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression/submap"

# # for i in range(4):
# i = 1
# submap1 = cv2.imread(os.path.join(submap_dir,str(i) + '.pgm'))
    
    
# submap1 = cv2.resize(submap1,(448,448))
# # submap2 = skimage.data.imread(os.path.join(submap_dir,'1.pgm'))
# # img = cv2.merge([submap1,submap2])
# cv2.imshow("img",submap1)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# print(np.shape(submap1))

In [3]:
label_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression"
pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression/picture"
submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression/submap"

train_txt = os.path.join(label_dir, "label.txt")
count = len(open(train_txt, 'r').readlines())
print(count)
file = open(train_txt, 'r')
s = file.readlines()
all_images = []
all_labels = []

for i in range(0, count-2):
#     image1 = skimage.data.imread(os.path.join(pic_dir, s[i].split(";")[0]))
    submap1 = cv2.imread(os.path.join(submap_dir,str(i) + '.pgm'))
    submap1 = cv2.resize(submap1,(448,448))
    submap2 = cv2.imread(os.path.join(submap_dir,str(i+1) + '.pgm'))
    submap2 = cv2.resize(submap2,(448,448))
    label = s[i].split(";")[1:3]
    label = list(map(float,label))
#     image2 = skimage.data.imread(os.path.join(pic_dir, s[i].split(";")[0]))
#     image3 = skimage.data.imread(os.path.join(pic_dir, s[i+1].split(";")[0]))
#     image4 = skimage.data.imread(os.path.join(pic_dir, s[i+2].split(";")[0]))
    img = cv2.merge([submap1,submap2])
#     img = cv2.merge([image1,image2,image3,image4])

    all_images.append(img)
    all_labels.append(label)
    
print(np.shape(all_images))
print(np.shape(all_labels))

4026
(4024, 448, 448, 6)
(4024, 2)


In [4]:
def get_train_data_batch(num):
    idx = np.arange(0, count-2)
    np.random.shuffle(idx)
    data_idx = idx[:num]

    labels = []
    images = []

    for i in range(num):
        images.append(all_images[data_idx[i]])
        labels.append(all_labels[data_idx[i]])

    return np.asarray(images), np.asarray(labels)
X,Y = get_train_data_batch(10)
print(Y)
print(np.shape(X))
print(np.shape(Y))

[[-2.30153998e+00 -1.04930384e+01]
 [ 1.97840992e+01  9.58769297e-01]
 [-3.05771810e+01  1.06716167e+01]
 [-2.87421323e+01 -2.19219096e+01]
 [ 1.49299090e+00  2.74776712e-02]
 [-3.08408373e+01  9.18608482e+00]
 [-2.87829100e+01 -1.63245994e+01]
 [-4.65354138e+00 -9.68551880e+00]
 [ 9.30219858e+00 -9.85694935e+00]
 [-1.19117154e+01 -6.85686176e+00]]
(10, 448, 448, 6)
(10, 2)


In [5]:
with tf.name_scope("input"):
    input_image = tf.placeholder("float", [None, 448,448,6],name='input_image')
#     input_image = tf.pad(image,np.array([[0, 0], [3, 3], [3, 3], [0, 0]]))
    y_ = tf.placeholder("float", [None, 2],name='y_') 

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape = shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding="SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")


W_conv0 = weight_variable([7, 7, 6, 64])
b_conv0 = bias_variable([64])

h_conv0 = tf.nn.leaky_relu(tf.nn.conv2d(input_image, W_conv0, strides=[1,1,1,1], padding="SAME") + b_conv0)
h_pool0 = max_pool_2x2(h_conv0)   #输出变成224*224*64 [None,224,224,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度

W_conv1 = weight_variable([7, 7, 64, 64])
b_conv1 = bias_variable([64])

h_conv1 = tf.nn.leaky_relu(conv2d(h_pool0, W_conv1) + b_conv1)
# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1, strides=[1,2,2,1], padding="SAME") + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64   [None,112,112,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度
# W_conv1 = weight_variable([7, 7, 6, 64])
# b_conv1 = bias_variable([64])

# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1,strides=[1,2,2,1],padding="SAME") + b_conv1)
# h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64

#第二层卷积层
W_conv2 = weight_variable([3, 3, 64, 192])
b_conv2 = bias_variable([192])

h_conv2 = tf.nn.leaky_relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)  #输出变为56*56*192


#第三层卷积层
W_conv3 = weight_variable([3, 3, 192, 128])
b_conv3 = bias_variable([128])

h_conv3 = tf.nn.leaky_relu(conv2d(h_pool2, W_conv3) + b_conv3)
h_pool3 = max_pool_2x2(h_conv3)   #输出为28*28*128


#第四层卷积层
W_conv4 = weight_variable([3, 3, 128, 64])
b_conv4 = bias_variable([64])

h_conv4 = tf.nn.leaky_relu(conv2d(h_pool3, W_conv4) + b_conv4)
h_pool4 = max_pool_2x2(h_conv4)   #输出变为14*14*64


#密集连接层1
W_fc1 = weight_variable([14*14*64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool4, [-1, 14*14*64])
h_fc1 = tf.nn.leaky_relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)   #输出为96*1024

keep_prob = tf.placeholder("float")
#relu函数作用是求出max(h_fc1,0)
h_fc1_drop1 = tf.nn.dropout(h_fc1, keep_prob)   #输出为96*1024


#密集连接层2
W_fc2 = weight_variable([1024, 512])
b_fc2 = bias_variable([512])

h_fc2 = tf.nn.leaky_relu(tf.matmul(h_fc1_drop1, W_fc2) + b_fc2)

#relu函数作用是求出max(h_fc1,0)
h_fc1_drop2 = tf.nn.dropout(h_fc2, keep_prob)

#输出层softmax层
W_fc3 = weight_variable([512, 2])

y_conv = tf.matmul(h_fc1_drop2, W_fc3)
# tf.summary.histogram('y_conv',y_conv)

# batch_x = images[1:3]
# batch_y = labels[1:3]
# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
#     print("shape of outputs is:",sess.run(tf.shape(y_conv),feed_dict={input_image:batch_x, 
#                                                                            y_:batch_y,keep_prob:1.0}))
#         print("learning rate is :",sess.run(learning_rate,feed_dict = {global_step:i}))


starter_learning_rate = 0.0002
steps_per_decay = 1000
decay_factor = 0.98
 
global_step = tf.Variable(tf.constant(0))
learning_rate = tf.train.exponential_decay(learning_rate = starter_learning_rate,
                                           global_step = global_step,
                                           decay_steps = steps_per_decay,
                                           decay_rate = decay_factor,
                                           staircase = True
                                           )

  
delta=tf.constant(1.25)
#huber损失函数
loss = tf.reduce_mean(tf.multiply(tf.square(delta),
                                          tf.sqrt(1. + tf.square((y_ - y_conv)/delta)) - 1.))

# cross_entropy = tf.reduce_sum(tf.square(y_-y_conv)) 
tf.summary.scalar("loss",loss)

train_step = tf.train.AdamOptimizer(learning_rate).minimize(loss)
# train_step = tf.train.AdadeltaOptimizer(learning_rate).minimize(cross_entropy)
# train_step = tf.train.RMSPropOptimizer(learning_rate).minimize(cross_entropy)

# correct_prediction = tf.equal(tf.argmax(y_conv, 1), tf.argmax(y_, 1))
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
# tf.summary.scalar("accuracy", accuracy)
merged = tf.summary.merge_all()

batch_size = 8               
checkpointsPath = "./checkpoints/"
reload = False

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #保存训练好的模型一遍下次使用
    saver = tf.train.Saver()
    writer = tf.summary.FileWriter("logs_dir/", sess.graph)
    
    if not os.path.exists(checkpointsPath):
        os.mkdir(checkpointsPath)
    
    if reload:
        checkPoint = tf.train.get_checkpoint_state(checkpointsPath)
        if checkPoint and checkPoint.model_checkpoint_path:
            saver.restore(sess,checkPoint.model_checkpoint_path)
            print("restored %s" % checkPoint.model_checkpoint_path)
        else:
            print("no checkpoint found!")
        
    for i in tqdm(range(60000)):
        batch_x,batch_y = get_train_data_batch(batch_size)
        batch_y = batch_y*1000
        summary,_ = sess.run([merged,train_step],feed_dict={global_step:i,
                                                            input_image:batch_x, 
                                                            y_:batch_y, 
                                                            keep_prob:0.8})
        writer.add_summary(summary, i)
        if (i % 1000) == 0 & (i != 0):
            print("save model")
            print("learning_rate is:\n",sess.run(learning_rate,feed_dict = {global_step:i}))
            print("real location is:\n",batch_y)
            print("prediction is:\n",sess.run(y_conv,feed_dict={input_image:batch_x, y_:batch_y,keep_prob:1.0}))
#             saver.save(sess, os.path.join(checkpointsPath,"saved_net.ckpt"), global_step=i)
            print("loss is:",sess.run(loss,feed_dict={input_image:batch_x, y_:batch_y, keep_prob:1.0}))
    print("done!")


  0%|          | 0/60000 [00:00<?, ?it/s]

save model
learning_rate is:
 0.0002
real location is:
 [[  2807.11369868 -10623.8392915 ]
 [ 30893.2155665   -4675.28437805]
 [ -3662.33991761   -634.95718102]
 [-28541.1234698   -5966.62581026]
 [ 12567.7303482   -7174.55263297]
 [ 30507.097668    -1753.86643243]
 [-19927.4997337   -7001.21353822]
 [ 18743.0708866   -9576.38234625]]
prediction is:
 [[ 529079.75 -313813.56]
 [ 530801.   -312222.84]
 [ 525034.75 -327428.94]
 [ 491353.53 -309008.78]
 [ 522349.62 -309323.66]
 [ 524897.6  -311715.62]
 [ 520661.66 -313349.88]
 [ 537118.9  -322049.38]]


  0%|          | 1/60000 [00:02<42:09:34,  2.53s/it]

loss is: 516359.0


  2%|▏         | 1000/60000 [05:45<5:30:52,  2.97it/s]

save model
learning_rate is:
 0.000196
real location is:
 [[ 4.52693515e+03  2.99784745e+02]
 [-5.36654937e+03 -7.62915958e+03]
 [ 2.42178563e+04  9.81383966e+02]
 [-7.52753750e+03 -6.69333340e+03]
 [ 2.78844044e+04  1.22327621e+03]
 [ 1.25905178e+04 -8.85172258e+03]
 [ 2.85947240e+04 -8.86650375e+03]
 [ 1.01954462e+04  4.70880064e+00]]
prediction is:
 [[ 8314.264  -2091.1538]
 [ 1334.6191 -2903.9236]
 [13429.379  -3246.421 ]
 [  974.1797 -1587.7667]
 [13780.556  -3829.6157]
 [ 9314.622  -4202.1826]
 [ 9342.154  -4183.26  ]
 [11648.426  -5022.796 ]]


  2%|▏         | 1001/60000 [05:45<6:39:51,  2.46it/s]

loss is: 8102.087


  3%|▎         | 2000/60000 [11:21<5:23:50,  2.99it/s]

save model
learning_rate is:
 0.00019208
real location is:
 [[-19753.0222626   -7137.1524289 ]
 [ 29019.4574544   -8693.01543653]
 [-30421.2051334    8641.62977769]
 [-28817.2563962  -15297.5831117 ]
 [-10723.2089575   -4964.87002822]
 [ 12209.6376271   -9601.38496861]
 [ -7633.95094444  -4749.9258858 ]
 [ 30772.1517097   -5914.16600382]]
prediction is:
 [[-20403.176   -3701.9238]
 [  7367.522   -8992.769 ]
 [-24430.023   -3105.9424]
 [-11547.099   -4711.4097]
 [-13934.988   -4613.777 ]
 [ 13623.812  -10242.785 ]
 [ -7196.0635  -6375.958 ]
 [ 29665.68   -10046.551 ]]


  3%|▎         | 2001/60000 [11:22<6:31:06,  2.47it/s]

loss is: 6604.1714


  5%|▌         | 3000/60000 [16:57<5:18:10,  2.99it/s]

save model
learning_rate is:
 0.0001882384
real location is:
 [[-30404.0772462   10954.1296457 ]
 [ 30861.6903915   -4028.99039655]
 [ 12553.0554096   -5251.17499089]
 [ 13155.5290823     613.0413734 ]
 [ 30635.9500947   -3452.7409843 ]
 [ -5938.61912015  -4272.45081555]
 [-16411.6819725   -5311.3164081 ]
 [ 23353.1000261    1023.94671283]]
prediction is:
 [[-24080.008    -1060.9204 ]
 [ 30152.324     -895.33563]
 [ -4847.7734   -6029.1904 ]
 [ 12910.589     -309.8767 ]
 [ 29598.984    -3705.2341 ]
 [ -8863.939    -4834.032  ]
 [-14608.891    -6221.795  ]
 [ 18952.416     2499.538  ]]


  5%|▌         | 3001/60000 [16:58<6:24:12,  2.47it/s]

loss is: 4287.091


  7%|▋         | 4000/60000 [22:33<5:12:44,  2.98it/s]

save model
learning_rate is:
 0.00018447363
real location is:
 [[-29811.2584728   -1302.81825678]
 [ -5692.0516286   -4006.64280538]
 [ 12787.3455848   -5055.35863215]
 [-26259.7807849   -5896.6898781 ]
 [-15016.8449282   -6862.33979289]
 [  8684.83111708 -10309.4653274 ]
 [ 13449.1604628   -9721.4223685 ]
 [-17915.7850097   -6970.43356294]]
prediction is:
 [[-27551.68     -3625.7468 ]
 [  -114.61755  -3645.8071 ]
 [  7705.114    -5091.3145 ]
 [-25069.586    -7968.168  ]
 [-12134.762    -5446.243  ]
 [ 12079.123    -3312.8708 ]
 [ 23094.062   -12341.86   ]
 [-16744.533    -7318.7363 ]]


  7%|▋         | 4001/60000 [22:34<6:17:59,  2.47it/s]

loss is: 3699.5803


  8%|▊         | 5000/60000 [28:09<5:07:51,  2.98it/s]

save model
learning_rate is:
 0.00018078416
real location is:
 [[-2.02765010e+04 -5.69389906e+03]
 [ 2.86879110e+04 -8.67121592e+03]
 [ 9.86544904e+03 -9.81899362e+03]
 [-2.74167142e+02 -2.11059511e+00]
 [ 3.32726609e+02 -1.54514356e+02]
 [-3.01656101e+04  5.43015182e+03]
 [ 3.09124766e+04 -7.79820741e+03]
 [-2.06837196e+04 -5.69860966e+03]]
prediction is:
 [[-23422.059    -6193.881  ]
 [ 17264.635    -7680.2593 ]
 [  9664.447    -8748.371  ]
 [  -197.1437    -622.45825]
 [-10853.381    -4005.8677 ]
 [-38267.4       4794.195  ]
 [ -4134.846    -7578.5386 ]
 [-27943.793    -7052.6846 ]]


  8%|▊         | 5001/60000 [28:09<6:11:16,  2.47it/s]

loss is: 6692.589


 10%|█         | 6000/60000 [33:45<5:01:42,  2.98it/s]

save model
learning_rate is:
 0.00017716849
real location is:
 [[-3.07204923e+04  7.60406809e+03]
 [ 1.22544977e+04  6.88096208e+02]
 [ 1.69337627e+04 -9.43026636e+03]
 [ 1.23715948e+04 -9.69519496e+03]
 [ 2.09108857e+04  8.10647018e+02]
 [-1.41603069e+04 -6.87406492e+03]
 [ 1.14315168e+04 -2.02691187e+00]
 [ 2.74798810e+04 -8.78224686e+03]]
prediction is:
 [[-25184.508   -1824.4741]
 [  9953.375     256.0539]
 [ 11563.969   -7486.8623]
 [  7613.9414 -10146.24  ]
 [ 10334.728   -1350.3608]
 [-12722.168   -7940.058 ]
 [  6993.6597  -7310.0674]
 [ 17443.613   -9605.67  ]]


 10%|█         | 6001/60000 [33:45<6:04:20,  2.47it/s]

loss is: 5316.1313


 12%|█▏        | 7000/60000 [39:21<4:56:15,  2.98it/s]

save model
learning_rate is:
 0.00017362511
real location is:
 [[ 1.24007255e+04 -3.80015679e+03]
 [-9.22827561e+03 -4.91926969e+03]
 [ 1.12211580e+04  2.16365891e+01]
 [-1.62654492e+04 -6.91853999e+03]
 [-2.94980429e+04 -3.99661662e+03]
 [-2.90731176e+04 -8.20660693e+03]
 [ 2.79978069e+04  1.04712292e+03]
 [-1.53532387e+04 -6.94555876e+03]]
prediction is:
 [[ 11871.762    -693.9946]
 [ -9377.286   -3698.168 ]
 [ 15976.685   -4800.046 ]
 [-12212.705   -4816.9497]
 [-33852.938    2578.5332]
 [ -4913.395   -3570.7485]
 [ 34114.957    3366.792 ]
 [-15388.115   -4298.084 ]]


 12%|█▏        | 7001/60000 [39:21<5:57:36,  2.47it/s]

loss is: 5590.751


 13%|█▎        | 8000/60000 [44:56<4:50:44,  2.98it/s]

save model
learning_rate is:
 0.00017015262
real location is:
 [[-29399.5216233   -5221.42383278]
 [ 11954.3195336    -284.72758356]
 [-28779.9307989  -17780.9230614 ]
 [  1683.10481143 -10212.0811334 ]
 [ 27496.2150154   -9028.56345004]
 [  4776.21303362   -147.23400141]
 [ 11021.0426726     619.9291123 ]
 [ 28128.8782183   -9026.11706721]]
prediction is:
 [[-15198.301    -5651.206  ]
 [ 10665.481    -2283.2463 ]
 [-32174.408   -16439.79   ]
 [   381.28033  -9583.896  ]
 [ 19155.168    -6746.9165 ]
 [ 11277.464    -4175.503  ]
 [ 11707.088     1763.2186 ]
 [ 26458.092    -5192.528  ]]


 13%|█▎        | 8001/60000 [44:57<5:50:38,  2.47it/s]

loss is: 4144.5244


 15%|█▌        | 9000/60000 [50:32<4:44:44,  2.99it/s]

save model
learning_rate is:
 0.00016674957
real location is:
 [[ 29445.9403257    1265.05066069]
 [ 10828.4630889     518.61536569]
 [ -1591.524436   -10675.4832614 ]
 [  9164.18949489  -9855.81332061]
 [ 28216.620006     1047.88751761]
 [ 28700.5024336    1196.56202795]
 [ 10074.9806254      43.84817428]
 [ 30609.6210102   -1313.23812946]]
prediction is:
 [[31143.855    -886.10364]
 [ 7833.6396   -659.8998 ]
 [ -465.23895 -6948.9805 ]
 [ 5546.384   -8571.74   ]
 [26339.248     864.2509 ]
 [22131.035     380.36047]
 [12536.734   -3301.946  ]
 [30466.582   -3121.383  ]]


 15%|█▌        | 9001/60000 [50:33<5:43:53,  2.47it/s]

loss is: 2731.4453


 17%|█▋        | 10000/60000 [56:08<4:40:55,  2.97it/s]

save model
learning_rate is:
 0.00016341459
real location is:
 [[ 10935.8784224   -9870.24763788]
 [ 30934.9173918   -7579.52620379]
 [   618.34872648    191.09632642]
 [ 27056.0410353     997.45714277]
 [-22447.0369709   -7103.41718431]
 [ 10048.8085883   -9778.3364633 ]
 [-28784.3907074  -20671.5866388 ]
 [-30480.5996448    9488.77559654]]
prediction is:
 [[  9765.771   -9328.619 ]
 [ 26272.13    -6741.798 ]
 [  4150.427   -4206.743 ]
 [ 25165.68     1294.7499]
 [-20106.059   -6770.0757]
 [  6283.17    -7589.9575]
 [-27805.795  -24422.52  ]
 [-30655.527   11936.042 ]]


 17%|█▋        | 10001/60000 [56:09<5:38:15,  2.46it/s]

loss is: 2600.7734


 18%|█▊        | 11000/60000 [1:01:44<4:33:53,  2.98it/s]

save model
learning_rate is:
 0.0001601463
real location is:
 [[ 27920.6663824    1041.6625443 ]
 [ -5935.22730034  -4328.07199889]
 [-15853.3001113   -5206.60910442]
 [-14592.2660525   -6865.99816121]
 [   472.56198073 -10401.1279368 ]
 [-29767.7727321    -711.35630051]
 [  8067.37036706    750.83115144]
 [-29539.7558143   -3351.79136244]]
prediction is:
 [[ 26421.574      480.46255]
 [ -4734.633    -3973.153  ]
 [-15777.59     -5368.1074 ]
 [-13363.824    -6783.4214 ]
 [  3960.3975  -12271.893  ]
 [-33640.582     -581.4004 ]
 [  7186.513     -889.6277 ]
 [-27955.945    -3183.3064 ]]


 18%|█▊        | 11001/60000 [1:01:45<5:30:39,  2.47it/s]

loss is: 1467.1135


 20%|██        | 12000/60000 [1:07:20<4:28:03,  2.98it/s]

save model
learning_rate is:
 0.00015694338
real location is:
 [[ -4924.34387866  -9257.5919026 ]
 [ 22061.3069036     955.32016637]
 [ -4598.27843745   -965.30650815]
 [   418.20083481 -10328.3952161 ]
 [ 24484.2003979    1089.22847326]
 [ -4822.52370734  -1134.95718964]
 [ -4661.24849729  -9901.12718688]
 [ -7108.5540368   -6663.62582519]]
prediction is:
 [[ -6309.757    -7981.033  ]
 [ 23391.068      147.44275]
 [ -3678.9412   -2498.533  ]
 [ -3745.7603  -12358.556  ]
 [ 24210.59       793.80414]
 [ -2026.8278   -1094.8734 ]
 [ -5551.4756  -10899.496  ]
 [ -6692.48     -6674.5693 ]]


 20%|██        | 12001/60000 [1:07:21<5:23:40,  2.47it/s]

loss is: 1495.8461


 22%|██▏       | 13000/60000 [1:12:56<4:23:04,  2.98it/s]

save model
learning_rate is:
 0.00015380452
real location is:
 [[ -9362.89337643  -6705.46974493]
 [  9865.44903627  -9818.99362332]
 [ -2125.16432576 -10541.3829524 ]
 [ 29328.7654729    1081.08899312]
 [-27807.4771669   -5917.48445639]
 [-29842.0717976   -1807.53011537]
 [   995.94018634    -99.29376103]
 [-14005.1539321   -5106.60915212]]
prediction is:
 [[ -8851.525    -5086.2695 ]
 [ 13131.02     -7175.56   ]
 [ -6563.3555   -9428.947  ]
 [ 26146.723      588.2534 ]
 [-24269.682    -5881.1924 ]
 [-30567.418    -2351.0476 ]
 [   375.7449     363.87793]
 [-12374.301    -4478.6475 ]]


 22%|██▏       | 13001/60000 [1:12:57<5:17:32,  2.47it/s]

loss is: 1986.7378


 23%|██▎       | 14000/60000 [1:18:32<4:16:58,  2.98it/s]

save model
learning_rate is:
 0.00015072842
real location is:
 [[ 23987.9429125   -9009.86885114]
 [-29432.7519626   -7334.56997142]
 [-24311.3564896   -5823.44027351]
 [ 12509.2714988     604.18386646]
 [ 25831.1601353    1144.44915936]
 [  6689.70191473 -10103.1471989 ]
 [  4281.04585258    289.54645432]
 [-29811.9775898      68.83418342]]
prediction is:
 [[ 17576.59     -8748.568  ]
 [-27510.82     -7140.63   ]
 [-19591.762    -5638.133  ]
 [ 12911.931      878.39514]
 [ 19087.254     -553.02045]
 [  2491.3433  -10257.899  ]
 [  4082.1252     -91.08937]
 [-27182.16     -1027.1343 ]]


 23%|██▎       | 14001/60000 [1:18:33<5:10:34,  2.47it/s]

loss is: 2457.0437


 25%|██▌       | 15000/60000 [1:24:08<4:12:46,  2.97it/s]

save model
learning_rate is:
 0.00014771386
real location is:
 [[ -9270.99814859  -6731.38979001]
 [ 12565.284275    -6978.90277297]
 [ 25831.1601353    1144.44915936]
 [-11886.7409056   -5060.01846275]
 [-28380.1651099   -5931.00294738]
 [-12382.1143094   -5074.80701233]
 [  1228.12217133 -10243.8451359 ]
 [-29546.0599336   -4942.00797483]]
prediction is:
 [[ -7973.255   -5660.9307]
 [ 11710.912   -6012.5923]
 [ 27916.936    1653.1129]
 [-10874.285   -5249.6353]
 [-26098.719   -5814.7534]
 [-10928.676   -4790.4043]
 [  2382.9683 -10095.925 ]
 [-31320.412   -5296.035 ]]


 25%|██▌       | 15001/60000 [1:24:09<5:05:00,  2.46it/s]

loss is: 1213.4459


 27%|██▋       | 16000/60000 [1:29:44<4:05:47,  2.98it/s]

save model
learning_rate is:
 0.00014475959
real location is:
 [[ -8393.98841594  -6708.0489686 ]
 [-28963.4153096  -14754.1794375 ]
 [ 30567.3755424   -2395.48868225]
 [-29007.6049325   -5859.81315841]
 [ 30619.9927843   -8358.97674225]
 [ 20070.5957594     805.86914898]
 [   341.79249692     73.16514451]
 [-30108.631483     3015.5668596 ]]
prediction is:
 [[ -8829.137    -6353.204  ]
 [-27320.94    -12919.692  ]
 [ 23792.723    -1860.0151 ]
 [-31154.535    -7068.7676 ]
 [ 32414.156    -9498.027  ]
 [ 19518.203      866.38226]
 [  1607.502      455.6383 ]
 [-25715.367      694.0777 ]]


 27%|██▋       | 16001/60000 [1:29:45<4:56:48,  2.47it/s]

loss is: 2095.4727


 28%|██▊       | 17000/60000 [1:35:20<4:00:15,  2.98it/s]

save model
learning_rate is:
 0.0001418644
real location is:
 [[ -1619.37510868 -10493.2863363 ]
 [-29251.8488324  -11586.7126375 ]
 [-29020.1495869  -13983.9152755 ]
 [ -7955.71790918  -6685.88494765]
 [-30710.7145607    8421.94861789]
 [ -7195.1304011   -4748.72224053]
 [-29077.8168634  -11325.0531233 ]
 [ 12985.9220739   -1494.45271512]]
prediction is:
 [[   973.5741 -11093.858 ]
 [-26353.293  -11218.751 ]
 [-27374.924  -14709.479 ]
 [ -9693.903   -6544.9805]
 [-29435.934    6392.2354]
 [ -8434.777   -4655.2046]
 [-32633.762  -12573.535 ]
 [ 12155.073   -1207.4059]]


 28%|██▊       | 17001/60000 [1:35:20<4:50:04,  2.47it/s]

loss is: 1660.1506


 30%|███       | 18000/60000 [1:40:56<3:54:43,  2.98it/s]

save model
learning_rate is:
 0.0001390271
real location is:
 [[  5663.13880399  -9985.08448297]
 [ 12649.1610473   -8254.73627219]
 [-29286.1909053  -13663.144762  ]
 [ 24637.7520662   -9017.06167827]
 [  1191.62498625 -10275.854581  ]
 [-30487.9048163    3907.42067961]
 [  9035.61837845  -9986.86913508]
 [ 27002.9510842    1108.27046235]]
prediction is:
 [[  1004.30365  -9698.574  ]
 [  8394.367    -7225.078  ]
 [-25664.814   -13532.809  ]
 [ 22886.691    -8138.667  ]
 [  2073.5503  -10176.203  ]
 [-25940.057     1266.7382 ]
 [  7998.0728  -10198.742  ]
 [ 26344.043     1918.4553 ]]


 30%|███       | 18001/60000 [1:40:56<4:43:31,  2.47it/s]

loss is: 2146.8447


 32%|███▏      | 19000/60000 [1:46:32<3:49:00,  2.98it/s]

save model
learning_rate is:
 0.00013624657
real location is:
 [[-29258.9679267  -14892.0047007 ]
 [  7354.06796903    433.07427335]
 [ 11961.0793949   -9606.64828928]
 [ -4612.93079063   -938.22066532]
 [ 27051.4142575   -8807.72238278]
 [  6481.09256116 -10024.664079  ]
 [-28747.728406   -18119.8248212 ]
 [ 30667.5231131   -1719.15602039]]
prediction is:
 [[-25558.707   -16021.941  ]
 [  7557.327      316.30948]
 [ 12793.296    -9004.697  ]
 [ -4219.4404   -1328.8823 ]
 [ 24136.793    -8749.5    ]
 [  5972.545    -8679.299  ]
 [-29415.266   -18188.588  ]
 [ 27198.98     -2214.5234 ]]


 32%|███▏      | 19001/60000 [1:46:32<4:36:39,  2.47it/s]

loss is: 1318.4031


 33%|███▎      | 20000/60000 [1:52:08<3:46:03,  2.95it/s]

save model
learning_rate is:
 0.00013352165
real location is:
 [[-30223.4424838    4457.28159021]
 [ 17848.9663707     823.36152453]
 [-23915.8024317   -7262.37806342]
 [-25264.6983881   -7473.48093967]
 [-25281.6647992   -7235.29338647]
 [ -3324.09812241   -510.8848763 ]
 [-20704.7193421   -7100.11720498]
 [ 30784.8754867   -2753.90230059]]
prediction is:
 [[-29371.844      1736.7498  ]
 [ 15373.22        -58.372437]
 [-22787.383     -7073.4766  ]
 [-24411.16      -7471.0454  ]
 [-23609.61      -7133.671   ]
 [ -2237.9512    -2950.5195  ]
 [-21163.545     -7447.2695  ]
 [ 32199.98      -1904.851   ]]


 33%|███▎      | 20001/60000 [1:52:08<4:31:44,  2.45it/s]

loss is: 1363.5022


 35%|███▌      | 21000/60000 [1:57:44<3:37:48,  2.98it/s]

save model
learning_rate is:
 0.00013085121
real location is:
 [[-15415.7516775   -5196.72133186]
 [-30264.9656723    5580.74094359]
 [-29616.43985     -2295.06479014]
 [ 12798.5330501   -7003.03089492]
 [-29842.0717976   -1807.53011537]
 [ 30678.4038322   -4058.64467399]
 [-11280.58787     -6831.30146701]
 [ 12659.6699597   -7720.54965029]]
prediction is:
 [[-14225.408   -5259.9424]
 [-32909.12     7434.9854]
 [-27116.223   -2596.479 ]
 [ 13608.615   -6418.2246]
 [-32459.438    -715.072 ]
 [ 29583.145   -4275.5283]
 [-11207.189   -6747.0845]
 [ 11370.828   -6706.1875]]


 35%|███▌      | 21001/60000 [1:57:44<4:22:56,  2.47it/s]

loss is: 1360.2592


 37%|███▋      | 22000/60000 [2:03:19<3:32:22,  2.98it/s]

save model
learning_rate is:
 0.0001282342
real location is:
 [[-11957.8245273   -5013.56010478]
 [  6441.69959065    -57.51278448]
 [-13421.8033281   -5131.50385438]
 [   722.71882442    139.48922552]
 [-24126.7080502   -7266.71083797]
 [ 30692.1419051   -4278.14810858]
 [-30244.0064008    8296.66348878]
 [-13009.382904    -6882.93501692]]
prediction is:
 [[-10427.494    -4445.7847 ]
 [  5308.0967    -443.2527 ]
 [-11052.484    -4898.6934 ]
 [   864.1194     209.87387]
 [-22274.902    -5804.379  ]
 [ 30206.16     -4168.82   ]
 [-36391.92      9832.967  ]
 [-12363.16     -5875.477  ]]


 37%|███▋      | 22001/60000 [2:03:20<4:16:28,  2.47it/s]

loss is: 1535.8398


 38%|███▊      | 23000/60000 [2:08:55<3:26:44,  2.98it/s]

save model
learning_rate is:
 0.00012566951
real location is:
 [[ -5042.565398    -1809.88959908]
 [ 26484.6855142    1040.67595286]
 [-11925.8036322   -6774.95118026]
 [ 17442.5164842    1045.69947516]
 [  1335.3638389     173.42421258]
 [ 12720.8397316     609.17944039]
 [ -9297.99429906  -6750.77760151]
 [-28910.0234128  -13696.7511889 ]]
prediction is:
 [[ -4986.6514   -1910.5979 ]
 [ 28109.584     1568.2393 ]
 [-11476.126    -6441.9365 ]
 [ 16287.703     1709.4453 ]
 [   898.54224    663.1896 ]
 [ 12009.625      899.0023 ]
 [-10036.978    -6855.832  ]
 [-28809.594   -13812.902  ]]


 38%|███▊      | 23001/60000 [2:08:56<4:09:34,  2.47it/s]

loss is: 615.5186


 40%|████      | 24000/60000 [2:14:31<3:21:04,  2.98it/s]

save model
learning_rate is:
 0.00012315613
real location is:
 [[-29271.5516128  -17114.9485818 ]
 [-28322.9020829  -22249.4334224 ]
 [ -7964.21369998  -6723.4802807 ]
 [-30868.1034646   12895.9680607 ]
 [  4969.69123553 -10095.7266037 ]
 [-28910.0234128  -13696.7511889 ]
 [ 30902.5360441   -4880.49075987]
 [-30415.8493212    3809.70409319]]
prediction is:
 [[-29753.45   -17183.295 ]
 [-28563.297  -21585.797 ]
 [ -7019.0566  -6681.868 ]
 [-31729.662   15814.318 ]
 [  6194.92    -9487.379 ]
 [-25881.055  -11756.152 ]
 [ 30279.592   -4607.793 ]
 [-31181.598    4735.8374]]


 40%|████      | 24001/60000 [2:14:32<4:02:54,  2.47it/s]

loss is: 1218.099


 42%|████▏     | 25000/60000 [2:20:07<3:19:09,  2.93it/s]

save model
learning_rate is:
 0.000120693
real location is:
 [[ 15978.9343768   -9557.11848497]
 [-13977.3846954   -5129.28746709]
 [-13505.0454519   -6841.47046975]
 [-28782.2810235  -17644.056876  ]
 [-29465.5510593   -4878.44902056]
 [ 11021.0426726     619.9291123 ]
 [-28611.0104093  -20955.4409979 ]
 [-29844.6656671     317.66306805]]
prediction is:
 [[ 13774.77    -9896.623 ]
 [-12607.967   -4204.0938]
 [-13340.5     -5674.4233]
 [-26725.809  -16507.582 ]
 [-24920.424   -3776.0295]
 [  9647.096     602.5066]
 [-25311.57   -19858.953 ]
 [-29799.469    1392.5947]]


 42%|████▏     | 25001/60000 [2:20:08<3:58:46,  2.44it/s]

loss is: 1710.7712


 43%|████▎     | 26000/60000 [2:25:43<3:10:09,  2.98it/s]

save model
learning_rate is:
 0.000118279146
real location is:
 [[ 2.35761490e+04  1.03349659e+03]
 [-2.85593846e+04 -2.25605194e+04]
 [ 1.06071754e+04  1.45482499e+01]
 [-1.41908668e+04 -5.39040788e+03]
 [-2.52816648e+04 -7.23529339e+03]
 [ 1.91222225e+04 -9.31232088e+03]
 [ 2.16665001e+03  8.25615539e+01]
 [-3.09732114e+04  9.71627673e+03]]
prediction is:
 [[ 23489.22      1513.9076 ]
 [-30131.451   -24971.824  ]
 [ 11191.064     -685.0783 ]
 [-12605.428    -5239.032  ]
 [-24607.594    -7415.3027 ]
 [ 20345.305    -9859.564  ]
 [  4792.218      400.66754]
 [-33251.582    10762.916  ]]


 43%|████▎     | 26001/60000 [2:25:44<3:49:26,  2.47it/s]

loss is: 1284.7


 45%|████▌     | 27000/60000 [2:31:19<3:04:22,  2.98it/s]

save model
learning_rate is:
 0.000115913565
real location is:
 [[  3245.77026591 -10646.4815034 ]
 [ 15738.9013388     789.65694242]
 [ -5215.09921166  -5796.71791835]
 [-29847.5484271    -982.92959151]
 [-24100.079791    -5809.6990611 ]
 [  3989.2713504  -10082.9710726 ]
 [-16861.4715773   -5355.97394864]
 [-30415.8493212    3809.70409319]]
prediction is:
 [[  3189.7249   -9375.191  ]
 [ 13217.414     1224.4144 ]
 [ -3908.1113   -5199.9004 ]
 [-28944.352      386.16345]
 [-22759.055    -5011.0547 ]
 [  4608.01     -9357.078  ]
 [-17031.25     -4838.6626 ]
 [-29618.586     4195.007  ]]


 45%|████▌     | 27001/60000 [2:31:20<3:42:46,  2.47it/s]

loss is: 1077.6301


 47%|████▋     | 28000/60000 [2:36:55<2:58:48,  2.98it/s]

save model
learning_rate is:
 0.00011359529
real location is:
 [[-30413.9307472    8452.8166256 ]
 [  1974.09900772    170.64864495]
 [-25264.6983881   -7473.48093967]
 [  1938.98577878 -10292.8190225 ]
 [-28344.6339745   -7647.9979423 ]
 [-17387.3897506   -7015.18402488]
 [  7361.57040289    380.12973149]
 [-14188.2721286   -5142.09035738]]
prediction is:
 [[-30490.21      8263.709  ]
 [  2300.5205     737.52783]
 [-23855.46     -6430.222  ]
 [  2660.4705   -9171.816  ]
 [-26976.23     -6994.785  ]
 [-17712.63     -6453.0757 ]
 [  8370.22       365.51752]
 [-13334.203    -5178.9033 ]]


 47%|████▋     | 28001/60000 [2:36:56<3:35:56,  2.47it/s]

loss is: 801.31915


 48%|████▊     | 29000/60000 [2:42:31<2:53:17,  2.98it/s]

save model
learning_rate is:
 0.00011132339
real location is:
 [[ 23986.7911607    1040.71686083]
 [ 30902.5429316   -7372.73711049]
 [-25420.8501945   -5874.82593064]
 [ 10317.9826371   -9798.78683053]
 [-21762.7581673   -7167.1179809 ]
 [  9306.30164505  -9822.33682688]
 [-26826.084133    -5984.33633703]
 [-29193.4397706  -19339.9741585 ]]
prediction is:
 [[ 25402.547     957.7142]
 [ 34733.26    -6192.974 ]
 [-26441.484   -5909.685 ]
 [  8604.975   -9934.85  ]
 [-21994.867   -7637.953 ]
 [  8886.977   -9393.607 ]
 [-23633.51    -5924.2104]
 [-28050.986  -19572.117 ]]


 48%|████▊     | 29001/60000 [2:42:32<3:29:17,  2.47it/s]

loss is: 1216.5754


 50%|█████     | 30000/60000 [2:48:07<2:49:52,  2.94it/s]

save model
learning_rate is:
 0.00010909693
real location is:
 [[-22199.4034054   -5578.14026094]
 [ 17112.6436792   -9332.86585357]
 [ 20184.8627414   -9204.89170116]
 [ 21157.5717624    1002.51089964]
 [ 29250.1694061    1068.70721342]
 [  3238.71768371    247.49857241]
 [-27803.6636604   -5931.7443907 ]
 [ -1722.8529865    -293.14477294]]
prediction is:
 [[-21096.586    -5674.4927 ]
 [ 16637.004    -9037.579  ]
 [ 17947.355    -9206.056  ]
 [ 18511.006      912.7196 ]
 [ 26355.898      427.69687]
 [  4667.8066    1013.2517 ]
 [-28746.91     -5989.6826 ]
 [ -1922.1622     264.1657 ]]


 50%|█████     | 30001/60000 [2:48:08<3:24:01,  2.45it/s]

loss is: 1126.066


 52%|█████▏    | 31000/60000 [2:53:43<2:42:01,  2.98it/s]

save model
learning_rate is:
 0.00010691498
real location is:
 [[-2.85613526e+04 -7.78624122e+03]
 [-1.46981062e+04 -5.25690600e+03]
 [-2.49476642e+04 -5.84164442e+03]
 [-6.98873457e+03 -4.72956684e+03]
 [ 1.04867687e+03 -3.56241426e+00]
 [ 3.05225541e+04 -1.97367433e+03]
 [ 1.70923448e+04 -9.57427878e+03]
 [-5.59546230e+03 -7.13933128e+03]]
prediction is:
 [[-26972.14    -6630.9844]
 [-14819.232   -5173.9614]
 [-25428.914   -5779.073 ]
 [ -6759.546   -4819.5107]
 [   693.2274   -677.4225]
 [ 28948.135   -2277.3076]
 [ 17073.834   -9035.875 ]
 [ -6055.75    -7294.255 ]]


 52%|█████▏    | 31001/60000 [2:53:44<3:15:43,  2.47it/s]

loss is: 614.92834


 53%|█████▎    | 32000/60000 [2:59:19<2:36:22,  2.98it/s]

save model
learning_rate is:
 0.00010477669
real location is:
 [[ -9480.9570996   -6809.23933152]
 [-16930.524906    -6972.94693751]
 [ -9169.2574333   -4893.68512424]
 [ -4593.52627047   -944.82145807]
 [ 22152.9145116   -9012.65366606]
 [ 12797.2691413   -6108.64079844]
 [-30480.5996448    9488.77559654]
 [ 31055.8033297   -7039.70452613]]
prediction is:
 [[ -9304.008   -6367.666 ]
 [-18442.277   -7283.953 ]
 [ -9747.088   -4871.285 ]
 [ -3387.1724  -1240.9266]
 [ 21324.309   -9495.063 ]
 [ 12595.485   -5817.2817]
 [-29137.926   10134.947 ]
 [ 32304.562   -8016.5615]]


 53%|█████▎    | 32001/60000 [2:59:20<3:09:00,  2.47it/s]

loss is: 823.64465


 55%|█████▌    | 33000/60000 [3:04:55<2:30:47,  2.98it/s]

save model
learning_rate is:
 0.00010268116
real location is:
 [[ -5154.91032095  -2238.19149189]
 [-19666.889617    -6976.27315938]
 [-29452.2133884   -6565.48876116]
 [-12977.8232657   -6876.32105867]
 [ 12375.2798783   -9802.72742754]
 [-30082.4189854    2830.66558795]
 [-27384.956958    -5884.84757235]
 [-11931.0254229   -6818.34128438]]
prediction is:
 [[ -5174.919   -1766.0405]
 [-19638.352   -6432.9463]
 [-28418.127   -5622.3506]
 [-11890.137   -6464.477 ]
 [ 11053.7295  -8915.85  ]
 [-30855.256    2986.0234]
 [-24052.63    -5329.2085]
 [-10067.139   -7143.328 ]]


 55%|█████▌    | 33001/60000 [3:04:56<3:02:10,  2.47it/s]

loss is: 1072.9941


 57%|█████▋    | 34000/60000 [3:10:31<2:25:19,  2.98it/s]

save model
learning_rate is:
 0.00010062754
real location is:
 [[ 31079.20038     -7573.40388109]
 [ 23234.9593549     876.98094783]
 [-27410.4125596   -7536.68219328]
 [ -5698.40934563  -7074.41237495]
 [ -6375.40655212  -6632.08638361]
 [-16246.071203    -6952.94529395]
 [-16128.1165435   -6970.91035948]
 [ 15699.7495659     729.33275686]]
prediction is:
 [[ 30426.596    -7334.039  ]
 [ 22610.936      365.13095]
 [-26028.496    -7124.7974 ]
 [ -3578.39     -7852.4307 ]
 [ -7740.9697   -6755.748  ]
 [-15572.731    -6855.9414 ]
 [-15737.7705   -7217.2485 ]
 [ 15263.506      829.1855 ]]


 57%|█████▋    | 34001/60000 [3:10:32<2:55:24,  2.47it/s]

loss is: 791.5683


 58%|█████▊    | 35000/60000 [3:16:07<2:21:49,  2.94it/s]

save model
learning_rate is:
 9.861498e-05
real location is:
 [[-28344.4934318   -7760.22100413]
 [ 13196.0067052     -67.43281217]
 [-28926.0440763  -13836.59128   ]
 [-30649.6313261    5335.02091923]
 [ 11043.7845686   -9757.52431883]
 [ 29460.8431947    1071.92537496]
 [-24972.7600188   -5853.7646025 ]
 [  4315.86825784 -10231.1049963 ]]
prediction is:
 [[-28892.621    -7685.9204 ]
 [ 13478.482     -139.97723]
 [-27840.273   -13406.009  ]
 [-28086.367     5787.784  ]
 [ 10768.734    -8231.623  ]
 [ 28853.879      910.96906]
 [-24319.107    -6050.869  ]
 [  3427.3677   -9695.814  ]]


 58%|█████▊    | 35001/60000 [3:16:08<2:50:06,  2.45it/s]

loss is: 807.28876


 60%|██████    | 36000/60000 [3:21:43<2:14:04,  2.98it/s]

save model
learning_rate is:
 9.664269e-05
real location is:
 [[ 12649.5631192   -6250.48000797]
 [ 12800.2581635   -4792.45572806]
 [ 26067.9427301   -9044.58135663]
 [-21179.5900384   -5638.01450417]
 [ -9013.3811083   -6767.22133496]
 [ 21689.0495744   -9113.05621978]
 [ -2262.77167997   -354.87361736]
 [-16109.690939    -6900.62828367]]
prediction is:
 [[ 12741.785   -5822.3516]
 [ 14877.328   -5099.5166]
 [ 23714.904   -9983.668 ]
 [-20377.105   -5732.6006]
 [ -7745.3164  -6907.4585]
 [ 21026.01    -8942.02  ]
 [ -2426.9136   -293.9937]
 [-15249.758   -7171.647 ]]


 60%|██████    | 36001/60000 [3:21:44<2:42:00,  2.47it/s]

loss is: 833.75684


 62%|██████▏   | 37000/60000 [3:27:19<2:08:37,  2.98it/s]

save model
learning_rate is:
 9.470984e-05
real location is:
 [[ 17776.2627957   -9450.14505378]
 [  7959.86435478    446.20335105]
 [ 24858.4419928   -8954.26140686]
 [ -4906.04537202  -1344.8223196 ]
 [-29277.9558517  -16860.9312673 ]
 [ 12397.4256595   -3019.50298998]
 [  4058.12687875 -10153.8663522 ]
 [-30014.8755328    1845.04796825]]
prediction is:
 [[ 17773.652   -9724.766 ]
 [  9033.387     249.0709]
 [ 23411.98    -8382.023 ]
 [ -4447.3936  -1534.3369]
 [-28547.637  -18368.152 ]
 [ 12984.75    -2834.9292]
 [  3160.8354  -9223.6875]
 [-26948.508    1359.0116]]


 62%|██████▏   | 37001/60000 [3:27:20<2:35:15,  2.47it/s]

loss is: 983.1542


 63%|██████▎   | 38000/60000 [3:32:55<2:02:51,  2.98it/s]

save model
learning_rate is:
 9.2815644e-05
real location is:
 [[-29172.5447501  -19584.9415763 ]
 [  1352.65949891 -10369.3222072 ]
 [-12239.1717809   -6815.80950984]
 [ -5233.67315233  -2502.34725382]
 [ 31217.7116569   -3913.15128303]
 [ 29448.1720984   -8665.807133  ]
 [ 29350.0470508    1202.36825097]
 [-29577.0172556   -3412.45095139]]
prediction is:
 [[-25993.309   -16958.848  ]
 [   940.35315 -10348.447  ]
 [-12879.15     -6730.8315 ]
 [ -5027.626    -2332.81   ]
 [ 29214.115    -3488.6794 ]
 [ 25900.766    -9578.825  ]
 [ 29196.225     1490.2645 ]
 [-28148.633    -2390.7593 ]]


 63%|██████▎   | 38001/60000 [3:32:56<2:28:22,  2.47it/s]

loss is: 1335.8914


 65%|██████▌   | 39000/60000 [3:38:31<1:57:26,  2.98it/s]

save model
learning_rate is:
 9.095934e-05
real location is:
 [[ 21835.3454894     949.98676866]
 [-28822.9198083  -15655.8857077 ]
 [-28389.4333082  -21570.2076843 ]
 [-15654.7564288   -5200.49509483]
 [-10925.7991949   -4941.66418959]
 [  4563.36802018 -10112.215186  ]
 [ 11967.1203329   -9825.77165371]
 [  2330.57948839 -10661.9041325 ]]
prediction is:
 [[ 19211.027     695.5443]
 [-27970.17   -14553.427 ]
 [-30436.86   -21945.793 ]
 [-16274.534   -5111.0195]
 [-10838.298   -4748.424 ]
 [  3198.7056  -8860.997 ]
 [ 11493.578   -9431.742 ]
 [  2359.954  -10970.631 ]]


 65%|██████▌   | 39001/60000 [3:38:32<2:21:45,  2.47it/s]

loss is: 941.2964


 67%|██████▋   | 40000/60000 [3:44:07<1:53:16,  2.94it/s]

save model
learning_rate is:
 8.914014e-05
real location is:
 [[-8.62419049e+03 -4.80730134e+03]
 [ 1.13060521e+04 -9.76455206e+03]
 [ 3.07329510e+04 -3.56661795e+03]
 [-1.12402558e+04 -5.03910178e+03]
 [ 9.38157297e+03  9.80780326e+00]
 [ 1.68475169e+03 -1.03079704e+04]
 [-2.89718211e+04 -1.29595422e+04]
 [-6.37621007e+03 -4.64302943e+03]]
prediction is:
 [[ -7625.09     -4365.3623 ]
 [ 11669.035    -9252.708  ]
 [ 30821.91     -3774.2397 ]
 [-10097.574    -4555.763  ]
 [  8443.119      249.94937]
 [  4117.9707  -10648.358  ]
 [-29166.062   -12497.82   ]
 [ -6518.6323   -3970.3904 ]]


 67%|██████▋   | 40001/60000 [3:44:08<2:16:00,  2.45it/s]

loss is: 753.2606


 68%|██████▊   | 41000/60000 [3:49:43<1:46:08,  2.98it/s]

save model
learning_rate is:
 8.7357344e-05
real location is:
 [[-21105.7240496   -5689.88341899]
 [-30243.9511099    4902.04841361]
 [-17815.4532405   -7026.2158966 ]
 [-24007.8752793   -5817.94490169]
 [ 12940.2023803     614.90470639]
 [-29077.8168634  -11325.0531233 ]
 [ -4340.09044284 -10240.6162167 ]
 [ -3105.79622454   -467.58395663]]
prediction is:
 [[-20382.969    -6100.402  ]
 [-29925.172     5652.795  ]
 [-17330.965    -7315.382  ]
 [-23215.865    -5835.426  ]
 [ 11447.037     -344.386  ]
 [-28426.723   -12016.628  ]
 [ -3923.5195  -10574.836  ]
 [ -4226.147      146.28458]]


 68%|██████▊   | 41001/60000 [3:49:44<2:08:12,  2.47it/s]

loss is: 784.85516


 70%|███████   | 42000/60000 [3:55:19<1:40:30,  2.99it/s]

save model
learning_rate is:
 8.56102e-05
real location is:
 [[-3.01675908e+04  1.00945813e+03]
 [ 3.11913570e+04 -4.47572321e+03]
 [ 3.01797314e+04 -8.54017070e+03]
 [ 2.80484249e+02  1.04694421e+02]
 [-9.67324420e+02 -1.04846883e+04]
 [ 1.73143763e+04  8.24110022e+02]
 [-2.74167142e+02 -2.11059511e+00]
 [ 1.25341191e+04 -5.29358311e+03]]
prediction is:
 [[-31186.102      777.4778 ]
 [ 29091.217    -4339.384  ]
 [ 30650.975    -7736.3584 ]
 [   360.18182   -431.69373]
 [ -1021.0424  -10517.287  ]
 [ 16733.604     1097.9089 ]
 [   118.47865    145.84363]
 [ 11856.69     -4921.5225 ]]


 70%|███████   | 42001/60000 [3:55:20<2:01:22,  2.47it/s]

loss is: 616.34143


 72%|███████▏  | 43000/60000 [4:00:55<1:34:56,  2.98it/s]

save model
learning_rate is:
 8.3898e-05
real location is:
 [[-12926.2354366   -5315.79902951]
 [ 12469.9312892   -4019.27534049]
 [-16128.1165435   -6970.91035948]
 [ 11673.202356      569.86946644]
 [ -2127.04467102   -332.70879338]
 [-15630.617731    -5197.83330797]
 [-16876.8213524   -6918.57973288]
 [-12363.9135459   -5067.19033397]]
prediction is:
 [[-13036.571    -4850.3604 ]
 [ 11418.29     -4353.0293 ]
 [-15371.589    -6476.352  ]
 [ 10574.014      913.50476]
 [ -1982.516     -497.2659 ]
 [-14975.719    -4801.3184 ]
 [-17395.104    -6782.7896 ]
 [-11337.899    -5045.491  ]]


 72%|███████▏  | 43001/60000 [4:00:56<1:54:38,  2.47it/s]

loss is: 601.3624


 73%|███████▎  | 44000/60000 [4:06:32<1:29:25,  2.98it/s]

save model
learning_rate is:
 8.222004e-05
real location is:
 [[ 30381.0929245     148.3479657 ]
 [ 11967.1203329   -9825.77165371]
 [  9306.30164505  -9822.33682688]
 [-17503.599461    -5603.49870894]
 [ 30772.1517097   -5914.16600382]
 [ 30498.7616517      98.24376811]
 [  8018.22785067  -9931.56648653]
 [ 15178.3170186   -9561.73419374]]
prediction is:
 [[ 27672.361     -603.72363]
 [ 11548.494    -8727.642  ]
 [  8240.014    -9367.149  ]
 [-16969.352    -5958.2393 ]
 [ 29659.484    -5417.0664 ]
 [ 27487.363     -302.15833]
 [  8318.58     -9425.146  ]
 [ 13894.338    -9709.363  ]]


 73%|███████▎  | 44001/60000 [4:06:32<1:47:58,  2.47it/s]

loss is: 1142.8123


 75%|███████▌  | 45000/60000 [4:12:08<1:24:57,  2.94it/s]

save model
learning_rate is:
 8.0575635e-05
real location is:
 [[-30055.307289     2418.54643296]
 [ -5757.60870366  -3759.59251213]
 [ 15738.9013388     789.65694242]
 [ 14951.5703538   -9579.62882744]
 [  3920.50750875   -163.55706509]
 [ -7428.26759455  -4812.82887542]
 [ -1241.04157508 -10462.3539642 ]
 [-24220.5093651   -5823.10107272]]
prediction is:
 [[-31122.96      2278.197  ]
 [ -7163.881    -3417.8018 ]
 [ 13310.15       398.6277 ]
 [ 16665.08     -9317.511  ]
 [  3128.9365    -104.82645]
 [ -6380.825    -4313.723  ]
 [ -5143.124    -9915.215  ]
 [-24526.453    -5514.3506 ]]


 75%|███████▌  | 45001/60000 [4:12:08<1:41:56,  2.45it/s]

loss is: 1186.8967


 77%|███████▋  | 46000/60000 [4:17:43<1:18:14,  2.98it/s]

save model
learning_rate is:
 7.896413e-05
real location is:
 [[ -5305.61637438  -8316.68236731]
 [ 12491.8263036   -4267.59353015]
 [ 16205.9894523   -9558.62081182]
 [ 30571.2837304    -500.42877575]
 [ 16737.4470537     755.11145527]
 [-12094.8237555   -5095.88282342]
 [ 19632.0567576     892.33975788]
 [ 24397.6122839    1032.7605676 ]]
prediction is:
 [[ -3296.7676   -7607.7593 ]
 [ 11309.327    -3625.5356 ]
 [ 14028.908    -8217.163  ]
 [ 32030.574     -354.16452]
 [ 15687.805     1170.8466 ]
 [-11826.754    -4617.623  ]
 [ 17374.604     1087.9894 ]
 [ 22622.986      961.8192 ]]


 77%|███████▋  | 46001/60000 [4:17:44<1:34:29,  2.47it/s]

loss is: 1262.2527


 78%|███████▊  | 47000/60000 [4:23:19<1:12:35,  2.99it/s]

save model
learning_rate is:
 7.7384844e-05
real location is:
 [[-24709.2891939   -5732.13708419]
 [ -5692.0516286   -4006.64280538]
 [ 13329.5422483     763.05755242]
 [ 19926.6438919   -9277.4242395 ]
 [-16702.5654612   -6960.80154537]
 [-29615.444632    -4065.78189884]
 [  5180.43129989    160.93060094]
 [   995.94018634    -99.29376103]]
prediction is:
 [[-23824.633    -5198.2534 ]
 [ -5394.615    -3656.542  ]
 [ 12975.449     1409.418  ]
 [ 19472.543    -9095.783  ]
 [-16565.367    -6790.2617 ]
 [-30141.402    -3577.0918 ]
 [  5556.3022     142.86566]
 [  -335.4459     375.45972]]


 78%|███████▊  | 47001/60000 [4:23:20<1:27:37,  2.47it/s]

loss is: 562.876


 80%|████████  | 48000/60000 [4:28:55<1:07:00,  2.98it/s]

save model
learning_rate is:
 7.583715e-05
real location is:
 [[-13576.1979857   -5098.80219262]
 [-10344.3115043   -4976.18598688]
 [  5003.13151912    466.84385901]
 [   938.78237645    112.15681209]
 [ 20763.1923816   -9158.87190514]
 [ -5481.94099134  -7388.21941896]
 [ -4244.85025539 -10319.4904744 ]
 [-13910.2024895   -6865.14921481]]
prediction is:
 [[-13161.859    -4954.345  ]
 [-10093.166    -4816.455  ]
 [  5179.688      143.62979]
 [  1937.4086    -125.31654]
 [ 19393.188    -9010.892  ]
 [ -4169.8994   -7429.631  ]
 [ -4519.416    -9696.004  ]
 [-12569.911    -6873.3125 ]]


 80%|████████  | 48001/60000 [4:28:56<1:20:53,  2.47it/s]

loss is: 609.65924


 82%|████████▏ | 49000/60000 [4:34:31<1:01:25,  2.98it/s]

save model
learning_rate is:
 7.432041e-05
real location is:
 [[ 12438.9096263   -4291.03225871]
 [ -3158.97738623 -10513.7120451 ]
 [ 12585.367144    -3691.21353485]
 [-29077.8168634  -11325.0531233 ]
 [ 29175.121294     1252.89273219]
 [-30433.4672912   12044.9270703 ]
 [ -9892.19942817  -4946.93007741]
 [   854.53264121 -10668.0585664 ]]
prediction is:
 [[ 11854.881   -3432.719 ]
 [ -3422.3394  -9708.155 ]
 [ 12104.636   -3690.232 ]
 [-28525.469  -11295.492 ]
 [ 28043.55     1594.1926]
 [-27206.533   10901.521 ]
 [ -9488.629   -4422.6074]
 [  1728.0668  -9501.975 ]]


 82%|████████▏ | 49001/60000 [4:34:31<1:14:12,  2.47it/s]

loss is: 966.11365


 83%|████████▎ | 50000/60000 [4:40:07<58:16,  2.86it/s]  

save model
learning_rate is:
 7.2834e-05
real location is:
 [[ -5031.5992594   -7217.98559905]
 [-13977.3846954   -5129.28746709]
 [-13505.0454519   -6841.47046975]
 [-16861.4715773   -5355.97394864]
 [-30206.0970139    4186.70585648]
 [-12967.4682215   -5077.72716455]
 [ 20522.3056692   -9170.0406013 ]
 [-30681.5259986    5767.54260749]]
prediction is:
 [[ -3793.767   -7425.039 ]
 [-13749.076   -4709.079 ]
 [-11860.926   -6158.1553]
 [-17210.947   -5094.7275]
 [-29878.086    3958.7466]
 [-12421.98    -4805.4565]
 [ 21262.047   -9180.861 ]
 [-30631.555    5862.5215]]


 83%|████████▎ | 50001/60000 [4:40:07<1:09:10,  2.41it/s]

loss is: 568.8222


 85%|████████▌ | 51000/60000 [4:45:43<50:18,  2.98it/s]  

save model
learning_rate is:
 7.1377326e-05
real location is:
 [[-19695.4398105   -7002.42470684]
 [  3863.26337047 -10541.6147523 ]
 [-28776.8565025  -16525.0212611 ]
 [  6752.80302023    412.81429059]
 [-30265.9309894    6746.06142414]
 [ 18439.4297345   -9339.22177812]
 [  4436.88119352 -10342.8507654 ]
 [ 11747.6051398   -9686.89934983]]
prediction is:
 [[-20153.441   -6923.3486]
 [  3133.9314  -9888.393 ]
 [-28204.812  -15737.378 ]
 [  7179.004     624.6402]
 [-29995.914    5555.613 ]
 [ 17911.53    -9454.561 ]
 [  4753.385   -9969.686 ]
 [ 10497.252   -9172.833 ]]


 85%|████████▌ | 51001/60000 [4:45:43<1:00:47,  2.47it/s]

loss is: 660.56116


 87%|████████▋ | 52000/60000 [4:51:19<44:42,  2.98it/s]  

save model
learning_rate is:
 6.994978e-05
real location is:
 [[ -4193.81893988   -751.73916678]
 [-29077.8168634  -11325.0531233 ]
 [ 30732.9509678   -3566.61795008]
 [ -5952.42909976  -6767.2923627 ]
 [ 25090.3337373    1018.39067624]
 [-12172.3034748   -6787.97614326]
 [ -5135.14418269  -2126.46664013]
 [-28509.1081436  -23604.1813882 ]]
prediction is:
 [[ -3619.3037    -585.3359 ]
 [-30438.291   -11899.428  ]
 [ 29640.533    -3809.8176 ]
 [ -5378.298    -5925.5386 ]
 [ 23992.64       291.86096]
 [-12462.466    -6807.772  ]
 [ -5238.066    -2063.672  ]
 [-27448.66    -24885.918  ]]


 87%|████████▋ | 52001/60000 [4:51:19<54:00,  2.47it/s]

loss is: 785.1118


 88%|████████▊ | 53000/60000 [4:56:55<39:08,  2.98it/s]

save model
learning_rate is:
 6.8550784e-05
real location is:
 [[ 11044.2626576     535.74939776]
 [ 17757.6066627     851.24659564]
 [ 29919.8077977   -8642.62517548]
 [ 27625.1786201    1022.57165615]
 [-29030.0959255  -12259.4231092 ]
 [-19695.4398105   -7002.42470684]
 [ 10000.2053138     770.45363305]
 [  -195.61245128 -10327.9483714 ]]
prediction is:
 [[  9864.416      116.94623]
 [ 16443.         902.10394]
 [ 27879.95     -8241.717  ]
 [ 25918.34      1037.8922 ]
 [-27934.379   -12842.641  ]
 [-18287.438    -6553.3076 ]
 [  8186.172      900.2885 ]
 [  -237.63266  -9404.962  ]]


 88%|████████▊ | 53001/60000 [4:56:55<47:15,  2.47it/s]

loss is: 1058.7556


 90%|█████████ | 54000/60000 [5:02:31<33:33,  2.98it/s]

save model
learning_rate is:
 6.7179775e-05
real location is:
 [[-18936.1533667   -5375.59343796]
 [-30203.7750266    4220.73242351]
 [ -8438.75645649  -5088.93296459]
 [ 15598.6053794     728.44057186]
 [-29549.5413307   -3818.31974348]
 [-23172.5036554   -5761.24417067]
 [ 31027.5242615   -6742.96860153]
 [-29191.1287837   -9448.98632914]]
prediction is:
 [[-17950.867    -5225.5293 ]
 [-26558.887     3930.5166 ]
 [ -8086.2734   -4584.941  ]
 [ 14424.184      700.90063]
 [-28563.426    -3388.0762 ]
 [-21761.264    -5872.089  ]
 [ 30607.451    -7007.6357 ]
 [-28696.877    -9570.531  ]]


 90%|█████████ | 54001/60000 [5:02:32<40:31,  2.47it/s]

loss is: 886.5576


 92%|█████████▏| 55000/60000 [5:08:07<28:40,  2.91it/s]

save model
learning_rate is:
 6.5836175e-05
real location is:
 [[ 19796.3699083    1037.5110907 ]
 [ 11268.2602918   -9744.93936309]
 [  3052.79326594 -10699.8861156 ]
 [   790.63998771   -110.72575648]
 [-30153.4040486    4988.50648761]
 [ 19467.3750725   -9580.27553572]
 [ 30645.3771888   -2063.79625124]
 [ 18172.9640874     850.37036618]]
prediction is:
 [[ 20467.25       936.0858 ]
 [ 10898.982    -8786.754  ]
 [  2739.7676  -10374.315  ]
 [   238.48071    117.61809]
 [-28587.922     4542.2983 ]
 [ 19426.29     -8462.549  ]
 [ 28689.55     -1783.7368 ]
 [ 18629.629     1165.3439 ]]


 92%|█████████▏| 55001/60000 [5:08:08<34:16,  2.43it/s]

loss is: 756.0115


 93%|█████████▎| 56000/60000 [5:13:43<22:21,  2.98it/s]

save model
learning_rate is:
 6.451946e-05
real location is:
 [[ 30881.4857178   -7978.78944599]
 [-29883.6276734     938.37062584]
 [    57.61526554 -10311.7413207 ]
 [ 18497.2501053   -9584.77956878]
 [ 30473.0284512   -1094.97304972]
 [-30265.8467781    6313.33302412]
 [ 29776.5067397    1096.64541477]
 [-30150.4898581    3547.06264431]]
prediction is:
 [[ 29624.293    -7483.1323 ]
 [-30068.7        744.02954]
 [   686.9855  -10231.537  ]
 [ 18154.383    -9901.422  ]
 [ 30105.992     -786.522  ]
 [-29509.61      5781.843  ]
 [ 28693.646      514.8431 ]
 [-31208.137     3033.9143 ]]


 93%|█████████▎| 56001/60000 [5:13:44<26:59,  2.47it/s]

loss is: 678.12964


 95%|█████████▌| 57000/60000 [5:19:19<16:45,  2.98it/s]

save model
learning_rate is:
 6.322906e-05
real location is:
 [[-24736.0830852   -7295.98177863]
 [ 30728.7326945   -2138.94763323]
 [  -223.0525988  -10583.9441506 ]
 [ 14951.5703538   -9579.62882744]
 [-18533.6913932   -5451.07000852]
 [ 22596.5786567     994.42422786]
 [ -9424.759263    -6772.18165398]
 [ -5917.28330488  -6781.86981111]]
prediction is:
 [[-23757.898    -7285.8887 ]
 [ 30282.303    -2235.8843 ]
 [  -764.20026 -10579.616  ]
 [ 14451.028    -9229.639  ]
 [-18102.684    -5251.0107 ]
 [ 22336.39       776.646  ]
 [ -9021.445    -6280.6396 ]
 [ -5256.909    -6097.541  ]]


 95%|█████████▌| 57001/60000 [5:19:20<20:14,  2.47it/s]

loss is: 488.79153


 97%|█████████▋| 58000/60000 [5:24:56<11:10,  2.98it/s]

save model
learning_rate is:
 6.1964485e-05
real location is:
 [[ 11125.8267434     842.85389371]
 [ 12946.5660871     610.62001202]
 [-18062.9370147   -6968.79791549]
 [ 17848.005933    -9284.44039917]
 [  4695.49757933 -10032.9465225 ]
 [ 31049.8151598   -7151.9752413 ]
 [ 21893.3567407   -9079.85421944]
 [ -1591.524436   -10675.4832614 ]]
prediction is:
 [[  9336.005     826.3705]
 [ 11863.848     721.6653]
 [-16897.596   -6468.6963]
 [ 18451.354   -8575.08  ]
 [  4865.76    -9161.264 ]
 [ 29230.467   -7010.9243]
 [ 21652.379   -8733.033 ]
 [ -1166.6177 -10979.595 ]]


 97%|█████████▋| 58001/60000 [5:24:56<13:29,  2.47it/s]

loss is: 802.9269


 98%|█████████▊| 59000/60000 [5:30:32<05:35,  2.98it/s]

save model
learning_rate is:
 6.07252e-05
real location is:
 [[ 24397.6122839    1032.7605676 ]
 [  1990.71429929    287.98204429]
 [-30353.1170969    2563.38381039]
 [ -4448.44085744 -10160.0563356 ]
 [-26135.3149102   -7547.18497683]
 [ 10558.1903528     798.99322222]
 [-28561.3525985   -7786.24121767]
 [ -7483.83930787  -4801.90445303]]
prediction is:
 [[ 24006.797      436.88922]
 [  1989.757     -318.97333]
 [-30526.664     2323.354  ]
 [ -4627.8916   -9943.274  ]
 [-25252.203    -7105.815  ]
 [ 10085.86       619.79517]
 [-28320.686    -7637.328  ]
 [ -7448.171    -4873.0176 ]]


 98%|█████████▊| 59001/60000 [5:30:32<06:44,  2.47it/s]

loss is: 379.48972


100%|██████████| 60000/60000 [5:36:08<00:00,  2.95it/s]

done!
