In [1]:
import os
import random
import skimage.data
from skimage import io
import skimage.transform as skt
import numpy as np 
import tensorflow as tf
from tqdm import tqdm
import sys
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
import cv2

In [2]:
# submap_dir = "/home/ysk/database/new_train_dateset/new_benhuan_train/submap"
# pic_dir = "/home/ysk/database/new_train_dateset/new_benhuan_train/picture"

# # for i in range(4):
# i = 4803
# submap1 = cv2.imread(os.path.join(submap_dir,str(4) + '.pgm'))
# submap1 = cv2.resize(submap1,(448,448))
# submap1 = cv2.transpose(submap1)
# submap1 = cv2.flip(submap1, 1)
# cv2.imshow("submap",submap1)


# pic1 = cv2.imread(os.path.join(pic_dir, '00004.jpg'))
# cv2.imshow("pic",pic1)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# print(np.shape(submap1))

In [3]:
train_label_dir = "/home/ysk/database/train_data/benhuan/"
train_pic_dir = "/home/ysk/database/train_data/benhuan//picture"
train_submap_dir = "/home/ysk/database/train_data/benhuan//submap"

def get_train_data_batch(num, pic_dir=train_pic_dir, label_dir=train_label_dir,submap_dir=train_submap_dir):
    train_txt = os.path.join(label_dir,"label.txt")
    count = len(open(train_txt,'r').readlines()) - 2
    idx = np.arange(0, count)      
    np.random.shuffle(idx)                
    data_idx = idx[:num]
#     print(data_idx)
    
    labels = []
    images = []
    
    for i in range(num):
        with open(train_txt,'r') as file:
            s = file.readlines()
            image1 = cv2.imread(os.path.join(pic_dir, s[data_idx[i]].split(";")[0]))
            submap1 = cv2.imread(os.path.join(submap_dir,str(data_idx[i]) + '.pgm'))
            submap1 = cv2.resize(submap1,(448,448))
            submap1 = cv2.transpose(submap1)
            submap1 = cv2.flip(submap1, 1)
            
#             image2 = skimage.data.imread(os.path.join(pic_dir, s[data_idx[i] + 1].split(";")[0]))
#             submap2 = cv2.imread(os.path.join(submap_dir,str(data_idx[i] + 1) + '.pgm'))
#             submap2 = cv2.resize(submap2,(448,448))
#             submap2 = cv2.transpose(submap2)
#             submap2 = cv2.flip(submap2, 1)
            
            img = cv2.merge([image1,submap1])
            images.append(img)

            label = s[data_idx[i]].split(";")[1:]
            label = list(map(float,label))
            labels.append(label)
    return np.asarray(images),np.asarray(labels)

num = 10
train_images, train_labels = get_train_data_batch(num)
print(np.shape(train_images))
print(np.shape(train_labels))
print(train_labels)
# print(train_labels*100)

(10, 448, 448, 6)
(10, 3)
[[ 4.76524191e+00 -9.45567618e-03  2.93363887e+01]
 [ 4.43271284e-01  4.08984742e+01 -1.78712495e+02]
 [-2.01186342e+01  3.10922817e+01  5.47269720e+01]
 [-2.04982069e+01  2.23735395e+01  9.09540108e+01]
 [-2.07016608e+01  2.49265516e+01 -9.05415450e+01]
 [ 1.97974406e+01  9.72902974e+00 -1.35495256e+02]
 [-3.92272906e+00  4.09250827e+01 -1.78212792e+02]
 [ 1.57762121e+00  5.50293045e-02 -1.78421059e+02]
 [-1.12727559e+01  3.98404415e+01 -1.39241934e+02]
 [-2.07357034e+01  2.28561526e+01 -8.68345800e+01]]


In [ ]:
with tf.name_scope("input"):
    input_image = tf.placeholder("float", [None, 448,448,6],name='input_image')/255.*2.-1
    y_ = tf.placeholder("float", [None, 3],name='y_') 

def weight_variable(shape):
    w = tf.Variable(tf.truncated_normal(shape, stddev=0.1))
    tf.add_to_collection('losses',tf.contrib.layers.l2_regularizer(0.1)(w))
    return w

def bias_variable(shape):
    initial = tf.constant(0.1, shape = shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding="SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")


#第0层卷积
with tf.name_scope("conv_0"):
    W_conv0 = weight_variable([7, 7, 6, 64])
    b_conv0 = bias_variable([64])
    conv_layer0 = tf.nn.conv2d(input_image, W_conv0, strides=[1,1,1,1], padding="SAME") + b_conv0
#     conv_layer_nor0 = tf.layers.batch_normalization(conv_layer0,training=True)
    
    h_conv0 = tf.nn.leaky_relu(conv_layer0)
with tf.name_scope("max_pool_0"):
    h_pool0 = max_pool_2x2(h_conv0)   #输出变成224*224*64 [None,224,224,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度
with tf.name_scope("conv_1"):
    W_conv1 = weight_variable([5, 5, 64, 128])
    b_conv1 = bias_variable([128])
    conv_layer1 = conv2d(h_pool0, W_conv1) + b_conv1
#     conv_layer_nor1 = tf.layers.batch_normalization(conv_layer1,training=True)

    h_conv1 = tf.nn.leaky_relu(conv_layer1)
with tf.name_scope("max_pool1"):
    h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64   [None,112,112,64]

#第二层卷积层
with tf.name_scope("conv_2"):
    W_conv2 = weight_variable([5, 5, 128, 192])
    b_conv2 = bias_variable([192])
    conv_layer2 = conv2d(h_pool1, W_conv2) + b_conv2
#     conv_layer_nor2 = tf.layers.batch_normalization(conv_layer2,training=True)

    h_conv2 = tf.nn.leaky_relu(conv_layer2)
with tf.name_scope("max_pool_2"):
    h_pool2 = max_pool_2x2(h_conv2)  #输出变为56*56*192


#第三层卷积层
with tf.name_scope("conv_3"):
    W_conv3 = weight_variable([3, 3, 192, 128])
    b_conv3 = bias_variable([128])
    conv_layer3 = conv2d(h_pool2, W_conv3) + b_conv3
#     conv_layer_nor3 = tf.layers.batch_normalization(conv_layer3,training=True)
    
    h_conv3 = tf.nn.leaky_relu(conv_layer3)
with tf.name_scope("max_pool_3"):
    h_pool3 = max_pool_2x2(h_conv3)   #输出为28*28*128


#第四层卷积层
with tf.name_scope("conv_4"):
    W_conv4 = weight_variable([3, 3, 128, 64])
    b_conv4 = bias_variable([64])
    conv_layer4 = conv2d(h_pool3, W_conv4) + b_conv4
#     conv_layer_nor4 = tf.layers.batch_normalization(conv_layer4,training=True)

    h_conv4 = tf.nn.leaky_relu(conv_layer4)
with tf.name_scope("max_pool_4"):
    h_pool4 = max_pool_2x2(h_conv4)   #输出变为14*14*64


keep_prob = tf.placeholder("float")

#密集连接层0
with tf.name_scope("fc0"):
    W_fc0 = weight_variable([14*14*64, 2048])
    b_fc0 = bias_variable([2048])

    h_pool4_flat = tf.reshape(h_pool4, [-1, 14*14*64])
    
    out_fc0 = tf.matmul(h_pool4_flat, W_fc0) + b_fc0
    out_nor_fc0 = tf.layers.batch_normalization(out_fc0,training=True)
    
    h_fc0 = tf.nn.leaky_relu(out_nor_fc0)   #输出为96*2048

    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop0 = tf.nn.dropout(h_fc0, keep_prob)   #输出为96*2048

#密集连接层1
with tf.name_scope("fc1"):
    W_fc1 = weight_variable([2048, 1024])
    b_fc1 = bias_variable([1024])
    
    out_fc1 = tf.matmul(h_fc1_drop0, W_fc1) + b_fc1
    out_nor_fc1 = tf.layers.batch_normalization(out_fc1,training=True)

    h_fc1 = tf.nn.leaky_relu(out_nor_fc1)   #输出为2048*1024

    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop1 = tf.nn.dropout(h_fc1, keep_prob)   #输出为2048*1024

#密集连接层2
with tf.name_scope("fc2"):
    W_fc2 = weight_variable([1024, 512])
    b_fc2 = bias_variable([512])
    
    out_fc2 = tf.matmul(h_fc1_drop1, W_fc2) + b_fc2
    out_nor_fc2 = tf.layers.batch_normalization(out_fc2,training=True)

    h_fc2 = tf.nn.leaky_relu(out_nor_fc2)
    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop2 = tf.nn.dropout(h_fc2, keep_prob)
    

#输出层
with tf.name_scope("out_layer"):
    W_fc3 = weight_variable([512, 3])
    y_conv = tf.matmul(h_fc1_drop2, W_fc3)

starter_learning_rate = 0.8
steps_per_decay = 10000
decay_factor = 0.92

global_step = tf.Variable(tf.constant(0))
learning_rate = tf.train.exponential_decay(learning_rate = starter_learning_rate,
                                           global_step = global_step,
                                           decay_steps = steps_per_decay,
                                           decay_rate = decay_factor,
                                           staircase = True
                                           )

delta=tf.constant(1.25)
#huber损失函数

loss1 = tf.reduce_mean(tf.multiply(tf.square(delta),
                                  tf.sqrt(1. + tf.square((y_ - y_conv)/delta)) - 1.))
loss = loss1 + tf.add_n(tf.get_collection('losses'))
# loss = loss1

    
tf.summary.scalar("loss",loss)
     
train_step = tf.train.AdamOptimizer(learning_rate).minimize(loss)

merged = tf.summary.merge_all()

batch_size = 6       
checkpointsPath = "/home/ysk/database/checkpoints/only_fc_bn_l2_dro_0.6_new/"
reload = True

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    var_list = tf.trainable_variables()
    g_list = tf.global_variables()
    bn_moving_vars = [g for g in g_list if 'moving_mean' in g.name]
    bn_moving_vars += [g for g in g_list if 'moving_variance' in g.name]
    var_list += bn_moving_vars
    saver = tf.train.Saver(var_list=var_list,max_to_keep=5)
    
    writer = tf.summary.FileWriter("logs_dir/", sess.graph)
    
    if not os.path.exists(checkpointsPath):
        os.mkdir(checkpointsPath)
    
    if reload:
        checkPoint = tf.train.get_checkpoint_state(checkpointsPath)
        if checkPoint and checkPoint.model_checkpoint_path:
            
#             saver = tf.train.Saver(var_list=var_list)
#             saver.restore(sess, checkPoint.model_checkpoint_path)

#             var = tf.global_variables()
            var_to_restore = [val for val in var_list if 'fc0' not in val.name or 
                              'fc1' not in val.name or 'fc2' not in val.name or 'out_layer' not in val.name]
            saver = tf.train.Saver(var_to_restore )
            saver.restore(sess, checkPoint.model_checkpoint_path)
            var_to_init = [val for val in var_list if 'fc0' in val.name or 
                              'fc1' in val.name or 'fc2' in val.name or 'out_layer' in val.name]
            tf.variables_initializer(var_to_init)
            print("restored %s" % checkPoint.model_checkpoint_path)
        else:
            print("no checkpoint found!")
    else:
        sess.run(tf.global_variables_initializer())
        
    for i in tqdm(range(500000)):
        batch_x,batch_y = get_train_data_batch(batch_size)
        batch_y = batch_y*10000
        summary,_ = sess.run([merged,train_step],feed_dict={global_step:i,
                                                            input_image:batch_x, 
                                                            y_:batch_y, 
                                                            keep_prob:0.5})
        writer.add_summary(summary, i)
        if (i % 1000) == 0 & (i != 0):
            print("save model")
            print("learning_rate is:\n",sess.run(learning_rate,feed_dict = {global_step:i}))
            print("real location is:\n",batch_y)
            print("prediction is:\n",sess.run(y_conv,feed_dict={input_image:batch_x, 
                                                                y_:batch_y,keep_prob:1.0}))
              
            saver.save(sess, os.path.join(checkpointsPath,"saved_net.ckpt"), global_step=i)
            print("loss is:",sess.run(loss,feed_dict={input_image:batch_x, y_:batch_y, keep_prob:1.0}))
    print("done!")


INFO:tensorflow:Restoring parameters from /home/ysk/database/checkpoints/only_fc_bn_l2_dro_0.6_new/saved_net.ckpt-275000


  0%|          | 0/500000 [00:00<?, ?it/s]

restored /home/ysk/database/checkpoints/only_fc_bn_l2_dro_0.6_new/saved_net.ckpt-275000
save model
learning_rate is:
 0.8
real location is:
 [[-7.34099865e+04  2.51243676e+03  1.77831156e+06]
 [-9.06865384e+04  4.08505503e+05 -1.78471574e+06]
 [ 1.45569692e+05  4.08206109e+04 -1.32507605e+06]
 [-1.70166896e+05  6.77957380e+04  1.37350013e+06]
 [-7.03903136e+03  6.90595529e+02  2.64491780e+03]
 [-2.04706632e+05  3.04542765e+05  6.86712297e+05]]
prediction is:
 [[-26362.592  169550.84   -21749.96  ]
 [ -2088.5278  42888.383  -16423.64  ]
 [-29656.281  179359.94   -24622.105 ]
 [-26762.025  165047.31   -23584.887 ]
 [-36596.51   217986.28   -24355.195 ]
 [-36226.684  209136.84   -26488.473 ]]


  0%|          | 1/500000 [00:08<1204:09:31,  8.67s/it]

loss is: 1404436.6


  0%|          | 1000/500000 [04:49<31:36:54,  4.38it/s]

save model
learning_rate is:
 0.8
real location is:
 [[ 2.94829561e+04  6.73560861e+02 -1.77559823e+06]
 [ 2.03083215e+05  1.03233574e+05  5.24750787e+05]
 [-1.80708552e+05  3.30853412e+05  4.77637545e+05]
 [ 1.87238106e+05  3.26085425e+05 -4.54290028e+05]
 [ 1.44896032e+05  3.68765047e+05 -4.22534636e+05]
 [-8.02815443e+04  4.08220568e+03  2.43342336e+04]]
prediction is:
 [[  57181.75    111013.34   -184210.72  ]
 [  15253.      182375.28      6565.924 ]
 [  -7973.335   156840.      -54585.797 ]
 [  17080.943   221745.       -2388.6484]
 [  -3827.5425  156071.38    -46913.53  ]
 [  -4537.5166  164492.05    -38837.703 ]]


  0%|          | 1001/500000 [04:49<41:00:40,  3.38it/s]

loss is: 614212.4


  0%|          | 2000/500000 [08:09<25:50:12,  5.35it/s]

save model
learning_rate is:
 0.8
real location is:
 [[ 2.81509174e+04  4.08564537e+05 -4.29934619e+03]
 [ 5.78637779e+04  5.39690030e+01 -1.09130212e+04]
 [ 2.07426081e+05  2.23433699e+05  9.32974797e+05]
 [ 9.91798465e+04  3.24758740e+03 -1.76979603e+06]
 [-3.54018203e+04  1.94664901e+03 -1.67766872e+04]
 [ 2.07551656e+05  1.96527452e+05  9.03611981e+05]]
prediction is:
 [[-62187.72   199020.62    -5088.5957]
 [-76204.94   203040.81    37363.297 ]
 [-65259.72   211694.56     2066.7612]
 [-53289.152  197181.94   -30712.535 ]
 [ -8844.225   96202.984    7434.7393]
 [-59006.92   251896.48    76033.67  ]]


  0%|          | 2002/500000 [08:10<33:04:07,  4.18it/s]

loss is: 566574.4


  1%|          | 3000/500000 [11:05<23:18:41,  5.92it/s]

save model
learning_rate is:
 0.8
real location is:
 [[-1.26438064e+05  2.77935484e+04  1.39636565e+06]
 [-2.05857778e+05  2.18410584e+05  9.24480910e+05]
 [-1.81838075e+05  7.80146494e+04 -4.37294365e+05]
 [ 3.45884579e+03  4.09412805e+05 -1.78083829e+06]
 [-9.39016507e+04  4.08766329e+05 -1.75172907e+06]
 [ 8.34878315e+04  2.81647515e+02  2.18560179e+03]]
prediction is:
 [[  3084.477  205995.12   -41528.395 ]
 [  2907.6965 203622.72   -33827.71  ]
 [-15271.28   205951.19   -89980.016 ]
 [ 13764.301   83927.06   -41864.17  ]
 [-10904.665  143474.9    -38344.254 ]
 [ 29969.078  235054.28    -8195.408 ]]


  1%|          | 3002/500000 [11:06<30:37:51,  4.51it/s]

loss is: 758168.1


  1%|          | 4000/500000 [13:55<22:34:44,  6.10it/s]

save model
learning_rate is:
 0.8
real location is:
 [[-122104.556551    390166.642608    438311.897512  ]
 [-204995.719983    189694.384345    927586.650664  ]
 [-188221.061664     85312.3732236  1347895.80475   ]
 [-205549.983338    113937.771876   -789573.248258  ]
 [ -24165.8045405   407575.733155     12211.9538712 ]
 [-101821.084059      8416.37632054 1459219.53643   ]]
prediction is:
 [[-19352.418 106457.44   85668.05 ]
 [-25725.8   165003.34   86644.75 ]
 [-16020.234  99868.83   86502.55 ]
 [-54998.336 239446.28  168906.78 ]
 [-32963.47  136004.    -40271.902]
 [-11334.768 150606.47   74471.45 ]]


  1%|          | 4002/500000 [13:56<30:01:34,  4.59it/s]

loss is: 647062.75


  1%|          | 5000/500000 [16:44<23:13:59,  5.92it/s]

save model
learning_rate is:
 0.8
real location is:
 [[ 132441.397388    379795.021787   -421781.893302  ]
 [-145307.079381     43601.4452785  -420925.294008  ]
 [ 163723.753251    350139.641084   1364286.67165   ]
 [ 109469.447274    400205.770507   -395197.003762  ]
 [-111219.772622    399520.683455    417815.774231  ]
 [ 113561.607654      6252.81174098  430665.375246  ]]
prediction is:
 [[ -30036.26   197395.75   -62945.438]
 [ -52860.21   190496.98   -32803.89 ]
 [ -25320.844  183405.12   -45920.207]
 [ -31802.46   208186.12   -97690.11 ]
 [  27232.355   53676.703  -26557.145]
 [ -34724.984  127567.88  -121626.55 ]]


  1%|          | 5002/500000 [16:45<30:59:34,  4.44it/s]

loss is: 542060.1


  1%|          | 6000/500000 [19:32<22:50:45,  6.01it/s]

save model
learning_rate is:
 0.8
real location is:
 [[  -29835.4056701   409437.122904  -1784562.05234  ]
 [ -205826.02292     283893.881323    881894.508479 ]
 [  -37924.6342787   408758.338604  -1798296.15019  ]
 [ -205881.177012    274405.120703    916980.868663 ]
 [  187908.300875     85084.7360498 -1291236.11876  ]
 [  207781.157749    169700.242412    915270.053932 ]]
prediction is:
 [[-22003.094  237420.      -3605.377 ]
 [-33521.69   219946.6     45373.49  ]
 [-27539.838  256105.53     4157.799 ]
 [-34838.586  227930.98    43469.96  ]
 [  4458.124  115154.89   -31154.455 ]
 [ -9823.8955 190818.73    -7639.993 ]]


  1%|          | 6002/500000 [19:33<30:38:54,  4.48it/s]

loss is: 767689.44


  1%|▏         | 7000/500000 [22:21<23:07:46,  5.92it/s]

save model
learning_rate is:
 0.8
real location is:
 [[-6.05459890e+04  3.31701584e+03 -1.22686351e+04]
 [-2.70506140e+04  1.35107652e+03 -2.48109242e+04]
 [ 1.75034073e+03 -1.85387943e+03 -2.82672536e+05]
 [-1.90341198e+05  3.21021128e+05 -1.31726543e+06]
 [-2.06789069e+05  2.63942783e+05 -9.27288268e+05]
 [ 1.11211254e+05  8.30832778e+03 -1.38860961e+06]]
prediction is:
 [[ 11505.869  220087.89   -16389.04  ]
 [  9349.146  170493.81      927.5742]
 [-52954.254   65181.14   -90368.06  ]
 [  7422.243  248362.62   -12863.459 ]
 [ 13266.549  250927.44   -13225.705 ]
 [ 23477.09   212310.22     6331.9287]]


  1%|▏         | 7002/500000 [22:21<30:38:50,  4.47it/s]

loss is: 600783.25


  2%|▏         | 8000/500000 [25:06<22:53:44,  5.97it/s]

save model
learning_rate is:
 0.8
real location is:
 [[ 8.81078603e+04  8.67574889e+02  5.47262722e+04]
 [ 2.06638972e+05  1.54537297e+05 -9.08490391e+05]
 [ 2.07952389e+05  1.64348971e+05  9.20773249e+05]
 [ 9.19325129e+04  4.09643087e+05  1.75841141e+06]
 [ 1.04427894e+05  4.29233828e+03 -1.60067146e+06]
 [-1.57278114e+05  3.55093473e+05  4.59214789e+05]]
prediction is:
 [[ -8668.949 172478.4    24840.03 ]
 [-27835.773 236723.16   32747.203]
 [-16162.883 205185.83   16898.102]
 [-18027.754 229041.02   15920.047]
 [ 24886.904 136351.72  -28963.793]
 [-23580.494 278710.56   21755.393]]


  2%|▏         | 8002/500000 [25:06<30:02:20,  4.55it/s]

loss is: 752085.1


  2%|▏         | 9000/500000 [27:53<22:56:40,  5.94it/s]

save model
learning_rate is:
 0.8
real location is:
 [[-1.53861387e+04  4.08243405e+05  5.92619813e+03]
 [-1.68397887e+05  6.47312643e+04 -4.18058524e+05]
 [-5.92636260e+04  3.25362477e+03 -1.23008365e+04]
 [-3.78241853e+03  4.07725858e+05  5.61833678e+03]
 [ 1.33461563e+03  4.09358718e+05 -1.78170740e+06]
 [-2.05426706e+05  2.92728546e+05 -9.21004898e+05]]
prediction is:
 [[ 30576.334  208583.25      616.6538]
 [  8393.762  173054.6      6576.2314]
 [ -3496.4087  50816.395  -48827.312 ]
 [ 16218.243  259978.17    22303.104 ]
 [ -6349.1353 188433.02    -8519.803 ]
 [ 23282.832  167337.73    -3064.129 ]]


  2%|▏         | 9002/500000 [27:54<29:58:06,  4.55it/s]

loss is: 526149.5


  2%|▏         | 10000/500000 [30:42<22:35:05,  6.03it/s]

save model
learning_rate is:
 0.736
real location is:
 [[ -49860.111226    408493.9262       11513.650062  ]
 [-204286.105602    163230.861673    902763.656251  ]
 [-140345.822088    372305.147201    454887.338801  ]
 [ -82022.0218723   407998.888862      8830.04741417]
 [-205032.940491    181790.373164    921465.299476  ]
 [ 206568.727179    135937.349876   -897772.854529  ]]
prediction is:
 [[-11980.468  143676.64   -73282.734 ]
 [ -1156.125  199125.06   -42616.35  ]
 [ 29467.854  124024.33   -24259.434 ]
 [ -8051.1387 178650.25   -57150.53  ]
 [ -1122.053  172114.19   -40737.04  ]
 [ 53894.07   120617.375  -14859.127 ]]


  2%|▏         | 10002/500000 [30:42<30:26:22,  4.47it/s]

loss is: 482036.62


  2%|▏         | 11000/500000 [33:30<22:50:12,  5.95it/s]

save model
learning_rate is:
 0.736
real location is:
 [[ -116700.332874     20375.7528794  -426330.877435 ]
 [ -208343.770547    189876.308092   -915436.758297 ]
 [ -115109.228467    396059.567056    402851.676201 ]
 [  197974.406108     97290.2974233 -1354952.56224  ]
 [ -207354.905838    237276.081523   -924888.177424 ]
 [  136756.893609    376296.540886   1365356.70166  ]]
prediction is:
 [[  3719.6753   91688.945   -10244.123  ]
 [ -1377.0779  251400.16    -39810.957  ]
 [  9661.607   237564.44    -31031.328  ]
 [   283.35507 213014.17    -36265.336  ]
 [ 14233.255   138007.12    -24750.092  ]
 [  1955.6667  263561.5     -29930.857  ]]


  2%|▏         | 11002/500000 [33:30<30:34:21,  4.44it/s]

loss is: 633540.1


  2%|▏         | 12000/500000 [36:18<22:46:36,  5.95it/s]

save model
learning_rate is:
 0.736
real location is:
 [[  -78377.2890125      3208.71852904  1795000.04772   ]
 [   81852.7435952    409120.020476      26046.6768781 ]
 [ -188066.923198     323879.324198     456772.566627  ]
 [ -205276.925102     291005.21176     -920227.499995  ]
 [ -129550.591412     382876.973226   -1353924.22713   ]
 [ -147264.583138      46454.7104428   1388521.08585   ]]
prediction is:
 [[ 23075.041  177112.03    -2776.1296]
 [ 23813.148  187638.69      554.854 ]
 [ 27674.209  235007.1      3486.2993]
 [ 24492.348  214076.62    -3583.3254]
 [ 29144.64   240657.05     4373.6836]
 [  8698.373   88694.09   -15462.672 ]]


  2%|▏         | 12002/500000 [36:19<30:48:23,  4.40it/s]

loss is: 796707.6


  3%|▎         | 13000/500000 [39:07<22:44:55,  5.95it/s]

save model
learning_rate is:
 0.736
real location is:
 [[ -204991.635615    178457.379979    920554.87136  ]
 [  205375.548031    209707.881517    909869.53205  ]
 [ -107227.631972     12177.1403354  1417331.51644  ]
 [   84526.9617684   409208.090514     25106.2090249]
 [  -50762.8813778   408684.995501  -1783910.42927  ]
 [ -140245.939431     39002.7349987  -423402.440015 ]]
prediction is:
 [[ 32854.094  205983.78    19078.068 ]
 [ 20695.2    244394.25    36409.87  ]
 [ 45745.883   87155.69    -3611.7256]
 [ 11883.992  227064.34    38056.164 ]
 [  3440.546  182663.28    17850.184 ]
 [  3965.9038 121034.75   -11029.102 ]]


  3%|▎         | 13002/500000 [39:07<29:56:30,  4.52it/s]

loss is: 618605.44


  3%|▎         | 14000/500000 [41:55<22:42:52,  5.94it/s]

save model
learning_rate is:
 0.736
real location is:
 [[  -44313.110541     408771.904413   -1793722.5009    ]
 [  -76691.0921437      4027.07421343    -3783.99541984]
 [ -141701.724738     370648.435584   -1335250.10773   ]
 [  196407.466775     316660.629394    -442128.894823  ]
 [  166862.92128       62703.9016015  -1316063.91833   ]
 [  150362.67877      363576.612363    -425303.347574  ]]
prediction is:
 [[-43169.152 178202.88   23663.453]
 [-54344.57  183743.77  -18301.422]
 [-58094.812 212583.94   41905.492]
 [  8310.475  37672.36   33789.2  ]
 [-56872.375 210744.58   47018.094]
 [-63804.242 209135.06   44007.387]]


  3%|▎         | 14002/500000 [41:55<30:14:05,  4.47it/s]

loss is: 679405.7


  3%|▎         | 15000/500000 [44:43<23:03:56,  5.84it/s]

save model
learning_rate is:
 0.736
real location is:
 [[ -180963.816598    331024.018075    458946.858552 ]
 [   30301.9112554   409125.348609  -1786994.68029  ]
 [  205587.145574    197345.445477   -831453.904436 ]
 [   86547.3499739   408984.676364     26689.5896619]
 [ -204489.24835     146442.811615    908711.366057 ]
 [  -23191.4056158   408902.658927  -1793344.25176  ]]
prediction is:
 [[-20713.645  149064.34   -46742.57  ]
 [-17233.336  129863.055  -35956.973 ]
 [ -3306.315  144442.88   -38253.566 ]
 [ -2026.2754 137210.22   -32659.14  ]
 [-36155.504  211511.     -46288.387 ]
 [  2071.7107  97944.64   -18003.07  ]]


  3%|▎         | 15002/500000 [44:44<29:44:37,  4.53it/s]

loss is: 824119.75


  3%|▎         | 16000/500000 [47:32<22:14:24,  6.05it/s]

save model
learning_rate is:
 0.736
real location is:
 [[  104925.448079       4233.84214344 -1561539.70509   ]
 [  112088.892319     398348.554242    1449742.49403   ]
 [ -206969.504695     251468.581721    -917067.958138  ]
 [ -182659.414136      78242.030411    -425084.653721  ]
 [   -9590.43206308   408664.820777   -1799158.64098   ]
 [ -204295.283652     134442.632924     922405.831141  ]]
prediction is:
 [[-40354.12   172552.77   -52436.953 ]
 [-23859.648  313326.38     5862.9087]
 [-43200.504  251518.67   -15078.842 ]
 [-25417.129  251902.66   -15563.189 ]
 [ -6373.4307 107938.99   -34536.08  ]
 [-34742.82   249819.56    -8882.277 ]]


  3%|▎         | 16002/500000 [47:32<29:48:44,  4.51it/s]

loss is: 776188.4


  3%|▎         | 17000/500000 [50:21<22:47:51,  5.89it/s]

save model
learning_rate is:
 0.736
real location is:
 [[  172805.449389      64185.0834014  -1381232.97408   ]
 [   -2327.17469318   407734.608587       4918.56165732]
 [ -205836.56391      273147.777501     912518.121838  ]
 [  157359.640037     355866.17684     -458819.745555  ]
 [   30545.2045248    408929.954048       2549.50293457]
 [  145687.79161       40467.4011812    475776.129815  ]]
prediction is:
 [[-13881.123 170542.34  -20022.22 ]
 [-15782.431 255353.22  -23131.783]
 [-21703.37  205908.25   23690.14 ]
 [ -8360.98  118564.66   -1846.668]
 [-11611.896 148561.16  -11377.427]
 [ -9239.498 178398.22  -11885.091]]


  3%|▎         | 17002/500000 [50:21<30:11:09,  4.44it/s]

loss is: 458265.12


  4%|▎         | 18000/500000 [53:10<22:25:23,  5.97it/s]

save model
learning_rate is:
 0.736
real location is:
 [[   55137.1110499     -1404.92806247 -1371525.9271    ]
 [ -140748.061079      39888.7890417   -391530.566015  ]
 [  207228.33504      128043.782977     840182.54614   ]
 [ -207168.379793     120291.961018    -813792.475136  ]
 [ -205655.82548      291010.204099     908001.821529  ]
 [  207630.337327     182608.618366     916157.211147  ]]
prediction is:
 [[ 15554.668 106093.69    8264.304]
 [ 22670.979 158174.52   42166.707]
 [ 22530.773 179749.9    32102.918]
 [ 25977.31  173272.75   47694.582]
 [ 42140.133 253970.56   78256.8  ]
 [ 44298.445 206937.25   52631.5  ]]


  4%|▎         | 18002/500000 [53:10<29:58:45,  4.47it/s]

loss is: 619404.4


  4%|▍         | 19000/500000 [55:58<22:29:09,  5.94it/s]

save model
learning_rate is:
 0.736
real location is:
 [[ 120871.831076   391010.406783  -412502.339805 ]
 [ 140078.778158   373129.016118  1371450.40635  ]
 [-205139.58685    299340.670816  -945615.610514 ]
 [-207277.227521   224339.644326  -898290.160225 ]
 [-184916.839536   327082.642388   460489.816387 ]
 [ -69862.7235234  408000.054528    12924.1711252]]
prediction is:
 [[  1597.94   138773.38   -31298.857 ]
 [  9774.078  271425.88    27603.06  ]
 [ 11273.276  256211.94     1764.1492]
 [  3956.0269 183991.75   -29208.254 ]
 [  4047.2856 160947.31   -14465.975 ]
 [  7607.9043 277597.25    25708.588 ]]


  4%|▍         | 19002/500000 [55:59<30:04:51,  4.44it/s]

loss is: 551466.1


  4%|▍         | 20000/500000 [58:47<22:36:50,  5.90it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[   4501.96579242  408258.030725     55629.0966325 ]
 [ 205585.69431     219003.6249      873633.920606  ]
 [ -96079.4346271   407475.952119     77497.4135664 ]
 [ 145333.557817    368351.781986   1355951.20159   ]
 [-177518.061505    333914.413792    481940.231457  ]
 [-186675.686969     82168.2134079  -439972.166687  ]]
prediction is:
 [[-28884.914 242611.62   41279.727]
 [-29118.742 145702.4     2284.709]
 [-59603.59  309189.2    15346.322]
 [-28050.984 121629.66    2863.169]
 [-40308.156 239784.25    8880.364]
 [-58899.062 169556.56  -32593.734]]


  4%|▍         | 20002/500000 [58:48<30:06:26,  4.43it/s]

loss is: 429154.66


  4%|▍         | 21000/500000 [1:01:36<22:38:04,  5.88it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[ 198142.892355     98235.8499999   444549.429079  ]
 [-108069.897249     12848.1651452  1402371.0523    ]
 [ 206541.532848    133305.606909   -900253.629262  ]
 [ 183023.028455    332074.872321   1395045.96215   ]
 [-135036.938251     35317.4924927  1394520.75024   ]
 [ 106687.453047      2488.65697699  190765.897082  ]]
prediction is:
 [[-13789.729  161966.38   -16778.49  ]
 [-13129.656   55638.65   -21703.365 ]
 [-24554.785  237225.75   -16928.459 ]
 [-20424.484  274012.44   -19486.012 ]
 [-19330.555  305279.2    -16947.584 ]
 [ -7593.4663 213770.27   -12442.957 ]]


  4%|▍         | 21002/500000 [1:01:36<29:57:46,  4.44it/s]

loss is: 717927.06


  4%|▍         | 22000/500000 [1:04:24<22:15:06,  5.97it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[  169467.856622      61310.0384167  -1389059.41342   ]
 [  148600.882393      43508.3615473    471789.149291  ]
 [   60086.2738392    408686.576438      -2916.22819907]
 [ -208291.725269     192038.398645    -915064.030315  ]
 [ -207357.033725     228561.526265    -868345.799996  ]
 [  207972.314542     157843.965978     899927.759574  ]]
prediction is:
 [[  4425.1084 137855.66   -15782.8   ]
 [  6592.121  133079.78   -20462.66  ]
 [-31641.781  263013.38    -3137.5127]
 [-10626.614  165463.19    -6883.9604]
 [  5674.0493 127008.34   -21304.668 ]
 [ -5517.6636 254199.3    -14991.3545]]


  4%|▍         | 22002/500000 [1:04:25<29:00:05,  4.58it/s]

loss is: 727281.2


  5%|▍         | 23000/500000 [1:07:12<22:20:42,  5.93it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[-2.04358004e+05  1.29435815e+05  9.28461409e+05]
 [-1.67912131e+05  3.44056736e+05  4.67339490e+05]
 [-6.22362034e+02  5.42334606e+02  1.28416280e+03]
 [-8.49169989e+04  4.09806194e+03 -1.86109858e+04]
 [ 2.05921306e+05  2.92001084e+05  9.46594745e+05]
 [-2.06063870e+05  2.69227829e+05  9.14125678e+05]]
prediction is:
 [[-21317.09   210644.45   -13069.647 ]
 [-24386.19   225270.98   -12280.9375]
 [-15606.457   54373.875   12114.391 ]
 [-23217.191  201010.02    -2548.0098]
 [-20422.174  232791.16    -4329.324 ]
 [-21407.297  239522.44    -4952.3105]]


  5%|▍         | 23002/500000 [1:07:13<29:39:11,  4.47it/s]

loss is: 535642.56


  5%|▍         | 24000/500000 [1:10:01<22:15:53,  5.94it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[-2.07409462e+05  2.29697448e+05 -8.61257950e+05]
 [ 7.68930715e+04  3.59409045e+02  1.54725879e+04]
 [-1.87271057e+05  8.40776497e+04  1.35127479e+06]
 [ 3.99072060e+04 -5.62534412e+01  2.97556716e+04]
 [ 2.04689853e+05  2.37670027e+05 -8.91423590e+05]
 [ 2.06580157e+05  1.53316266e+05 -9.02417923e+05]]
prediction is:
 [[  9259.692  214025.25     4256.5576]
 [ 14788.587  167603.94     1266.9697]
 [ 15714.779  151326.38     1575.3789]
 [  1784.9205   9180.281  -35095.914 ]
 [  2843.3772 234910.56    -4437.163 ]
 [ 13117.486  194479.84    -2125.0825]]


  5%|▍         | 24002/500000 [1:10:02<29:28:50,  4.49it/s]

loss is: 478174.0


  5%|▌         | 25000/500000 [1:12:50<22:30:25,  5.86it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[ 2.04947398e+05  2.06536071e+05 -8.98324665e+05]
 [-1.01821084e+05  8.41637632e+03  1.45921954e+06]
 [-2.07209767e+05  1.95744595e+05 -8.99248886e+05]
 [ 1.31674429e+05  3.80531853e+05 -4.21925744e+05]
 [ 1.89697972e+05  8.76638805e+04  5.22292083e+05]
 [ 8.67246558e+04  7.71395645e+02  5.59519588e+04]]
prediction is:
 [[  1201.1814 180581.6     35719.125 ]
 [  3889.6768 138804.     -10513.37  ]
 [ -8344.222  178080.78    30891.348 ]
 [ -7552.864  173721.05    28405.477 ]
 [ -5046.8022 113449.734   23561.797 ]
 [ -8736.51   101111.945   -7488.5723]]


  5%|▌         | 25002/500000 [1:12:50<29:49:56,  4.42it/s]

loss is: 554628.56


  5%|▌         | 26000/500000 [1:15:37<22:08:55,  5.94it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[ 5.83448958e+04  4.09715334e+05 -1.79948440e+06]
 [ 2.06580157e+05  1.53316266e+05 -9.02417923e+05]
 [ 2.05395484e+05  1.06420233e+05 -1.12800697e+06]
 [ 1.20382171e+05  1.59227291e+04  4.54911699e+05]
 [-8.31411279e+04  2.77626086e+03  1.79453043e+06]
 [ 1.34204325e+04  5.08232583e+02 -1.78256418e+06]]
prediction is:
 [[-28600.7   181892.72  -18062.742]
 [-17729.045 159608.25   -8649.92 ]
 [ -1703.146 168810.47  -28524.268]
 [-14690.895 160624.12  -13119.252]
 [ -7945.187 152471.19  -14527.159]
 [ 10343.561  41394.473 -13060.014]]


  5%|▌         | 26002/500000 [1:15:38<29:29:16,  4.47it/s]

loss is: 777081.3


  5%|▌         | 27000/500000 [1:18:26<22:00:38,  5.97it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[ 174395.561914     69888.1458111   492293.003531  ]
 [ 204564.043347    243795.079565   -875906.687867  ]
 [ 113561.607654      6252.81174098  430665.375246  ]
 [-204964.066752    215338.305891    858187.717167  ]
 [ -25148.0170748     1160.77587768  -34433.5040875 ]
 [-163965.427464     60800.6744246  -427574.273977  ]]
prediction is:
 [[-17507.318   148612.1       1098.6221 ]
 [-26040.836   222121.38     -2932.8486 ]
 [-26982.555   209850.22     -6596.091  ]
 [-25855.055   213872.7       -920.69336]
 [  9757.944    28317.805   -17548.273  ]
 [-26177.82    222172.62     -4445.033  ]]


  5%|▌         | 27002/500000 [1:18:26<29:29:22,  4.46it/s]

loss is: 493666.7


  6%|▌         | 28000/500000 [1:21:14<22:14:40,  5.89it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[ 1.78052331e+05  3.36497121e+05  1.37967582e+06]
 [-1.00602476e+05  7.56130804e+03 -3.24819729e+05]
 [-6.81419180e+04  4.09371845e+05 -1.79509810e+06]
 [-8.62971268e+04  4.08636877e+05 -1.78504635e+06]
 [ 1.50585375e+05  4.54330935e+04  4.73670560e+05]
 [-2.34563936e+04  1.19312585e+03 -2.13242262e+04]]
prediction is:
 [[ 24175.975  207136.06   -70332.3   ]
 [ 18173.248  201106.53   -60307.79  ]
 [ 22326.174  223384.72   -50373.805 ]
 [ 21517.629  217383.56   -55130.566 ]
 [ 20457.826  203623.69   -57791.04  ]
 [ -3449.6155  65064.61   -34268.406 ]]


  6%|▌         | 28002/500000 [1:21:15<29:23:09,  4.46it/s]

loss is: 721823.4


  6%|▌         | 29000/500000 [1:24:02<22:10:03,  5.90it/s]

save model
learning_rate is:
 0.67712003
real location is:
 [[ 7.66311371e+04  4.09769987e+05  1.79650484e+06]
 [-2.06103219e+05  2.58303033e+05  9.12687593e+05]
 [ 1.27613598e+05  2.28187172e+04 -1.37326643e+06]
 [ 4.32664599e+04  1.01853179e+03  1.79995470e+06]
 [-5.56638322e+04  2.46792862e+03  1.78832769e+06]
 [-1.52859567e+05  5.16786205e+04  1.37650941e+06]]
prediction is:
 [[ 27613.645  165566.56   -17712.41  ]
 [ 45342.742  218334.69    -4195.0215]
 [ 29032.998  174881.31   -28210.906 ]
 [ -8955.922   31762.547  -26408.135 ]
 [ 45254.203  217747.75    -1842.136 ]
 [ 36021.812  196729.4     11688.182 ]]


  6%|▌         | 29002/500000 [1:24:03<28:53:01,  4.53it/s]

loss is: 928817.2


  6%|▌         | 30000/500000 [1:26:50<21:33:43,  6.05it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[ -146929.806416    365288.404817  -1343738.80744  ]
 [ -191545.730246     88696.2759454  1345738.67443  ]
 [  174852.125272    339459.922621   1379878.62024  ]
 [  206248.488401    166699.87296    -869958.061136 ]
 [ -133446.36001      33737.9161158  1383179.62722  ]
 [  124306.802037     19807.9972349 -1370272.41557  ]]
prediction is:
 [[-25889.703  234335.38    24345.137 ]
 [-29369.535  168869.94    33091.297 ]
 [-24327.06   160688.44   -10248.945 ]
 [-21940.68   215162.81    24703.895 ]
 [-21238.574  195964.14     7234.1963]
 [  2397.0752 101177.97    -1521.8982]]


  6%|▌         | 30002/500000 [1:26:51<28:36:43,  4.56it/s]

loss is: 823629.6


  6%|▌         | 31000/500000 [1:29:38<21:51:33,  5.96it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[ 193111.973009    92031.8910931  554345.769457 ]
 [-204586.178237   163141.784013   920843.129173 ]
 [-190556.073082   321475.67774    448148.113806 ]
 [ 100692.288507   406774.731941  1465364.94789  ]
 [-205379.989689   203341.929544   911735.104085 ]
 [-205343.989745   294916.999811  -915937.008    ]]
prediction is:
 [[ 19917.426  168244.97    11354.5625]
 [ 23579.082  260427.12     6777.8975]
 [ 23307.938  278545.8      7283.7207]
 [ 11792.243   36962.242  -37935.28  ]
 [ 23220.422  245743.72     8435.677 ]
 [ 21410.512  249077.69     6993.532 ]]


  6%|▌         | 31002/500000 [1:29:39<28:57:16,  4.50it/s]

loss is: 729437.06


  6%|▋         | 32000/500000 [1:32:27<21:47:33,  5.97it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[-1.76734229e+05  3.34663312e+05  4.84953081e+05]
 [ 2.06080626e+05  2.78997930e+05  9.05070011e+05]
 [-7.33529909e+04  3.45715257e+03 -2.27423567e+04]
 [ 7.40694156e+04  1.77131135e+03 -1.77030475e+06]
 [-1.97210000e+05  9.37361344e+04 -4.77513089e+05]
 [-4.22117951e+04  5.62211366e+02  1.79048392e+06]]
prediction is:
 [[ 18795.674  245783.47    15163.086 ]
 [ 24386.668   63555.01   -10630.66  ]
 [ 19529.34   219017.72     7527.4844]
 [ 15323.745  254457.34    12772.023 ]
 [  6841.385  269786.62     7472.4536]
 [ 19884.887  164746.3      6183.1064]]


  6%|▋         | 32002/500000 [1:32:27<29:03:03,  4.47it/s]

loss is: 1005390.0


  7%|▋         | 33000/500000 [1:35:15<21:52:37,  5.93it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[-189057.614145   322480.544626   487445.293937 ]
 [ -77679.810505   408631.710258  1799110.13927  ]
 [-188875.9627      85018.2175115 -451213.649965 ]
 [ 207733.270244   174063.7588     919287.418043 ]
 [ 206232.563234   195217.712065   974311.85719  ]
 [ 206023.715956   192094.833694  -880379.805031 ]]
prediction is:
 [[ 40112.527 197666.31  -28529.102]
 [ 34701.46  142610.84   26480.217]
 [ 11684.766  70595.3   -50742.33 ]
 [ 38605.11  181027.34  -31007.332]
 [ 48115.805 195696.94  -25909.098]
 [ 34786.83  205542.88  -28073.941]]


  7%|▋         | 33002/500000 [1:35:16<28:57:45,  4.48it/s]

loss is: 567776.9


  7%|▋         | 34000/500000 [1:38:04<21:56:27,  5.90it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[ -149236.714088     47241.2871857  -428793.438381 ]
 [ -204345.291667    160841.420798    904886.564347 ]
 [  125666.349847     21136.8922413   452394.118694 ]
 [   48725.4114346   409402.791596  -1772726.39434  ]
 [  206192.035174    168085.302476   -881594.197175 ]
 [ -205770.011386    285097.953317    887586.511565 ]]
prediction is:
 [[ 2.6760190e+03  1.9141809e+05 -3.1759400e+04]
 [ 8.5145117e+03  2.7483556e+05 -9.2777656e+04]
 [ 9.7018418e+03  1.0082297e+05 -4.6358543e+04]
 [ 6.6775957e+03  2.8221919e+05 -9.0868312e+04]
 [-1.5637170e+02  2.0609888e+05 -3.9399902e+04]
 [-1.3412596e+04  1.7181919e+05 -3.2870582e+04]]


  7%|▋         | 34002/500000 [1:38:05<29:04:49,  4.45it/s]

loss is: 733589.75


  7%|▋         | 35000/500000 [1:40:53<21:45:47,  5.94it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[-2.08352027e+05  2.08272866e+05 -8.86447706e+05]
 [-3.18754696e+04  4.09403625e+05 -1.77707982e+06]
 [ 2.07555961e+05  2.07206404e+05  9.20476483e+05]
 [ 4.60301312e+04  1.06333286e+03  1.79549853e+06]
 [ 1.72285647e+05  6.75528360e+04  4.86752922e+05]
 [ 2.06503642e+05  1.47216956e+05 -8.86539706e+05]]
prediction is:
 [[ -3621.4111 192746.06   -59358.656 ]
 [ 10942.442  215734.56   -52715.203 ]
 [  2470.9785 185985.34   -49938.016 ]
 [ 42960.406   58976.625  -21984.129 ]
 [ 34114.316  238280.14   -38740.63  ]
 [ 15974.34   222080.95   -51263.18  ]]


  7%|▋         | 35002/500000 [1:40:54<29:06:20,  4.44it/s]

loss is: 857810.06


  7%|▋         | 36000/500000 [1:43:42<21:44:34,  5.93it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[ 9.72971446e+04  4.09127532e+05  1.65991897e+06]
 [ 9.78861146e+04  4.08612858e+05 -1.96917040e+05]
 [-7.44250151e+04  4.09354375e+05 -1.78263470e+06]
 [-2.08110531e+05  1.32080304e+05 -8.68205849e+05]
 [ 1.76222200e+03 -1.89527639e+03 -6.52266550e+05]
 [-1.91180023e+05  8.74069414e+04 -4.57308648e+05]]
prediction is:
 [[ 15977.64  160978.56   28686.79 ]
 [ 20627.23  235526.08   38261.977]
 [ 20813.416 182515.     61012.03 ]
 [ 20982.504 180368.81   60591.844]
 [ 22297.72  140944.22  -17661.799]
 [ 10237.604 179133.67    6486.583]]


  7%|▋         | 36002/500000 [1:43:43<28:55:40,  4.46it/s]

loss is: 604474.6


  7%|▋         | 37000/500000 [1:46:31<21:03:08,  6.11it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[-1.80708552e+05  3.30853412e+05  4.77637545e+05]
 [-2.07459061e+05  1.22484847e+05 -8.19268075e+05]
 [ 2.06614563e+05  1.34257794e+05 -8.87685403e+05]
 [-1.93088349e+05  3.19005777e+05  4.51668053e+05]
 [-7.90567728e+04  4.07788923e+03 -7.39340700e+02]
 [-1.45143445e+05  3.67089950e+05 -1.34096102e+06]]
prediction is:
 [[ -1088.5151 172234.44   -22545.727 ]
 [  2900.9824 130080.55   -23396.023 ]
 [ 26423.613  107257.95   -15919.352 ]
 [ -7053.4277 181468.33   -27242.352 ]
 [-13678.546   97849.984   -7369.5625]
 [ 12185.539  181380.69   -22772.463 ]]


  7%|▋         | 37002/500000 [1:46:31<28:30:47,  4.51it/s]

loss is: 654186.5


  8%|▊         | 38000/500000 [1:49:19<22:09:27,  5.79it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[  166445.728978    346743.830296   -421622.050492 ]
 [  -35851.4759081   407417.320612     20668.7758899]
 [  -34412.1370249   407440.111845     17055.1804084]
 [  206508.259584    149676.13175    -895232.617318 ]
 [  154935.659635     48486.9775646 -1380952.00647  ]
 [ -205810.621108    217341.674171    929850.321549 ]]
prediction is:
 [[ 50761.293  168235.16    -7705.474 ]
 [ 27890.754  144464.31     1393.7715]
 [ 25712.18   123335.89    -1081.0955]
 [ 58762.406  207042.17    -4625.713 ]
 [ 10119.8     77237.016  -28107.895 ]
 [ 30073.383  179917.22    -3097.3071]]


  8%|▊         | 38002/500000 [1:49:19<29:09:15,  4.40it/s]

loss is: 450019.8


  8%|▊         | 39000/500000 [1:52:07<21:31:48,  5.95it/s]

save model
learning_rate is:
 0.62295043
real location is:
 [[-1.16921375e+05  1.98305641e+04  1.41401001e+06]
 [ 1.64572554e+05  6.02295807e+04 -1.31792146e+06]
 [-2.07366709e+05  1.39475983e+05 -8.96002121e+05]
 [ 1.10521654e+04  5.13524190e+02 -1.79286591e+06]
 [-1.58023959e+05  3.54325980e+05  4.57947483e+05]
 [ 2.05620385e+05  2.96311324e+05  9.69594550e+05]]
prediction is:
 [[ 2.0863594e+04  2.6903938e+05 -2.2203328e+04]
 [ 2.3466664e+04  2.5370556e+05 -3.9738137e+03]
 [ 1.3700799e+04  2.3806073e+05 -3.2274358e+03]
 [-9.0432373e+01  3.9540590e+04 -2.8286893e+04]
 [ 2.3278105e+04  2.5122394e+05 -1.9881256e+03]
 [ 3.2583141e+04  2.4561259e+05  2.8095679e+02]]


  8%|▊         | 39002/500000 [1:52:08<28:42:40,  4.46it/s]

loss is: 689999.3


  8%|▊         | 40000/500000 [1:54:55<21:49:44,  5.85it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[ 2.04126247e+05  2.58855936e+05 -8.73409868e+05]
 [-2.07900471e+05  2.35145186e+05 -9.26861016e+05]
 [ 2.07263954e+05  2.39627925e+05  9.12421227e+05]
 [ 9.70471043e+04  3.98507283e+02  3.36269092e+04]
 [ 1.78581223e+05  7.45704613e+04  4.91938509e+05]
 [ 1.24809349e+05  1.84474495e+04  4.89719825e+05]]
prediction is:
 [[-11405.275  201648.81    16436.152 ]
 [-14390.633  213191.1     16119.26  ]
 [ -2535.4995 162163.34    15025.142 ]
 [ -3755.7058 187868.5     17395.666 ]
 [ -3038.103  176379.62    16457.799 ]
 [ -4408.1616   1234.5918 -12293.6   ]]


  8%|▊         | 40002/500000 [1:54:56<28:22:19,  4.50it/s]

loss is: 513360.0


  8%|▊         | 41000/500000 [1:57:44<21:05:14,  6.05it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[  128511.004393     383626.619073    -440316.680217  ]
 [  191734.512394      88317.8368402  -1225714.56949   ]
 [  207294.847258     241821.966307     914796.618181  ]
 [  -49860.111226     408493.9262        11513.650062  ]
 [  -30559.4687263      1631.97837138   -34499.7680926 ]
 [  -43970.8833231      2267.32731191    -8520.55412317]]
prediction is:
 [[-24617.344  249124.53   -18728.35  ]
 [-14635.113  212275.25    -4763.3877]
 [-25678.895  246193.9     -6622.462 ]
 [-31823.219  268566.8    -30223.123 ]
 [-20977.826   74886.05   -29543.416 ]
 [-23384.234  239663.28   -21909.908 ]]


  8%|▊         | 41002/500000 [1:57:45<28:27:06,  4.48it/s]

loss is: 396074.16


  8%|▊         | 42000/500000 [2:00:33<21:36:33,  5.89it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[  -19058.5378888    408836.466922   -1795186.45586   ]
 [  204633.91474      238137.847144    -894302.383008  ]
 [  207528.06204      208305.677776     923078.736388  ]
 [  145304.932713      39711.9894505  -1360957.02246   ]
 [ -206193.74479      267524.774559    -923297.909065  ]
 [  -64001.4819955      3482.82719445   -15159.7469392 ]]
prediction is:
 [[ 1.9738992e+04  2.0364153e+05 -4.5551279e+03]
 [ 1.0502290e+04  1.9404794e+05  7.8852852e+03]
 [ 1.2216911e+04  2.0800262e+05  3.9505806e+03]
 [ 2.7790510e+04  2.5949653e+05 -1.1235742e+02]
 [ 8.0830928e+03  1.8786566e+05  6.8421401e+03]
 [-1.7380348e+04  4.0864781e+04 -9.3029766e+03]]


  8%|▊         | 42002/500000 [2:00:33<28:40:26,  4.44it/s]

loss is: 1085640.0


  9%|▊         | 43000/500000 [2:03:21<21:10:22,  6.00it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[ -206103.218928     258303.033457     912687.592955  ]
 [ -203856.905801     122449.195956     957321.392076  ]
 [ -191645.995336      88841.4567519   1327313.74098   ]
 [  180968.911803     333380.522977    -439974.632946  ]
 [ -146627.755005     366051.463424     466549.146106  ]
 [   75586.8198809      1866.91365129 -1784100.6504    ]]
prediction is:
 [[ 13290.672   244697.86    -47215.25   ]
 [ 18434.47     63912.938     -596.28906]
 [ 20375.4     192322.8     -32535.127  ]
 [ 14774.574   226999.69    -43868.7    ]
 [ 10429.014   264954.88    -50768.12   ]
 [-17491.963   181342.92    -45297.67   ]]


  9%|▊         | 43002/500000 [2:03:22<28:09:47,  4.51it/s]

loss is: 678531.75


  9%|▉         | 44000/500000 [2:06:09<21:39:56,  5.85it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[  206036.971893    117890.36808     902066.899829 ]
 [  152723.190132     48096.1751617 -1333782.70061  ]
 [  -73353.8599939   409395.665371  -1785281.74563  ]
 [  207898.240162    166465.264255    930241.846218 ]
 [ -152281.857443    360074.481084    456346.806171 ]
 [ -117986.850382    393716.636992    412082.405846 ]]
prediction is:
 [[  9541.59   110941.67   -24858.57  ]
 [-11186.283  174278.28   -39124.13  ]
 [-30858.875  216011.94   -45548.383 ]
 [  4078.3953 181409.12   -34849.31  ]
 [ -7617.9307 180998.1    -38137.863 ]
 [-40304.008  247397.89   -50522.695 ]]


  9%|▉         | 44002/500000 [2:06:10<28:11:32,  4.49it/s]

loss is: 645246.25


  9%|▉         | 45000/500000 [2:08:58<21:19:39,  5.93it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[ 2.06232563e+05  1.95217712e+05  9.74311857e+05]
 [-4.33715961e+04  1.03880627e+03  1.78105612e+06]
 [ 9.84061066e+04  4.08779053e+05  1.59579994e+06]
 [-2.29988740e+04 -6.59824094e+02  1.79968235e+06]
 [-1.51881321e+05  4.97091511e+04 -4.25767845e+05]
 [ 6.44502892e+04  4.08565551e+05 -1.86282711e+03]]
prediction is:
 [[ 18430.059  175207.34   -41177.336 ]
 [ 16481.246  151394.02   -36297.145 ]
 [ 12597.992  210916.17   -44737.625 ]
 [ 47589.133   80073.09     4108.5366]
 [  5571.8037 176711.47   -53931.656 ]
 [ 31054.812  133298.72    -9686.398 ]]


  9%|▉         | 45002/500000 [2:08:59<28:23:32,  4.45it/s]

loss is: 704478.4


  9%|▉         | 46000/500000 [2:11:46<21:16:10,  5.93it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[ 1.66166315e+05  3.47786669e+05  1.36953611e+06]
 [ 1.76323660e+05  7.20940175e+04  4.80575397e+05]
 [ 2.81640136e+04  3.90532081e+02 -1.81428863e+03]
 [ 2.06646052e+05  1.60084764e+05 -8.50755902e+05]
 [-2.05379990e+05  2.03341930e+05  9.11735104e+05]
 [ 1.38433973e+05  3.32398257e+04 -1.35121164e+06]]
prediction is:
 [[  6376.8994 234440.84   -33308.96  ]
 [ 17717.438  130490.36     5585.1914]
 [ 40591.18    61021.473  -21812.979 ]
 [  6305.0737 202176.81   -30771.484 ]
 [  4819.4683 238241.66   -37009.965 ]
 [ 10548.539  160355.31   -13962.026 ]]


  9%|▉         | 46002/500000 [2:11:46<28:18:37,  4.45it/s]

loss is: 657559.8


  9%|▉         | 47000/500000 [2:14:34<20:59:52,  5.99it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[ -205857.778498    218410.583767    924480.910209 ]
 [ -159912.13272     352473.573881    462939.525963 ]
 [  123430.217215     19518.0401169 -1361756.92428  ]
 [ -204493.02423     108909.389713   -753647.523738 ]
 [  -77827.190326    407924.892257     -6454.8986304]
 [   52941.7314343   409484.207559  -1786264.76126  ]]
prediction is:
 [[-30598.66   176823.38    -6409.3604]
 [-30252.531  175515.44    -4389.0513]
 [ 64868.29    45810.03    12908.9795]
 [-16725.537  189397.66   -23234.898 ]
 [-35094.176  164115.14   -12362.667 ]
 [-32649.05   182793.53    -8097.673 ]]


  9%|▉         | 47002/500000 [2:14:35<28:04:09,  4.48it/s]

loss is: 593330.1


 10%|▉         | 48000/500000 [2:17:24<21:07:26,  5.94it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[-1.92745341e+05  8.90957296e+04 -4.67363120e+05]
 [ 1.78748388e+05  3.34734907e+05 -4.44923759e+05]
 [-2.05311587e+05  2.43169362e+05  9.30778209e+05]
 [ 9.96224596e+04  4.07454078e+05  1.49633916e+06]
 [ 8.47714736e+03  5.76643558e+02  5.65257054e+03]
 [ 1.02905768e+05  3.54845330e+03 -1.64609398e+06]]
prediction is:
 [[ -57543.004   322224.     -112208.97  ]
 [  18514.72    168823.1     -47523.844 ]
 [   7117.01    158406.      -43792.98  ]
 [  13712.57    218475.81    -61549.89  ]
 [  16947.266   117245.414   -31667.22  ]
 [  -3492.5444  156768.4     -34069.04  ]]


 10%|▉         | 48002/500000 [2:17:24<28:12:48,  4.45it/s]

loss is: 601262.6


 10%|▉         | 49000/500000 [2:20:12<21:12:52,  5.91it/s]

save model
learning_rate is:
 0.57311445
real location is:
 [[ 1.12689318e+05  5.52051061e+03  3.98228408e+05]
 [-1.66471859e+05  3.45516956e+05 -1.34258005e+06]
 [-1.78188703e+05  7.54287671e+04  1.36335520e+06]
 [ 1.58785392e+05  3.55464534e+05 -4.38124355e+05]
 [ 6.94762431e+04  1.66070560e+03 -1.77248529e+06]
 [-6.65371678e+04  2.85778174e+03  1.78598893e+06]]
prediction is:
 [[-3.8857883e+04  1.9027441e+05 -4.5203930e+04]
 [-2.1018814e+04  1.8567622e+05 -2.6698281e+04]
 [-1.2843133e+04  1.7249875e+05 -1.4673400e+04]
 [-2.3498457e+04  2.0462970e+05 -3.5305570e+04]
 [ 1.1910010e+02  5.0014609e+04 -8.7662471e+03]
 [-1.3391598e+04  1.7790875e+05 -1.5527959e+04]]


 10%|▉         | 49002/500000 [2:20:13<28:12:18,  4.44it/s]

loss is: 727288.75


 10%|█         | 50000/500000 [2:23:01<21:14:51,  5.88it/s]

save model
learning_rate is:
 0.52726525
real location is:
 [[ -103718.970513       9486.2459643   1423082.46229   ]
 [  -81863.6323573      3884.98891126   -21045.9940922 ]
 [  207333.728208     218072.268562     883685.010293  ]
 [  206194.856007     176715.868744    -887610.60778   ]
 [ -154194.89069      358523.815758   -1343785.92209   ]
 [  -91439.085081     407749.66205        2703.39384851]]
prediction is:
 [[ -8213.064   55124.992   16410.73  ]
 [-26329.328  173333.1      7673.742 ]
 [-30052.117  233076.69    38563.94  ]
 [-38699.035  216085.38    29342.424 ]
 [-40580.5    221999.62    33142.81  ]
 [-44949.33   209159.62    -8017.2725]]


 10%|█         | 50002/500000 [2:23:02<28:09:11,  4.44it/s]

loss is: 615724.1


 10%|█         | 51000/500000 [2:25:49<21:08:25,  5.90it/s]

save model
learning_rate is:
 0.52726525
real location is:
 [[ 2.05574173e+05  2.61854762e+05  9.12927360e+05]
 [ 8.44316588e+04  1.72505245e+03 -1.77301348e+06]
 [-1.48863544e+04  4.08751618e+05 -1.79325919e+06]
 [-1.18836779e+05  2.13572129e+04  1.39992016e+06]
 [ 1.92982199e+05  9.19236590e+04  5.42317474e+05]
 [-2.05032940e+05  1.81790373e+05  9.21465299e+05]]
prediction is:
 [[-31617.398  223237.19    -7804.965 ]
 [ -5479.918  155911.22   -11955.0205]
 [ -1503.5776  49281.65   -18810.617 ]
 [-25088.209  211059.25   -16232.754 ]
 [-18976.793  176053.       1751.8174]
 [-30763.184  233854.31   -17843.295 ]]


 10%|█         | 51002/500000 [2:25:50<28:00:21,  4.45it/s]

loss is: 739608.7


 10%|█         | 52000/500000 [2:28:38<20:52:00,  5.96it/s]

save model
learning_rate is:
 0.52726525
real location is:
 [[  153908.42013      48670.5474392   468888.743426 ]
 [  206126.598315    276785.25604     933541.276272 ]
 [ -208226.195259    226447.217176   -908304.30718  ]
 [  164478.333682     57017.4739938 -1369597.36607  ]
 [   10868.9485001   409114.875036  -1787594.93732  ]
 [   89817.7397117   409866.916731   1788198.3955   ]]
prediction is:
 [[ 52352.34  183809.78   29972.828]
 [ 55441.758 202330.67   33679.22 ]
 [ 61743.652 219815.62   31126.695]
 [ 46617.742 165343.4    23885.045]
 [ 13913.624  47068.1   -14693.262]
 [ 64373.652 218189.56   30039.129]]


 10%|█         | 52002/500000 [2:28:39<27:58:28,  4.45it/s]

loss is: 690143.7


 11%|█         | 53000/500000 [2:31:28<20:53:49,  5.94it/s]

save model
learning_rate is:
 0.52726525
real location is:
 [[ 8.24384723e+04  4.14616673e+02  3.40325054e+04]
 [-1.74132257e+05  3.38085556e+05 -1.34329213e+06]
 [ 1.11506106e+05  3.98715832e+05 -3.47148432e+05]
 [ 2.07551656e+05  1.96527452e+05  9.03611981e+05]
 [-1.66731578e+04  4.08215322e+05  5.38295965e+03]
 [ 2.05019285e+05  2.25207088e+05 -8.22758366e+05]]
prediction is:
 [[  1943.1499  123082.67      -234.13928]
 [ -1449.2085  147417.62    -19280.598  ]
 [  -265.5537  220752.53    -20818.742  ]
 [ -2160.0469  214020.55    -29760.477  ]
 [  5126.5513   30505.514    -5830.307  ]
 [  -760.8291  220664.89    -20101.559  ]]


 11%|█         | 53002/500000 [2:31:28<27:53:14,  4.45it/s]

loss is: 476584.1


 11%|█         | 54000/500000 [2:34:17<21:01:50,  5.89it/s]

save model
learning_rate is:
 0.52726525
real location is:
 [[-5.70824507e+04  1.36689235e+03  1.76812727e+06]
 [-2.08419915e+05  2.20990128e+05 -9.13272256e+05]
 [-1.88200149e+05  8.50284851e+04  1.34158441e+06]
 [ 2.06048760e+05  1.16604047e+05  9.14223581e+05]
 [ 1.59971245e+05  5.53022091e+04 -1.31890158e+06]
 [-1.95086194e+05  9.26624428e+04  1.32512273e+06]]
prediction is:
 [[-16477.053  201095.1    -18323.086 ]
 [-14945.697  179898.75   -82636.61  ]
 [-15827.397  224807.     -34079.492 ]
 [-12489.     142695.98   -19527.71  ]
 [ -1493.5626 109345.42    -5823.2637]
 [-19613.498  267477.28   -33251.566 ]]


 11%|█         | 54002/500000 [2:34:17<28:01:58,  4.42it/s]

loss is: 764631.25


 11%|█         | 54881/500000 [2:36:46<20:58:29,  5.89it/s]