In [1]:
import os
import random
import skimage.data
from skimage import io
import skimage.transform as skt
import numpy as np
import tensorflow as tf
from tqdm import tqdm
import sys
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
import cv2

In [2]:
# submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhuan/submap"
# pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhuan/picture"

# # for i in range(4):
# i = 1
# submap1 = cv2.imread(os.path.join(submap_dir,str(0) + '.pgm'))
# submap1 = cv2.resize(submap1,(448,448))
# submap1 = cv2.transpose(submap1)
# submap1 = cv2.flip(submap1, 1)
# # submap1 = np.rot90(submap1)
# cv2.imshow("submap",submap1)


# pic1 = cv2.imread(os.path.join(pic_dir, '00000.jpg'))
# cv2.imshow("pic",pic1)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# print(np.shape(submap1))

In [3]:
train_label_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhuan448_angle"
train_pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhuan448_angle/picture"
train_submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhuan448_angle/submap"

def get_train_data_batch(num, pic_dir=train_pic_dir, label_dir=train_label_dir,submap_dir=train_submap_dir):
    train_txt = os.path.join(label_dir,"label.txt")
    count = len(open(train_txt,'r').readlines()) - 1    
    idx = np.arange(0, count)      
    np.random.shuffle(idx)                
    data_idx = idx[:num]
#     print(data_idx)
    
    labels = []
    images = []
    
    for i in range(num):
        with open(train_txt,'r') as file:
            s = file.readlines()
            image1 = skimage.data.imread(os.path.join(pic_dir, s[data_idx[i]].split(";")[0]))
            submap1 = cv2.imread(os.path.join(submap_dir,str(data_idx[i]) + '.pgm'))
            submap1 = cv2.resize(submap1,(448,448))
            submap1 = cv2.transpose(submap1)
            submap1 = cv2.flip(submap1, 1)
            img = cv2.merge([image1,submap1])
            images.append(img)

            label = s[data_idx[i]].split(";")[1:]
            label = list(map(float,label))
            labels.append(label)
    return np.asarray(images),np.asarray(labels)

num = 10
# for i in range(10):
train_images, train_labels = get_train_data_batch(num)
#     print(train_labels)
print(np.shape(train_images))
print(np.shape(train_labels))
print(train_labels)
# print(train_labels*100)

(10, 448, 448, 6)
(10, 3)
[[ 1.20145202e+01  1.61486020e+00  4.35688194e+01]
 [ 8.53054872e+00 -1.52672803e-02  3.61049877e+00]
 [-1.31765933e+01  3.81320659e+01  4.58146481e+01]
 [-7.59490129e+00  4.08376702e+01 -1.78374512e+02]
 [ 1.82988268e+01  3.31585331e+01 -4.38750893e+01]
 [ 1.01337654e+01  9.48796657e-02 -2.36536049e+00]
 [ 2.05375280e+01  2.18238879e+01  8.77467826e+01]
 [-2.29385749e+00  4.09209276e+01 -1.77453135e+02]
 [-2.05247972e+01  1.56634498e+01  9.37428051e+01]
 [-1.44638066e+01  3.67247033e+01 -1.34656029e+02]]


In [4]:
with tf.name_scope("input"):
    input_image = tf.placeholder("float", [None, 448,448,6],name='input_image')/255.*2.-1
#     input_image = tf.pad(image,np.array([[0, 0], [3, 3], [3, 3], [0, 0]]))
    y_ = tf.placeholder("float", [None, 3],name='y_') 

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape = shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding="SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")


W_conv0 = weight_variable([7, 7, 6, 64])
b_conv0 = bias_variable([64])

h_conv0 = tf.nn.leaky_relu(tf.nn.conv2d(input_image, W_conv0, strides=[1,1,1,1], padding="SAME") + b_conv0)
h_pool0 = max_pool_2x2(h_conv0)   #输出变成224*224*64 [None,224,224,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度

W_conv1 = weight_variable([7, 7, 64, 128])
b_conv1 = bias_variable([128])

h_conv1 = tf.nn.leaky_relu(conv2d(h_pool0, W_conv1) + b_conv1)
# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1, strides=[1,2,2,1], padding="SAME") + b_conv1)
h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64   [None,112,112,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度
# W_conv1 = weight_variable([7, 7, 6, 64])
# b_conv1 = bias_variable([64])

# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1,strides=[1,2,2,1],padding="SAME") + b_conv1)
# h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64

#第二层卷积层
W_conv2 = weight_variable([3, 3, 128, 192])
b_conv2 = bias_variable([192])

h_conv2 = tf.nn.leaky_relu(conv2d(h_pool1, W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2)  #输出变为56*56*192


#第三层卷积层
W_conv3 = weight_variable([3, 3, 192, 128])
b_conv3 = bias_variable([128])

h_conv3 = tf.nn.leaky_relu(conv2d(h_pool2, W_conv3) + b_conv3)
h_pool3 = max_pool_2x2(h_conv3)   #输出为28*28*128


#第四层卷积层
W_conv4 = weight_variable([3, 3, 128, 64])
b_conv4 = bias_variable([64])

h_conv4 = tf.nn.leaky_relu(conv2d(h_pool3, W_conv4) + b_conv4)
h_pool4 = max_pool_2x2(h_conv4)   #输出变为14*14*64


#密集连接层1
W_fc1 = weight_variable([14*14*64, 1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool4, [-1, 14*14*64])
h_fc1 = tf.nn.leaky_relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)   #输出为96*1024

keep_prob = tf.placeholder("float")
#relu函数作用是求出max(h_fc1,0)
h_fc1_drop1 = tf.nn.dropout(h_fc1, keep_prob)   #输出为96*1024


#密集连接层2
W_fc2 = weight_variable([1024, 512])
b_fc2 = bias_variable([512])

h_fc2 = tf.nn.leaky_relu(tf.matmul(h_fc1_drop1, W_fc2) + b_fc2)

#relu函数作用是求出max(h_fc1,0)
h_fc1_drop2 = tf.nn.dropout(h_fc2, keep_prob)

#输出层softmax层
W_fc3 = weight_variable([512, 3])

y_conv = tf.matmul(h_fc1_drop2, W_fc3)
# tf.summary.histogram('y_conv',y_conv)

# batch_x = images[1:3]
# batch_y = labels[1:3]
# with tf.Session() as sess:
#     sess.run(tf.global_variables_initializer())
#     print("shape of outputs is:",sess.run(tf.shape(y_conv),feed_dict={input_image:batch_x, 
#                                                                            y_:batch_y,keep_prob:1.0}))
#         print("learning rate is :",sess.run(learning_rate,feed_dict = {global_step:i}))


starter_learning_rate = 0.0003
steps_per_decay = 3000
decay_factor = 0.9

global_step = tf.Variable(tf.constant(0))
learning_rate = tf.train.exponential_decay(learning_rate = starter_learning_rate,
                                           global_step = global_step,
                                           decay_steps = steps_per_decay,
                                           decay_rate = decay_factor,
                                           staircase = True
                                           )

delta=tf.constant(1.25)
#huber损失函数
loss = tf.reduce_mean(tf.multiply(tf.square(delta),
                                          tf.sqrt(1. + tf.square((y_ - y_conv)/delta)) - 1.))

# cross_entropy = tf.reduce_sum(tf.square(y_-y_conv)) 
tf.summary.scalar("loss",loss)

train_step = tf.train.AdamOptimizer(learning_rate).minimize(loss)
# train_step = tf.train.AdadeltaOptimizer(learning_rate).minimize(cross_entropy)
# train_step = tf.train.RMSPropOptimizer(learning_rate).minimize(cross_entropy)

# correct_prediction = tf.equal(tf.argmax(y_conv, 1), tf.argmax(y_, 1))
# accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
# tf.summary.scalar("accuracy", accuracy)
merged = tf.summary.merge_all()

batch_size = 4          
checkpointsPath = "./checkpoints/"
reload = False

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    #保存训练好的模型一遍下次使用
    saver = tf.train.Saver()
    writer = tf.summary.FileWriter("logs_dir/", sess.graph)
    
    if not os.path.exists(checkpointsPath):
        os.mkdir(checkpointsPath)
    
    if reload:
        checkPoint = tf.train.get_checkpoint_state(checkpointsPath)
        if checkPoint and checkPoint.model_checkpoint_path:
            saver.restore(sess,checkPoint.model_checkpoint_path)
            print("restored %s" % checkPoint.model_checkpoint_path)
        else:
            print("no checkpoint found!")
        
    for i in tqdm(range(100000)):
        batch_x,batch_y = get_train_data_batch(batch_size)
        batch_y = batch_y*1000
        summary,_ = sess.run([merged,train_step],feed_dict={global_step:i,
                                                            input_image:batch_x, 
                                                            y_:batch_y, 
                                                            keep_prob:0.8})
        writer.add_summary(summary, i)
        if (i % 1000) == 0 & (i != 0):
            print("save model")
            print("learning_rate is:\n",sess.run(learning_rate,feed_dict = {global_step:i}))
            print("real location is:\n",batch_y)
            print("prediction is:\n",sess.run(y_conv,feed_dict={input_image:batch_x, y_:batch_y,keep_prob:1.0}))
#             saver.save(sess, os.path.join(checkpointsPath,"saved_net.ckpt"), global_step=i)
            print("loss is:",sess.run(loss,feed_dict={input_image:batch_x, y_:batch_y, keep_prob:1.0}))
    print("done!")


  0%|          | 0/100000 [00:00<?, ?it/s]

save model
learning_rate is:
 0.0003
real location is:
 [[-1.51696841e+02  4.09584690e+04 -1.77542120e+05]
 [-1.52656074e+04  3.59238357e+04 -1.35359471e+05]
 [ 2.03574610e+04  2.91090618e+04 -8.56803649e+04]
 [-1.13988161e+04  1.61386346e+03  1.38558885e+05]]
prediction is:
 [[ -253918.64  -369651.75 -1177068.5 ]
 [ -295920.94  -380123.34 -1132698.5 ]
 [ -282159.03  -357545.12 -1148225.5 ]
 [ -280174.25  -385554.47 -1148778.5 ]]


  0%|          | 1/100000 [00:02<63:20:57,  2.28s/it]

loss is: 734679.94


  1%|          | 1001/100000 [04:24<8:23:57,  3.27it/s]

save model
learning_rate is:
 0.0003
real location is:
 [[-9.68628829e+03  4.07763240e+04 -1.72939326e+05]
 [ 2.06014297e+04  2.02034331e+04  9.30666077e+04]
 [-2.15941747e+03  4.09510337e+04 -1.79600258e+05]
 [ 6.64186802e+03 -2.47784676e+01  1.78642047e+05]]
prediction is:
 [[ 3550.2676 14826.844   8031.783 ]
 [11315.46   16895.365  55668.086 ]
 [ 4906.853  22775.607  43616.53  ]
 [ 2990.6284  9672.088   4658.639 ]]
loss is: 73533.82


  2%|▏         | 2001/100000 [08:45<8:18:49,  3.27it/s]

save model
learning_rate is:
 0.0003
real location is:
 [[ 1.02304022e+04  9.46848909e+01 -1.46416495e+05]
 [ 1.53356281e+04  3.60060468e+04  1.34920800e+05]
 [ 2.06081334e+04  1.96006957e+04  9.19603758e+04]
 [-6.21132295e+03  3.50405308e+02  2.32549970e+02]]
prediction is:
 [[  -611.56665  13594.121   -21111.55   ]
 [  6239.072    22487.844    41812.633  ]
 [ 14022.939    15252.244    72919.23   ]
 [  6535.3896   12718.287    13472.706  ]]
loss is: 34758.734


  3%|▎         | 3001/100000 [13:06<8:13:29,  3.28it/s]

save model
learning_rate is:
 0.00027000002
real location is:
 [[-11141.1885667    1541.2242487  -17654.2231739 ]
 [-14267.9762639    4157.03665759 136644.531314  ]
 [-13421.0492662   37886.0347585   45403.3281066 ]
 [-17818.6840277    7478.98438182 -44726.8171565 ]]
prediction is:
 [[ -2720.291   6315.952 -32629.566]
 [-16360.775   5603.745 111342.33 ]
 [ -5290.877  11635.74   48599.652]
 [-11524.869   4624.009 -24063.37 ]]
loss is: 12956.949


  4%|▍         | 4001/100000 [17:27<8:12:14,  3.25it/s]

save model
learning_rate is:
 0.00027000002
real location is:
 [[ -20343.0745457    10782.7775159   -81634.9585718 ]
 [ -16436.7041122     6172.41170158  -43258.2511581 ]
 [  -2293.8574905    40920.9276118  -177453.135448  ]
 [  -3397.19356765   40898.8379432  -179124.383747  ]]
prediction is:
 [[ -14512.424    24356.293   -75402.65  ]
 [ -11164.1045    6449.4736  -40362.367 ]
 [   8754.835    49909.984  -181874.48  ]
 [   9007.476    39131.242   -96963.516 ]]
loss is: 16131.175


  5%|▌         | 5001/100000 [21:48<8:03:39,  3.27it/s]

save model
learning_rate is:
 0.00027000002
real location is:
 [[ -10097.2359256    40697.9097858    21348.4781738 ]
 [  -5860.3161796    40987.3690408      206.24049755]
 [    443.65671618   40981.1714513  -177485.486332  ]
 [ -19952.6155303     9727.74831985  -52268.8302828 ]]
prediction is:
 [[-6.84690234e+03  2.38529961e+04  1.05907998e+04]
 [-5.13526709e+03  2.14277988e+04  4.33298906e+04]
 [-8.58520508e+01  2.60570000e+04 -1.30754734e+05]
 [-7.17353418e+03  1.27431699e+04 -5.03853477e+04]]
loss is: 18136.314


  6%|▌         | 6001/100000 [26:09<7:58:25,  3.27it/s]

save model
learning_rate is:
 0.00024299999
real location is:
 [[ 14919.8979751  36405.1811552 135306.237612 ]
 [ 20669.7660429  13724.6066077  89783.8327599]
 [ 20666.0396735  14408.6350276  92538.7591414]
 [-20698.6119612  22346.7720028  89578.7744893]]
prediction is:
 [[ 10633.765   32865.656  124998.22  ]
 [ 15173.121   16508.598   52027.348 ]
 [ 16094.943   15658.2705  90991.84  ]
 [-17082.6     18852.4     80856.4   ]]
loss is: 9099.6045


  7%|▋         | 7001/100000 [30:30<7:53:57,  3.27it/s]

save model
learning_rate is:
 0.00024299999
real location is:
 [[ -20501.6604809    28240.8597252   -91141.8774673 ]
 [   8380.54789544     143.70251676   -2654.64533444]
 [ -13702.0294949    37578.1112059  -135486.383702  ]
 [  -2758.03481502   41144.9810955     3952.5928247 ]]
prediction is:
 [[  3369.8875  22777.389  -51708.69  ]
 [ 13047.359   10589.648   43507.574 ]
 [ -7987.4604  26669.99   -89427.125 ]
 [ -7002.232   35390.043   -9915.054 ]]
loss is: 22560.096


  8%|▊         | 8001/100000 [34:51<7:48:17,  3.27it/s]

save model
learning_rate is:
 0.00024299999
real location is:
 [[ -20544.629683     29424.8086245   -91915.2841199 ]
 [ -15447.8636739    35797.2724105  -136482.92968   ]
 [ -15154.549036      4976.29403691  137709.292942  ]
 [ -17301.1949768     6960.23324845  135875.168368  ]]
prediction is:
 [[ -26436.336    24926.54    -84131.69  ]
 [ -12680.344    27518.219  -101140.016 ]
 [ -18105.715     1439.8324  136575.31  ]
 [ -24833.625    -3487.9224  143247.72  ]]
loss is: 10158.625


  9%|▉         | 9001/100000 [39:12<7:42:52,  3.28it/s]

save model
learning_rate is:
 0.0002187
real location is:
 [[-11172.0303984    1525.51946121 -39664.4378304 ]
 [ 10006.9732339   40757.9460241  -32780.219852  ]
 [-11320.3925873    1649.80593432 -39289.8209807 ]
 [ -6812.27223455  40984.0378797    3387.83285756]]
prediction is:
 [[-1.5673079e+04 -2.7986572e+01 -2.6136984e+04]
 [ 8.6439873e+03  2.2492844e+04 -9.0850537e+02]
 [-1.2371557e+04  1.6244471e+03 -4.4718672e+04]
 [-6.4718394e+03  3.1763602e+04  6.3611777e+03]]
loss is: 9386.087


 10%|█         | 10001/100000 [43:33<7:37:57,  3.28it/s]

save model
learning_rate is:
 0.0002187
real location is:
 [[  20588.0668493    12212.6930486    90941.0121705 ]
 [ -13832.1228231     3790.28190259  137276.356508  ]
 [  20823.8805935    15235.0098669   -87889.6877739 ]
 [  -3926.48284832   40886.9917152  -179180.978119  ]]
prediction is:
 [[ 2.1135941e+04  1.4196273e+04  9.2323641e+04]
 [-1.1183509e+04  8.2745422e+01  1.4834172e+05]
 [ 1.6399488e+04  1.8258578e+04 -3.8990812e+04]
 [-2.9132812e+03  3.7005992e+04 -1.5703019e+05]]
loss is: 10907.546


 11%|█         | 11001/100000 [47:53<7:32:59,  3.27it/s]

save model
learning_rate is:
 0.0002187
real location is:
 [[ 14289.1496411   37040.7450555  136724.644891  ]
 [ -5837.81130293    342.77975935   -835.80335082]
 [-16286.9912388    6030.0676484  -42673.5735302 ]
 [-17834.7676379   33389.0281898   47006.6350306 ]]
prediction is:
 [[  9596.504    33147.023   113649.99   ]
 [ -7073.0293   -2198.2244     155.48926]
 [-17969.387     5846.067   -44785.57   ]
 [-22873.18     26980.93     65720.25   ]]
loss is: 7349.1724


 12%|█▏        | 12001/100000 [52:14<7:27:41,  3.28it/s]

save model
learning_rate is:
 0.00019682996
real location is:
 [[-1.35059999e+04  3.47754762e+03 -4.19591641e+04]
 [ 5.81017472e+03 -4.96832892e+01 -1.81841412e+03]
 [-2.06473668e+04  2.51027565e+04  8.26507505e+04]
 [-9.96013268e+03  3.51868901e+02  1.42289400e+05]]
prediction is:
 [[-21785.814   10361.006  -77360.19  ]
 [  -794.4434  -1644.357  -13726.461 ]
 [-21980.441   30207.129   76388.484 ]
 [ -7633.9614  -1165.6282 174417.44  ]]
loss is: 12430.005


 13%|█▎        | 13001/100000 [56:35<7:22:42,  3.28it/s]

save model
learning_rate is:
 0.00019682996
real location is:
 [[  19568.2455693     9374.79398203   50990.4868917 ]
 [ -20680.0728019    25689.0462606   -91513.9595084 ]
 [  18509.2377904    32913.6503809   134961.521126  ]
 [  19833.7125994     9948.48255831 -143089.865604  ]]
prediction is:
 [[  19275.176   19219.484   56237.445]
 [ -19691.25    20573.791  -80214.45 ]
 [  19377.492   31844.758  153947.7  ]
 [  14606.214   18489.176 -107732.81 ]]
loss is: 10710.612


 14%|█▍        | 14001/100000 [1:00:56<7:25:01,  3.22it/s]

save model
learning_rate is:
 0.00019682996
real location is:
 [[-14674.4949769    4566.01958238 -44332.6094385 ]
 [-20581.8154466   14923.1414546  -89692.5089    ]
 [ 13977.2924929    3508.89210637  45606.9108268 ]
 [-15582.8541266    5412.78708529 -42019.7819092 ]]
prediction is:
 [[-10866.414    3658.487  -36728.695 ]
 [-14354.1455   4206.617  -46438.68  ]
 [ 14095.193   -2422.74    35874.4   ]
 [-13231.061    5031.5938 -33617.33  ]]
loss is: 10356.255


 15%|█▌        | 15001/100000 [1:05:17<7:12:57,  3.27it/s]

save model
learning_rate is:
 0.00017714698
real location is:
 [[  17283.1160224     6753.15423469 -131360.094986  ]
 [ -20405.8639274    30273.9002029  -107857.086936  ]
 [ -20588.1913337    18177.8511362    88510.7127857 ]
 [ -20704.5686066    16659.4116669   -89682.9507161 ]]
prediction is:
 [[  16197.074    9767.863 -118319.89 ]
 [  -5801.603   24464.762  -43754.51 ]
 [ -14536.023   22999.04    57776.375]
 [ -19490.375   15300.092  -77139.734]]
loss is: 16496.494


 16%|█▌        | 16001/100000 [1:09:38<7:07:29,  3.27it/s]

save model
learning_rate is:
 0.00017714698
real location is:
 [[ -12885.676005    38410.9108329 -135964.35587  ]
 [ -20535.7558119   12542.0480281  -86640.8660739]
 [ -18779.5948071   32298.9909806 -133225.447851 ]
 [ -15966.6424131   35434.9204884   43916.3921185]]
prediction is:
 [[  -8342.078   41165.89  -133988.53 ]
 [ -20660.43    15250.021  -90244.84 ]
 [ -12865.429   31406.824 -128843.234]
 [ -16012.318   20431.818   89778.016]]
loss is: 9145.313


 17%|█▋        | 17001/100000 [1:13:59<7:03:33,  3.27it/s]

save model
learning_rate is:
 0.00017714698
real location is:
 [[ 6.91917298e+03 -3.04398555e+01  1.78020574e+05]
 [-2.05676067e+04  1.37653359e+04 -9.20631049e+04]
 [ 3.39167466e+03  4.11925304e+04  2.10005658e+03]
 [-8.37003531e+03  4.08425961e+04 -1.78526879e+05]]
prediction is:
 [[  12041.991     3739.8713  187953.4   ]
 [ -16428.113    10091.228   -61583.652 ]
 [   5185.3623   41179.375    -4129.5464]
 [  -9116.315    37092.156  -146686.31  ]]
loss is: 10570.6045


 18%|█▊        | 18001/100000 [1:18:20<6:57:22,  3.27it/s]

save model
learning_rate is:
 0.0001594323
real location is:
 [[  20828.9687958    15098.1515029   -86911.1754864 ]
 [ -20682.4821832    23793.8602798    89715.9887267 ]
 [  -4888.72970419   40853.5603043  -178399.483317  ]
 [ -16132.9655771     5867.89391796  137509.735774  ]]
prediction is:
 [[  15281.004    14316.53    -94989.71  ]
 [ -19748.445    17282.027    98793.5   ]
 [  -6824.5327   35679.266  -169998.81  ]
 [ -16797.645     7016.047   136510.66  ]]
loss is: 5129.0815


 19%|█▉        | 19001/100000 [1:22:41<6:52:06,  3.28it/s]

save model
learning_rate is:
 0.0001594323
real location is:
 [[  10329.9143404      255.7986143    30929.7161228 ]
 [   4658.17954679   41111.5672272  -178157.626694  ]
 [ -20690.5988379    25050.2676795   -90579.0912817 ]
 [ -20710.6954346    22961.1549357   -92147.6995093 ]]
prediction is:
 [[   7996.7793     623.5475   30938.664 ]
 [   4829.733    38114.17   -173438.03  ]
 [ -22001.438    23017.562   -83272.56  ]
 [ -20662.12     19294.895   -85801.21  ]]
loss is: 3259.884


 20%|██        | 20001/100000 [1:27:02<6:47:45,  3.27it/s]

save model
learning_rate is:
 0.0001594323
real location is:
 [[ -11046.4108396    40058.7945016    40309.5454531 ]
 [ -10773.0643014    40280.3573279    37112.4105643 ]
 [   3368.59173893   40928.4955141  -178957.225832  ]
 [  20640.3076393    18819.84066      89288.3760821 ]]
prediction is:
 [[ -13999.93    39935.617   60984.367]
 [  -8417.514   43174.055   37721.59 ]
 [   2434.336   42722.062 -171652.58 ]
 [  20640.805   18274.352   90164.78 ]]
loss is: 4276.1104


 21%|██        | 21001/100000 [1:31:22<6:42:11,  3.27it/s]

save model
learning_rate is:
 0.00014348906
real location is:
 [[ -13038.9586687     3091.2004691   -39214.6393504 ]
 [  -5134.87966785     179.86683033 -164882.291721  ]
 [  20822.2080703    11636.7397497   -95476.1611875 ]
 [  -8901.97274503   40803.7233213  -176312.652193  ]]
prediction is:
 [[ -12057.252      2168.607    -34065.633  ]
 [    467.0952     -836.36914 -126235.61   ]
 [  21994.578      8553.4      -97972.86   ]
 [  -7169.366     34743.07    -156359.81   ]]
loss is: 9041.846


 22%|██▏       | 22001/100000 [1:35:43<6:36:44,  3.28it/s]

save model
learning_rate is:
 0.00014348906
real location is:
 [[-2.05490752e+04  2.91912445e+04 -9.13794953e+04]
 [-9.54282545e+03  5.07051840e+01  1.44838939e+05]
 [ 1.21535941e+04  3.91632123e+04 -3.80096321e+04]
 [ 1.89712908e+04  3.25483578e+04  1.28552392e+05]]
prediction is:
 [[-21993.492   29483.822  -81190.734 ]
 [-14093.952   -3637.9092 147901.1   ]
 [ 10809.318   39283.945  -41228.355 ]
 [ 18184.336   32469.578  116412.06  ]]
loss is: 4260.6733


 23%|██▎       | 23001/100000 [1:40:04<6:31:33,  3.28it/s]

save model
learning_rate is:
 0.00014348906
real location is:
 [[  20616.6161151   23228.8955281   91822.7504519]
 [ -11573.4443097   39523.7679164 -138850.455902 ]
 [  20829.9126695   11760.5696315  -93858.5210387]
 [  20615.50247     20032.9687293   93635.0049681]]
prediction is:
 [[  22068.422    22761.781    94999.72  ]
 [ -10762.262    40216.547  -134852.45  ]
 [  21588.018     8009.6777 -109112.016 ]
 [  19788.148    17634.912    92795.625 ]]
loss is: 3584.39


 24%|██▍       | 24001/100000 [1:44:25<6:26:28,  3.28it/s]

save model
learning_rate is:
 0.00012914014
real location is:
 [[ -20323.6525885   30577.0623641   58433.1667427]
 [  20609.7011341   20357.4485156  -86401.4103109]
 [  17048.7935083   34341.0699139  134906.033084 ]
 [  20785.0958572   11341.4650176 -101603.851463 ]]
prediction is:
 [[-16631.535  26972.234  68788.41 ]
 [ 18107.707  21256.262 -86353.68 ]
 [ 20517.93   36010.523 137704.1  ]
 [ 19444.21   11836.699 -97688.05 ]]
loss is: 3622.325


 25%|██▌       | 25001/100000 [1:48:46<6:21:20,  3.28it/s]

save model
learning_rate is:
 0.00012914014
real location is:
 [[-2.05787320e+04  1.48041575e+04 -8.86988958e+04]
 [ 2.05783076e+04  1.10429596e+04  8.61347162e+04]
 [ 5.64145649e+03  4.09554930e+04 -1.79718252e+05]
 [ 1.82236043e+03  4.11509303e+04  1.27278651e+02]]
prediction is:
 [[ -18460.777    14941.847   -93264.84  ]
 [  17299.732    10098.262    88358.43  ]
 [   4674.901    34413.38   -132487.92  ]
 [  -1739.666    39940.62     -1619.1549]]
loss is: 7761.599


 26%|██▌       | 26001/100000 [1:53:07<6:16:25,  3.28it/s]

save model
learning_rate is:
 0.00012914014
real location is:
 [[ -16949.5511382     6660.42895638  -41839.0253166 ]
 [   6747.75510106   41272.3869793    -2482.12748849]
 [   7757.22165302   41165.1746194  -177516.57178   ]
 [  -4503.42704138   40866.1573731  -178879.965588  ]]
prediction is:
 [[ -15754.967     6409.3447  -43364.984 ]
 [   8896.3125   41223.566   -18651.809 ]
 [   6286.1113   44426.83   -207457.97  ]
 [  -4351.4194   39684.812  -183434.97  ]]
loss is: 6446.481


 27%|██▋       | 27001/100000 [1:57:28<6:12:53,  3.26it/s]

save model
learning_rate is:
 0.00011622612
real location is:
 [[ 8.66427845e+03 -1.55920950e+02 -9.65798112e+02]
 [ 1.48864468e+04  3.64836652e+04  1.36689630e+05]
 [ 3.45812010e+03  1.62162336e+02  1.78735109e+05]
 [ 2.06493434e+04  1.84280385e+04  9.16643663e+04]]
prediction is:
 [[  7914.338     1457.9408     346.24268]
 [ 16385.742    39973.414   149125.66   ]
 [  3766.417     1343.3998  166324.     ]
 [ 21603.713    17410.516    97636.76   ]]
loss is: 4471.964


 28%|██▊       | 28001/100000 [2:01:48<6:06:17,  3.28it/s]

save model
learning_rate is:
 0.00011622612
real location is:
 [[ -20447.3541145   13861.9162254   90977.2767976]
 [ -15348.5840113   35837.9179875 -135093.907696 ]
 [  20501.3456608   27570.7472208   90543.0292139]
 [ -20271.7553561   10389.6216913  -73292.0258493]]
prediction is:
 [[ -19870.441   11762.136   84799.85 ]
 [ -14383.276   33376.754 -130438.52 ]
 [  19813.09    28143.193   89062.53 ]
 [ -15557.306   11776.229  -76493.53 ]]
loss is: 3017.1604


 29%|██▉       | 29001/100000 [2:06:09<6:01:41,  3.27it/s]

save model
learning_rate is:
 0.00011622612
real location is:
 [[ -1354.7391094   41142.6182824   -1451.3100747 ]
 [ 20416.812896    27984.2884252  -90124.3860299 ]
 [-11341.8660651    1542.16769776 137244.472005  ]
 [-20554.078265    26181.997627   -90709.6907749 ]]
prediction is:
 [[ -2395.9502  41487.844   -2473.398 ]
 [ 22607.139   28896.818  -90314.375 ]
 [-12782.746     918.9905 146167.06  ]
 [-22794.002   27296.807  -92804.11  ]]
loss is: 2304.3948


 30%|███       | 30001/100000 [2:10:30<5:56:15,  3.27it/s]

save model
learning_rate is:
 0.0001046035
real location is:
 [[ 5.60924647e+03  2.10046387e+01 -1.41377685e+03]
 [-5.18948358e+03  1.61910887e+02 -1.62148699e+05]
 [ 6.08305967e+03  8.33624287e+00 -3.98945423e+03]
 [ 1.19344457e+04  3.92420099e+04  1.39098356e+05]]
prediction is:
 [[   5363.013     1514.0115    2531.613 ]
 [   2048.206    -1313.927  -153513.61  ]
 [   7530.004     3527.956     8669.636 ]
 [  14154.286    35880.64    131891.03  ]]
loss is: 5565.8804


 31%|███       | 31001/100000 [2:14:51<5:50:55,  3.28it/s]

save model
learning_rate is:
 0.0001046035
real location is:
 [[-1.44223662e+04  3.67669978e+04 -1.34516861e+05]
 [-9.72103954e+03  5.46931778e+02  1.59227574e+05]
 [ 1.41364265e+04  3.72278882e+04 -4.68788060e+04]
 [ 7.69534108e+03 -1.46264869e+02 -1.73342598e+03]]
prediction is:
 [[ -10963.506     35611.098   -124382.984  ]
 [  -7569.637       850.59656  163984.31   ]
 [  14418.594     33473.13     -44888.773  ]
 [   6891.228      -503.252     -5467.9385 ]]
loss is: 3423.752


 32%|███▏      | 32001/100000 [2:19:12<5:46:00,  3.28it/s]

save model
learning_rate is:
 0.0001046035
real location is:
 [[ -20715.5690204    18479.5820078   -89632.5412825 ]
 [  -7478.20055238     220.38418543 -179696.267174  ]
 [  -9817.98173138     420.63003366  -37737.1421    ]
 [ -11664.7202147    39445.7032364  -139385.74013   ]]
prediction is:
 [[ -20186.11      14974.       -83400.05   ]
 [  -4809.301      1549.1262  -167734.88   ]
 [  -9896.701      -830.68445  -42610.805  ]
 [ -11513.598     37715.938   -133102.03   ]]
loss is: 4227.0703


 33%|███▎      | 33001/100000 [2:23:33<5:40:49,  3.28it/s]

save model
learning_rate is:
 9.414316e-05
real location is:
 [[  11189.2506892      812.82837367 -141167.963542  ]
 [  13221.4033646     2680.57398989 -137818.956489  ]
 [ -16006.4061398     5745.20837904  139707.181273  ]
 [ -17834.7676379    33389.0281898    47006.6350306 ]]
prediction is:
 [[  11392.578    -1055.6189 -142767.3   ]
 [  13945.508     1250.4506 -141819.88  ]
 [ -16028.141     5186.107   134581.03  ]
 [ -18058.992    34481.547    43369.875 ]]
loss is: 2132.4792


 34%|███▍      | 34001/100000 [2:27:53<5:35:37,  3.28it/s]

save model
learning_rate is:
 9.414316e-05
real location is:
 [[ 2.05587350e+04  2.36879414e+04 -8.64746506e+04]
 [ 2.36116696e+03  1.62977711e+01 -3.32129482e+02]
 [-2.05985562e+04  1.78056822e+04  8.99260430e+04]
 [ 2.06221869e+04  2.17158775e+04 -9.28095500e+04]]
prediction is:
 [[ 20509.578   22948.14   -84911.52  ]
 [  2698.5955   1175.7759  -1266.5977]
 [-19276.453   18821.21    84665.42  ]
 [ 20261.367   23051.254  -92699.69  ]]
loss is: 1476.3339


 35%|███▌      | 35001/100000 [2:32:14<5:31:14,  3.27it/s]

save model
learning_rate is:
 9.414316e-05
real location is:
 [[  20636.5541474   21825.0664928   78568.6388331]
 [  17320.9662404   34067.4962339  137385.397154 ]
 [  19927.6769481   10018.7204212 -147216.240559 ]
 [ -20539.3393944   29543.0069647  -92319.822564 ]]
prediction is:
 [[  22031.59    21494.01    80322.07 ]
 [  17519.963   32106.656  134553.28 ]
 [  19280.104   12240.585 -141945.08 ]
 [ -20029.977   28223.7    -88393.125]]
loss is: 2328.3792


 36%|███▌      | 36001/100000 [2:36:35<5:25:54,  3.27it/s]

save model
learning_rate is:
 8.472883e-05
real location is:
 [[ 14438.4453214    3976.71430706  45467.1671829 ]
 [ 18011.9057841   33401.5872154  135633.949516  ]
 [  9642.14674993  40926.9501109  167036.876997  ]
 [ 20851.2133278   25328.7185379   67682.8557097 ]]
prediction is:
 [[ 14909.668   2683.917  44053.484]
 [ 17715.023  32233.863 124965.016]
 [  8764.122  39453.844 166394.66 ]
 [ 20034.96   26449.047  71306.195]]
loss is: 2484.3254


 37%|███▋      | 37001/100000 [2:40:56<5:20:25,  3.28it/s]

save model
learning_rate is:
 8.472883e-05
real location is:
 [[ 2.04124281e+04  2.65024370e+04 -8.90359354e+04]
 [ 2.05902050e+04  1.13296346e+04  9.06850909e+04]
 [-9.62057468e+03  4.07449716e+04 -1.77298383e+05]
 [ 6.50029796e+03 -2.29287100e+01  1.78577012e+05]]
prediction is:
 [[  22451.818   23577.752  -90152.53 ]
 [  21684.262   11691.137   91866.3  ]
 [  -8558.825   41721.53  -186240.25 ]
 [   6382.245    2117.806  188741.75 ]]
loss is: 3344.3906


 38%|███▊      | 38001/100000 [2:45:17<5:15:33,  3.27it/s]

save model
learning_rate is:
 8.472883e-05
real location is:
 [[ -20679.1241989    12019.0780548   -84576.6677965 ]
 [   8095.17777795   40979.2816038  -178805.304646  ]
 [  20661.5696565    16836.2235904    91167.4261431 ]
 [  20670.6144607    15959.7280185    89468.7488882 ]]
prediction is:
 [[ -22269.297    12077.867   -85400.57  ]
 [   8037.749    41797.363  -180499.84  ]
 [  20066.434    17087.027    92604.53  ]
 [  19956.041    15091.6875   82655.28  ]]
loss is: 1636.1549


 39%|███▉      | 39001/100000 [2:49:38<5:10:12,  3.28it/s]

save model
learning_rate is:
 7.625595e-05
real location is:
 [[ 1.68376821e+04  6.43411072e+03  4.67317278e+04]
 [-4.04119000e+03  4.08837298e+04 -1.78260533e+05]
 [ 4.91233920e+03  6.53271260e+01  1.78141808e+05]
 [ 1.95843712e+04  9.57978118e+03  5.05146198e+04]]
prediction is:
 [[  17338.146     8050.9526   45202.84  ]
 [  -5369.8276   41147.18   -187091.72  ]
 [   8383.721     2393.2422  162196.83  ]
 [  22086.064    14229.631    58773.82  ]]
loss is: 5334.3228


 40%|████      | 40001/100000 [2:53:59<5:05:35,  3.27it/s]

save model
learning_rate is:
 7.625595e-05
real location is:
 [[ 1.90679073e+04  8.85965379e+03  5.06970723e+04]
 [ 2.05926054e+04  1.23909920e+04  8.85812947e+04]
 [ 7.12880224e+03 -3.83533521e+01  1.78106386e+05]
 [ 2.03905324e+04  3.06382606e+04 -8.24380771e+04]]
prediction is:
 [[ 19041.201    7484.6143  49222.89  ]
 [ 20689.566   10883.245   85138.41  ]
 [  5878.836   -1446.0874 174341.83  ]
 [ 11543.08    25674.729  -84718.06  ]]
loss is: 3168.9375


 41%|████      | 41001/100000 [2:58:19<4:59:50,  3.28it/s]

save model
learning_rate is:
 7.625595e-05
real location is:
 [[ -14752.336359     36431.8051884  -135743.399981  ]
 [  10069.4469705      299.64170963   14730.5935746 ]
 [ -20508.06064      11089.9699866   -78322.3831724 ]
 [ -12692.2636381    38612.8149947    45447.0956821 ]]
prediction is:
 [[ -14727.7      35414.562  -134196.1   ]
 [  11511.828    -1292.5134   16045.142 ]
 [ -19750.598    10484.1045  -72350.58  ]
 [  -8483.881    38660.19     40665.566 ]]
loss is: 2426.6401


 42%|████▏     | 42001/100000 [3:02:40<4:55:29,  3.27it/s]

save model
learning_rate is:
 6.8630354e-05
real location is:
 [[ 8.12121709e+03 -3.37070052e+01  3.25929185e+03]
 [-2.06904158e+04  2.48217171e+04 -9.00168168e+04]
 [-1.16090927e+04  3.96406460e+04 -1.36147484e+05]
 [ 3.24568712e+03  1.67005880e+02  1.77790300e+05]]
prediction is:
 [[ 6.7982593e+03 -6.3663208e+01  3.1952246e+03]
 [-2.0012953e+04  2.1755260e+04 -8.6588750e+04]
 [-1.1859670e+04  3.7505320e+04 -1.3104899e+05]
 [ 3.4054287e+03 -2.1149709e+03  1.7366030e+05]]
loss is: 2357.3054


 43%|████▎     | 43001/100000 [3:07:01<4:50:37,  3.27it/s]

save model
learning_rate is:
 6.8630354e-05
real location is:
 [[-2.77595550e+03  3.63168679e+02  6.43978444e+04]
 [-1.47288912e+04  3.66116406e+04  4.46504994e+04]
 [-1.41130246e+04  4.06047244e+03 -3.90781642e+04]
 [ 6.08305967e+03  8.33624287e+00 -3.98945423e+03]]
prediction is:
 [[ -3820.2036    150.8617  66270.35  ]
 [-13556.508   31271.688   40122.68  ]
 [-13313.786    7342.282  -43442.047 ]
 [  6311.7715   1611.5856  -3601.3586]]
loss is: 2585.3352


 44%|████▍     | 44001/100000 [3:11:22<4:44:51,  3.28it/s]

save model
learning_rate is:
 6.8630354e-05
real location is:
 [[  17035.820995      6641.10675898   46661.1716789 ]
 [ -10302.6553952      889.56188415  -35093.2407817 ]
 [   8807.88597995   40982.5629427  -179946.050544  ]
 [  20672.2974396    16926.9476903    88893.2370895 ]]
prediction is:
 [[  17004.27       6350.294     46817.246  ]
 [ -10775.994       189.13281  -36148.27   ]
 [   8233.257     40942.547   -174608.61   ]
 [  20614.895     17178.45      93523.97   ]]
loss is: 1415.0029


 45%|████▌     | 45001/100000 [3:15:43<4:39:41,  3.28it/s]

save model
learning_rate is:
 6.1767314e-05
real location is:
 [[  20416.5986185    27742.8927559   -89382.2872859 ]
 [  20425.2544689    30720.9776767   106822.480152  ]
 [  17126.8113816     6573.80600405 -131216.094551  ]
 [  12229.5078414     1855.05435483   44772.7665805 ]]
prediction is:
 [[  18890.662    27507.43    -89613.69  ]
 [  19643.23     28559.23    104112.72  ]
 [  15103.157     7845.9917 -128023.45  ]
 [  12396.983     3081.9126   45437.797 ]]
loss is: 1685.332


 46%|████▌     | 46001/100000 [3:20:04<4:34:47,  3.28it/s]

save model
learning_rate is:
 6.1767314e-05
real location is:
 [[ 4.90823571e+03 -4.35335304e+01  3.38149744e+02]
 [-1.58395171e+04  5.61489753e+03 -4.33644541e+04]
 [ 2.00568181e+04  1.00371924e+04  4.19466331e+04]
 [ 2.05601091e+04  2.44367417e+04  9.08753925e+04]]
prediction is:
 [[ 3.6812876e+03  8.0332092e+01 -3.4847371e+03]
 [-1.4646436e+04  5.1852705e+03 -4.0563977e+04]
 [ 2.0641303e+04  1.1776336e+04  4.3559738e+04]
 [ 1.9300641e+04  2.1717113e+04  8.2100938e+04]]
loss is: 2736.6858


 47%|████▋     | 47001/100000 [3:24:25<4:29:24,  3.28it/s]

save model
learning_rate is:
 6.1767314e-05
real location is:
 [[ 1.74698274e+04  3.39686889e+04 -4.35551173e+04]
 [ 5.46204007e+03 -4.27404664e+01 -7.38924532e+02]
 [-1.97294421e+04  9.45661906e+03 -4.95718894e+04]
 [-1.62742614e+04  3.49670779e+04 -1.34565445e+05]]
prediction is:
 [[  17276.29      34785.938    -40123.305  ]
 [   5378.11        733.31        661.48425]
 [ -19333.33       8745.043    -49292.94   ]
 [ -16413.355     33452.797   -134781.34   ]]
loss is: 1035.8273


 48%|████▊     | 48001/100000 [3:28:45<4:24:37,  3.27it/s]

save model
learning_rate is:
 5.5590586e-05
real location is:
 [[-2.06593044e+04  2.25571934e+04 -9.08246841e+04]
 [ 2.04086043e+04  2.66914241e+04 -8.90962771e+04]
 [ 1.06690753e+04  4.56094265e+02  3.27605436e+04]
 [ 1.03288222e+04  3.19083878e+01 -1.07072865e+05]]
prediction is:
 [[ -19660.898     22142.086    -93330.18   ]
 [  19090.11      26246.016    -89181.14   ]
 [   9960.303       448.4749    33493.492  ]
 [   8249.847       570.15314 -106194.625  ]]
loss is: 1114.3439


 49%|████▉     | 49001/100000 [3:33:06<4:19:32,  3.28it/s]

save model
learning_rate is:
 5.5590586e-05
real location is:
 [[ 12754.972224   38475.586665  134075.829448 ]
 [-12932.0518118  38375.081224   44568.2660013]
 [ 20839.5110447  16468.9315215 -90611.5302953]
 [-20483.4502705  30193.2984004  74273.5315548]]
prediction is:
 [[ 11762.008  38483.863 126458.47 ]
 [-13366.     35227.582  48320.297]
 [ 21551.854  16145.753 -94477.28 ]
 [-18354.246  27492.982  69416.9  ]]
loss is: 3179.6467


 50%|█████     | 50001/100000 [3:37:27<4:16:25,  3.25it/s]

save model
learning_rate is:
 5.5590586e-05
real location is:
 [[  11180.1984833    39841.4502816   142637.141182  ]
 [  19482.3765193    31953.7247548   132024.432794  ]
 [  20856.8250328    12567.2723314   -94516.2703897 ]
 [  10373.7401714      198.73050829 -146759.084527  ]]
prediction is:
 [[  11772.71     40418.086   144263.14  ]
 [  19356.383    30399.344   133994.81  ]
 [  21783.852    13725.262   -89489.34  ]
 [  10068.105    -1956.3818 -151695.08  ]]
loss is: 2181.2092


 51%|█████     | 51001/100000 [3:41:48<4:09:22,  3.27it/s]

save model
learning_rate is:
 5.0031525e-05
real location is:
 [[ 6.96055442e+03  8.34189625e+01  1.13133882e+05]
 [-1.49336685e+04  4.78073925e+03  1.36304874e+05]
 [ 9.36204079e+03  4.11778018e+04  1.74382719e+05]
 [-1.05725501e+04  8.53255900e+02  1.39402669e+05]]
prediction is:
 [[  5958.083     -650.88043 116615.84   ]
 [-15138.6875    5010.792   135544.34   ]
 [ 10787.086    38930.113   168821.38   ]
 [-11642.271      787.83813 143414.3    ]]
loss is: 2164.6042


 52%|█████▏    | 52001/100000 [3:46:09<4:04:10,  3.28it/s]

save model
learning_rate is:
 5.0031525e-05
real location is:
 [[ -20639.394479     15612.1552503   -82661.0020032 ]
 [  10442.4808041    40439.5306623   141643.487948  ]
 [  -4759.20081683   40859.4938769  -177771.553481  ]
 [  15638.7964822     5187.0460271    46355.2315496 ]]
prediction is:
 [[ -20212.121    13823.857   -84019.43  ]
 [   8954.488    37598.727   136523.44  ]
 [  -5570.454    41602.586  -183887.1   ]
 [  16745.383     5216.0464   46404.523 ]]
loss is: 2277.361


 53%|█████▎    | 53001/100000 [3:50:30<3:59:31,  3.27it/s]

save model
learning_rate is:
 5.0031525e-05
real location is:
 [[ -20681.8388994   24198.1554897   89677.7266173]
 [ -20226.5468479   30685.2643536 -126261.150895 ]
 [ -20568.4078857   25724.0552404  -92943.89507  ]
 [  12751.4050616   38491.8803535  135264.35543  ]]
prediction is:
 [[ -18437.295   24009.055   79516.875]
 [ -19288.73    30918.098 -122561.16 ]
 [ -19416.232   25514.723  -91457.016]
 [  12256.764   35725.77   128979.57 ]]
loss is: 3108.759


 54%|█████▍    | 54001/100000 [3:54:51<3:54:46,  3.27it/s]

save model
learning_rate is:
 4.502837e-05
real location is:
 [[-2.06827851e+04  2.33245968e+04  8.98627092e+04]
 [ 2.04729724e+04  2.53621957e+04 -8.70042026e+04]
 [ 6.89106025e+03 -5.63729460e+01 -3.67918876e+02]
 [-2.06363128e+04  2.69069183e+04 -9.33785698e+04]]
prediction is:
 [[-18043.6      22020.426    87946.734  ]
 [ 19937.816    25650.678   -86556.67   ]
 [  6711.9473     829.45593   1036.3949 ]
 [-18622.361    25184.691   -90030.7    ]]
loss is: 1736.3353


 55%|█████▌    | 55001/100000 [3:59:11<3:48:48,  3.28it/s]

save model
learning_rate is:
 4.502837e-05
real location is:
 [[-10512.3635231    1109.28469193 -34459.2569696 ]
 [-15235.6501202    5067.71773597 137424.328896  ]
 [-20563.2850514   28662.6718892  -92972.3559441 ]
 [ 20627.1014177   19137.1839572   92965.5635498 ]]
prediction is:
 [[ -9933.855    1339.9746 -31735.29  ]
 [-15002.643    3905.267  137554.84  ]
 [-21933.863   29074.508  -96226.61  ]
 [ 20215.121   18332.072   88185.55  ]]
loss is: 1674.7847


 56%|█████▌    | 56001/100000 [4:03:32<3:43:57,  3.27it/s]

save model
learning_rate is:
 4.502837e-05
real location is:
 [[  19927.6769481   10018.7204212 -147216.240559 ]
 [  13001.8161169   38482.2006983  -49193.8135378]
 [ -20693.8767537   12240.1717708  -89042.5840304]
 [  20537.5441377   24107.7980863   82337.4339652]]
prediction is:
 [[  20473.758    8839.116 -144071.98 ]
 [  12029.064   36793.703  -53476.168]
 [ -19197.16    12099.258  -90995.81 ]
 [  20481.629   23959.797   83172.59 ]]
loss is: 1711.3021


 57%|█████▋    | 57001/100000 [4:07:53<3:38:49,  3.27it/s]

save model
learning_rate is:
 4.0525538e-05
real location is:
 [[  20582.9931485    29457.6084926    91721.124067  ]
 [ -20605.6356213    27783.7890645   -91780.1203951 ]
 [  -1879.40281053   40937.0384354  -178347.732224  ]
 [ -20607.1616027    24478.4414668   -93539.48257   ]]
prediction is:
 [[  19185.648    27800.477    85933.43  ]
 [ -21209.213    26011.168   -92826.19  ]
 [   -655.7749   40018.094  -177803.83  ]
 [ -20624.05     24869.912   -96554.77  ]]
loss is: 1912.4608


 58%|█████▊    | 58001/100000 [4:12:14<3:33:36,  3.28it/s]

save model
learning_rate is:
 4.0525538e-05
real location is:
 [[ 2.06333298e+04  1.98046492e+04  9.30151383e+04]
 [-1.05183734e+04  9.35575663e+02  1.51381973e+05]
 [ 7.34089527e+03 -6.67154090e+01  1.69179589e+05]
 [ 7.46284396e+03  4.11555922e+04 -1.78168531e+05]]
prediction is:
 [[  21313.543    19111.824    89055.7   ]
 [ -11846.977     2272.664   158737.84  ]
 [   7213.8364    -774.8855  160969.17  ]
 [   7202.7754   40313.367  -170751.4   ]]
loss is: 3427.513


 59%|█████▉    | 59001/100000 [4:16:35<3:28:36,  3.28it/s]

save model
learning_rate is:
 4.0525538e-05
real location is:
 [[-1.38759864e+04  3.73373837e+04 -1.35159805e+05]
 [ 9.06516062e+03 -9.28990057e+01  1.78463363e+05]
 [-1.05364458e+04  4.04658083e+04 -1.51965884e+05]
 [ 5.68737604e+03  4.68815741e+01 -1.79035596e+05]]
prediction is:
 [[ -14526.172     34266.22    -127205.88   ]
 [   9437.516      -274.29053  173225.4    ]
 [ -12572.433     42063.195   -156860.94   ]
 [   6448.2095     1239.6907  -162372.88   ]]
loss is: 4645.4956


 60%|██████    | 60001/100000 [4:20:56<3:23:30,  3.28it/s]

save model
learning_rate is:
 3.6472975e-05
real location is:
 [[  12578.7459777   38655.8893072  136892.143942 ]
 [ -20691.0427447   24992.5997741  -90288.6400585]
 [ -19298.9205156   31766.4828114 -130046.501538 ]
 [ -13252.5881781    3255.0363407  -42471.7053258]]
prediction is:
 [[  11057.391   35845.6    128216.92 ]
 [ -20338.182   25746.727  -91748.61 ]
 [ -18636.416   29873.98  -126950.445]
 [ -12296.887    3160.06   -41410.35 ]]
loss is: 2429.368


 61%|██████    | 61001/100000 [4:25:17<3:18:29,  3.27it/s]

save model
learning_rate is:
 3.6472975e-05
real location is:
 [[ -4167.59289428    201.51025912  -2963.82318774]
 [ 20550.9432585   24928.018196    90228.4854956 ]
 [ 11964.8079833   39309.8260571  -38024.2862354 ]
 [  8315.36347471   -151.79988382   -274.74934053]]
prediction is:
 [[ -3672.9458     127.98514  -1984.1453 ]
 [ 20437.676    26143.701    92346.3    ]
 [  9679.53     38025.414   -32520.281  ]
 [  9406.269     -184.37466   -389.33588]]
loss is: 1592.8569


 62%|██████▏   | 62001/100000 [4:29:37<3:13:22,  3.27it/s]

save model
learning_rate is:
 3.6472975e-05
real location is:
 [[ -20747.865673     18628.3520078   -89909.4762665 ]
 [ -20094.8990354     9941.79440462  -58717.4236244 ]
 [ -18141.7603445    32989.7374122  -135315.30252   ]
 [   5884.61155305   40954.7071064   179325.124823  ]]
prediction is:
 [[ -19958.977    18019.445   -88284.41  ]
 [ -17569.06      9440.707   -56119.594 ]
 [ -16285.724    31059.832  -126798.86  ]
 [   4287.4736   42152.6     189809.6   ]]
loss is: 3564.011


 63%|██████▎   | 63001/100000 [4:33:58<3:08:40,  3.27it/s]

save model
learning_rate is:
 3.282568e-05
real location is:
 [[-20094.8990354    9941.79440462 -58717.4236244 ]
 [-18892.8457351    8542.30354406 -46103.6405505 ]
 [-16453.9470621    6181.38145029 136099.501806  ]
 [  9538.82134183   -159.81737639  12113.7793073 ]]
prediction is:
 [[-17850.633    9631.762  -57523.99  ]
 [-18668.225    7756.3745 -47441.57  ]
 [-16061.963    5907.1597 122785.24  ]
 [ 10368.514     704.1647  12285.396 ]]
loss is: 2284.0613


 64%|██████▍   | 64001/100000 [4:38:19<3:03:08,  3.28it/s]

save model
learning_rate is:
 3.282568e-05
real location is:
 [[  10788.0794207      583.23420768   32207.9836704 ]
 [ -10536.4458384    40465.8082611  -151965.883852  ]
 [ -20680.0728019    25689.0462606   -91513.9595084 ]
 [  -9039.66426861     242.5915169   175376.64949   ]]
prediction is:
 [[ 1.16853633e+04 -7.97919617e+01  3.24955723e+04]
 [-1.09340625e+04  4.01261953e+04 -1.52727641e+05]
 [-1.96434219e+04  2.38480586e+04 -8.98381953e+04]
 [-8.70873047e+03 -1.98082336e+02  1.75999156e+05]]
loss is: 966.6048


 65%|██████▌   | 65001/100000 [4:42:40<2:58:08,  3.27it/s]

save model
learning_rate is:
 3.282568e-05
real location is:
 [[ 8.57235167e+03 -1.27240022e+02 -1.79046955e+05]
 [-2.04153560e+04  1.06738791e+04 -7.57687169e+04]
 [-1.53637676e+04  3.58776969e+04 -1.36475990e+05]
 [-9.36303905e+03  4.07496494e+04  1.79335861e+05]]
prediction is:
 [[  10088.497     515.004 -174615.19 ]
 [ -19688.137   12183.43   -73637.8  ]
 [ -15104.589   34612.08  -132993.56 ]
 [  -7853.343   39925.734  167671.81 ]]
loss is: 3119.5554


 66%|██████▌   | 66001/100000 [4:47:01<2:53:05,  3.27it/s]

save model
learning_rate is:
 2.954311e-05
real location is:
 [[ -1936.66205744  41148.0381987    1497.07359357]
 [ 20868.9002828   12749.8567828  -94588.294248  ]
 [-20689.4905745   16013.5252319  -86672.9820755 ]
 [-11311.9097677    1636.89785448 -39688.1109633 ]]
prediction is:
 [[ -1324.164   38619.477    -472.1555]
 [ 23228.727   13852.045  -94997.21  ]
 [-21019.586   15969.26   -86252.36  ]
 [-11579.906     744.6047 -41203.758 ]]
loss is: 1295.539


 67%|██████▋   | 67001/100000 [4:51:22<2:47:52,  3.28it/s]

save model
learning_rate is:
 2.954311e-05
real location is:
 [[-20527.9973225   25550.0234896   94248.3247917 ]
 [  9400.85359865    115.27758259  -1435.15346955]
 [-11536.8544374    1824.27313992 -39578.0190616 ]
 [-20592.4946607   18018.7188432   88663.8708568 ]]
prediction is:
 [[-17455.545    22557.61     96121.17   ]
 [  9233.952      778.28015   -617.166  ]
 [-10908.875     2140.911   -38438.016  ]
 [-19961.387    17848.703    89778.586  ]]
loss is: 1413.6547


 68%|██████▊   | 68001/100000 [4:55:43<2:42:47,  3.28it/s]

save model
learning_rate is:
 2.954311e-05
real location is:
 [[ 13682.6139796   37571.9141015  134770.186143  ]
 [ 16638.700067     6223.99959926  46733.9462704 ]
 [ 20446.3978537   10490.4897846   60477.9049749 ]
 [ 10069.4469705     299.64170963  14730.5935746 ]]
prediction is:
 [[ 14356.8125   37410.297   131279.02   ]
 [ 17182.514     5428.2007   44995.246  ]
 [ 19267.365     9331.16     51055.855  ]
 [ 11193.046      143.84601  16038.912  ]]
loss is: 2264.4211


 69%|██████▉   | 69001/100000 [5:00:04<2:37:45,  3.27it/s]

save model
learning_rate is:
 2.65888e-05
real location is:
 [[-16480.2692268   34860.0936944   48088.0760796 ]
 [ 18624.1285007   32871.2994667  138929.88109   ]
 [ 16586.6248644    6040.61717345  42881.7085438 ]
 [-13468.1611139   37838.7374465   45179.3005548 ]]
prediction is:
 [[-16352.0625  37066.977   40893.54  ]
 [ 19323.29    33508.78   136843.3   ]
 [ 16524.457    5542.4277  40446.625 ]
 [-12414.193   38796.965   42681.66  ]]
loss is: 2129.494


 70%|███████   | 70001/100000 [5:04:24<2:32:48,  3.27it/s]

save model
learning_rate is:
 2.65888e-05
real location is:
 [[-1.56142924e+04  3.56342013e+04 -1.36006839e+05]
 [-2.03799011e+04  1.21167086e+04  9.44827181e+04]
 [ 1.47339212e+03  1.71169625e+01 -7.54747626e+02]
 [-2.02385344e+04  1.01943904e+04  1.06718870e+05]]
prediction is:
 [[ -14824.416     34145.234   -132002.44   ]
 [ -19641.02      11978.864     95909.9    ]
 [   1209.2479      652.81445   -2130.254  ]
 [ -19001.684     11436.32     103095.42   ]]
loss is: 1765.5986


 71%|███████   | 71001/100000 [5:08:45<2:27:37,  3.27it/s]

save model
learning_rate is:
 2.65888e-05
real location is:
 [[ 1.22352076e+04  3.89640097e+04  1.38050874e+05]
 [ 8.98757379e+03  1.25661040e+02 -1.66945894e+03]
 [-1.50969165e+04  3.60921463e+04 -1.36634891e+05]
 [-5.20740301e+02  4.14263523e+02 -1.78361740e+05]]
prediction is:
 [[ 1.38068320e+04  3.63983789e+04  1.24519625e+05]
 [ 8.29975293e+03  7.19465942e+02 -5.52935400e+03]
 [-1.52622715e+04  3.54623086e+04 -1.33259031e+05]
 [-2.15348145e+03  7.18830872e+01 -1.76929406e+05]]
loss is: 3163.9102


 72%|███████▏  | 72001/100000 [5:13:06<2:22:24,  3.28it/s]

save model
learning_rate is:
 2.3929919e-05
real location is:
 [[ 2.05305515e+04  2.27651700e+04  9.24320479e+04]
 [ 3.78339599e+02  4.11120188e+04  1.16057592e+03]
 [ 9.60927124e+03 -9.44767922e+01  1.78460172e+05]
 [-2.06884179e+04  2.28711556e+04  8.85947739e+04]]
prediction is:
 [[ 1.9638953e+04  2.2263852e+04  8.8362125e+04]
 [ 6.1091669e+02  3.9871914e+04 -1.5923730e+03]
 [ 9.2231250e+03 -1.5730466e+02  1.6989359e+05]
 [-2.0704703e+04  2.2468844e+04  8.3555766e+04]]
loss is: 2515.281


 73%|███████▎  | 73001/100000 [5:17:27<2:18:47,  3.24it/s]

save model
learning_rate is:
 2.3929919e-05
real location is:
 [[  15970.0712665     5280.97358329 -126185.291255  ]
 [  15759.0046298     4940.60950489 -136151.193555  ]
 [  -3678.31539453     320.02997914 -177747.494555  ]
 [  20679.159312     17251.2640203    89034.078323  ]]
prediction is:
 [[  15851.095     5826.9736 -125268.92  ]
 [  10052.879     8932.164  -129366.95  ]
 [  -4856.0806    -694.3564 -172558.8   ]
 [  20949.11     17934.787    90065.31  ]]
loss is: 2855.6082


 74%|███████▍  | 74001/100000 [5:21:48<2:12:19,  3.27it/s]

save model
learning_rate is:
 2.3929919e-05
real location is:
 [[ 1.35810124e+02  4.19216391e+00  2.81465888e+03]
 [-1.03671700e+04  4.05542253e+04 -1.54905837e+05]
 [-1.56691194e+04  5.48918565e+03 -4.12314564e+04]
 [ 2.06285798e+04  2.29904974e+04  9.18255751e+04]]
prediction is:
 [[    509.79413     255.87325    3159.8027 ]
 [ -10180.684     39955.79    -153760.34   ]
 [ -15649.328      5652.545    -41569.047  ]
 [  20584.855     22960.582     88910.79   ]]
loss is: 666.19867


 75%|███████▌  | 75001/100000 [5:26:09<2:07:15,  3.27it/s]

save model
learning_rate is:
 2.1536925e-05
real location is:
 [[  19011.9023146     8798.64231447 -129448.868708  ]
 [  20546.2519898    25728.0011269    90711.192618  ]
 [  18490.1152169     8142.18174865   48531.6903268 ]
 [  16888.1296926     6303.72971599 -132017.490418  ]]
prediction is:
 [[  20321.314     8729.184  -139003.42  ]
 [  20376.682    25546.215    88041.94  ]
 [  18477.523     7683.3257   45714.875 ]
 [  15746.332     5479.3115 -132151.28  ]]
loss is: 2013.2719


 76%|███████▌  | 76001/100000 [5:30:30<2:02:08,  3.27it/s]

save model
learning_rate is:
 2.1536925e-05
real location is:
 [[ 1.16175677e+04  3.95077897e+04  1.41889574e+05]
 [ 2.05788268e+04  2.13543353e+04  8.41374374e+04]
 [ 1.00250119e+04 -9.47318303e+01 -1.79581839e+05]
 [ 1.25536319e+04  2.12175532e+03  4.33445470e+04]]
prediction is:
 [[  12103.961    38069.945   137460.47  ]
 [  19995.68     21744.252    83329.305 ]
 [  10311.529     1255.9259 -187123.95  ]
 [  12147.267     2414.5078   40175.07  ]]
loss is: 2204.9412


 77%|███████▋  | 77001/100000 [5:34:51<1:57:05,  3.27it/s]

save model
learning_rate is:
 2.1536925e-05
real location is:
 [[ -8430.00769677    405.36238402  -1291.94324915]
 [ 20623.2614593   11862.7185357   86751.6884627 ]
 [-20585.6726572   18446.385651    91767.4977265 ]
 [ 14637.7957472    4182.93666662  45928.7024404 ]]
prediction is:
 [[ -7703.712     -498.58978  -1146.5461 ]
 [ 21067.828    12120.775    83768.78   ]
 [-20849.531    16392.406    93266.95   ]
 [ 14489.83      5037.326    46498.945  ]]
loss is: 1128.7592


 78%|███████▊  | 78001/100000 [5:39:11<1:51:59,  3.27it/s]

save model
learning_rate is:
 1.9383235e-05
real location is:
 [[ -20334.1599359    11562.5223319    94508.3335854 ]
 [   6648.40726308   41134.2892742  -178696.691417  ]
 [ -20441.1900902    13251.9484935    93844.6633393 ]
 [  20525.1981192    26731.5344878    91252.5252564 ]]
prediction is:
 [[ -20236.684   11128.053   95578.875]
 [   6520.227   41226.836 -174570.22 ]
 [ -21606.941   13006.067   93199.81 ]
 [  20630.121   25933.375   88243.34 ]]
loss is: 1239.9447


 79%|███████▉  | 79001/100000 [5:43:32<1:46:52,  3.27it/s]

save model
learning_rate is:
 1.9383235e-05
real location is:
 [[ 6.51448484e+03  4.12811053e+04 -2.57377268e+03]
 [-1.68881543e+04  6.60529343e+03 -4.45967699e+04]
 [-2.07432556e+04  2.21322586e+04 -9.03898371e+04]
 [ 4.14843927e+03  1.32617344e+02  1.77143249e+05]]
prediction is:
 [[  6422.5547  41174.273   -3618.3535]
 [-16274.338    6643.602  -41791.37  ]
 [-20283.861   21384.242  -85750.4   ]
 [  4648.5405    679.5182 170631.12  ]]
loss is: 1884.5714


 80%|████████  | 80001/100000 [5:47:53<1:41:52,  3.27it/s]

save model
learning_rate is:
 1.9383235e-05
real location is:
 [[ 13861.4762779   37436.7080501  136639.038301  ]
 [ 16373.8924031   35002.2094443  134170.032052  ]
 [-10861.5431903    1295.84560308 -36249.4523945 ]
 [ 12477.3619559   38912.9715758  -36167.6133848 ]]
prediction is:
 [[ 14090.047  38709.652 132531.27 ]
 [ 16485.602  35825.492 134942.78 ]
 [-10519.385   1040.662 -34862.023]
 [ 10065.168  36568.277 -31672.062]]
loss is: 1931.1722


 81%|████████  | 81001/100000 [5:52:14<1:36:43,  3.27it/s]

save model
learning_rate is:
 1.7444909e-05
real location is:
 [[ -20603.0182631    29221.7243253    90336.490168  ]
 [  -3865.27609292   41057.3943696     3901.51740601]
 [   2466.54108989   40918.1405933  -179506.182089  ]
 [  20826.2154415    25665.9784652    92010.2771339 ]]
prediction is:
 [[ -19250.314    27880.027    83280.08  ]
 [  -3797.8608   39037.65      2929.3813]
 [   2143.6362   42771.508  -183829.62  ]
 [  20149.547    25587.879    93926.1   ]]
loss is: 2288.0671


 82%|████████▏ | 82001/100000 [5:56:35<1:31:33,  3.28it/s]

save model
learning_rate is:
 1.7444909e-05
real location is:
 [[   7448.03318939   41249.7690633    -2451.98529062]
 [ -11002.8064199    40202.3809026  -149834.204259  ]
 [ -20748.1191152    21148.3681767   -89282.8741805 ]
 [ -13371.6945384    37913.6296443  -134219.358254  ]]
prediction is:
 [[   6140.3223   41562.54     -2058.7354]
 [ -11630.705    42217.293  -152579.42  ]
 [ -19052.973    20236.125   -84930.61  ]
 [ -13484.838    38638.555  -133767.05  ]]
loss is: 1628.8348


 83%|████████▎ | 83001/100000 [6:00:56<1:26:31,  3.27it/s]

save model
learning_rate is:
 1.7444909e-05
real location is:
 [[ 1.03288222e+04  3.19083878e+01 -1.07072865e+05]
 [ 1.14652799e+04  1.04627749e+03 -1.39580549e+05]
 [ 8.35389733e+03 -2.53097898e+01  3.11380092e+03]
 [-1.08157873e+04  1.22692976e+03 -3.86049916e+04]]
prediction is:
 [[   8564.512       786.55023  -99491.195  ]
 [  10741.414       546.53613 -132182.47   ]
 [   8393.431      -248.04034    2022.5134 ]
 [ -11370.494       958.3843   -37923.367  ]]
loss is: 2246.4346


 84%|████████▍ | 84001/100000 [6:05:17<1:21:24,  3.28it/s]

save model
learning_rate is:
 1.5700418e-05
real location is:
 [[ -8250.41450635  40842.9691132  178940.995645  ]
 [ 20315.9146722   10313.5183733   53332.9842842 ]
 [ 18407.8630669    8051.06376946  47790.8966776 ]
 [-16104.6862423   35296.4835554   53035.3680397 ]]
prediction is:
 [[ -8419.118   41185.58   175982.47  ]
 [ 19446.01     8038.9775  47141.598 ]
 [ 18311.941    7860.1787  48415.75  ]
 [-13590.051   34793.562   52154.785 ]]
loss is: 1833.3854


 85%|████████▌ | 85001/100000 [6:09:38<1:16:17,  3.28it/s]

save model
learning_rate is:
 1.5700418e-05
real location is:
 [[-1.47101566e+04  3.64731737e+04 -1.35730868e+05]
 [-1.99431679e+04  9.70545544e+03 -5.18933008e+04]
 [ 1.42253318e+03  1.59880644e+01 -1.18796531e+03]
 [-8.16771541e+03  4.07550847e+04  1.78697340e+05]]
prediction is:
 [[-1.5494105e+04  3.6434055e+04 -1.3570712e+05]
 [-2.0280756e+04  9.7055488e+03 -5.2213773e+04]
 [ 1.0251050e+03 -9.0949661e+01  1.6569092e+01]
 [-9.2838711e+03  3.9863398e+04  1.8449486e+05]]
loss is: 1146.4021


 86%|████████▌ | 86001/100000 [6:13:58<1:11:25,  3.27it/s]

save model
learning_rate is:
 1.5700418e-05
real location is:
 [[  20672.8747306    13973.3987497    89216.3966738 ]
 [  -1167.04902762   40955.6052194  -178868.19779   ]
 [ -20483.4502705    30193.2984004    74273.5315548 ]
 [ -13827.2453596    37450.8907275  -134693.40479   ]]
prediction is:
 [[  20910.414    12436.619    85728.08  ]
 [   -957.5468   40455.566  -180424.69  ]
 [ -19994.9      31201.701    75226.01  ]
 [ -13324.952    35191.2    -130951.4   ]]
loss is: 1715.3231


 87%|████████▋ | 87001/100000 [6:18:19<1:06:08,  3.28it/s]

save model
learning_rate is:
 1.4130375e-05
real location is:
 [[  20408.5361517    30777.8169202   109081.727807  ]
 [ -20111.5055997    30882.9581088    49952.3406964 ]
 [ -20518.9493042    12318.6881117   -85152.7734989 ]
 [  -6282.71096113   40797.5091462  -179214.688047  ]]
prediction is:
 [[  19688.355   31227.414  104015.75 ]
 [ -21942.44    30402.188   49285.84 ]
 [ -20247.562   12992.133  -83386.984]
 [  -6450.401   39777.453 -174033.81 ]]
loss is: 1903.981


 88%|████████▊ | 88001/100000 [6:22:40<1:01:02,  3.28it/s]

save model
learning_rate is:
 1.4130375e-05
real location is:
 [[ 4.77849225e+03  4.18224972e+01 -1.24255207e+03]
 [-1.57372990e+04  5.51689575e+03 -4.44202509e+04]
 [ 4.17458050e+02  1.91369827e+01  1.93378406e+02]
 [-3.15200140e+03  1.41445870e+02 -2.06031645e+03]]
prediction is:
 [[  4607.603      358.38715  -2426.3083 ]
 [-15389.817     5888.206   -44681.76   ]
 [   347.90372   -153.81659   -160.94177]
 [ -2753.4536    -213.8722   -2504.6553 ]]
loss is: 461.6235


 89%|████████▉ | 89001/100000 [6:27:01<55:57,  3.28it/s]  

save model
learning_rate is:
 1.4130375e-05
real location is:
 [[-20405.4710802   11299.891893   -83323.2723039 ]
 [  9285.45861781  40972.4852113  178249.613314  ]
 [-20498.9511614   28564.8171329  -89821.7926927 ]
 [ 20673.9885029   16248.2731776   90296.9458761 ]]
prediction is:
 [[-19885.879  11930.44  -83121.46 ]
 [  8673.269  40188.484 180696.44 ]
 [-16630.523  29757.719 -94573.17 ]
 [ 21310.746  15761.346  87471.28 ]]
loss is: 1973.13


 90%|█████████ | 90001/100000 [6:31:22<50:54,  3.27it/s]

save model
learning_rate is:
 1.2717338e-05
real location is:
 [[ 2.06397212e+04  1.31436855e+04  9.09049775e+04]
 [ 8.92410546e+03 -8.72435618e+01  1.78780405e+05]
 [ 2.06659112e+04  1.63268028e+04  9.04466898e+04]
 [-2.01821201e+04  1.00807998e+04 -6.15888227e+04]]
prediction is:
 [[ 19906.584   13960.012   85889.75  ]
 [  7652.832   -1423.4015 181408.05  ]
 [ 20308.83    15785.922   87608.41  ]
 [-20596.184    9748.317  -59099.19  ]]
loss is: 1953.8746


 91%|█████████ | 91001/100000 [6:35:43<45:46,  3.28it/s]

save model
learning_rate is:
 1.2717338e-05
real location is:
 [[ 2.04981025e+04  2.47082939e+04 -8.73837087e+04]
 [ 2.05260279e+04  1.06637394e+04  7.07266754e+04]
 [ 7.82331720e+03 -5.17487444e+01  3.73937172e+03]
 [ 1.65864961e+03  4.11563652e+04 -3.86709682e+02]]
prediction is:
 [[ 2.0993121e+04  2.4787371e+04 -8.5062453e+04]
 [ 1.9084643e+04  1.1326135e+04  6.7913172e+04]
 [ 7.4946519e+03 -1.6660461e+01  3.9544233e+03]
 [ 1.9613339e+03  4.0040852e+04 -4.5407977e+02]]
loss is: 1027.2983


 92%|█████████▏| 92001/100000 [6:40:04<40:41,  3.28it/s]

save model
learning_rate is:
 1.2717338e-05
real location is:
 [[  -2881.85674961   40939.9894575  -176747.147767  ]
 [ -16586.0469217     6313.18206285  -43776.6803731 ]
 [ -15182.3598591    36007.8880695  -136272.651335  ]
 [   3217.10790982   41186.0889138     2352.0701334 ]]
prediction is:
 [[  -2998.6426    40472.508   -176620.2    ]
 [ -16794.18       5995.1123   -42219.14   ]
 [ -16212.754     36462.83    -137643.62   ]
 [   2705.3933    39035.453       195.37468]]
loss is: 1089.0962


 93%|█████████▎| 93001/100000 [6:44:24<35:36,  3.28it/s]

save model
learning_rate is:
 1.1445603e-05
real location is:
 [[ -20445.2557458   30106.8018974 -100427.772322 ]
 [ -20500.5980264   28309.0286569  -91102.5814101]
 [ -20703.9792445   16776.4979137  -89929.9531571]
 [  20510.7318517   23578.7085624   90599.7181754]]
prediction is:
 [[ -20744.527   28289.95  -100795.94 ]
 [ -21541.895   26406.102  -85270.65 ]
 [ -20123.34    15594.242  -87865.336]
 [  20241.633   22977.352   90841.766]]
loss is: 1685.9869


 94%|█████████▍| 94001/100000 [6:48:45<30:30,  3.28it/s]

save model
learning_rate is:
 1.1445603e-05
real location is:
 [[  20832.3169955   11823.5649129  -92790.3267497]
 [  12235.2075557   38964.0096712  138050.874261 ]
 [  13889.2285942   37495.8491747  -47632.0636249]
 [ -11307.7948953   39756.2443956 -139189.076989 ]]
prediction is:
 [[  20405.984   11609.234  -94768.95 ]
 [  13264.81    38270.84   134879.73 ]
 [  13548.564   37040.25   -46554.227]
 [ -11600.477   39474.246 -142367.16 ]]
loss is: 1367.1952


 95%|█████████▌| 95001/100000 [6:53:06<25:26,  3.27it/s]

save model
learning_rate is:
 1.1445603e-05
real location is:
 [[-20689.7597639   25225.1488719  -91129.7585008 ]
 [-13982.0874226    3942.72738042 -43421.066263  ]
 [ 20914.6492195   17723.2336926  -93897.376311  ]
 [-20415.3559991   10673.8791153  -75768.716872  ]]
prediction is:
 [[-20905.12   25368.793 -89120.2  ]
 [-13900.111   4321.684 -42951.17 ]
 [ 21571.988  17297.035 -92980.03 ]
 [-20534.336  12127.904 -74501.61 ]]
loss is: 846.39777


 96%|█████████▌| 96001/100000 [6:57:27<20:35,  3.24it/s]

save model
learning_rate is:
 1.0301043e-05
real location is:
 [[ 5.67121363e+03 -4.62316098e+01 -2.31228999e+03]
 [ 1.99600283e+04  3.14392823e+04 -4.71836376e+04]
 [-1.21025899e+04  3.91618440e+04  4.13984478e+04]
 [-1.92243589e+04  3.18568159e+04 -1.30112358e+05]]
prediction is:
 [[   4802.022      -141.44434   -3477.608  ]
 [  19204.727     31424.275    -45521.05   ]
 [ -11665.479     37652.953     37372.445  ]
 [ -19754.502     30838.178   -128841.56   ]]
loss is: 1389.5073


 97%|█████████▋| 97001/100000 [7:01:48<15:15,  3.28it/s]

save model
learning_rate is:
 1.0301043e-05
real location is:
 [[ 2.05834871e+04  2.28386156e+04 -8.33714139e+04]
 [ 7.66329383e+03 -4.13906923e+01 -1.79903789e+05]
 [-1.77053910e+04  7.35608631e+03  1.36488125e+05]
 [-2.05727982e+04  1.34162979e+04 -9.15117512e+04]]
prediction is:
 [[  20029.115    22812.012   -82338.01  ]
 [  10907.815    -1397.6372 -172122.88  ]
 [ -17983.027     7249.1006  135523.8   ]
 [ -20468.973    13140.697   -92244.55  ]]
loss is: 1712.7379


 98%|█████████▊| 98001/100000 [7:06:09<10:10,  3.28it/s]

save model
learning_rate is:
 1.0301043e-05
real location is:
 [[   4361.08746478   41098.3118707  -177524.696329  ]
 [  20367.7612361    10335.4012906  -136800.993962  ]
 [ -20575.1015798    13238.939678    -90776.9626421 ]
 [   6011.58512397   40952.4132041   179376.303526  ]]
prediction is:
 [[   4760.6553   39196.973  -173292.25  ]
 [  20529.777    11471.343  -137719.89  ]
 [ -19992.346    12854.722   -89597.375 ]
 [   4461.966    41994.594   185480.47  ]]
loss is: 2039.3492


 99%|█████████▉| 99001/100000 [7:10:30<05:05,  3.27it/s]

save model
learning_rate is:
 9.270939e-06
real location is:
 [[  14548.3614373    36802.0650863   -44521.1412181 ]
 [ -16215.1250027     5944.55476491  136612.510056  ]
 [ -20704.5686066    16659.4116669   -89682.9507161 ]
 [ -15054.0602627    36134.0448937  -136295.077326  ]]
prediction is:
 [[  14828.919    37727.53    -46290.93  ]
 [ -15254.471     5228.3604  134514.2   ]
 [ -20267.275    16030.196   -84935.25  ]
 [ -13957.767    35329.402  -135945.5   ]]
loss is: 1541.7407


100%|██████████| 100000/100000 [7:14:50<00:00,  3.84it/s]

done!
