In [1]:
import os
import random
import skimage.data
from skimage import io
import skimage.transform as skt
import numpy as np
import tensorflow as tf
from tqdm import tqdm
import sys
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
import cv2

In [2]:
# submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhaun_448_test_with_no_barrier1/submap"
# pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhaun_448_test_with_no_barrier1/picture"

# # for i in range(4):
# i = 1
# submap1 = cv2.imread(os.path.join(submap_dir,str(1189) + '.pgm'))
# submap1 = cv2.resize(submap1,(448,448))
# submap1 = cv2.transpose(submap1)
# submap1 = cv2.flip(submap1, 1)
# # submap1 = np.rot90(submap1)
# cv2.imshow("submap",submap1)


# pic1 = cv2.imread(os.path.join(pic_dir, '01189.jpg'))
# cv2.imshow("pic",pic1)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# print(np.shape(submap1))

In [3]:
train_label_dir = "/home/ysk/database/test_data/benhaun_test"
train_pic_dir = "/home/ysk/database/test_data/benhaun_test/picture"
train_submap_dir = "/home/ysk/database/test_data/benhaun_test/submap"

# train_label_dir = "/home/ysk/database/train_data_map_pic/benhuan_train"
# train_pic_dir = "/home/ysk/database/train_data_map_pic/benhuan_train/picture"
# train_submap_dir = "/home/ysk/database/train_data_map_pic/benhuan_train/submap"

train_txt = os.path.join(train_label_dir,"label.txt")
count = len(open(train_txt,'r').readlines()) - 1   #1190
file = open(train_txt,'r')
s = file.readlines()

def get_train_data_batch(i, pic_dir=train_pic_dir, label_dir=train_label_dir,submap_dir=train_submap_dir):
    labels = []
    images = []
    
    image1 = skimage.data.imread(os.path.join(pic_dir, s[i].split(";")[0]))
    submap1 = cv2.imread(os.path.join(submap_dir,str(i) + '.pgm'))
    submap1 = cv2.resize(submap1,(448,448))
    submap1 = cv2.transpose(submap1)
    submap1 = cv2.flip(submap1, 1)
    
#     image2 = skimage.data.imread(os.path.join(pic_dir, s[i+1].split(";")[0]))
#     submap2 = cv2.imread(os.path.join(submap_dir,str(i+1) + '.pgm'))
#     submap2 = cv2.resize(submap2,(448,448))
#     submap2 = cv2.transpose(submap2)
#     submap2 = cv2.flip(submap2, 1)
    
    
#     img = cv2.merge([image1,submap1,image2,submap2])
    img = cv2.merge([image1,submap1])
    images.append(img)
    
    label = s[i].split(";")[1:]
    label = list(map(float,label))
    labels.append(label)
    
    return np.asarray(images),np.asarray(labels)
    
num = 0
train_images, train_labels = get_train_data_batch(num)
print(np.shape(train_images))
print(np.shape(train_labels))
print(train_labels)

(1, 448, 448, 6)
(1, 3)
[[ 0.25599488 -0.06013947 -6.1226604 ]]


In [4]:
with tf.name_scope("input"):
    input_image = tf.placeholder("float", [None, 448,448,6],name='input_image')/255.*2.-1
    y_ = tf.placeholder("float", [None, 3],name='y_') 

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape = shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding="SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")


#第0层卷积
with tf.name_scope("conv_0"):
    W_conv0 = weight_variable([7, 7, 6, 64])
    b_conv0 = bias_variable([64])
    conv_layer0 = tf.nn.conv2d(input_image, W_conv0, strides=[1,1,1,1], padding="SAME") + b_conv0
    conv_layer_nor0 = tf.layers.batch_normalization(conv_layer0,training=False)
    
    h_conv0 = tf.nn.leaky_relu(conv_layer_nor0)
with tf.name_scope("max_pool_0"):
    h_pool0 = max_pool_2x2(h_conv0)   #输出变成224*224*64 [None,224,224,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度
with tf.name_scope("conv_1"):
    W_conv1 = weight_variable([5, 5, 64, 128])
    b_conv1 = bias_variable([128])
    conv_layer1 = conv2d(h_pool0, W_conv1) + b_conv1
    conv_layer_nor1 = tf.layers.batch_normalization(conv_layer1,training=False)

    h_conv1 = tf.nn.leaky_relu(conv_layer_nor1)
# h_conv1 = tf.nn.relu(tf.nn.conv2d(input_image, W_conv1, strides=[1,2,2,1], padding="SAME") + b_conv1)
with tf.name_scope("max_pool1"):
    h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64   [None,112,112,64]

#第二层卷积层
with tf.name_scope("conv_2"):
    W_conv2 = weight_variable([5, 5, 128, 192])
    b_conv2 = bias_variable([192])
    conv_layer2 = conv2d(h_pool1, W_conv2) + b_conv2
    conv_layer_nor2 = tf.layers.batch_normalization(conv_layer2,training=False)

    h_conv2 = tf.nn.leaky_relu(conv_layer_nor2)
with tf.name_scope("max_pool_2"):
    h_pool2 = max_pool_2x2(h_conv2)  #输出变为56*56*192


#第三层卷积层
with tf.name_scope("conv_3"):
    W_conv3 = weight_variable([3, 3, 192, 128])
    b_conv3 = bias_variable([128])
    conv_layer3 = conv2d(h_pool2, W_conv3) + b_conv3
    conv_layer_nor3 = tf.layers.batch_normalization(conv_layer3,training=False)
    

    h_conv3 = tf.nn.leaky_relu(conv_layer_nor3)
with tf.name_scope("max_pool_3"):
    h_pool3 = max_pool_2x2(h_conv3)   #输出为28*28*128


#第四层卷积层
with tf.name_scope("conv_4"):
    W_conv4 = weight_variable([3, 3, 128, 64])
    b_conv4 = bias_variable([64])
    conv_layer4 = conv2d(h_pool3, W_conv4) + b_conv4
    conv_layer_nor4 = tf.layers.batch_normalization(conv_layer4,training=False)

    h_conv4 = tf.nn.leaky_relu(conv_layer_nor4)
with tf.name_scope("max_pool_4"):
    h_pool4 = max_pool_2x2(h_conv4)   #输出变为14*14*64


keep_prob = tf.placeholder("float")

#密集连接层0
with tf.name_scope("fc0"):
    W_fc0 = weight_variable([14*14*64, 2048])
    b_fc0 = bias_variable([2048])

    h_pool4_flat = tf.reshape(h_pool4, [-1, 14*14*64])
    
    out_fc0 = tf.matmul(h_pool4_flat, W_fc0) + b_fc0
    out_nor_fc0 = tf.layers.batch_normalization(out_fc0,training=False)
    
    h_fc0 = tf.nn.leaky_relu(out_nor_fc0)   #输出为96*2048

    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop0 = tf.layers.dropout(h_fc0, keep_prob)   #输出为96*2048

#密集连接层1
with tf.name_scope("fc1"):
    W_fc1 = weight_variable([2048, 1024])
    b_fc1 = bias_variable([1024])
    
    out_fc1 = tf.matmul(h_fc1_drop0, W_fc1) + b_fc1
    out_nor_fc1 = tf.layers.batch_normalization(out_fc1,training=False)

    h_fc1 = tf.nn.leaky_relu(out_nor_fc1)   #输出为2048*1024

    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop1 = tf.layers.dropout(h_fc1, keep_prob)   #输出为2048*1024

#密集连接层2
with tf.name_scope("fc2"):
    W_fc2 = weight_variable([1024, 512])
    b_fc2 = bias_variable([512])
    
    out_fc2 = tf.matmul(h_fc1_drop1, W_fc2) + b_fc2
    out_nor_fc2 = tf.layers.batch_normalization(out_fc2,training=False)

    h_fc2 = tf.nn.leaky_relu(out_nor_fc2)
    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop2 = tf.layers.dropout(h_fc2, keep_prob)
    
#输出层
with tf.name_scope("out_layer"):
    W_fc3 = weight_variable([512, 3])
    y_conv = tf.matmul(h_fc1_drop2, W_fc3)

    
delta=tf.constant(1.25)
#huber损失函数
loss1 = tf.reduce_mean(tf.multiply(tf.square(delta),
                                          tf.sqrt(1. + tf.square((y_[:2] - y_conv[:2])/delta)) - 1.))
loss2 = 500 * tf.reduce_mean(tf.multiply(tf.square(delta),
                                          tf.sqrt(1. + tf.square((y_[2:] - y_conv[2:])/delta)) - 1.))
loss = loss1 + loss2


checkpointsPath = "/home/ysk/database/train_data/benhuan/fc_bn_checkpoints_4805/"
path = os.getcwd()
test_result_path = os.path.join(path,'test_result','new_test_6in_3out_test_result.txt')

if os.path.exists(test_result_path):
    os.remove(test_result_path)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    checkPoint = tf.train.get_checkpoint_state(checkpointsPath)
    if checkPoint and checkPoint.model_checkpoint_path:
        saver.restore(sess,checkPoint.model_checkpoint_path)
        print("restored %s" % checkPoint.model_checkpoint_path)
        
    else:
        print("no checkpoint found!")
        
    for i in range(count-2):
        batch_x,batch_y = get_train_data_batch(i)
        batch_y = batch_y*10000
        
        y_pre = sess.run(y_conv,feed_dict={input_image:batch_x, y_:batch_y,keep_prob:1.0})
              
        with open(test_result_path,'a') as f:
            for i in range(3):
                f.write(str(batch_y[0][i]) + ',')
            for i in range(2):
                f.write(str(y_pre[0][i]) + ',')
            f.write(str(y_pre[0][2]) + '\n')

        print("real location is:\n",batch_y)
        print("prediction is:\n",y_pre)
        print("\n")
    print("done!")


INFO:tensorflow:Restoring parameters from /home/ysk/database/train_data/benhuan/fc_bn_checkpoints_4805/saved_net.ckpt-199000
restored /home/ysk/database/train_data/benhuan/fc_bn_checkpoints_4805/saved_net.ckpt-199000
real location is:
 [[  2559.94878646   -601.39466037 -61226.6039933 ]]
prediction is:
 [[  6611.1445   2414.3284 -52533.906 ]]


real location is:
 [[  3628.3898691    -653.78329356 -46311.8708672 ]]
prediction is:
 [[ 19674.861    1927.4335 -41299.11  ]]


real location is:
 [[  4660.80391257   -713.05870336 -37682.2471485 ]]
prediction is:
 [[29667.043 12034.835 -9769.773]]


real location is:
 [[  5694.51729164   -757.93697074 -39235.9535478 ]]
prediction is:
 [[ 14588.324  12846.366 -51560.867]]


real location is:
 [[  6756.30097055   -848.62083795 -38530.0963466 ]]
prediction is:
 [[ 27211.357   5995.176 -34636.13 ]]


real location is:
 [[ 7807.6845113   -882.19755469 -7146.68964555]]
prediction is:
 [[20525.09  11051.607 24781.258]]


real location is:
 [[8860.0682

real location is:
 [[77583.453617    -109.40832222  7171.68709474]]
prediction is:
 [[-165093.95  193153.4  -693404.06]]


real location is:
 [[78567.4297328   -121.81863826 10637.2727279 ]]
prediction is:
 [[-163818.48  166690.2  -675407.9 ]]


real location is:
 [[79609.9814589   -125.24339174  8467.68035461]]
prediction is:
 [[-172841.72  198952.14 -778293.  ]]


real location is:
 [[80731.9325902   -128.90559939  9782.66189967]]
prediction is:
 [[-160115.75  142695.73 -605906.2 ]]


real location is:
 [[81779.1080814   -124.92300889 17480.436746  ]]
prediction is:
 [[-172542.23  170391.5  -800375.44]]


real location is:
 [[82854.8385365  -102.3178427 25000.9458922]]
prediction is:
 [[-177770.34  203090.94 -971768.  ]]


real location is:
 [[ 8.39197939e+04 -7.70294905e+01  2.52418084e+04]]
prediction is:
 [[-173099.28  168398.98 -844734.25]]


real location is:
 [[ 8.49462426e+04 -6.06783679e+01  3.00066376e+04]]
prediction is:
 [[-116927.51   83780.9  -459551.  ]]


real location

real location is:
 [[149743.953322   43977.2466914 453045.94898  ]]
prediction is:
 [[  29971.209  113809.45  -205729.36 ]]


real location is:
 [[150666.422391   44878.7348914 452931.271256 ]]
prediction is:
 [[  32101.527  110326.57  -157299.27 ]]


real location is:
 [[151585.389729   45768.4624687 451675.563026 ]]
prediction is:
 [[  15549.269  110393.6   -372458.66 ]]


real location is:
 [[152481.807829   46645.6000256 451775.687992 ]]
prediction is:
 [[  47282.734   99492.54  -454804.   ]]


real location is:
 [[153409.111969   47550.2299475 453594.452345 ]]
prediction is:
 [[  24253.068  101283.1   -475854.12 ]]


real location is:
 [[154322.006948   48465.8926158 455887.164216 ]]
prediction is:
 [[  29931.932   91360.805 -358331.7  ]]


real location is:
 [[155274.944029   49376.4593189 452827.966926 ]]
prediction is:
 [[ 102765.445   78879.39  -518259.44 ]]


real location is:
 [[156175.244345   50221.7526377 446880.973412 ]]
prediction is:
 [[  95175.34   78197.   -232255.48

real location is:
 [[204535.362539 105597.599906 647977.748523]]
prediction is:
 [[143843.2   108971.625 433820.28 ]]


real location is:
 [[204940.727447 106552.422494 695644.09088 ]]
prediction is:
 [[112648.35 129064.53 469962.53]]


real location is:
 [[205280.958143 107556.44423  734850.037664]]
prediction is:
 [[205747.5  183830.42 855057.25]]


real location is:
 [[205552.06442  108542.255044 774802.990382]]
prediction is:
 [[101051.71 191686.1  533469.9 ]]


real location is:
 [[205752.478682 109578.660741 815438.571206]]
prediction is:
 [[120292.58 193468.   354004.1 ]]


real location is:
 [[205879.71758  110667.452864 851553.568624]]
prediction is:
 [[207666.88 145084.31 811591.3 ]]


real location is:
 [[205964.173221 111721.829933 875248.994068]]
prediction is:
 [[206593.6  147768.52 864194.4 ]]


real location is:
 [[206006.135873 112835.921275 899965.843441]]
prediction is:
 [[213123.3  150298.34 933126.94]]


real location is:
 [[206024.070538 113950.361839 914045.48894

real location is:
 [[206227.605252 183591.437202 924783.507135]]
prediction is:
 [[211818.44 179627.42 925043.1 ]]


real location is:
 [[206187.806357 184640.925785 921642.243475]]
prediction is:
 [[214824.39 195605.9  942435.06]]


real location is:
 [[206152.183372 185713.61972  917922.436958]]
prediction is:
 [[216336.11 206217.64 935326.25]]


real location is:
 [[206130.669231 186786.398331 911349.880419]]
prediction is:
 [[208856.58 193868.92 910194.94]]


real location is:
 [[206117.600047 187836.967447 910160.62935 ]]
prediction is:
 [[215998.75 218148.97 956625.6 ]]


real location is:
 [[206124.687499 188933.51705  905660.802288]]
prediction is:
 [[216844.88 227999.36 929949.6 ]]


real location is:
 [[206119.138985 190047.294682 905507.06959 ]]
prediction is:
 [[206399.47 198597.31 898841.25]]


real location is:
 [[206118.368554 191130.68332  901893.74878 ]]
prediction is:
 [[205517.14 190323.78 878697.06]]


real location is:
 [[206135.448491 192211.378086 901552.038329]]

real location is:
 [[204601.735591 272567.338229 912375.405561]]
prediction is:
 [[197373.69 185278.9  623741.5 ]]


real location is:
 [[204591.580685 273664.667055 912995.84887 ]]
prediction is:
 [[192430.52 196548.72 566777.3 ]]


real location is:
 [[204566.098966 274810.10032  912473.594001]]
prediction is:
 [[193186.   206676.95 661691.9 ]]


real location is:
 [[204537.099322 275996.952797 911314.558263]]
prediction is:
 [[199093.36 205115.89 744294.5 ]]


real location is:
 [[204526.351198 277119.68126  903908.173356]]
prediction is:
 [[199211.52 203914.08 712434.75]]


real location is:
 [[204529.172495 278264.00084  896846.334458]]
prediction is:
 [[199262.48 217677.89 763751.1 ]]


real location is:
 [[204554.339107 279434.809534 892752.280918]]
prediction is:
 [[197176.36 253871.14 855270.6 ]]


real location is:
 [[204577.581425 280494.152811 892745.393231]]
prediction is:
 [[193988.58 288144.84 877013.25]]


real location is:
 [[204602.766637 281574.724199 897144.14717 ]]

real location is:
 [[ 173098.394195  341071.973826 1362620.72616 ]]
prediction is:
 [[ 169730.31  338206.4  1305347.6 ]]


real location is:
 [[ 172281.636928  341875.179579 1362320.65169 ]]
prediction is:
 [[ 169148.69  342166.5  1320267.5 ]]


real location is:
 [[ 171470.619631  342669.869516 1362825.07547 ]]
prediction is:
 [[ 162145.5   328672.94 1280894.1 ]]


real location is:
 [[ 170587.846415  343515.812179 1358147.39902 ]]
prediction is:
 [[ 162455.03  327145.22 1294335.5 ]]


real location is:
 [[ 169727.296197  344365.408306 1357102.52217 ]]
prediction is:
 [[ 158900.25  329535.88 1300734.5 ]]


real location is:
 [[ 168904.038492  345197.10711  1358197.33737 ]]
prediction is:
 [[126846.414 320910.84  776395.9  ]]


real location is:
 [[ 168061.759441  346007.819778 1364485.56478 ]]
prediction is:
 [[ 163930.98  331454.88 1304529.4 ]]


real location is:
 [[ 167215.185341  346826.371536 1366738.95739 ]]
prediction is:
 [[ 165261.1   328878.97 1291096.  ]]


real location is

real location is:
 [[ 115685.026611  395640.955289 1444094.64456 ]]
prediction is:
 [[ 119635.41  383048.75 1358718.2 ]]


real location is:
 [[ 114729.85716   396343.138028 1444038.24498 ]]
prediction is:
 [[ 116578.664  382187.12  1351841.4  ]]


real location is:
 [[ 113835.256529  396999.981223 1443580.87544 ]]
prediction is:
 [[ 121736.57  376775.78 1350514.9 ]]


real location is:
 [[ 112989.652356  397620.313035 1443199.54846 ]]
prediction is:
 [[ 121324.836  376931.03  1344027.6  ]]


real location is:
 [[ 112125.994526  398249.676511 1443311.43289 ]]
prediction is:
 [[ 117777.164  377127.75  1357254.9  ]]


real location is:
 [[ 111228.104695  398922.53414  1436727.7096  ]]
prediction is:
 [[ 111424.97  391946.1  1370502.4 ]]


real location is:
 [[ 110393.371122  399545.743663 1429582.63225 ]]
prediction is:
 [[ 108840.64  390218.16 1372834.6 ]]


real location is:
 [[ 109553.655556  400189.363722 1419293.22865 ]]
prediction is:
 [[ 108893.266  394008.34  1387286.9  ]]


real

real location is:
 [[   40168.6513422   409146.2269    -1796876.73263  ]]
prediction is:
 [[   34742.848   382333.84  -1727233.2  ]]


real location is:
 [[   38964.738609   409164.91743  -1799704.7133  ]]
prediction is:
 [[   37252.25   382129.62 -1742835.6 ]]


real location is:
 [[  37779.8011185  409174.778015  1795381.69868  ]]
prediction is:
 [[   35447.656   386484.97  -1754892.5  ]]


real location is:
 [[  36600.4941494  409199.116287  1792851.96658  ]]
prediction is:
 [[   21197.488   375672.8   -1503615.6  ]]


real location is:
 [[  35376.953572  409227.179827 1797089.90179 ]]
prediction is:
 [[   24892.428   386268.78  -1711313.9  ]]


real location is:
 [[   34218.7217164   409237.531675  -1798909.01584  ]]
prediction is:
 [[   33768.195   386387.22  -1737094.   ]]


real location is:
 [[   33017.6272256   409247.195156  -1794880.52891  ]]
prediction is:
 [[   27896.48   378944.88 -1735275.9 ]]


real location is:
 [[   31858.1006104   409248.617547  -1788805.7666   ]]
pr

real location is:
 [[  -41429.2398431   408671.195886  -1790900.27555  ]]
prediction is:
 [[  -26570.857   393832.22  -1747703.9  ]]


real location is:
 [[  -42672.7115192   408665.14503   -1792321.76496  ]]
prediction is:
 [[  -45421.492   390494.72  -1745195.8  ]]


real location is:
 [[  -43884.2560972   408669.416447  -1789552.64225  ]]
prediction is:
 [[  -41453.53   386091.75 -1720320.8 ]]


real location is:
 [[  -45095.521543   408646.08195  -1786945.63983 ]]
prediction is:
 [[ 1.3571982e+03  3.8768291e+05 -1.4206720e+06]]


real location is:
 [[  -46252.4805516   408634.499147  -1787842.12204  ]]
prediction is:
 [[  99165.414  341777.1   -441809.88 ]]


real location is:
 [[  -47409.6716911   408619.099218  -1789278.58933  ]]
prediction is:
 [[  -24325.277   375715.7   -1239088.2  ]]


real location is:
 [[  -48685.7876925   408607.967713  -1789419.39259  ]]
prediction is:
 [[130555.484 320353.34  -23207.707]]


real location is:
 [[  -49876.3251702   408601.846664  -1795815.

real location is:
 [[ -117726.047926   394161.402672 -1402830.8755  ]]
prediction is:
 [[ -104137.1    373839.34 -1380456.5 ]]


real location is:
 [[ -118566.535043   393460.229621 -1399779.60187 ]]
prediction is:
 [[ -117950.7    366179.88 -1376846.2 ]]


real location is:
 [[ -119407.723139   392775.592417 -1400448.48993 ]]
prediction is:
 [[ -113365.336   371146.25  -1382770.2  ]]


real location is:
 [[ -120263.51942    392089.450381 -1403430.5828  ]]
prediction is:
 [[ -120372.47   377558.38 -1370802.6 ]]


real location is:
 [[ -121084.174577   391395.66558  -1398480.16943 ]]
prediction is:
 [[ -118795.47   364637.47 -1369518.1 ]]


real location is:
 [[ -121887.376732   390741.094127 -1386090.51488 ]]
prediction is:
 [[ -127131.78   363078.8  -1337023.2 ]]


real location is:
 [[ -122675.405061   390058.707348 -1375449.39896 ]]
prediction is:
 [[ -116584.35   378026.53 -1334856.2 ]]


real location is:
 [[ -123483.824263   389320.217795 -1367633.23237 ]]
prediction is:
 [[ -118

real location is:
 [[ -168556.834479   343268.340071 -1345113.4039  ]]
prediction is:
 [[ -158949.17   333481.53 -1338900.9 ]]


real location is:
 [[ -169324.115254   342478.588599 -1337696.32667 ]]
prediction is:
 [[ -156002.23   332483.34 -1334917.1 ]]


real location is:
 [[ -170073.405282   341714.004753 -1337961.07106 ]]
prediction is:
 [[ -156795.73   331839.97 -1335701.  ]]


real location is:
 [[ -170851.299216   340908.759015 -1338359.7432  ]]
prediction is:
 [[ -155772.11   334996.75 -1332204.8 ]]


real location is:
 [[ -171547.598934   340181.180042 -1331452.38388 ]]
prediction is:
 [[ -158467.03   336992.06 -1318606.1 ]]


real location is:
 [[ -172237.605514   339446.759408 -1327333.4396  ]]
prediction is:
 [[ -157090.28   328010.88 -1051537.9 ]]


real location is:
 [[ -172975.024009   338659.939146 -1328778.77309 ]]
prediction is:
 [[ -163674.6    329463.25 -1179359.  ]]


real location is:
 [[ -173678.273636   337923.609055 -1328488.47072 ]]
prediction is:
 [[ -165420

real location is:
 [[-205615.185075  279405.003244 -914722.385737]]
prediction is:
 [[-183557.53  274593.62 -844763.8 ]]


real location is:
 [[-205663.703111  278191.301052 -917364.817452]]
prediction is:
 [[-186836.84  266827.7  -729634.7 ]]


real location is:
 [[-205714.531661  276967.255124 -923750.28559 ]]
prediction is:
 [[-194895.61  264496.03 -884043.8 ]]


real location is:
 [[-205758.254026  275662.323726 -924454.791085]]
prediction is:
 [[-198142.61  256695.1  -862562.7 ]]


real location is:
 [[-205808.093765  274402.945359 -924313.953384]]
prediction is:
 [[-193505.6  259945.6 -859840.1]]


real location is:
 [[-205857.732125  273183.297611 -924005.780025]]
prediction is:
 [[-196155.98  251322.9  -855787.25]]


real location is:
 [[-205915.839162  271992.220871 -924648.830871]]
prediction is:
 [[-191685.    255834.11 -893451.3 ]]


real location is:
 [[-205986.387614  270795.662033 -918954.179018]]
prediction is:
 [[-193989.66  257304.98 -882574.4 ]]


real location is:
 

real location is:
 [[-207817.756103  190771.632817 -910830.277638]]
prediction is:
 [[-200565.42  190749.92 -867237.  ]]


real location is:
 [[-207857.350189  189427.263846 -911675.328074]]
prediction is:
 [[-204849.53  194787.   -877182.  ]]


real location is:
 [[-207896.048464  188158.108505 -912633.423378]]
prediction is:
 [[-202393.92  194190.33 -876276.7 ]]


real location is:
 [[-207937.154087  186775.398977 -912171.817309]]
prediction is:
 [[-201557.6   190183.2  -874982.75]]


real location is:
 [[-207965.767162  185458.99538  -912116.978445]]
prediction is:
 [[-199690.05  181703.9  -880297.  ]]


real location is:
 [[-207989.953422  184178.650843 -910389.565354]]
prediction is:
 [[-200857.31  181779.67 -861456.4 ]]


real location is:
 [[-207981.29702   182833.958394 -900338.25357 ]]
prediction is:
 [[-201754.73  177965.39 -865029.2 ]]


real location is:
 [[-207992.639182  181494.568998 -895090.83903 ]]
prediction is:
 [[-201098.28  180607.28 -860273.  ]]


real location is

real location is:
 [[-200397.10985     97960.2702534 -523077.259155 ]]
prediction is:
 [[-204239.89  103171.23 -348985.56]]


real location is:
 [[-199700.601763    97042.4140446 -509981.455115 ]]
prediction is:
 [[-213327.58  114303.98 -428881.1 ]]


real location is:
 [[-198999.053156    96191.6731623 -502028.431405 ]]
prediction is:
 [[-211571.84  110207.1  -464306.1 ]]


real location is:
 [[-198318.292984    95323.1049308 -495762.535515 ]]
prediction is:
 [[-215119.67  112717.07 -486615.  ]]


real location is:
 [[-197663.030531    94466.3562517 -499423.150723 ]]
prediction is:
 [[-208064.11  102561.81 -343302.44]]


real location is:
 [[-196995.869489    93651.5839712 -498660.829759 ]]
prediction is:
 [[-202141.89  102229.6  -347898.94]]


real location is:
 [[-196296.402143    92835.7993589 -494772.244697 ]]
prediction is:
 [[-207445.64   112190.266 -484956.94 ]]


real location is:
 [[-195597.092619    91987.3780935 -488675.233272 ]]
prediction is:
 [[-205326.95  109749.49 -491

real location is:
 [[-146472.030687    44900.7501105 -411149.524856 ]]
prediction is:
 [[-149320.6    57942.13 -401800.16]]


real location is:
 [[-145642.630413    44151.9431762 -415404.594323 ]]
prediction is:
 [[-149016.77   54475.57 -406244.2 ]]


real location is:
 [[-144834.698211    43426.1789746 -417007.670552 ]]
prediction is:
 [[-145103.98    47266.324 -377138.03 ]]


real location is:
 [[-144041.025677    42706.5434504 -417474.879472 ]]
prediction is:
 [[-146640.33   46785.71 -409029.2 ]]


real location is:
 [[-143278.468397    42025.0046229 -417614.671496 ]]
prediction is:
 [[-152453.77    52098.355 -427075.28 ]]


real location is:
 [[-142495.428836    41292.0043154 -418142.251887 ]]
prediction is:
 [[-145385.45    44784.605 -390912.84 ]]


real location is:
 [[-141721.100291    40595.3979465 -418429.867228 ]]
prediction is:
 [[-145834.89    45505.332 -409342.4  ]]


real location is:
 [[-140907.058783    39856.8716352 -418221.582013 ]]
prediction is:
 [[-147112.8    4384

real location is:
 [[-85046.3937993    3666.94300024 -30730.1457533 ]]
prediction is:
 [[-77115.43      -487.67773   4807.034  ]]


real location is:
 [[-83594.3573743    3574.37142215 -19886.5991985 ]]
prediction is:
 [[-70184.18   11103.272  25973.271]]


real location is:
 [[-82168.3093413    3500.47105384 -17685.5652771 ]]
prediction is:
 [[-77738.08   16115.586  24733.986]]


real location is:
 [[-80740.4387064    3432.70283286 -17516.4090084 ]]
prediction is:
 [[-76420.57    9872.432  17160.   ]]


real location is:
 [[-79275.2909242    3385.10435642  -8694.6232049 ]]
prediction is:
 [[-68275.484  11812.342  39052.832]]


real location is:
 [[-77812.8032266    3331.60493277 -19820.2580036 ]]
prediction is:
 [[-74481.82    8317.268  27084.213]]


real location is:
 [[-76386.7615912    3239.52868066 -21581.6723573 ]]
prediction is:
 [[-69051.055   9555.415  27957.555]]


real location is:
 [[-74937.837894     3138.64301984 -27982.2720368 ]]
prediction is:
 [[-67904.21     228.457  

real location is:
 [[6284.69292813 -862.60753203 5112.14650841]]
prediction is:
 [[-35753.1     7105.631  52920.004]]


real location is:
 [[7600.1448936  -877.09713898 4445.2954287 ]]
prediction is:
 [[-9359.493 15790.24  61335.145]]


real location is:
 [[8875.87275415 -886.83853362 6514.39055833]]
prediction is:
 [[-25264.367  14780.258  61312.973]]


real location is:
 [[10223.5475448   -895.59650797  2303.46716998]]
prediction is:
 [[-12351.982  10740.42   62036.28 ]]


real location is:
 [[11551.7485255   -889.21230099 12699.122416  ]]
prediction is:
 [[ 8099.04    1218.3167 77371.06  ]]


real location is:
 [[12804.5897059   -861.76093484 18359.0005001 ]]
prediction is:
 [[ 8402.937 -5535.552 92171.914]]


real location is:
 [[14128.5120138   -842.44922858 18128.4319514 ]]
prediction is:
 [[16859.865  -5217.8945 61183.734 ]]


real location is:
 [[15405.2096094  -846.3828702 15214.2303157]]
prediction is:
 [[ 1064.6843 -5755.3564 41230.33  ]]


real location is:
 [[16663.2849526

real location is:
 [[95568.6179762   1388.14807303 62801.2569332 ]]
prediction is:
 [[134648.5   58418.68 226324.14]]


real location is:
 [[96707.8994938   1554.39452938 86609.1180797 ]]
prediction is:
 [[84073.05   -3920.2458 63276.57  ]]


real location is:
 [[ 97789.9728608    1716.29391319 105678.752152  ]]
prediction is:
 [[ 82303.93     1822.2139 118460.46  ]]


real location is:
 [[ 98915.8441921    1947.74522806 132492.735609  ]]
prediction is:
 [[ 86326.11   -1506.353 185310.02 ]]


real location is:
 [[ 99899.5409331    2208.16454731 156730.636145  ]]
prediction is:
 [[ 84213.28     7202.1562 188071.33  ]]


real location is:
 [[100878.684044     2503.64399584 181329.573304  ]]
prediction is:
 [[ 90393.445  57053.77  132963.52 ]]


real location is:
 [[101874.711166     2833.59114405 201415.195159  ]]
prediction is:
 [[ 78047.86 123579.05 157271.47]]


real location is:
 [[102889.656569     3193.90398643 208343.544739  ]]
prediction is:
 [[ 81871.54  85681.84 183897.16]]


r

real location is:
 [[154718.269555   49199.5393637 453615.587995 ]]
prediction is:
 [[161420.66   42774.816 431741.1  ]]


real location is:
 [[155482.572163   49946.1247942 453873.68023  ]]
prediction is:
 [[160962.9    44081.594 422817.12 ]]


real location is:
 [[156258.621925   50682.2553392 445438.925498 ]]
prediction is:
 [[148348.77  36179.7  287007.75]]


real location is:
 [[157051.220321   51402.3896613 438186.729751 ]]
prediction is:
 [[139162.92   45458.105 212935.56 ]]


real location is:
 [[157872.282104   52156.0074143 438109.99732  ]]
prediction is:
 [[63915.508 55445.395 63003.883]]


real location is:
 [[158652.589015   52871.1789703 441743.853654 ]]
prediction is:
 [[ 67019.516  46191.76  104990.41 ]]


real location is:
 [[159448.626802  53624.021181 442107.385634]]
prediction is:
 [[  9371.933  56892.91  -35467.215]]


real location is:
 [[160252.833863   54371.6929194 448209.715769 ]]
prediction is:
 [[66331.555 41500.9   72929.52 ]]


real location is:
 [[160981.

real location is:
 [[205725.857714 110490.549469 838563.997069]]
prediction is:
 [[190310.4  161856.67 561403.1 ]]


real location is:
 [[205866.255254 111789.82526  866020.007902]]
prediction is:
 [[203977.9 160534.8 764728. ]]


real location is:
 [[205925.844735 112988.198906 891950.921997]]
prediction is:
 [[214849.72 145536.31 923187.8 ]]


real location is:
 [[205935.261067 114203.65929  913615.813231]]
prediction is:
 [[222052.72 159328.06 987841.75]]


real location is:
 [[205960.636399 115388.945901 915161.126981]]
prediction is:
 [[215438.22 150284.92 966516.56]]


real location is:
 [[205978.918988 116564.720206 913980.153249]]
prediction is:
 [[213505.19 147844.98 956606.5 ]]


real location is:
 [[205979.020961 117762.345952 916723.241845]]
prediction is:
 [[211084.53 137248.98 939286.8 ]]


real location is:
 [[206002.491894 118937.147327 916532.084607]]
prediction is:
 [[212652.92 135384.95 923290.44]]


real location is:
 [[206014.466694 120137.162805 907692.253424]]
pr

real location is:
 [[206682.40976  194105.612119 904589.511291]]
prediction is:
 [[210270.08 212395.47 938844.3 ]]


real location is:
 [[206674.031476 195241.607695 907966.005164]]
prediction is:
 [[211345.2  200765.25 900382.7 ]]


real location is:
 [[206666.670636 196375.966644 905223.41532 ]]
prediction is:
 [[207302.38 183000.44 873834.6 ]]


real location is:
 [[206671.971156 197515.658912 899181.685598]]
prediction is:
 [[204331.9  200264.23 883112.8 ]]


real location is:
 [[206683.266776 198715.255847 900194.809968]]
prediction is:
 [[208772.42 205553.64 890481.5 ]]


real location is:
 [[206703.768193 199904.961026 908203.371491]]
prediction is:
 [[210513.31 219490.72 917253.  ]]


real location is:
 [[206681.296491 201020.698244 916836.245618]]
prediction is:
 [[207688.8  224331.16 925524.94]]


real location is:
 [[206602.631524 202148.727182 924276.534293]]
prediction is:
 [[209133.2  217417.2  906587.06]]


real location is:
 [[206565.85553  203295.982605 923717.043282]]

real location is:
 [[206137.452814 285590.501854 926414.394435]]
prediction is:
 [[200411.11 271001.94 842732.6 ]]


real location is:
 [[206094.059518 286800.47052  928919.818879]]
prediction is:
 [[202603.44 278654.78 896410.9 ]]


real location is:
 [[206039.809512 287854.11694  933510.715732]]
prediction is:
 [[201050.56 292626.6  935756.06]]


real location is:
 [[205977.584512 288953.414876 938568.886761]]
prediction is:
 [[198880.05 267508.   849345.56]]


real location is:
 [[205933.374605 290016.011955 937611.498189]]
prediction is:
 [[203961.86 272239.34 899993.9 ]]


real location is:
 [[205888.212286 291055.342628 931114.508984]]
prediction is:
 [[196021.25 281282.75 961544.75]]


real location is:
 [[205839.980373 292200.699453 930432.796968]]
prediction is:
 [[194904.7  282822.62 932656.4 ]]


real location is:
 [[205792.812681 293280.389225 929810.418688]]
prediction is:
 [[199843.31 276621.94 892685.7 ]]


real location is:
 [[205755.095267 294342.610762 929703.570961]]

real location is:
 [[ 176659.51822  336410.56403 1561110.89014]]
prediction is:
 [[ -61253.754  277157.28  -199007.5  ]]


real location is:
 [[ 175614.566431  337074.766582 1426992.48314 ]]
prediction is:
 [[172319.27 217478.61 820100.9 ]]


real location is:
 [[ 174701.173139  337850.272547 1379936.77905 ]]
prediction is:
 [[212947.97 235607.77 920308.6 ]]


real location is:
 [[ 173841.31245   338668.545776 1351370.08891 ]]
prediction is:
 [[ 167680.11  291347.94 1253404.8 ]]


real location is:
 [[ 173037.572542  339501.662442 1344921.04919 ]]
prediction is:
 [[ 187175.8   248151.08 1017326.7 ]]


real location is:
 [[ 172193.729843  340374.182009 1343855.58398 ]]
prediction is:
 [[187604.61 241935.47 994541.56]]


real location is:
 [[ 171385.537334  341202.797874 1339095.78647 ]]
prediction is:
 [[183598.92 243268.78 988537.25]]


real location is:
 [[ 170531.82209   342088.329141 1340201.28325 ]]
prediction is:
 [[185554.47 232584.86 977397.6 ]]


real location is:
 [[ 169730.78

real location is:
 [[ 114921.716056  396160.591128 1443043.94563 ]]
prediction is:
 [[ 116166.63  388766.2  1359403.8 ]]


real location is:
 [[ 113890.41336   396914.686959 1447710.69136 ]]
prediction is:
 [[ 121671.31  372244.88 1350266.8 ]]


real location is:
 [[ 112867.811829  397614.527392 1448776.19059 ]]
prediction is:
 [[ 121828.46  372884.9  1337174.  ]]


real location is:
 [[ 111837.788591  398343.93917  1447856.04069 ]]
prediction is:
 [[ 122855.58  370172.16 1330960.9 ]]


real location is:
 [[ 110772.151457  399103.967517 1447501.0315  ]]
prediction is:
 [[ 113683.33  381008.06 1351912.  ]]


real location is:
 [[ 109720.889084  399840.542942 1446943.4378  ]]
prediction is:
 [[ 110784.06  386332.06 1359882.  ]]


real location is:
 [[ 108628.117841  400607.399271 1437854.0573  ]]
prediction is:
 [[ 108861.195  388350.88  1381590.9  ]]


real location is:
 [[ 107596.482067  401377.547811 1427612.29546 ]]
prediction is:
 [[ 108150.92  388014.12 1365575.5 ]]


real location

real location is:
 [[   37488.1878202   410183.810601  -1785740.81245  ]]
prediction is:
 [[   33537.15   385926.16 -1729722.  ]]


real location is:
 [[   36387.1914476   410146.205655  -1780611.52269  ]]
prediction is:
 [[   36153.504   389012.16  -1715219.   ]]


real location is:
 [[   35293.1101577   410134.927017  -1787783.30821  ]]
prediction is:
 [[   34130.17   386648.72 -1722509.1 ]]


real location is:
 [[   34239.8011883   410126.774255  -1790890.708    ]]
prediction is:
 [[   27088.732   383460.88  -1728243.4  ]]


real location is:
 [[   33180.0461994   410117.440016  -1793769.1691   ]]
prediction is:
 [[   36685.32   384386.7  -1745544.6 ]]


real location is:
 [[   32145.2328489   410101.632015  -1798911.84553  ]]
prediction is:
 [[   24958.984   392092.88  -1766172.   ]]


real location is:
 [[  31081.9606473  410111.15745   1796584.09328  ]]
prediction is:
 [[ 28636.5  335224.94  88909.69]]


real location is:
 [[  30006.9912503  410132.145856  1799316.4819   ]]
predi

real location is:
 [[  -40314.8094416   409786.932542  -1789858.22628  ]]
prediction is:
 [[  -45458.496   362372.88  -1423198.9  ]]


real location is:
 [[  -41389.7475551   409751.87124   -1781173.2647   ]]
prediction is:
 [[  -53438.055   357742.44  -1514336.8  ]]


real location is:
 [[  -42447.7015598   409734.11395   -1779231.36015  ]]
prediction is:
 [[  -56481.496   324557.22  -1293833.5  ]]


real location is:
 [[  -43532.213824   409713.535877 -1778912.56571 ]]
prediction is:
 [[  -45236.477   372209.3   -1650537.1  ]]


real location is:
 [[  -44579.6412482   409693.288935  -1779130.37801  ]]
prediction is:
 [[  -51153.14   363082.4  -1579887.2 ]]


real location is:
 [[  -45662.7865646   409676.266573  -1786328.18162  ]]
prediction is:
 [[  -27823.258   351845.94  -1230580.   ]]


real location is:
 [[  -46723.1555019   409661.227694  -1785950.5798   ]]
prediction is:
 [[  -40303.35   362813.84 -1564737.6 ]]


real location is:
 [[  -47831.5706376   409644.137386  -1786942.

real location is:
 [[ -112793.382108   398176.729973 -1397474.10383 ]]
prediction is:
 [[ -100623.84   391162.56 -1375061.  ]]


real location is:
 [[ -113721.02571    397393.791935 -1397926.27601 ]]
prediction is:
 [[ -106651.93   384330.1  -1361600.9 ]]


real location is:
 [[ -114709.790908   396562.908969 -1393252.94788 ]]
prediction is:
 [[ -100721.91   378199.7  -1365562.8 ]]


real location is:
 [[ -115589.267317   395799.76752  -1390948.24117 ]]
prediction is:
 [[ -102614.29   381595.88 -1382899.8 ]]


real location is:
 [[ -116591.804329   394938.149776 -1386897.77163 ]]
prediction is:
 [[ -100414.31   373451.5  -1375310.6 ]]


real location is:
 [[ -117602.932332   394056.205585 -1392746.88425 ]]
prediction is:
 [[ -112954.266   374338.44  -1356114.9  ]]


real location is:
 [[ -118515.331762   393262.481025 -1392391.28814 ]]
prediction is:
 [[ -110778.91   378497.44 -1372635.8 ]]


real location is:
 [[ -119507.028877   392418.846321 -1388160.73438 ]]
prediction is:
 [[ -108

real location is:
 [[ -181959.33175    330290.935647 -1350657.15414 ]]
prediction is:
 [[ -178006.19   257027.61 -1021648.44]]


real location is:
 [[ -182942.429962   329312.634468 -1351092.31138 ]]
prediction is:
 [[ -183651.3   298308.5 -1247498.2]]


real location is:
 [[ -183867.262469   328406.258647 -1347604.05407 ]]
prediction is:
 [[-181783.14  268853.03 -927899.1 ]]


real location is:
 [[ -184828.377809   327431.140777 -1343243.70629 ]]
prediction is:
 [[-174627.66  276876.34 -822567.  ]]


real location is:
 [[ -185770.819699   326404.702754 -1316559.96407 ]]
prediction is:
 [[ -180444.23   307723.38 -1293267.2 ]]


real location is:
 [[ -186677.28054    325379.790296 -1305763.90753 ]]
prediction is:
 [[ -189414.52   287271.06 -1273617.8 ]]


real location is:
 [[ -187627.426396   324289.85184  -1307135.72918 ]]
prediction is:
 [[ -181767.92   311905.62 -1297929.  ]]


real location is:
 [[ -188524.262382   323259.63522  -1308257.57449 ]]
prediction is:
 [[ -181915.44   322

real location is:
 [[-207204.832154  253372.019184 -922868.586646]]
prediction is:
 [[-202202.33  236756.55 -906261.1 ]]


real location is:
 [[-207250.457777  252357.366949 -919052.126184]]
prediction is:
 [[-198909.92  238750.95 -873942.94]]


real location is:
 [[-207258.318033  251250.497854 -910245.230353]]
prediction is:
 [[-203722.17  256682.1  -886179.44]]


real location is:
 [[-207264.52703   250119.413712 -901789.753252]]
prediction is:
 [[-199943.8   252312.02 -840013.7 ]]


real location is:
 [[-207268.789639  249026.010166 -894851.799136]]
prediction is:
 [[-195643.22  240232.84 -838801.9 ]]


real location is:
 [[-207275.889815  247971.011707 -899615.26611 ]]
prediction is:
 [[-196505.92  248746.39 -847393.56]]


real location is:
 [[-207288.525916  246938.359947 -916215.087092]]
prediction is:
 [[-201616.8   235847.53 -858866.6 ]]


real location is:
 [[-207350.17213   245885.512171 -924011.057916]]
prediction is:
 [[-194667.36  229738.95 -847190.75]]


real location is

real location is:
 [[-207909.707973  175720.311729 -881675.531329]]
prediction is:
 [[-203580.2   174930.28 -860192.6 ]]


real location is:
 [[-207892.829687  174627.530947 -890291.985619]]
prediction is:
 [[-201738.78  179172.81 -864386.8 ]]


real location is:
 [[-207899.997766  173572.89757  -898268.635301]]
prediction is:
 [[-208945.45  182864.42 -883336.75]]


real location is:
 [[-207913.19283   172494.529103 -900836.198998]]
prediction is:
 [[-211381.64  188404.14 -880123.  ]]


real location is:
 [[-207930.727732  171377.194401 -902334.404764]]
prediction is:
 [[-207288.2   178005.64 -891645.7 ]]


real location is:
 [[-207934.659501  170336.500261 -902426.423621]]
prediction is:
 [[-205691.86  177516.94 -885989.5 ]]


real location is:
 [[-207967.342157  169289.862091 -902722.970388]]
prediction is:
 [[-210994.4   178882.08 -886126.8 ]]


real location is:
 [[-207984.258523  168177.033753 -902863.308514]]
prediction is:
 [[-206073.6  175137.4 -885163. ]]


real location is:
 

real location is:
 [[-202277.680616  101499.345563 -614962.347165]]
prediction is:
 [[-224731.98  111191.71 -607895.8 ]]


real location is:
 [[-201660.476914  100275.644382 -586193.780836]]
prediction is:
 [[-221567.44  113839.43 -591988.2 ]]


real location is:
 [[-201018.728885    99158.6229365 -556959.323026 ]]
prediction is:
 [[-197196.9    94363.7  -519368.06]]


real location is:
 [[-200324.547968    97992.8079143 -544551.256518 ]]
prediction is:
 [[-200771.67  105771.1  -538513.7 ]]


real location is:
 [[-199570.011275    96795.0837921 -535181.348076 ]]
prediction is:
 [[-183855.55   88937.11 -448206.7 ]]


real location is:
 [[-198785.576084    95634.2238871 -510034.687332 ]]
prediction is:
 [[-193064.36   93780.01 -405120.03]]


real location is:
 [[-197933.872384    94514.4361042 -486065.232501 ]]
prediction is:
 [[-203897.72  100618.44 -276802.22]]


real location is:
 [[-196997.913925    93339.5755807 -477432.730883 ]]
prediction is:
 [[-207386.92   105621.734 -391495.   

real location is:
 [[-137508.555323    36409.4815474 -416716.262437 ]]
prediction is:
 [[-139673.8     43778.055 -414705.03 ]]


real location is:
 [[-136583.220978    35559.9239434 -417536.249384 ]]
prediction is:
 [[-140195.98    44193.746 -418357.12 ]]


real location is:
 [[-135610.407965    34685.0900085 -410548.93155  ]]
prediction is:
 [[-137725.17   41253.4  -411215.44]]


real location is:
 [[-134657.236046    33828.2851221 -407665.235878 ]]
prediction is:
 [[-137227.33   40732.82 -402603.88]]


real location is:
 [[-133679.778647    32993.5029242 -398504.859926 ]]
prediction is:
 [[-122996.9     28893.688 -363299.75 ]]


real location is:
 [[-132684.537995    32147.4184126 -391473.667903 ]]
prediction is:
 [[-117713.52    28682.344 -327789.3  ]]


real location is:
 [[-131698.897957    31316.9254389 -391867.223834 ]]
prediction is:
 [[-129606.21    39169.246 -384448.8  ]]


real location is:
 [[-130720.895425    30503.9588534 -387098.470967 ]]
prediction is:
 [[-119176.08    

real location is:
 [[-66929.876524     3142.74129721 -25049.2840045 ]]
prediction is:
 [[-50801.793    3445.1636  25026.195 ]]


real location is:
 [[-65807.316586     3056.80060815 -23601.7342355 ]]
prediction is:
 [[-50265.51     7242.5205  15639.104 ]]


real location is:
 [[-64730.8473421    2995.99502268 -20707.417207  ]]
prediction is:
 [[-61583.805    2533.9277  17375.402 ]]


real location is:
 [[-63698.024166     2937.41016639 -17249.7056237 ]]
prediction is:
 [[-68558.9      4916.5996   7722.752 ]]


real location is:
 [[-62588.2961302    2880.47786444 -15827.7074544 ]]
prediction is:
 [[-47962.56   10084.811   9520.603]]


real location is:
 [[-61480.896021     2828.93296346 -21219.6741384 ]]
prediction is:
 [[-57906.863  11790.674  10861.16 ]]


real location is:
 [[-60413.2833012    2763.44193675 -23284.1024231 ]]
prediction is:
 [[-68639.88     9015.6875  12962.786 ]]


real location is:
 [[-59348.5363447    2701.61112338 -23573.7157447 ]]
prediction is:
 [[-62245.46    8

real location is:
 [[   1013.85826682   -1111.10658451 -606815.025033  ]]
prediction is:
 [[  15093.421  -28960.352 -329565.5  ]]


real location is:
 [[   1011.10323781   -1105.7799524  -791794.766823  ]]
prediction is:
 [[  -1385.3262  -25789.967  -406678.22  ]]


real location is:
 [[   1035.18911089   -1146.18305569 -968155.57949   ]]
prediction is:
 [[   11689.695    13974.931 -1020617.4  ]]


real location is:
 [[ 1.03034919e+03 -1.17478396e+03 -1.14869376e+06]]
prediction is:
 [[ -36107.266  -25216.918 -921128.4  ]]


real location is:
 [[ 1.02745968e+03 -1.22285924e+03 -1.32864197e+06]]
prediction is:
 [[  -28441.416   -33414.625 -1302290.2  ]]


real location is:
 [[ 1.00785391e+03 -1.26631423e+03 -1.51070755e+06]]
prediction is:
 [[   21474.334     7427.876 -1311831.9  ]]


real location is:
 [[ 8.91633621e+02 -1.33567645e+03 -1.68791776e+06]]
prediction is:
 [[   10490.445     -3431.1035 -1630148.9   ]]


real location is:
 [[-2.13463078e+02 -1.38772477e+03  1.74441649e+06]]

real location is:
 [[  -70794.3761951      2970.75297058 -1783865.28659   ]]
prediction is:
 [[ -66919.48    31190.562 1675196.5  ]]


real location is:
 [[  -71893.4606702      2962.34267368 -1780886.0934    ]]
prediction is:
 [[ -68985.87   34824.28 1648846.4 ]]


real location is:
 [[  -73070.9303893      2949.85504111 -1782063.95535   ]]
prediction is:
 [[ -71443.875   24391.598 1659506.8  ]]


real location is:
 [[  -74131.9565666      2924.87689746 -1782612.57407   ]]
prediction is:
 [[ -73397.22    24844.648 1650222.   ]]


real location is:
 [[  -75226.9112663      2902.48171362 -1782682.92688   ]]
prediction is:
 [[ -75693.78   25513.75 1655161.1 ]]


real location is:
 [[  -76332.4132225      2883.20622157 -1783485.59399   ]]
prediction is:
 [[ -76073.47    26199.645 1653061.6  ]]


real location is:
 [[  -77477.2475439      2875.30172608 -1783315.75779   ]]
prediction is:
 [[ -75923.19    27051.127 1659326.8  ]]


real location is:
 [[  -78660.6975369     2852.1832623 -17844

real location is:
 [[-137609.970893    37690.3278133 1392078.45041  ]]
prediction is:
 [[-123127.71    62374.656 1323654.   ]]


real location is:
 [[-138419.58242     38401.9943696 1396299.47884  ]]
prediction is:
 [[-123182.34   38161.79 1379004.8 ]]


real location is:
 [[-139338.688977    39210.3392293 1389502.16901  ]]
prediction is:
 [[-125663.54   54536.91 1374490.5 ]]


real location is:
 [[-140155.176682   39942.078625 1382780.70504 ]]
prediction is:
 [[-128847.65    64165.473 1340751.5  ]]


real location is:
 [[-141023.21688     40709.9436252 1378073.32652  ]]
prediction is:
 [[-135871.62   76179.94 1311282.2 ]]


real location is:
 [[-141868.671848    41505.2375232 1376503.14163  ]]
prediction is:
 [[-138563.9    61373.77 1335574.  ]]


real location is:
 [[-142663.200099    42262.3565876 1370811.97498  ]]
prediction is:
 [[-158238.6   139216.61 1094687.5 ]]


real location is:
 [[-143465.905864    43033.4313574 1369232.66103  ]]
prediction is:
 [[-136496.19   73694.02 1246

real location is:
 [[-194764.527816    92114.7130199 1331630.00117  ]]
prediction is:
 [[-193098.52  100565.05 1302751.5 ]]


real location is:
 [[-195537.894095    92955.3970834 1332917.59803  ]]
prediction is:
 [[-189369.2    101631.055 1288455.9  ]]


real location is:
 [[-196330.4972      93818.0335618 1327218.59955  ]]
prediction is:
 [[-196229.95  127035.79 1313393.2 ]]


real location is:
 [[-197081.277189    94621.7512532 1326737.47021  ]]
prediction is:
 [[-197626.7   110608.08 1337131.  ]]


real location is:
 [[-197865.223491   95479.506355 1318702.15258 ]]
prediction is:
 [[-184565.97    92897.086 1363909.   ]]


real location is:
 [[-198629.317983    96367.4449538 1317742.43107  ]]
prediction is:
 [[-197584.2    97064.74 1336321.5 ]]


real location is:
 [[-199390.094928    97235.5197396 1305434.5905   ]]
prediction is:
 [[-192924.9   104197.56 1312409.1 ]]


real location is:
 [[-200145.388626   98172.841395 1273825.70245 ]]
prediction is:
 [[-194746.4   112605.27 1265778

real location is:
 [[-204810.208427  175518.259091  918508.099871]]
prediction is:
 [[-191600.03  181453.02  850741.9 ]]


real location is:
 [[-204842.15194   176749.91794   920657.673199]]
prediction is:
 [[-195968.84  175528.2   855498.4 ]]


real location is:
 [[-204857.465326  177996.925964  920869.947643]]
prediction is:
 [[-193493.42  182775.88  839632.44]]


real location is:
 [[-204883.83118   179346.915691  920067.396195]]
prediction is:
 [[-193584.34  188139.98  825374.06]]


real location is:
 [[-204917.421278  180557.476219  923064.424958]]
prediction is:
 [[-192182.52  190276.28  852270.2 ]]


real location is:
 [[-204955.402772  181758.824956  926195.304911]]
prediction is:
 [[-189770.5   188102.19  876022.3 ]]


real location is:
 [[-204986.039379  182964.843117  932408.805319]]
prediction is:
 [[-187545.3  186550.9  916697.9]]


real location is:
 [[-205057.876389  184182.325513  936142.757574]]
prediction is:
 [[-189193.83  175032.72  921274.2 ]]


real location is:
 

real location is:
 [[-206255.316747  264879.543201  902197.191178]]
prediction is:
 [[-199077.28  257199.77  871495.1 ]]


real location is:
 [[-206240.802578  266242.652894  897112.474698]]
prediction is:
 [[-200686.03  252941.22  915489.75]]


real location is:
 [[-206215.093746  267516.00845   887280.777626]]
prediction is:
 [[-201329.62  260194.28  910087.06]]


real location is:
 [[-206150.659097  268759.35882   891716.249862]]
prediction is:
 [[-198488.7   278658.66  857294.75]]


real location is:
 [[-206148.911536  270016.80521   901096.965514]]
prediction is:
 [[-194331.14  265448.97  865246.06]]


real location is:
 [[-206161.815048  271293.32394   921702.13783 ]]
prediction is:
 [[-187814.75  269413.4   856464.1 ]]


real location is:
 [[-206192.169479  272680.310336  917209.033927]]
prediction is:
 [[-199553.31  262966.62  884593.06]]


real location is:
 [[-206222.816448  274034.133098  906427.342746]]
prediction is:
 [[-194859.12  270740.56  859427.25]]


real location is

real location is:
 [[-176529.241722  335615.598776  469329.329887]]
prediction is:
 [[-166328.47  248433.97  848117.2 ]]


real location is:
 [[-175781.201943  336409.128518  468835.975744]]
prediction is:
 [[-171149.45  194388.56  976709.56]]


real location is:
 [[-175009.373538  337195.902425  467882.376448]]
prediction is:
 [[-170665.12  245576.5   825680.1 ]]


real location is:
 [[-174277.581765  337982.815379  467611.012197]]
prediction is:
 [[-179256.31  158436.69 1031041.4 ]]


real location is:
 [[-173546.756849  338749.048422  474290.998921]]
prediction is:
 [[-170267.25  165916.6  1084558.6 ]]


real location is:
 [[-172835.456071  339516.51161   478438.409186]]
prediction is:
 [[-170385.69  229172.08  866940.25]]


real location is:
 [[-172097.270628  340307.248737  477477.276463]]
prediction is:
 [[-171543.19  174057.34 1109016.  ]]


real location is:
 [[-171359.786916  341055.350456  458052.591633]]
prediction is:
 [[-178079.55  305943.72  585437.25]]


real location is

real location is:
 [[-122322.914668  390275.496461  426493.706231]]
prediction is:
 [[-125145.305  380340.5    437175.62 ]]


real location is:
 [[-121486.041642  391025.099644  418936.453336]]
prediction is:
 [[-129177.42  387805.75  431278.78]]


real location is:
 [[-120653.095235  391723.32451   412975.414014]]
prediction is:
 [[-132853.94  383604.66  429824.66]]


real location is:
 [[-119834.811016  392385.100446  411848.552295]]
prediction is:
 [[-135753.64  383160.25  427760.28]]


real location is:
 [[-118998.327961  393104.455708  411151.542101]]
prediction is:
 [[-134379.62  382552.28  425414.44]]


real location is:
 [[-118128.517841  393838.276846  410093.819528]]
prediction is:
 [[-131179.14  371399.03  438490.22]]


real location is:
 [[-117240.189125  394575.589489  408657.725219]]
prediction is:
 [[-130329.664  371228.38   455459.34 ]]


real location is:
 [[-116385.551486  395299.360464  413943.591759]]
prediction is:
 [[-134878.14  358379.28  391376.56]]


real locat

real location is:
 [[-30459.300691  407625.826987   26447.1158972]]
prediction is:
 [[-22012.018 392014.8    59620.555]]


real location is:
 [[-29082.3509919 407667.057186   22922.5222852]]
prediction is:
 [[-22819.787 389037.3    43706.152]]


real location is:
 [[-27657.2513367 407689.969894   16616.8528933]]
prediction is:
 [[-29922.277 389498.78   48556.074]]


real location is:
 [[-26283.2993477 407681.236083   10365.5743151]]
prediction is:
 [[-11150.734 405694.66   77585.77 ]]


real location is:
 [[-24886.1974671 407710.59157    10956.5132029]]
prediction is:
 [[-10760.834 404065.62   97878.04 ]]


real location is:
 [[-23555.7634608 407734.855224   10326.9553888]]
prediction is:
 [[ -7425.1387 394803.75    79264.27  ]]


real location is:
 [[-22106.6517292  407744.765119     4939.42502428]]
prediction is:
 [[ -9375.916 390053.9    46174.434]]


real location is:
 [[-20712.1371062  407763.031056     4297.74828284]]
prediction is:
 [[-21017.098 395911.25   70502.42 ]]


real lo

real location is:
 [[ 67132.9020072  408579.939215    -7081.28081675]]
prediction is:
 [[ 63352.09  378746.94   46612.316]]


real location is:
 [[ 68470.6742995  408557.537844    -6705.21631156]]
prediction is:
 [[ 66960.766 378193.25   35605.51 ]]


real location is:
 [[ 69953.6793286  408526.6769       3648.73921485]]
prediction is:
 [[ 63353.734 386713.7    97419.086]]


real location is:
 [[ 71270.5530447 408529.753938    9564.6480896]]
prediction is:
 [[ 61958.406 389486.16   89508.26 ]]


real location is:
 [[ 72524.0452052 408537.606168   10885.2189323]]
prediction is:
 [[ 65395.617 389630.06   78743.16 ]]


real location is:
 [[ 73795.7920249 408564.38769    14484.4091595]]
prediction is:
 [[ 70181.484 388772.2    97934.83 ]]


real location is:
 [[ 75151.0646563 408592.40625    18878.4226819]]
prediction is:
 [[ 73433.66 385415.88 107594.41]]


real location is:
 [[ 76436.3591213 408652.432882   23522.0726333]]
prediction is:
 [[ 74937.39 390219.2   84258.53]]


real location

real location is:
 [[ 136157.205145  376163.853111 -417204.007831]]
prediction is:
 [[ 115297.36  356864.72 -394350.97]]


real location is:
 [[ 136968.296101  375427.373036 -412428.409362]]
prediction is:
 [[ 125621.234  348237.84  -403590.16 ]]


real location is:
 [[ 137791.309343  374694.957865 -413879.889201]]
prediction is:
 [[ 112309.68  365080.56 -411550.78]]


real location is:
 [[ 138576.264986  373990.686065 -415286.024913]]
prediction is:
 [[ 116209.28  363349.62 -405864.1 ]]


real location is:
 [[ 139429.843404  373209.439029 -415348.453168]]
prediction is:
 [[ 125303.15  351797.75 -405742.34]]


real location is:
 [[ 140273.829528  372444.336642 -416111.918527]]
prediction is:
 [[ 122606.17  358784.16 -415993.3 ]]


real location is:
 [[ 141081.292803  371714.653518 -417305.02282 ]]
prediction is:
 [[ 125867.53  364608.03 -432336.8 ]]


real location is:
 [[ 141921.160033  370948.242324 -418543.641529]]
prediction is:
 [[ 124936.195  368809.06  -422241.3  ]]


real locat

real location is:
 [[ 196270.335306  316744.602672 -448193.737398]]
prediction is:
 [[ 175424.11  299981.06 -446674.44]]


real location is:
 [[ 197014.079646  315994.780832 -444944.491392]]
prediction is:
 [[ 181814.6   307907.62 -460447.38]]


real location is:
 [[ 197836.866699  315190.491006 -435894.039503]]
prediction is:
 [[  96952.266  166292.38  -109754.08 ]]


real location is:
 [[ 198637.547867  314414.844377 -437363.627193]]
prediction is:
 [[ 98837.63  131986.78  -11284.926]]


real location is:
 [[ 199433.632784  313621.050325 -460201.09925 ]]
prediction is:
 [[ 196488.5   278909.53 -364973.7 ]]


real location is:
 [[ 200143.57007   312845.153459 -484956.956308]]
prediction is:
 [[ 203697.88  286538.56 -446918.6 ]]


real location is:
 [[ 200860.552684  312001.807384 -510344.262623]]
prediction is:
 [[ 194857.36  277968.16 -496068.72]]


real location is:
 [[ 201500.182817  311153.759987 -535889.861517]]
prediction is:
 [[ 202711.53  294830.84 -498838.75]]


real location

real location is:
 [[ 204771.781413  236256.290298 -882604.048919]]
prediction is:
 [[ 194278.56  218165.3  -867064.94]]


real location is:
 [[ 204789.567007  234978.83017  -891499.076252]]
prediction is:
 [[ 193872.28  217921.81 -825095.25]]


real location is:
 [[ 204802.537752  233766.47039  -891692.841513]]
prediction is:
 [[ 196478.62  234191.34 -859752.8 ]]


real location is:
 [[ 204824.115709  232550.292041 -882019.784663]]
prediction is:
 [[ 198420.45  201396.97 -856227.5 ]]


real location is:
 [[ 204855.045021  231303.625898 -873100.144219]]
prediction is:
 [[ 197900.56  203636.28 -862548.9 ]]


real location is:
 [[ 204913.193667  230132.05215  -869191.538258]]
prediction is:
 [[ 201439.6   209645.44 -832855.7 ]]


real location is:
 [[ 204988.872529  228914.371108 -861367.870821]]
prediction is:
 [[ 196753.31  206680.38 -833796.06]]


real location is:
 [[ 205056.217884  227713.909258 -854937.407687]]
prediction is:
 [[ 199971.88  192954.64 -844516.4 ]]


real location is

real location is:
 [[ 206587.121746  150054.702459 -906093.521564]]
prediction is:
 [[ 196704.6   159927.53 -866147.2 ]]


real location is:
 [[ 206581.234851  148838.983336 -897387.21041 ]]
prediction is:
 [[ 194613.84  157925.69 -876208.3 ]]


real location is:
 [[ 206581.369585  147709.064262 -898143.7444  ]]
prediction is:
 [[ 202069.44  164876.67 -872571.56]]


real location is:
 [[ 206561.817494  146545.288506 -901580.802279]]
prediction is:
 [[ 206787.86  147120.33 -871044.2 ]]


real location is:
 [[ 206548.725135  145338.857667 -901396.243725]]
prediction is:
 [[ 203847.42  146836.08 -865563.06]]


real location is:
 [[ 206523.759943  144194.623439 -901641.720728]]
prediction is:
 [[ 206134.89  147614.56 -869101.06]]


real location is:
 [[ 206486.523215  143004.229084 -903296.733686]]
prediction is:
 [[ 204392.05  141761.34 -862928.9 ]]


real location is:
 [[ 206457.172444  141718.885118 -903995.681358]]
prediction is:
 [[ 208457.66  138995.6  -866193.4 ]]


real location is

real location is:
 [[  178726.808436     75093.7085649 -1318613.84543  ]]
prediction is:
 [[  161285.75    65535.07 -1310635.8 ]]


real location is:
 [[  177925.785475     74257.3472261 -1319325.02074  ]]
prediction is:
 [[  161576.44     65529.688 -1312224.8  ]]


real location is:
 [[  177186.156426     73468.3392017 -1319352.4669   ]]
prediction is:
 [[  166117.44    68661.25 -1303205.8 ]]


real location is:
 [[  176411.325309     72635.9653099 -1319898.27356  ]]
prediction is:
 [[  169864.77    64828.25 -1269255.  ]]


real location is:
 [[  175675.178406     71865.5753228 -1323510.57421  ]]
prediction is:
 [[  173234.53     60032.312 -1246729.6  ]]


real location is:
 [[  174935.280466    71099.660999 -1326383.03519 ]]
prediction is:
 [[  171240.08     65120.832 -1276364.2  ]]


real location is:
 [[  174106.240371     70220.3279118 -1322896.83399  ]]
prediction is:
 [[  175809.8      55149.395 -1225968.8  ]]


real location is:
 [[  173317.739933     69380.7190767 -1319766.158

real location is:
 [[  123063.546451     19626.9815848 -1369729.43146  ]]
prediction is:
 [[  112536.87      -3166.5615 -1366787.    ]]


real location is:
 [[  122221.568522     18882.9400954 -1367047.03213  ]]
prediction is:
 [[  116854.87       1544.1592 -1377075.5   ]]


real location is:
 [[  121409.938711     18118.8868616 -1349923.20144  ]]
prediction is:
 [[ 1.2158921e+05  8.0108691e+02 -1.3440566e+06]]


real location is:
 [[  120644.340401     17347.8377202 -1345200.52322  ]]
prediction is:
 [[ 1.2056835e+05  4.5144238e+02 -1.3369762e+06]]


real location is:
 [[  119772.657128     16496.6971421 -1350202.36425  ]]
prediction is:
 [[  106585.1        3163.0889 -1355761.1   ]]


real location is:
 [[  118927.53385      15657.8893271 -1351581.58061  ]]
prediction is:
 [[  106917.09       5227.8115 -1346807.6   ]]


real location is:
 [[  118105.039036    14865.287001 -1352395.49261 ]]
prediction is:
 [[  112419.47     11419.928 -1296700.9  ]]


real location is:
 [[  117260.4411

real location is:
 [[ 4.99805508e+04  7.45022823e+02 -1.79021749e+06]]
prediction is:
 [[ 4.1317070e+04 -3.9777734e+02 -1.6950119e+06]]


real location is:
 [[ 4.88999417e+04  7.44432926e+02 -1.79359373e+06]]
prediction is:
 [[   41977.594    -7671.295 -1711078.6  ]]


real location is:
 [[ 4.77770881e+04  7.32180918e+02 -1.78680768e+06]]
prediction is:
 [[   48207.715     4141.001 -1633070.5  ]]


real location is:
 [[ 4.66881772e+04  7.09103624e+02 -1.78626063e+06]]
prediction is:
 [[   53898.02       3362.2627 -1667336.1   ]]


real location is:
 [[4.55305865e+04 6.80799993e+02 1.79918042e+06]]
prediction is:
 [[   56382.867     -7017.1523 -1718095.    ]]


real location is:
 [[4.43890343e+04 6.76795669e+02 1.79622763e+06]]
prediction is:
 [[   43734.223    -3248.373 -1713813.8  ]]


real location is:
 [[ 4.32719809e+04  6.87070012e+02 -1.79967489e+06]]
prediction is:
 [[ 3.9457809e+04 -8.0688086e+02 -1.7342406e+06]]


real location is:
 [[ 4.21545052e+04  6.68004358e+02 -1.79547383

real location is:
 [[-2.88934752e+04  6.20998042e+02 -1.79170251e+06]]
prediction is:
 [[-109193.93    43050.977  590713.1  ]]


real location is:
 [[-2.99336766e+04  6.39253513e+02 -1.79278222e+06]]
prediction is:
 [[ -67882.57   31139.81 1218665.  ]]


real location is:
 [[-3.10164212e+04  6.55382863e+02 -1.79146229e+06]]
prediction is:
 [[ -83020.516   40054.836 1257525.   ]]


real location is:
 [[-3.20878791e+04  6.71133937e+02 -1.78547754e+06]]
prediction is:
 [[ -55769.883     8057.6797 1099253.6   ]]


real location is:
 [[-3.31350610e+04  6.70230584e+02 -1.78522808e+06]]
prediction is:
 [[ 19594.709  24234.137 571523.75 ]]


real location is:
 [[-3.42103701e+04  6.68577129e+02 -1.78342913e+06]]
prediction is:
 [[-31323.088  54782.92  738834.6  ]]


real location is:
 [[-3.53289772e+04  6.42672309e+02 -1.78111817e+06]]
prediction is:
 [[-43168.93 179965.9  671585.25]]


real location is:
 [[-3.63621835e+04  6.43259183e+02 -1.78213656e+06]]
prediction is:
 [[-113541.266  190937.

real location is:
 [[-107252.799463    12088.0730922 1407975.77108  ]]
prediction is:
 [[-118179.76   57483.82 1290754.8 ]]


real location is:
 [[-108372.818897    12895.9375247 1407964.2849   ]]
prediction is:
 [[-121598.375   53511.492 1293693.4  ]]


real location is:
 [[-109443.914294    13670.0933674 1409687.03242  ]]
prediction is:
 [[-133547.84   59625.32 1267932.9 ]]


real location is:
 [[-110561.844732    14477.2730468 1399356.35834  ]]
prediction is:
 [[-123145.46   37083.3  1277338.6 ]]


real location is:
 [[-111550.732751    15262.2539074 1396208.33839  ]]
prediction is:
 [[-120261.3    37109.04 1293642.6 ]]


real location is:
 [[-112604.415074    16104.2395799 1403842.89619  ]]
prediction is:
 [[-122549.3     43542.684 1274644.5  ]]


real location is:
 [[-113643.366877    16897.4745144 1411092.62108  ]]
prediction is:
 [[-121658.63   55540.11 1350847.8 ]]


real location is:
 [[-114713.303139    17698.2165405 1411337.9823   ]]
prediction is:
 [[-118820.945   49105.168

real location is:
 [[-173866.181412    70991.2113218 1367410.11798  ]]
prediction is:
 [[-161921.52   79070.21 1357961.5 ]]


real location is:
 [[-174886.546596    71933.7169374 1371872.34511  ]]
prediction is:
 [[-161018.08   83506.19 1343506.5 ]]


real location is:
 [[-175875.654833    72859.4174681 1373527.85084  ]]
prediction is:
 [[-157738.48   89692.08 1325726.1 ]]


real location is:
 [[-176895.536817    73810.5274792 1373575.19035  ]]
prediction is:
 [[-163210.61   84872.46 1350545.1 ]]


real location is:
 [[-177887.861863    74741.9460915 1369511.51183  ]]
prediction is:
 [[-162807.45    75109.055 1365230.5  ]]


real location is:
 [[-178775.849596    75592.2280757 1368764.94792  ]]
prediction is:
 [[-160014.48    74618.734 1354301.9  ]]


real location is:
 [[-179802.560507    76555.3229895 1363416.14145  ]]
prediction is:
 [[-168524.89    83914.016 1353388.8  ]]


real location is:
 [[-180723.138979    77440.7576977 1359090.8534   ]]
prediction is:
 [[-166055.78   84740.8

real location is:
 [[-204315.65393   139660.467119  917949.065529]]
prediction is:
 [[-190749.75  129824.47  919595.  ]]


real location is:
 [[-204337.767793  140721.637162  910060.86574 ]]
prediction is:
 [[-181819.14  147634.2   877532.75]]


real location is:
 [[-204341.787196  141735.162372  911149.724951]]
prediction is:
 [[-179627.97  150490.16  877619.94]]


real location is:
 [[-204352.892136  142863.109604  909330.569396]]
prediction is:
 [[-185237.34  143610.56  896489.3 ]]


real location is:
 [[-204373.680454  143925.092281  909175.723438]]
prediction is:
 [[-178790.8   143049.95  893050.25]]


real location is:
 [[-204400.561033  145016.941281  909909.248144]]
prediction is:
 [[-183062.    156786.45  894901.06]]


real location is:
 [[-204415.650566  146094.458153  907351.527513]]
prediction is:
 [[-175429.69  147623.84  887722.6 ]]


real location is:
 [[-204401.831568  147190.113689  902533.752145]]
prediction is:
 [[-182758.56  159213.31  881395.4 ]]


real location is

real location is:
 [[-205010.611378  215295.485836  920284.446064]]
prediction is:
 [[-185049.42  226282.86  794341.25]]


real location is:
 [[-205048.929817  216406.196436  918614.166829]]
prediction is:
 [[-194315.8   221739.95  881650.1 ]]


real location is:
 [[-205090.070291  217488.830197  922586.553122]]
prediction is:
 [[-186150.36  234120.28  819268.4 ]]


real location is:
 [[-205145.451911  218564.217353  929716.701132]]
prediction is:
 [[-109771.85  284324.47  380486.62]]


real location is:
 [[-205226.53809   219640.193561  930716.224062]]
prediction is:
 [[-55445.625 281785.06  205533.53 ]]


real location is:
 [[-205291.521439  220719.401244  931688.05852 ]]
prediction is:
 [[-186874.8   237277.52  821765.5 ]]


real location is:
 [[-205343.337035  221778.540605  927912.766819]]
prediction is:
 [[-187271.81  260815.    701032.94]]


real location is:
 [[-205386.847172  222832.531185  920204.296561]]
prediction is:
 [[-191255.42  240055.86  761355.4 ]]


real location is

real location is:
 [[-205316.037113  290560.072769  908878.369465]]
prediction is:
 [[-178695.69  189425.6  1060550.1 ]]


real location is:
 [[-205346.497291  291737.819591  916549.728987]]
prediction is:
 [[-186397.31  200591.62 1103170.9 ]]


real location is:
 [[-205388.754302  292848.962421  917443.712316]]
prediction is:
 [[-179686.19  168439.97 1206078.8 ]]


real location is:
 [[-205441.605421  293948.399778  917535.23684 ]]
prediction is:
 [[-191187.14  236071.1   960782.3 ]]


real location is:
 [[-205477.716747  295115.404362  916787.001504]]
prediction is:
 [[-187696.5   231308.56 1018790.  ]]


real location is:
 [[-205509.891515  296211.634232  914157.081615]]
prediction is:
 [[-190347.94  225356.9  1019773.  ]]


real location is:
 [[-205543.461105  297338.089243  906250.031816]]
prediction is:
 [[ 65594.6   311695.7    24994.969]]


real location is:
 [[-205536.153213  298421.241712  881370.153214]]
prediction is:
 [[ 130216.53  322125.34 -159640.25]]


real location is

real location is:
 [[-150675.113725  361632.033395  471967.602093]]
prediction is:
 [[-163200.94  347976.3   454622.28]]


real location is:
 [[-149791.55273   362547.1504    466257.218712]]
prediction is:
 [[-163016.05  366589.4   426573.22]]


real location is:
 [[-148850.829997  363518.736468  464849.155467]]
prediction is:
 [[-159706.03  370886.38  444490.16]]


real location is:
 [[-147978.133772  364450.858885  464872.667472]]
prediction is:
 [[-157459.17  372677.62  440012.75]]


real location is:
 [[-147090.813549  365369.047715  472383.29874 ]]
prediction is:
 [[-149845.4   360677.53  403221.  ]]


real location is:
 [[-146179.328463  366301.39325   466569.079855]]
prediction is:
 [[-154552.1   377210.97  441687.03]]


real location is:
 [[-145296.995946  367187.729768  465314.795516]]
prediction is:
 [[-155668.1   370047.3   443117.38]]


real location is:
 [[-144420.021393  368099.260337  465358.947463]]
prediction is:
 [[-139189.5   366917.97  427749.56]]


real location is

real location is:
 [[-76541.7797295 409562.643858   40988.8500398]]
prediction is:
 [[-155627.45  182510.03  641825.25]]


real location is:
 [[-75474.6813986 409630.627947   39903.38559  ]]
prediction is:
 [[-159544.73  193724.94  609671.6 ]]


real location is:
 [[-74317.2731092 409699.726368   38099.5079382]]
prediction is:
 [[-157644.48  202526.73  601493.8 ]]


real location is:
 [[-73193.6886386 409769.602102   29538.6846045]]
prediction is:
 [[-134607.78  229322.61  402598.06]]


real location is:
 [[-72155.2458389 409805.503714   23291.549936 ]]
prediction is:
 [[-129617.914  338083.44   255251.2  ]]


real location is:
 [[-71020.4651956 409842.571154   22249.9692287]]
prediction is:
 [[-125141.5   330480.    276345.03]]


real location is:
 [[-69936.8972983 409871.901      16269.3479632]]
prediction is:
 [[-95785.445 366657.16  195949.03 ]]


real location is:
 [[-68840.741056 409874.075656  10318.722939]]
prediction is:
 [[-84314.45 363358.8  206516.11]]


real location is:
 

real location is:
 [[  1862.20789578 408651.151203    23486.4245789 ]]
prediction is:
 [[  6602.6836 391237.66    68200.42  ]]


real location is:
 [[  2975.38692027 408689.556967    45876.3717459 ]]
prediction is:
 [[ 11221.414 386481.3    76551.29 ]]


real location is:
 [[  4085.61161928 408782.925948    52185.9846986 ]]
prediction is:
 [[-11492.412 385186.88   73227.58 ]]


real location is:
 [[  5198.75411146 408863.295889    48299.6077699 ]]
prediction is:
 [[ 10005.858 389701.8    97855.54 ]]


real location is:
 [[  6294.26341192 408903.9708      42424.6264595 ]]
prediction is:
 [[ -3336.873 388789.7   108786.336]]


real location is:
 [[  7387.21971889 408946.442739    39382.9396015 ]]
prediction is:
 [[  7692.703 388914.34   73690.734]]


real location is:
 [[  8442.23355316 408976.712134    32725.560332  ]]
prediction is:
 [[ 32480.18 382723.7   82397.43]]


real location is:
 [[  9532.01182776 409026.943234    47150.2498497 ]]
prediction is:
 [[  8195.841 375253.94  140566.

real location is:
 [[ 80624.5490949 409037.457522   20492.5752664]]
prediction is:
 [[ 73439.47 388605.47 106454.03]]


real location is:
 [[ 81735.6495454 409063.972155   19920.0579578]]
prediction is:
 [[ 75782.28  393422.2   102732.836]]


real location is:
 [[ 82810.570555  409080.336348   12516.8298679]]
prediction is:
 [[ 71497.69 393173.25 116040.27]]


real location is:
 [[ 83895.8160363  409094.134082     9735.68426707]]
prediction is:
 [[ 71402.28 390942.2  121920.83]]


real location is:
 [[ 84995.9518906  409112.133376     9603.99998831]]
prediction is:
 [[ 70485.8  389915.38 126972.59]]


real location is:
 [[ 86080.4850078  409105.457551     9774.92741031]]
prediction is:
 [[ 70664.68 392909.7  121612.8 ]]


real location is:
 [[ 87145.7221315  409125.585732     9352.44004213]]
prediction is:
 [[ 75020.21 391264.38 127966.06]]


real location is:
 [[ 88236.1019797  409131.286566     9018.46359033]]
prediction is:
 [[ 85616.53 380570.72 135519.98]]


real location is:
 [[ 

real location is:
 [[ 144588.846566  368301.294348 -427704.067265]]
prediction is:
 [[ 123792.89  380136.06 -401192.78]]


real location is:
 [[ 145351.031558  367569.439225 -428327.740441]]
prediction is:
 [[ 130117.1   369643.12 -433925.47]]


real location is:
 [[ 146202.029447  366756.767056 -432714.532495]]
prediction is:
 [[ 129483.93  360822.16 -432458.2 ]]


real location is:
 [[ 147023.430035  365962.032696 -432350.564556]]
prediction is:
 [[ 127178.58  372147.1  -404091.4 ]]


real location is:
 [[ 147879.790737  365147.686044 -433279.607867]]
prediction is:
 [[ 134527.22  358341.56 -442130.25]]


real location is:
 [[ 148710.104167  364319.637795 -434943.745362]]
prediction is:
 [[ 137459.92  360974.75 -442024.62]]


real location is:
 [[ 149469.145579  363568.265592 -434990.494543]]
prediction is:
 [[ 137443.69  354199.5  -433407.22]]


real location is:
 [[ 150251.758536  362816.017068 -435418.313052]]
prediction is:
 [[ 138323.56  366307.72 -428533.53]]


real location is

real location is:
 [[ 201426.489256  311239.034545 -540393.946235]]
prediction is:
 [[ 203767.64  301060.66 -530708.5 ]]


real location is:
 [[ 202081.852701  310255.20057  -588630.002922]]
prediction is:
 [[ 199226.31  296947.75 -591050.75]]


real location is:
 [[ 202670.828372  309152.786355 -649789.42726 ]]
prediction is:
 [[ 186679.33  311358.4  -601934.9 ]]


real location is:
 [[ 203185.465374  307825.633293 -728796.040477]]
prediction is:
 [[ 195620.05  296899.88 -745574.94]]


real location is:
 [[ 203499.734917  306519.696844 -793966.314149]]
prediction is:
 [[ 201289.23  263252.56 -812525.25]]


real location is:
 [[ 203678.209925  305213.008187 -841998.539988]]
prediction is:
 [[ 201289.67  256504.97 -850327.3 ]]


real location is:
 [[ 203765.601512  303955.279885 -872939.339408]]
prediction is:
 [[ 198090.06  301157.28 -840080.1 ]]


real location is:
 [[ 203782.977744  302802.7051   -899931.278234]]
prediction is:
 [[ 196661.17  295482.03 -907000.1 ]]


real location is

real location is:
 [[ 205075.845349  226533.045673 -840789.736203]]
prediction is:
 [[ 202367.16  198915.84 -837248.6 ]]


real location is:
 [[ 205178.089559  225249.123853 -839133.997064]]
prediction is:
 [[ 197735.31  211278.   -825576.9 ]]


real location is:
 [[ 205309.962926  223923.708378 -841472.927955]]
prediction is:
 [[ 197927.16  209877.77 -842623.1 ]]


real location is:
 [[ 205392.605753  222725.134897 -851742.239638]]
prediction is:
 [[ 197426.19  203913.55 -815788.44]]


real location is:
 [[ 205469.869419  221412.418853 -873643.194249]]
prediction is:
 [[ 196657.4   204653.55 -851789.9 ]]


real location is:
 [[ 205468.228774  220220.347599 -900059.011819]]
prediction is:
 [[ 194026.28  225912.42 -850099.06]]


real location is:
 [[ 205434.168142  219016.066122 -903307.726823]]
prediction is:
 [[ 198847.88  191566.66 -851568.9 ]]


real location is:
 [[ 205408.524203  217860.216064 -904698.090322]]
prediction is:
 [[ 197459.67  221161.55 -881420.44]]


real location is

real location is:
 [[ 206570.562686  137238.39067  -893334.251932]]
prediction is:
 [[ 199703.81  147507.75 -867308.56]]


real location is:
 [[ 206592.140156  135902.473927 -886346.296906]]
prediction is:
 [[ 191293.97  143404.86 -867916.9 ]]


real location is:
 [[ 206599.790949  134647.456497 -889587.533251]]
prediction is:
 [[ 199377.1   140610.69 -855513.2 ]]


real location is:
 [[ 206620.948312  133411.434966 -886370.291813]]
prediction is:
 [[ 203866.62  141564.4  -861284.5 ]]


real location is:
 [[ 206614.548004  132176.457343 -891987.535054]]
prediction is:
 [[ 202502.98  141346.52 -845936.4 ]]


real location is:
 [[ 206615.169789  130904.378674 -893771.721586]]
prediction is:
 [[ 198113.31  143191.86 -856725.6 ]]


real location is:
 [[ 206618.005517  129688.631046 -898812.868466]]
prediction is:
 [[ 204917.78  124069.85 -856737.5 ]]


real location is:
 [[ 206620.668024  128347.446932 -901114.33936 ]]
prediction is:
 [[ 202654.31  131145.47 -848742.4 ]]


real location is