In [1]:
import os
import random
import skimage.data
from skimage import io
import skimage.transform as skt
import numpy as np
import tensorflow as tf
from tqdm import tqdm
import sys
sys.path.remove('/opt/ros/kinetic/lib/python2.7/dist-packages')
import cv2

In [2]:
# submap_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhaun_448_test_with_no_barrier1/submap"
# pic_dir = "/home/ysk/catkin_ws/laser_pic_code/pic/regression_benhaun_448_test_with_no_barrier1/picture"

# # for i in range(4):
# i = 1
# submap1 = cv2.imread(os.path.join(submap_dir,str(1189) + '.pgm'))
# submap1 = cv2.resize(submap1,(448,448))
# submap1 = cv2.transpose(submap1)
# submap1 = cv2.flip(submap1, 1)
# # submap1 = np.rot90(submap1)
# cv2.imshow("submap",submap1)


# pic1 = cv2.imread(os.path.join(pic_dir, '01189.jpg'))
# cv2.imshow("pic",pic1)

# cv2.waitKey(0)
# cv2.destroyAllWindows()
# print(np.shape(submap1))

In [3]:
# train_label_dir = "/home/ysk/database/new_test_dateset/benhuan_test"
# train_pic_dir = "/home/ysk/database/new_test_dateset/benhuan_test/picture"
# train_submap_dir = "/home/ysk/database/new_test_dateset/benhuan_test/submap"

train_label_dir = "/home/ysk/database/new_train_dateset/new_benhuan_train"
train_pic_dir = "/home/ysk/database/new_train_dateset/new_benhuan_train/picture"
train_submap_dir = "/home/ysk/database/new_train_dateset/new_benhuan_train/submap"

train_txt = os.path.join(train_label_dir,"label.txt")
count = len(open(train_txt,'r').readlines()) - 1
file = open(train_txt,'r')
s = file.readlines()

def get_train_data_batch(i, pic_dir=train_pic_dir, label_dir=train_label_dir,submap_dir=train_submap_dir):
    labels = []
    images = []
    
    image1 = skimage.data.imread(os.path.join(pic_dir, s[i].split(";")[0]))
    submap1 = cv2.imread(os.path.join(submap_dir,str(i) + '.pgm'))
    submap1 = cv2.resize(submap1,(448,448))
    submap1 = cv2.transpose(submap1)
    submap1 = cv2.flip(submap1, 1)
    
#     image2 = skimage.data.imread(os.path.join(pic_dir, s[i+1].split(";")[0]))
#     submap2 = cv2.imread(os.path.join(submap_dir,str(i+1) + '.pgm'))
#     submap2 = cv2.resize(submap2,(448,448))
#     submap2 = cv2.transpose(submap2)
#     submap2 = cv2.flip(submap2, 1)
    
    
#     img = cv2.merge([image1,submap1,image2,submap2])
    img = cv2.merge([image1,submap1])
    images.append(img)
    
    label = s[i].split(";")[1:]
    label = list(map(float,label))
    labels.append(label)
    
    return np.asarray(images),np.asarray(labels)
    
num = 0
train_images, train_labels = get_train_data_batch(num)
print(np.shape(train_images))
print(np.shape(train_labels))
print(train_labels)

(1, 448, 448, 6)
(1, 3)
[[ 6.28203890e-02 -2.89475932e-02 -1.73297033e+02]]


In [4]:
with tf.name_scope("input"):
    input_image = tf.placeholder("float", [None, 448,448,6],name='input_image')/255.*2.-1
    y_ = tf.placeholder("float", [None, 3],name='y_') 

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape = shape)
    return tf.Variable(initial)

def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding="SAME")

def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding="SAME")

#第0层卷积
with tf.name_scope("conv_0"):
    W_conv0 = weight_variable([7, 7, 6, 64])
    b_conv0 = bias_variable([64])
    conv_layer0 = tf.nn.conv2d(input_image, W_conv0, strides=[1,1,1,1], padding="SAME") + b_conv0
#     conv_layer_nor0 = tf.layers.batch_normalization(conv_layer0,training=True)
    
    h_conv0 = tf.nn.leaky_relu(conv_layer0)
with tf.name_scope("max_pool_0"):
    h_pool0 = max_pool_2x2(h_conv0)   #输出变成224*224*64 [None,224,224,64]

# #第一层卷积层
# #参数的前两维为卷积核的维度，第三个参数为当前层的深度，第四个为输出到层的深度
with tf.name_scope("conv_1"):
    W_conv1 = weight_variable([5, 5, 64, 128])
    b_conv1 = bias_variable([128])
    conv_layer1 = conv2d(h_pool0, W_conv1) + b_conv1
#     conv_layer_nor1 = tf.layers.batch_normalization(conv_layer1,training=True)

    h_conv1 = tf.nn.leaky_relu(conv_layer1)
with tf.name_scope("max_pool1"):
    h_pool1 = max_pool_2x2(h_conv1)   #输出变成112*112*64   [None,112,112,64]

#第二层卷积层
with tf.name_scope("conv_2"):
    W_conv2 = weight_variable([5, 5, 128, 192])
    b_conv2 = bias_variable([192])
    conv_layer2 = conv2d(h_pool1, W_conv2) + b_conv2
#     conv_layer_nor2 = tf.layers.batch_normalization(conv_layer2,training=True)

    h_conv2 = tf.nn.leaky_relu(conv_layer2)
with tf.name_scope("max_pool_2"):
    h_pool2 = max_pool_2x2(h_conv2)  #输出变为56*56*192


#第三层卷积层
with tf.name_scope("conv_3"):
    W_conv3 = weight_variable([3, 3, 192, 128])
    b_conv3 = bias_variable([128])
    conv_layer3 = conv2d(h_pool2, W_conv3) + b_conv3
#     conv_layer_nor3 = tf.layers.batch_normalization(conv_layer3,training=True)
    
    h_conv3 = tf.nn.leaky_relu(conv_layer3)
with tf.name_scope("max_pool_3"):
    h_pool3 = max_pool_2x2(h_conv3)   #输出为28*28*128


#第四层卷积层
with tf.name_scope("conv_4"):
    W_conv4 = weight_variable([3, 3, 128, 64])
    b_conv4 = bias_variable([64])
    conv_layer4 = conv2d(h_pool3, W_conv4) + b_conv4
#     conv_layer_nor4 = tf.layers.batch_normalization(conv_layer4,training=True)

    h_conv4 = tf.nn.leaky_relu(conv_layer4)
with tf.name_scope("max_pool_4"):
    h_pool4 = max_pool_2x2(h_conv4)   #输出变为14*14*64


keep_prob = tf.placeholder("float")

#密集连接层0
with tf.name_scope("fc0"):
    W_fc0 = weight_variable([14*14*64, 2048])
    b_fc0 = bias_variable([2048])

    h_pool4_flat = tf.reshape(h_pool4, [-1, 14*14*64])
    
    out_fc0 = tf.matmul(h_pool4_flat, W_fc0) + b_fc0
#     out_nor_fc0 = tf.layers.batch_normalization(out_fc0,training=True)
    
    h_fc0 = tf.nn.leaky_relu(out_fc0)   #输出为96*2048

    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop0 = tf.nn.dropout(h_fc0, keep_prob)   #输出为96*2048

#密集连接层1
with tf.name_scope("fc1"):
    W_fc1 = weight_variable([2048, 1024])
    b_fc1 = bias_variable([1024])
    
    out_fc1 = tf.matmul(h_fc1_drop0, W_fc1) + b_fc1
#     out_nor_fc1 = tf.layers.batch_normalization(out_fc1,training=True)

    h_fc1 = tf.nn.leaky_relu(out_fc1)   #输出为2048*1024

    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop1 = tf.nn.dropout(h_fc1, keep_prob)   #输出为2048*1024

#密集连接层2
with tf.name_scope("fc2"):
    W_fc2 = weight_variable([1024, 512])
    b_fc2 = bias_variable([512])
    
    out_fc2 = tf.matmul(h_fc1_drop1, W_fc2) + b_fc2
#     out_nor_fc2 = tf.layers.batch_normalization(out_fc2,training=True)

    h_fc2 = tf.nn.leaky_relu(out_fc2)
    #relu函数作用是求出max(h_fc1,0)
    h_fc1_drop2 = tf.nn.dropout(h_fc2, keep_prob)
    

#输出层
with tf.name_scope("out_layer"):
    W_fc3 = weight_variable([512, 3])
    y_conv = tf.matmul(h_fc1_drop2, W_fc3)

checkpointsPath = "/home/ysk/database/new_train_dateset/new_benhuan_train/l2_nor_4803_6in_3out_checkpoints/"

path = "/home/ysk/database/"
test_result_path = os.path.join(path,'final_test_result','train_l2_nor_4803_6in_3out_test_result.txt')

if os.path.exists(test_result_path):
    os.remove(test_result_path)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    saver = tf.train.Saver()
    checkPoint = tf.train.get_checkpoint_state(checkpointsPath)
    if checkPoint and checkPoint.model_checkpoint_path:
        saver.restore(sess,checkPoint.model_checkpoint_path)
        print("restored %s" % checkPoint.model_checkpoint_path)
        
    else:
        print("no checkpoint found!")
        
    for i in range(count-2):
        batch_x,batch_y = get_train_data_batch(i)
        batch_y = batch_y*10000
        
        y_pre = sess.run(y_conv,feed_dict={input_image:batch_x, y_:batch_y,keep_prob:1.0})
        
#         print(batch_y[0][2:])
#         print(y_pre[0][2:])
        
        with open(test_result_path,'a') as f:
            for i in range(3):
                f.write(str(batch_y[0][i]) + ',')
            for i in range(2):
                f.write(str(y_pre[0][i]) + ',')
            f.write(str(y_pre[0][2]) + '\n')

        print("real location is:\n",batch_y)
        print("prediction is:\n",y_pre)
        print("\n")
    print("done!")


INFO:tensorflow:Restoring parameters from /home/ysk/database/new_train_dateset/new_benhuan_train/l2_nor_4803_6in_3out_checkpoints/saved_net.ckpt-199000
restored /home/ysk/database/new_train_dateset/new_benhuan_train/l2_nor_4803_6in_3out_checkpoints/saved_net.ckpt-199000
real location is:
 [[ 6.28203890e+02 -2.89475932e+02 -1.73297033e+06]]
prediction is:
 [[ 4.2335693e+02 -7.8721149e+02 -1.6990166e+06]]


real location is:
 [[-4.04042674e+02 -3.38605794e+02 -1.77859856e+06]]
prediction is:
 [[ 2.5238171e+02 -1.5765383e+03 -1.7777989e+06]]


real location is:
 [[-1.44962029e+03 -3.49789385e+02 -1.79931312e+06]]
prediction is:
 [[    2767.5107     2768.5203 -1781067.9   ]]


real location is:
 [[-2.50802167e+03 -3.41654550e+02  1.79723024e+06]]
prediction is:
 [[-5.2464180e+03  1.0406023e+03  1.7378605e+06]]


real location is:
 [[-3.55557483e+03 -3.08319886e+02  1.79731864e+06]]
prediction is:
 [[  -5962.4707   -2726.903  1725156.    ]]


real location is:
 [[-4.66533527e+03 -2.97051979

real location is:
 [[ -66537.1677844     2857.78174205 1785988.93057   ]]
prediction is:
 [[ -69047.75     3239.445 1774076.5  ]]


real location is:
 [[ -67617.5865249     2907.18382378 1786592.8647    ]]
prediction is:
 [[-6.5920719e+04  1.4303345e+03  1.7535476e+06]]


real location is:
 [[ -68702.4334219     2930.25605346 1792072.82979   ]]
prediction is:
 [[ -72437.27      4012.3274 1764673.9   ]]


real location is:
 [[ -69794.0705707     2959.01277348 1790263.63711   ]]
prediction is:
 [[-6.4303523e+04 -1.7250425e+03  1.7651524e+06]]


real location is:
 [[ -70844.3456704     2985.34578523 1788187.06558   ]]
prediction is:
 [[ -70034.86      2135.2173 1751258.1   ]]


real location is:
 [[ -71927.5003387    3029.5903215 1786985.17279  ]]
prediction is:
 [[ -74402.836     3562.7107 1741772.4   ]]


real location is:
 [[ -72995.580072      3062.83413318 1783754.59049   ]]
prediction is:
 [[ -71747.5      -1805.9707 1759490.5   ]]


real location is:
 [[ -74068.9273859     3105.006

real location is:
 [[-130203.774278    31077.7823737 1389590.30236  ]]
prediction is:
 [[-130350.1     32018.256 1368188.5  ]]


real location is:
 [[-131174.393264   31932.159146 1389254.35609 ]]
prediction is:
 [[-127076.      30816.748 1350149.   ]]


real location is:
 [[-132107.784882    32761.5758994 1394588.31277  ]]
prediction is:
 [[-134971.03    28843.773 1381624.8  ]]


real location is:
 [[-133068.512411    33607.1848467 1394547.04406  ]]
prediction is:
 [[-131769.45    29218.842 1384410.4  ]]


real location is:
 [[-134061.651237    34460.8256102 1399773.07676  ]]
prediction is:
 [[-131661.92    30447.566 1371914.9  ]]


real location is:
 [[-135036.938251    35317.4924927 1394520.75024  ]]
prediction is:
 [[-135793.1     34860.598 1369247.4  ]]


real location is:
 [[-136006.511673    36156.3707172 1394087.73297  ]]
prediction is:
 [[-130912.555   31114.09  1379810.   ]]


real location is:
 [[-136993.048553    37008.6345269 1393449.88706  ]]
prediction is:
 [[-130972.15 

real location is:
 [[-195931.262958    93609.7353652 1325004.07599  ]]
prediction is:
 [[-191081.03   82702.26 1301004.6 ]]


real location is:
 [[-196840.541857    94608.9363568 1334010.71682  ]]
prediction is:
 [[-197620.61   81645.45 1309060.5 ]]


real location is:
 [[-197736.782661    95535.5311556 1342463.16113  ]]
prediction is:
 [[-189361.16   78709.43 1307552.6 ]]


real location is:
 [[-198565.243814    96430.2814942 1335448.32521  ]]
prediction is:
 [[-197495.     92274.45 1276372.2 ]]


real location is:
 [[-199420.318403    97397.0396682 1319930.10299  ]]
prediction is:
 [[-198934.69   84331.02 1277568.6 ]]


real location is:
 [[-200240.634257    98392.4923971 1300842.15812  ]]
prediction is:
 [[-197025.75    92382.414 1258159.2  ]]


real location is:
 [[-201075.767591    99529.3185949 1251010.04966  ]]
prediction is:
 [[-199568.14    96979.086 1204772.   ]]


real location is:
 [[-201810.959201  100729.310545 1195976.82988 ]]
prediction is:
 [[-199900.22   94638.95 1164

real location is:
 [[-204695.913255  167561.827479  932792.761822]]
prediction is:
 [[-202617.58  164700.11  908703.5 ]]


real location is:
 [[-204732.702062  168610.702766  931039.574944]]
prediction is:
 [[-206050.6   165267.08  912489.5 ]]


real location is:
 [[-204781.569752  169698.002154  930566.345714]]
prediction is:
 [[-199067.44  163184.56  904225.7 ]]


real location is:
 [[-204808.303574  170795.78216   929934.118652]]
prediction is:
 [[-205291.88  165355.11  913281.25]]


real location is:
 [[-204835.054447  171907.007926  924352.659976]]
prediction is:
 [[-203187.6   166591.66  900261.3 ]]


real location is:
 [[-204860.073608  173025.17716   922991.818248]]
prediction is:
 [[-204192.33  168682.56  886880.8 ]]


real location is:
 [[-204886.212564  174113.552305  922614.107829]]
prediction is:
 [[-205541.67  172424.84  900292.25]]


real location is:
 [[-204914.998146  175196.803693  923069.384573]]
prediction is:
 [[-205990.08  175756.92  891772.  ]]


real location is

real location is:
 [[-206487.648478  246197.606528  906033.075199]]
prediction is:
 [[-201931.7   247672.58  892268.4 ]]


real location is:
 [[-206480.168076  247330.186981  900303.485763]]
prediction is:
 [[-203582.42  240866.38  877535.75]]


real location is:
 [[-206461.926014  248454.22359   899815.348834]]
prediction is:
 [[-204376.03  244195.55  881857.06]]


real location is:
 [[-206444.163489  249492.527195  904701.913382]]
prediction is:
 [[-207948.08  249241.92  895583.6 ]]


real location is:
 [[-206432.886932  250612.31058   900283.544792]]
prediction is:
 [[-206094.28  241511.33  883799.75]]


real location is:
 [[-206415.862743  251707.264596  895176.389934]]
prediction is:
 [[-199681.92  239503.06  877938.9 ]]


real location is:
 [[-206390.491398  252813.259233  892223.920588]]
prediction is:
 [[-201819.81  241869.06  875877.06]]


real location is:
 [[-206332.312077  253879.665662  876110.893797]]
prediction is:
 [[-201916.    241428.86  849230.8 ]]


real location is

real location is:
 [[-191427.47806   320651.105569  449098.603417]]
prediction is:
 [[-186635.05  316447.38  444467.62]]


real location is:
 [[-190556.073082  321475.67774   448148.113806]]
prediction is:
 [[-186881.4   322994.62  445676.9 ]]


real location is:
 [[-189719.856657  322269.19617   450878.636829]]
prediction is:
 [[-184309.48  317167.34  441371.34]]


real location is:
 [[-188876.881793  323082.285194  453119.055086]]
prediction is:
 [[-183828.98  319448.3   439192.47]]


real location is:
 [[-188066.923198  323879.324198  456772.566627]]
prediction is:
 [[-184091.69  313734.03  442670.2 ]]


real location is:
 [[-187282.88142   324662.258063  461237.261706]]
prediction is:
 [[-180795.98  306822.22  458165.56]]


real location is:
 [[-186542.545439  325408.856231  460848.196631]]
prediction is:
 [[-181854.72  311714.53  460080.75]]


real location is:
 [[-185737.269735  326248.831969  460818.74009 ]]
prediction is:
 [[-181013.95  321912.8   449441.38]]


real location is

real location is:
 [[-134744.223549  377732.615679  455181.288815]]
prediction is:
 [[-132038.38  373609.06  442396.6 ]]


real location is:
 [[-133986.108729  378508.657198  458918.985606]]
prediction is:
 [[-132184.52  368907.28  444800.97]]


real location is:
 [[-133167.539615  379317.627887  458479.974084]]
prediction is:
 [[-134229.73  370912.53  441443.  ]]


real location is:
 [[-132426.860163  380090.905879  461296.27658 ]]
prediction is:
 [[-130845.88  372286.88  440008.94]]


real location is:
 [[-131652.349081  380890.86714   464095.306316]]
prediction is:
 [[-131147.7   373109.2   440937.84]]


real location is:
 [[-130857.306485  381725.642074  463564.84136 ]]
prediction is:
 [[-132336.84  375258.    446181.72]]


real location is:
 [[-130041.79197   382552.101469  447516.534252]]
prediction is:
 [[-128102.336  376654.66   432163.56 ]]


real location is:
 [[-129239.931289  383335.264362  442086.117325]]
prediction is:
 [[-127099.46  378374.12  425005.  ]]


real location

real location is:
 [[-66199.4053545 408027.652096   15946.802014 ]]
prediction is:
 [[-64849.418 394164.3    15692.272]]


real location is:
 [[-65018.7064289 408057.457234   11715.1558432]]
prediction is:
 [[-61826.805 403997.5    10660.307]]


real location is:
 [[-63782.9776881  408064.801375     9761.29878234]]
prediction is:
 [[-63704.645 396241.8     6349.27 ]]


real location is:
 [[-62549.5522756  408075.169954     8268.58220616]]
prediction is:
 [[-59575.848  402602.2      6035.4336]]


real location is:
 [[-61404.5939996 408082.424249   15267.0824582]]
prediction is:
 [[-57744.45  390656.94   11930.012]]


real location is:
 [[-60127.3635574 408113.818675   35050.4026262]]
prediction is:
 [[-57380.3   400747.22   27501.309]]


real location is:
 [[-58873.0876571 408178.136534   43972.0138117]]
prediction is:
 [[-55067.48  403324.2    36577.742]]


real location is:
 [[-57571.588281  408255.943409   41781.4407173]]
prediction is:
 [[-57798.13 396003.8   31023.35]]


real locat

real location is:
 [[ 24072.5192211  409116.718847    -5284.75225605]]
prediction is:
 [[ 24818.793   395783.22      -591.93164]]


real location is:
 [[ 25392.4494359 409066.119044   -3935.258547 ]]
prediction is:
 [[ 26453.254 397147.72   -1167.544]]


real location is:
 [[ 26667.2487541  409005.365205     3425.89193827]]
prediction is:
 [[ 29761.37   395971.47     2657.7825]]


real location is:
 [[ 27932.5383243  408990.757082    -1953.01372776]]
prediction is:
 [[ 30296.705  393020.1      1327.3594]]


real location is:
 [[ 29208.5874436  408951.301435     2931.86069434]]
prediction is:
 [[ 33015.953  402519.53    -1400.5283]]


real location is:
 [[ 30545.2045248  408929.954048     2549.50293457]]
prediction is:
 [[ 33200.41   405199.78     1422.0542]]


real location is:
 [[ 31882.8627579 408903.354159    1389.8844705]]
prediction is:
 [[ 32856.68   404739.25     1197.7456]]


real location is:
 [[ 33209.6439831  408852.341502     3136.63379989]]
prediction is:
 [[ 37488.53  401

real location is:
 [[ 107136.220455  402243.059129 -395782.639586]]
prediction is:
 [[ 109580.96  389698.25 -371623.28]]


real location is:
 [[ 107934.400025  401534.781773 -399190.433957]]
prediction is:
 [[ 108488.59  395716.88 -376964.03]]


real location is:
 [[ 108712.053594  400869.829414 -399807.576331]]
prediction is:
 [[ 109880.84  394138.28 -381548.38]]


real location is:
 [[ 109469.447274  400205.770507 -395197.003762]]
prediction is:
 [[ 109546.27  394251.66 -377775.72]]


real location is:
 [[ 110301.261477  399536.598096 -385698.313867]]
prediction is:
 [[ 114023.16  390438.78 -378865.25]]


real location is:
 [[ 111134.793435  398871.982836 -377541.444478]]
prediction is:
 [[ 112538.73  389990.16 -363731.7 ]]


real location is:
 [[ 111966.866243  398234.461142 -370242.986172]]
prediction is:
 [[ 110459.766  387975.38  -359467.1  ]]


real location is:
 [[ 112801.069543  397604.583299 -365736.39714 ]]
prediction is:
 [[ 110081.34  383985.9  -355696.2 ]]


real location

real location is:
 [[ 161765.11509   351143.523502 -444137.611501]]
prediction is:
 [[ 156201.52  330975.53 -422994.8 ]]


real location is:
 [[ 162568.668975  350359.989073 -434397.981591]]
prediction is:
 [[ 156770.66  338762.78 -422224.88]]


real location is:
 [[ 163339.340012  349629.506806 -426902.793562]]
prediction is:
 [[ 156965.14  341639.66 -411147.1 ]]


real location is:
 [[ 164078.684713  348909.896118 -419767.863477]]
prediction is:
 [[ 159353.67  340241.44 -407738.78]]


real location is:
 [[ 164845.117231  348221.784739 -417236.768903]]
prediction is:
 [[ 159658.39  339838.1  -397800.78]]


real location is:
 [[ 165652.038233  347469.718899 -417499.870998]]
prediction is:
 [[ 162120.25  335968.47 -408784.9 ]]


real location is:
 [[ 166445.728978  346743.830296 -421622.050492]]
prediction is:
 [[ 160941.3   334459.22 -405700.25]]


real location is:
 [[ 167244.503405  346016.089145 -428191.270358]]
prediction is:
 [[ 163790.4   337790.72 -405775.28]]


real location is

real location is:
 [[ 203877.272744  284061.62324  -879485.198074]]
prediction is:
 [[ 206345.8  281751.3 -873578. ]]


real location is:
 [[ 203885.947171  282536.180656 -898586.116814]]
prediction is:
 [[ 196194.02  271601.4  -879856.94]]


real location is:
 [[ 203890.481367  281099.049699 -895168.107782]]
prediction is:
 [[ 205224.22  271153.2  -871250.06]]


real location is:
 [[ 203873.584852  279628.695574 -905958.675108]]
prediction is:
 [[ 202008.5   270897.56 -886002.9 ]]


real location is:
 [[ 203842.860255  278194.840575 -907181.574744]]
prediction is:
 [[ 205711.42  271103.84 -887113.25]]


real location is:
 [[ 203827.575737  276757.378742 -901174.769299]]
prediction is:
 [[ 198895.4   271361.97 -878768.56]]


real location is:
 [[ 203829.471277  275302.180331 -890571.71965 ]]
prediction is:
 [[ 196469.5   267526.4  -877812.25]]


real location is:
 [[ 203862.768154  273846.699182 -879936.224987]]
prediction is:
 [[ 203117.11  260435.34 -867502.5 ]]


real location is:
 

real location is:
 [[ 206068.808663  186594.237589 -877119.342095]]
prediction is:
 [[ 196283.77  189496.88 -858553.  ]]


real location is:
 [[ 206106.527219  185173.274902 -879904.36334 ]]
prediction is:
 [[ 204279.48  184023.45 -852444.5 ]]


real location is:
 [[ 206145.338508  183746.861698 -872074.303865]]
prediction is:
 [[ 198897.62  176737.17 -842131.2 ]]


real location is:
 [[ 206206.760415  182380.008083 -878993.741741]]
prediction is:
 [[ 201174.25  178272.14 -856821.75]]


real location is:
 [[ 206236.014493  180939.75291  -890691.596558]]
prediction is:
 [[ 201552.75  179422.   -856470.44]]


real location is:
 [[ 206223.982185  179520.089402 -892500.878181]]
prediction is:
 [[ 203400.33  174318.22 -862519.1 ]]


real location is:
 [[ 206201.100979  178179.264242 -893143.630718]]
prediction is:
 [[ 207019.08  173333.31 -874562.44]]


real location is:
 [[ 206194.856007  176715.868744 -887610.60778 ]]
prediction is:
 [[ 206659.5  171758.1 -872639.9]]


real location is:
 

real location is:
 [[  199586.150698    98746.437039 -1391839.79802 ]]
prediction is:
 [[  200017.81    92767.29 -1364585.4 ]]


real location is:
 [[  198771.807779     98033.0454016 -1381070.57125  ]]
prediction is:
 [[  196670.78    89949.42 -1356936.9 ]]


real location is:
 [[  197974.406108     97290.2974233 -1354952.56224  ]]
prediction is:
 [[  198165.66    86300.47 -1340607.2 ]]


real location is:
 [[  197250.461953     96525.1012926 -1313267.7396   ]]
prediction is:
 [[  196069.58    89223.75 -1266313.8 ]]


real location is:
 [[  196549.202049     95725.3395273 -1284598.74479  ]]
prediction is:
 [[  193084.48    85743.9  -1261589.4 ]]


real location is:
 [[  195908.098908     94877.4809831 -1262187.7592   ]]
prediction is:
 [[  193520.83    90199.38 -1247247.1 ]]


real location is:
 [[  195266.406741     94000.3654324 -1246402.00398  ]]
prediction is:
 [[  198862.97    85163.45 -1215545.2 ]]


real location is:
 [[  194660.157199     93066.5926631 -1211348.94865  ]]
predi

real location is:
 [[  154100.934118     47747.3371831 -1376512.4895   ]]
prediction is:
 [[  149998.52     45362.215 -1326816.8  ]]


real location is:
 [[  153282.86901      46998.1352468 -1370350.70516  ]]
prediction is:
 [[  149990.02    37641.72 -1329686.2 ]]


real location is:
 [[  152495.202659     46273.1310014 -1370000.13164  ]]
prediction is:
 [[  149108.34     49605.516 -1338575.8  ]]


real location is:
 [[  151717.46319     45567.032848 -1370588.3437  ]]
prediction is:
 [[  145360.56     45617.918 -1347111.9  ]]


real location is:
 [[  150895.565898     44820.9555923 -1364993.80843  ]]
prediction is:
 [[  136817.58     36521.676 -1348000.8  ]]


real location is:
 [[  150076.603612     44091.1342062 -1367014.23237  ]]
prediction is:
 [[  150105.94     42738.125 -1363404.9  ]]


real location is:
 [[  149277.852979     43355.8691717 -1367230.92601  ]]
prediction is:
 [[  153035.4      38508.066 -1358950.5  ]]


real location is:
 [[  148467.206412     42647.4845202 -13648

real location is:
 [[  103960.471265       3868.63546312 -1603916.97025   ]]
prediction is:
 [[   99029.875     3598.316 -1585156.4  ]]


real location is:
 [[  102905.768032       3548.45329937 -1646093.98321   ]]
prediction is:
 [[   98322.21       1792.3969 -1609167.2   ]]


real location is:
 [[  101825.790836       3308.49352889 -1681932.54097   ]]
prediction is:
 [[   98171.305      5043.6924 -1654549.8   ]]


real location is:
 [[  100692.446363       3136.36001439 -1708180.7351    ]]
prediction is:
 [[   94320.73       2184.0537 -1653562.8   ]]


real location is:
 [[   99538.5254889      2996.94131874 -1723592.26823   ]]
prediction is:
 [[   97841.63       2765.3455 -1678590.    ]]


real location is:
 [[   98389.3823187      2893.82087941 -1733401.76769   ]]
prediction is:
 [[   93048.86      7403.192 -1675904.6  ]]


real location is:
 [[   97232.318494       2796.58735812 -1739711.63474   ]]
prediction is:
 [[   90380.68      8910.574 -1682944.1  ]]


real location is:
 [[ 

real location is:
 [[ 2.76391105e+04  5.67459872e+02 -1.79299192e+06]]
prediction is:
 [[ 2.6273922e+04 -1.5025850e+03 -1.7585979e+06]]


real location is:
 [[ 2.64745337e+04  5.45203376e+02 -1.79161614e+06]]
prediction is:
 [[   23959.562      2457.4736 -1754133.    ]]


real location is:
 [[ 2.52655378e+04  5.25949190e+02 -1.78654415e+06]]
prediction is:
 [[ 2.4045924e+04  2.9841479e+02 -1.7730299e+06]]


real location is:
 [[ 2.40913524e+04  5.37039875e+02 -1.79497296e+06]]
prediction is:
 [[ 2.4852016e+04 -7.5391797e+02 -1.7523441e+06]]


real location is:
 [[ 2.28879001e+04  5.02086542e+02 -1.79646968e+06]]
prediction is:
 [[   18915.934    -5588.882 -1727403.6  ]]


real location is:
 [[ 2.17041119e+04  5.06516858e+02 -1.79688654e+06]]
prediction is:
 [[   18388.967     -1960.9541 -1754636.9   ]]


real location is:
 [[2.04670008e+04 4.81522037e+02 1.79968774e+06]]
prediction is:
 [[  14164.182   -5228.584 1738421.1  ]]


real location is:
 [[1.92733124e+04 4.94258113e+02 1.79723

real location is:
 [[41793.8453668   -588.28721112 -8442.21842851]]
prediction is:
 [[38477.04      336.60077 -7186.915  ]]


real location is:
 [[42968.507849    -632.89705371 -6229.36072746]]
prediction is:
 [[40620.35    -560.7119 -1305.0996]]


real location is:
 [[44098.7151869   -665.83235631 -3598.58082065]]
prediction is:
 [[41886.53     -537.28894  -474.16943]]


real location is:
 [[45305.6260843   -676.55161262  -646.80434872]]
prediction is:
 [[40220.59    1386.9762  9615.835 ]]


real location is:
 [[46494.1689849   -743.85661633 -4954.06160953]]
prediction is:
 [[45805.73     904.8761 -1481.5325]]


real location is:
 [[47668.6961449   -778.7839352  -5412.85125879]]
prediction is:
 [[45026.26    -731.4574  4055.516 ]]


real location is:
 [[48814.5216503   -820.61958349  7134.80842448]]
prediction is:
 [[43854.223    875.3069 10631.971 ]]


real location is:
 [[49997.0317292   -807.61177348 28337.6405008 ]]
prediction is:
 [[46648.027    -494.78027 30395.508  ]]


real lo

real location is:
 [[80234.4088928    275.68860309  6698.35082499]]
prediction is:
 [[77179.63    1457.8484  7338.563 ]]


real location is:
 [[81284.132554     270.34206745  2876.34716055]]
prediction is:
 [[74680.61    2094.2952 10135.097 ]]


real location is:
 [[82350.3324942    272.53417034  2214.5476813 ]]
prediction is:
 [[78909.555  -1120.9331  4756.164 ]]


real location is:
 [[83487.8314877    281.64751463  2185.60179283]]
prediction is:
 [[78501.75    -549.3181  9182.738 ]]


real location is:
 [[84630.3762606    271.61512377 -5257.58837642]]
prediction is:
 [[77395.586    316.8697  8432.531 ]]


real location is:
 [[85714.2153451    266.80360839 -4367.39714504]]
prediction is:
 [[79452.07    -599.9853  2173.1848]]


real location is:
 [[86813.0073358    278.41025104 -5186.16742061]]
prediction is:
 [[79447.03      365.02917  4606.696  ]]


real location is:
 [[87993.0333194    276.9361241  -4290.80527167]]
prediction is:
 [[79975.195   -891.1848  3385.855 ]]


real location

real location is:
 [[144849.403044   39574.6527686 479207.848154 ]]
prediction is:
 [[143880.5    36363.965 469328.7  ]]


real location is:
 [[145687.79161    40467.4011812 475776.129815 ]]
prediction is:
 [[143887.14   40014.426 456919.53 ]]


real location is:
 [[146542.51752    41324.5657746 468153.916422 ]]
prediction is:
 [[143474.69   41085.055 440678.4  ]]


real location is:
 [[147362.964839   42160.2598461 468309.632246 ]]
prediction is:
 [[145181.23   39753.516 452969.44 ]]


real location is:
 [[148149.199737   42939.5890463 475070.558023 ]]
prediction is:
 [[144495.58   41888.875 447818.47 ]]


real location is:
 [[148966.489874   43787.3573498 481915.402915 ]]
prediction is:
 [[143919.22  44817.75 457984.47]]


real location is:
 [[149778.949415   44614.2089301 480718.877285 ]]
prediction is:
 [[148330.06  40422.59 466588.47]]


real location is:
 [[150585.375462   45433.0935078 473670.560081 ]]
prediction is:
 [[145916.61  44289.91 457659.56]]


real location is:
 [[1514

real location is:
 [[206005.497808 109334.798033 845800.666348]]
prediction is:
 [[201638.16  100546.484 813207.3  ]]


real location is:
 [[206098.290325 110443.592361 884096.237467]]
prediction is:
 [[200899.36  105712.836 844353.8  ]]


real location is:
 [[206135.914011 111542.424815 904684.491152]]
prediction is:
 [[206851.34 106223.54 867163.25]]


real location is:
 [[206162.748673 112667.197086 908854.164689]]
prediction is:
 [[205318.52  105574.305 864793.6  ]]


real location is:
 [[206243.229038 113885.438318 910087.697478]]
prediction is:
 [[204415.39 107749.46 876418.9 ]]


real location is:
 [[206269.712309 114955.242431 917608.622417]]
prediction is:
 [[207706.89 106858.09 861502.8 ]]


real location is:
 [[206291.913412 116046.406006 920522.667009]]
prediction is:
 [[200070.61 104948.75 861871.5 ]]


real location is:
 [[206317.497957 117132.321127 919375.71374 ]]
prediction is:
 [[204984.3  108121.66 874484.1 ]]


real location is:
 [[206331.949946 118175.507591 913763

real location is:
 [[207591.745429 185749.434106 905573.469329]]
prediction is:
 [[202102.11 184152.62 889708.44]]


real location is:
 [[207578.085991 186828.512029 905723.860576]]
prediction is:
 [[202311.88 189252.78 879862.3 ]]


real location is:
 [[207574.893058 187913.947766 909030.690542]]
prediction is:
 [[205932.   181758.52 869929.56]]


real location is:
 [[207582.350049 188947.339228 905716.252456]]
prediction is:
 [[205208.25 197398.2  889688.9 ]]


real location is:
 [[207578.51103  190044.092902 906074.233169]]
prediction is:
 [[204218.2  184729.05 882837.3 ]]


real location is:
 [[207575.843862 191075.691331 904122.142016]]
prediction is:
 [[202569.33 185678.12 875722.8 ]]


real location is:
 [[207575.894422 192179.17508  906474.101096]]
prediction is:
 [[206769.89 187320.48 891727.06]]


real location is:
 [[207569.116329 193259.681526 909607.963183]]
prediction is:
 [[201257.75 190697.   875398.5 ]]


real location is:
 [[207566.406916 194353.562527 910161.563437]]

real location is:
 [[206544.046708 265876.115285 922012.262479]]
prediction is:
 [[200906.97 264228.4  904957.56]]


real location is:
 [[206515.820151 266989.368946 912366.732704]]
prediction is:
 [[201243.45 261060.88 885194.  ]]


real location is:
 [[206509.685501 268039.927115 911511.964926]]
prediction is:
 [[199606.94 254295.17 879005.75]]


real location is:
 [[206473.60906  269142.470397 928210.697776]]
prediction is:
 [[200093.62 270152.7  909604.7 ]]


real location is:
 [[206435.902872 270225.205318 926718.179691]]
prediction is:
 [[205364.73 265437.97 894239.  ]]


real location is:
 [[206389.919485 271340.530931 927580.409009]]
prediction is:
 [[207997.94 264561.03 899527.06]]


real location is:
 [[206348.079663 272375.516559 935480.554746]]
prediction is:
 [[203520.33 270956.53 905955.8 ]]


real location is:
 [[206298.896904 273490.590001 937507.834804]]
prediction is:
 [[200769.2  270325.53 913444.1 ]]


real location is:
 [[206241.762042 274616.058481 936101.717785]]

real location is:
 [[ 176362.795578  338051.618451 1353933.30428 ]]
prediction is:
 [[ 165026.16  322804.88 1298858.1 ]]


real location is:
 [[ 175352.265187  339073.881736 1363205.65211 ]]
prediction is:
 [[ 170021.2  326632.3 1312426.9]]


real location is:
 [[ 174293.566587  340117.256069 1373800.89417 ]]
prediction is:
 [[ 171410.53  335339.03 1342373.9 ]]


real location is:
 [[ 173264.685955  341109.699923 1375834.22264 ]]
prediction is:
 [[ 170869.03  329528.25 1332689.9 ]]


real location is:
 [[ 172305.134171  342046.062985 1364851.51232 ]]
prediction is:
 [[ 171956.08  330099.7  1328120.4 ]]


real location is:
 [[ 171296.273814  343028.3158   1363886.30354 ]]
prediction is:
 [[ 170753.8  335438.  1332050.8]]


real location is:
 [[ 170258.964667  344076.667574 1365741.97757 ]]
prediction is:
 [[ 173088.42  337560.6  1318213.1 ]]


real location is:
 [[ 169220.4666    345075.903289 1368377.54898 ]]
prediction is:
 [[ 165174.78  342458.1  1328998.4 ]]


real location is:
 [[ 

real location is:
 [[  98406.1066429  408779.052847  1595799.94248  ]]
prediction is:
 [[ 105913.266  397169.3   1588764.   ]]


real location is:
 [[  97297.1445945  409127.531611  1659918.97281  ]]
prediction is:
 [[  98808.68  388559.72 1606869.5 ]]


real location is:
 [[  96303.5530542  409369.804482  1699632.2888   ]]
prediction is:
 [[ 101105.59  396460.03 1647917.  ]]


real location is:
 [[  95287.443449  409530.235239 1738379.45624 ]]
prediction is:
 [[  97413.32  387999.5  1689752.5 ]]


real location is:
 [[  94188.8389716  409642.450375  1771663.08741  ]]
prediction is:
 [[  96889.48  403419.84 1744386.1 ]]


real location is:
 [[  93060.1315685  409707.139178  1790242.972    ]]
prediction is:
 [[  95664.766  397615.47  1735479.8  ]]


real location is:
 [[  91976.0447259  409762.092376  1789760.60489  ]]
prediction is:
 [[  95496.33  393533.75 1734434.1 ]]


real location is:
 [[  90919.850934  409782.916836 1790358.87318 ]]
prediction is:
 [[  81682.83  392488.7  1731104

real location is:
 [[   24889.1002637   409040.601267  -1797582.60929  ]]
prediction is:
 [[   15633.039   396556.62  -1775695.1  ]]


real location is:
 [[  23827.960058  409055.022749 1794806.94584 ]]
prediction is:
 [[  34015.215  393671.94  1755113.2  ]]


real location is:
 [[  22785.4830533  409060.770755  1786146.72092  ]]
prediction is:
 [[  23754.406  399095.7   1738610.6  ]]


real location is:
 [[  21651.8851131  409082.321473  1786111.62332  ]]
prediction is:
 [[  21841.129  403288.12  1741544.   ]]


real location is:
 [[  20580.4955417  409130.6727    1795637.07671  ]]
prediction is:
 [[  19018.455  398391.84  1760490.   ]]


real location is:
 [[  19574.7677003  409129.745525  1799344.44414  ]]
prediction is:
 [[  20849.348  397205.84  1777254.2  ]]


real location is:
 [[  18485.1532138  409125.140511  1799301.58314  ]]
prediction is:
 [[  23036.438  401912.34  1770891.4  ]]


real location is:
 [[  17380.8209676  409127.845933  1798902.84344  ]]
prediction is:
 [[  273

real location is:
 [[  -43227.1918567   408771.979754  -1792768.80108  ]]
prediction is:
 [[  -38790.805   401536.84  -1749032.9  ]]


real location is:
 [[  -44313.110541   408771.904413 -1793722.5009  ]]
prediction is:
 [[  -38783.004   397387.28  -1748876.9  ]]


real location is:
 [[  -45409.2053591   408763.344167  -1789938.89356  ]]
prediction is:
 [[  -40877.88   402040.53 -1739006.8 ]]


real location is:
 [[  -46424.0974459   408755.538444  -1788784.39611  ]]
prediction is:
 [[  -39928.47   405741.56 -1771517.9 ]]


real location is:
 [[  -47525.9406437   408752.324453  -1789273.96727  ]]
prediction is:
 [[  -39828.13   400387.5  -1748127.1 ]]


real location is:
 [[  -48598.9737496   408728.723258  -1785124.98691  ]]
prediction is:
 [[  -41706.207   404915.88  -1750287.   ]]


real location is:
 [[  -49693.2157085   408709.707885  -1784670.38388  ]]
prediction is:
 [[  -44655.516   404824.12  -1744397.8  ]]


real location is:
 [[  -50762.8813778   408684.995501  -1783910.429

real location is:
 [[ -112951.162147   397899.521439 -1395869.38974 ]]
prediction is:
 [[ -113078.35   392038.78 -1368347.2 ]]


real location is:
 [[ -113941.799817   397039.234596 -1394553.61266 ]]
prediction is:
 [[ -110607.82   390630.53 -1359829.  ]]


real location is:
 [[ -115019.310649   396120.380928 -1385841.37967 ]]
prediction is:
 [[ -113654.97   386917.4  -1374885.8 ]]


real location is:
 [[ -116001.029177   395273.355923 -1385358.24175 ]]
prediction is:
 [[ -112569.76   385186.53 -1374026.6 ]]


real location is:
 [[ -117040.803513   394363.912051 -1388311.12454 ]]
prediction is:
 [[ -115119.36   382690.   -1360944.2 ]]


real location is:
 [[ -118096.721519   393488.706384 -1392791.79515 ]]
prediction is:
 [[ -110973.5    378560.06 -1353272.2 ]]


real location is:
 [[ -119122.070737   392614.51574  -1399462.03773 ]]
prediction is:
 [[ -116113.24   377943.1  -1345020.9 ]]


real location is:
 [[ -120192.318363   391742.664512 -1410299.67757 ]]
prediction is:
 [[ -113552

real location is:
 [[ -171524.441781   340711.696701 -1338452.75627 ]]
prediction is:
 [[ -167058.66   334687.28 -1294690.4 ]]


real location is:
 [[ -172393.410906   339878.669173 -1344454.74329 ]]
prediction is:
 [[ -167865.81   330101.12 -1286320.2 ]]


real location is:
 [[ -173297.611407   338932.945618 -1345087.1685  ]]
prediction is:
 [[ -173366.47   328176.7  -1302221.9 ]]


real location is:
 [[ -174132.257052   338085.55613  -1343292.12788 ]]
prediction is:
 [[ -168110.03   331497.28 -1313098.2 ]]


real location is:
 [[ -175035.56759    337151.979053 -1333327.6574  ]]
prediction is:
 [[ -176123.75   333067.2  -1278080.2 ]]


real location is:
 [[ -175890.332104   336229.530546 -1327953.12389 ]]
prediction is:
 [[ -174262.73   327463.5  -1291814.5 ]]


real location is:
 [[ -176701.026228   335382.577685 -1329224.09424 ]]
prediction is:
 [[ -179866.48   332994.53 -1286174.2 ]]


real location is:
 [[ -177482.223312   334524.131246 -1328136.1791  ]]
prediction is:
 [[ -179110

real location is:
 [[-205957.158661  272769.743255 -923997.494699]]
prediction is:
 [[-202886.62  260961.17 -894132.56]]


real location is:
 [[-206012.745158  271735.03082  -924358.211956]]
prediction is:
 [[-204248.38  262197.56 -888727.44]]


real location is:
 [[-206064.9696    270728.362345 -924119.999527]]
prediction is:
 [[-199615.34  266712.34 -895806.6 ]]


real location is:
 [[-206109.828585  269681.351745 -917483.565413]]
prediction is:
 [[-203558.48  264063.62 -901791.94]]


real location is:
 [[-206136.530572  268629.404052 -915069.891145]]
prediction is:
 [[-196892.23  262047.42 -882531.06]]


real location is:
 [[-206193.74479   267524.774559 -923297.909065]]
prediction is:
 [[-199792.2   254833.89 -887774.7 ]]


real location is:
 [[-206245.171185  266472.796983 -923343.362079]]
prediction is:
 [[-201225.11  260428.81 -888075.2 ]]


real location is:
 [[-206298.995284  265444.885707 -929386.663506]]
prediction is:
 [[-200139.45  257027.39 -890261.4 ]]


real location is

real location is:
 [[-207238.086828  194659.786088 -899189.510286]]
prediction is:
 [[-202110.98  190331.25 -870482.  ]]


real location is:
 [[-207254.023721  193602.808721 -900208.363296]]
prediction is:
 [[-201173.9   185183.34 -868845.1 ]]


real location is:
 [[-207245.321577  192476.469101 -900034.260396]]
prediction is:
 [[-202095.6   182661.34 -864743.9 ]]


real location is:
 [[-207238.256045  191408.193456 -900203.179257]]
prediction is:
 [[-196498.61  187366.38 -855168.94]]


real location is:
 [[-207253.424452  190337.971793 -904068.042001]]
prediction is:
 [[-200669.08  183885.6  -870518.25]]


real location is:
 [[-207250.670006  189234.070855 -906201.704362]]
prediction is:
 [[-202749.98  182107.08 -863466.56]]


real location is:
 [[-207265.965338  188153.610438 -904298.473442]]
prediction is:
 [[-201508.38  183087.3  -872290.5 ]]


real location is:
 [[-207265.834612  187070.182553 -894272.890624]]
prediction is:
 [[-203002.    181622.08 -858292.56]]


real location is

real location is:
 [[-205549.983338  113937.771876 -789573.248258]]
prediction is:
 [[-197200.97   108668.836 -746290.9  ]]


real location is:
 [[-205339.17007   112765.923179 -781324.577361]]
prediction is:
 [[-194893.36  107736.64 -742143.25]]


real location is:
 [[-205083.748266  111500.345237 -771909.989104]]
prediction is:
 [[-198080.94   103381.875 -744602.94 ]]


real location is:
 [[-204796.419011  110234.229885 -762525.623092]]
prediction is:
 [[-198232.27  105290.62 -713969.9 ]]


real location is:
 [[-204493.02423   108909.389713 -753647.523738]]
prediction is:
 [[-199921.4   106129.54 -722387.9 ]]


real location is:
 [[-204186.773537  107622.51585  -744676.212273]]
prediction is:
 [[-199472.11  101998.57 -704902.75]]


real location is:
 [[-203846.759879  106326.259027 -736621.409301]]
prediction is:
 [[-197167.31  104267.83 -707434.25]]


real location is:
 [[-203464.743438  104948.508396 -725539.788036]]
prediction is:
 [[-195836.67   102666.516 -705544.25 ]]


real lo

real location is:
 [[-153552.292053    51212.6495737 -415162.631354 ]]
prediction is:
 [[-142156.98   47551.18 -388880.8 ]]


real location is:
 [[-152754.609671    50494.0384082 -423299.388814 ]]
prediction is:
 [[-146023.27    47100.676 -396909.47 ]]


real location is:
 [[-151881.320789    49709.1510573 -425767.844971 ]]
prediction is:
 [[-142861.4     43907.754 -395852.4  ]]


real location is:
 [[-151076.469356    48943.8611946 -428285.077058 ]]
prediction is:
 [[-145273.66    44546.668 -402801.03 ]]


real location is:
 [[-150256.903127    48197.7246259 -425206.224423 ]]
prediction is:
 [[-140554.14   42436.34 -398960.56]]


real location is:
 [[-149469.861486    47504.0363296 -423654.936927 ]]
prediction is:
 [[-141383.95   43425.11 -398651.6 ]]


real location is:
 [[-148621.829885   46727.648573 -424414.387054]]
prediction is:
 [[-142835.94    41753.758 -397581.72 ]]


real location is:
 [[-147829.99351     45997.4029989 -424901.704983 ]]
prediction is:
 [[-140282.88    41855.

real location is:
 [[-100712.175622      8103.45829918 -305061.968971  ]]
prediction is:
 [[ -94637.73     9334.359 -283652.47 ]]


real location is:
 [[ -99821.7279501     7566.78026838 -298993.027152  ]]
prediction is:
 [[ -98529.87    10652.924 -284046.8  ]]


real location is:
 [[ -99028.5404825     7104.48556246 -292475.327118  ]]
prediction is:
 [[ -98306.984    8363.833 -283466.72 ]]


real location is:
 [[ -98170.211934      6623.91210982 -293729.33878   ]]
prediction is:
 [[ -95845.13     8669.354 -281401.03 ]]


real location is:
 [[ -97349.2421987     6154.53073596 -267262.965562  ]]
prediction is:
 [[ -93649.195    8596.407 -244010.58 ]]


real location is:
 [[ -96472.4801733     5728.10893463 -217125.265659  ]]
prediction is:
 [[ -90811.92      6328.7373 -205598.75  ]]


real location is:
 [[ -95350.6313684     5286.77926824 -172088.09038   ]]
prediction is:
 [[ -88234.234     6878.9385 -160110.16  ]]


real location is:
 [[ -94317.2783153     4972.81466981 -132071.809857 

real location is:
 [[-19711.1560397     998.75814478 -13741.8745636 ]]
prediction is:
 [[-19354.156      327.06857 -13006.567  ]]


real location is:
 [[-18442.8090491     963.11691286 -13300.4886407 ]]
prediction is:
 [[-17617.635       90.20598 -12537.239  ]]


real location is:
 [[-17160.3101218     908.64426149 -14310.1558886 ]]
prediction is:
 [[-15927.9        238.35858 -11952.191  ]]


real location is:
 [[-15895.0628647     874.21094931  -8077.4878397 ]]
prediction is:
 [[-14158.364      339.75833  -9754.502  ]]


real location is:
 [[-14638.7248464     842.80136959  -7221.77895914]]
prediction is:
 [[-13518.104    -750.2238  -7923.2954]]


real location is:
 [[-13352.0066825     820.95298592  -2522.23012626]]
prediction is:
 [[-12725.717      203.87537  -4777.496  ]]


real location is:
 [[-12089.1107334     783.76431553 -10315.327265  ]]
prediction is:
 [[-11023.95       353.89575  -7160.793  ]]


real location is:
 [[-10845.5603886     739.12956881  -9582.45867119]]
predicti

real location is:
 [[75504.5413083    363.51117892 28427.0266072 ]]
prediction is:
 [[69333.36     642.5325 33265.496 ]]


real location is:
 [[76893.0714851    359.40904496 15472.5878558 ]]
prediction is:
 [[75056.69      427.93805 22163.852  ]]


real location is:
 [[78293.7113218   365.0437812 13325.5171016]]
prediction is:
 [[73082.055   1164.1327 19642.154 ]]


real location is:
 [[79660.7788623    372.76720908 14023.3607381 ]]
prediction is:
 [[73356.75     -675.69696 18657.176  ]]


real location is:
 [[81092.2421673    377.52901702 21527.3671607 ]]
prediction is:
 [[74569.28    -346.2626 25063.875 ]]


real location is:
 [[82438.4722867    414.61667311 34032.5053504 ]]
prediction is:
 [[78139.61    3554.5366 39279.125 ]]


real location is:
 [[83895.4301314    524.42310749 44699.4085516 ]]
prediction is:
 [[76466.61   1116.808 42923.4  ]]


real location is:
 [[85349.4077134    638.48110056 54831.6602847 ]]
prediction is:
 [[ 7.8145266e+04 -2.3468536e+01  4.8689051e+04]]


real

real location is:
 [[144833.843537   39781.7192841 446621.119378 ]]
prediction is:
 [[138927.19   37556.824 428719.22 ]]


real location is:
 [[145596.749688   40513.2736227 451686.349511 ]]
prediction is:
 [[136984.94  39698.54 430286.53]]


real location is:
 [[146335.815205   41230.8215022 455600.542529 ]]
prediction is:
 [[143273.2   41522.22 441169.1 ]]


real location is:
 [[147091.965819   41962.3403208 458567.348662 ]]
prediction is:
 [[141857.58   39437.223 439984.97 ]]


real location is:
 [[147857.721375   42740.6097848 466874.047434 ]]
prediction is:
 [[139383.16   42363.387 443449.38 ]]


real location is:
 [[148600.882393   43508.3615473 471789.149291 ]]
prediction is:
 [[144749.9   42319.26 463278.72]]


real location is:
 [[149332.396432   44260.6350087 466709.958892 ]]
prediction is:
 [[141889.48   42515.832 448905.25 ]]


real location is:
 [[150056.504357   44967.9037997 457314.442005 ]]
prediction is:
 [[145482.61  43080.56 447090.  ]]


real location is:
 [[150859.

real location is:
 [[194956.438558  94455.990786 519173.851978]]
prediction is:
 [[188485.42  88898.64 506114.53]]


real location is:
 [[195639.430688   95306.4495605 510540.367796 ]]
prediction is:
 [[181339.31  86244.89 482140.  ]]


real location is:
 [[196336.873718   96121.5842012 499079.888398 ]]
prediction is:
 [[187596.1   86374.57 470355.5 ]]


real location is:
 [[197095.956018   96917.0552739 478344.803523 ]]
prediction is:
 [[190541.9  92108.4 465835.1]]


real location is:
 [[197853.474489   97718.4393189 470871.923217 ]]
prediction is:
 [[188277.92  93524.33 457545.8 ]]


real location is:
 [[198631.483493   98521.1978109 462033.876174 ]]
prediction is:
 [[193229.1   94254.28 448916.66]]


real location is:
 [[199400.61345    99282.7082776 460525.533259 ]]
prediction is:
 [[190517.83  93211.26 452650.03]]


real location is:
 [[200127.271793 100002.600018 460060.594842]]
prediction is:
 [[191826.94   96565.945 450394.03 ]]


real location is:
 [[200894.139878 100781.2781

real location is:
 [[206603.222664 182517.351012 914546.702806]]
prediction is:
 [[201001.88 181291.92 881687.25]]


real location is:
 [[206562.525398 183804.736475 922031.305779]]
prediction is:
 [[204090.77 180950.84 889486.56]]


real location is:
 [[206542.787685 185071.634662 922362.517288]]
prediction is:
 [[203174.95 180076.25 887209.25]]


real location is:
 [[206497.282001 186308.752823 915957.318897]]
prediction is:
 [[202001.19 181627.69 873211.  ]]


real location is:
 [[206474.006763 187618.775292 912533.120062]]
prediction is:
 [[199966.06 180807.4  875902.6 ]]


real location is:
 [[206451.744992 188938.300242 901128.796811]]
prediction is:
 [[201014.53 186753.06 864271.1 ]]


real location is:
 [[206461.032863 190165.414008 903824.160712]]
prediction is:
 [[201706.06 192159.81 886920.2 ]]


real location is:
 [[206451.376854 191472.569229 908313.598004]]
prediction is:
 [[201505.53 188351.27 879060.1 ]]


real location is:
 [[206404.437442 192794.67909  918860.863281]]

real location is:
 [[205339.724172 275839.926869 925824.091539]]
prediction is:
 [[202464.83 264993.8  890485.06]]


real location is:
 [[205326.447816 277052.288444 916507.597672]]
prediction is:
 [[205414.39 273410.16 896097.  ]]


real location is:
 [[205306.714587 278412.08092  911849.838614]]
prediction is:
 [[200113.23 269794.3  887430.44]]


real location is:
 [[205289.875595 279678.071381 909066.331185]]
prediction is:
 [[202507.66 272173.44 880045.56]]


real location is:
 [[205297.858655 280936.176999 908540.823894]]
prediction is:
 [[203415.1  275894.72 886800.8 ]]


real location is:
 [[205310.435936 282203.365917 907944.857936]]
prediction is:
 [[203230.6  281867.06 887952.3 ]]


real location is:
 [[205299.517217 283465.744345 912726.371231]]
prediction is:
 [[202221.3  287703.84 903033.94]]


real location is:
 [[205308.596376 284728.721482 912300.24312 ]]
prediction is:
 [[203707.36 279842.97 906075.2 ]]


real location is:
 [[205274.828833 286009.554429 918673.128754]]

real location is:
 [[ 171674.087888  342458.840463 1360688.36273 ]]
prediction is:
 [[ 167470.6   334630.25 1339194.2 ]]


real location is:
 [[ 170912.672654  343206.937489 1363847.27842 ]]
prediction is:
 [[ 173923.92  338377.2  1330717.  ]]


real location is:
 [[ 170103.000293  343996.308129 1365277.92981 ]]
prediction is:
 [[ 167832.31  337752.16 1322990.9 ]]


real location is:
 [[ 169294.089466  344762.888215 1371197.08131 ]]
prediction is:
 [[ 167987.39  331466.84 1325502.  ]]


real location is:
 [[ 168507.585417  345524.586446 1369694.17686 ]]
prediction is:
 [[ 168618.33  342797.53 1318919.  ]]


real location is:
 [[ 167725.659829  346280.127294 1369091.05503 ]]
prediction is:
 [[ 166093.6  337379.1 1322122.5]]


real location is:
 [[ 166935.059946  347034.131745 1368845.80235 ]]
prediction is:
 [[ 170656.86  342635.7  1329598.6 ]]


real location is:
 [[ 166166.314847  347786.668923 1369536.11345 ]]
prediction is:
 [[ 164196.55  345370.78 1331168.  ]]


real location is:
 

real location is:
 [[ 112777.35084   397485.834491 1435257.0744  ]]
prediction is:
 [[ 119257.75  386590.3  1381925.5 ]]


real location is:
 [[ 111865.938243  398172.954289 1434088.20413 ]]
prediction is:
 [[ 116035.734  388603.8   1373235.1  ]]


real location is:
 [[ 110939.763128  398873.486178 1434002.12201 ]]
prediction is:
 [[ 111711.73  385207.38 1369060.8 ]]


real location is:
 [[ 110042.596033  399544.101094 1433841.84654 ]]
prediction is:
 [[ 112836.88  390073.16 1387662.  ]]


real location is:
 [[ 109105.352183  400267.119128 1428854.08736 ]]
prediction is:
 [[ 107891.69  384838.22 1379829.5 ]]


real location is:
 [[ 108163.734047  400993.643029 1421577.96689 ]]
prediction is:
 [[ 109783.37  387226.5  1381927.6 ]]


real location is:
 [[ 107226.209343  401728.468012 1426538.09347 ]]
prediction is:
 [[ 112761.61  389376.88 1379954.  ]]


real location is:
 [[ 106258.693797  402457.421017 1427043.97496 ]]
prediction is:
 [[ 108387.08  395260.2  1384242.2 ]]


real location

real location is:
 [[   34578.2433496   409636.610715  -1792685.06464  ]]
prediction is:
 [[   37721.996   393051.66  -1757681.4  ]]


real location is:
 [[   33420.7942855   409623.622671  -1795189.78582  ]]
prediction is:
 [[   33331.074   394112.5   -1742972.5  ]]


real location is:
 [[   32328.7311611   409612.388701  -1795634.74351  ]]
prediction is:
 [[   30180.59   391922.75 -1753851.9 ]]


real location is:
 [[   31285.0634139   409602.495619  -1795618.72186  ]]
prediction is:
 [[   29768.943   390595.16  -1755750.   ]]


real location is:
 [[   30169.7031028   409600.881595  -1796410.72303  ]]
prediction is:
 [[   26757.7   399926.3 -1786762.1]]


real location is:
 [[  28983.0246184  409598.700206  1797674.27017  ]]
prediction is:
 [[  41119.402  399727.44  1777064.4  ]]


real location is:
 [[  27763.1281748  409610.62965   1795711.15803  ]]
prediction is:
 [[  37521.81  388945.06 1744177.  ]]


real location is:
 [[  26592.3071586  409632.776743  1795974.48497  ]]
predicti

real location is:
 [[  -31875.4695991   409403.625207  -1777079.82433  ]]
prediction is:
 [[  -27052.139   401113.75  -1739990.2  ]]


real location is:
 [[  -32930.1468351   409378.317815  -1777494.24093  ]]
prediction is:
 [[  -25578.195   401145.16  -1754479.1  ]]


real location is:
 [[  -33983.4448419   409350.345335  -1778364.10413  ]]
prediction is:
 [[  -30451.271   398698.16  -1747481.5  ]]


real location is:
 [[  -35036.8834409   409320.642677  -1779415.2608   ]]
prediction is:
 [[  -32218.45   398860.34 -1726432.9 ]]


real location is:
 [[  -36070.0918669   409311.579406  -1780361.85553  ]]
prediction is:
 [[  -30827.375   397842.5   -1741494.5  ]]


real location is:
 [[  -37139.9507154   409287.003062  -1780784.43181  ]]
prediction is:
 [[  -31598.535   396228.2   -1745718.2  ]]


real location is:
 [[  -38165.4679384   409273.141325  -1781691.67121  ]]
prediction is:
 [[  -35439.266   401430.7   -1733850.6  ]]


real location is:
 [[  -39227.2905991   409250.827315  -17

real location is:
 [[  -99266.976137   407801.267681 -1606310.66538 ]]
prediction is:
 [[ -102224.99   394380.66 -1554926.  ]]


real location is:
 [[ -100316.12232    407406.993511 -1566668.47114 ]]
prediction is:
 [[  -96543.61   388248.06 -1529112.2 ]]


real location is:
 [[ -101353.312517   406921.664106 -1525481.84503 ]]
prediction is:
 [[ -100234.875   397880.88  -1488600.4  ]]


real location is:
 [[ -102347.902005   406390.437312 -1486236.33568 ]]
prediction is:
 [[ -103016.445   397820.4   -1459924.9  ]]


real location is:
 [[ -103371.318158   405790.73798  -1459771.41971 ]]
prediction is:
 [[  -99362.516   395751.56  -1446750.9  ]]


real location is:
 [[ -104276.763464   405191.497962 -1443310.51245 ]]
prediction is:
 [[ -105405.45   392418.47 -1410619.8 ]]


real location is:
 [[ -105254.096936   404478.570721 -1421389.03894 ]]
prediction is:
 [[ -102700.125   391651.    -1407358.4  ]]


real location is:
 [[ -106147.544495   403786.79051  -1404779.4696  ]]
prediction is:

real location is:
 [[ -160308.036652   351853.890491 -1336802.37465 ]]
prediction is:
 [[ -160668.53   348339.62 -1301121.9 ]]


real location is:
 [[ -161185.619892   350908.016404 -1330369.32222 ]]
prediction is:
 [[ -161506.97   346069.53 -1308897.  ]]


real location is:
 [[ -162042.857283   349974.924472 -1334536.93861 ]]
prediction is:
 [[ -160659.73   342542.1  -1296411.6 ]]


real location is:
 [[ -162924.191553   349073.204467 -1344590.56213 ]]
prediction is:
 [[ -158732.61   340477.06 -1298524.2 ]]


real location is:
 [[ -163800.884289   348214.197112 -1345746.22817 ]]
prediction is:
 [[ -164924.23   339398.22 -1309806.6 ]]


real location is:
 [[ -164690.85306    347308.351481 -1346275.34493 ]]
prediction is:
 [[ -164140.38   335813.3  -1294179.6 ]]


real location is:
 [[ -165536.632392   346460.157465 -1341427.91522 ]]
prediction is:
 [[ -158432.44   340864.16 -1298015.5 ]]


real location is:
 [[ -166471.858952   345516.955549 -1342580.05449 ]]
prediction is:
 [[ -164324

real location is:
 [[-205837.886337  284027.505625 -932257.734722]]
prediction is:
 [[-204982.42  274478.2  -893674.1 ]]


real location is:
 [[-205898.305434  283005.895632 -933261.069443]]
prediction is:
 [[-199565.98  268610.1  -882586.06]]


real location is:
 [[-205970.011853  281891.747158 -928171.938889]]
prediction is:
 [[-205963.61  272581.8  -897200.25]]


real location is:
 [[-206011.198054  280811.399865 -919398.635107]]
prediction is:
 [[-198119.44  267142.2  -882734.2 ]]


real location is:
 [[-206052.456211  279764.940768 -912171.639863]]
prediction is:
 [[-199181.05  269970.44 -877482.7 ]]


real location is:
 [[-206069.728647  278767.624597 -919800.740884]]
prediction is:
 [[-205483.39  273699.25 -910676.75]]


real location is:
 [[-206128.258062  277676.5275   -928555.166675]]
prediction is:
 [[-202797.02  265674.97 -893644.75]]


real location is:
 [[-206202.770389  276688.966266 -928244.119425]]
prediction is:
 [[-203385.6   267143.53 -889071.5 ]]


real location is

real location is:
 [[-208349.695142  207220.137357 -887071.060805]]
prediction is:
 [[-201053.19  199003.28 -851774.3 ]]


real location is:
 [[-208352.620516  206162.679788 -886164.591753]]
prediction is:
 [[-199368.33  194786.78 -843974.25]]


real location is:
 [[-208339.370705  205085.467428 -881705.71137 ]]
prediction is:
 [[-200812.2   202920.14 -850542.2 ]]


real location is:
 [[-208331.184459  204009.207707 -882895.480584]]
prediction is:
 [[-201352.6   197895.86 -849261.25]]


real location is:
 [[-208329.568599  202950.494917 -882708.732946]]
prediction is:
 [[-200051.72  194755.12 -838165.9 ]]


real location is:
 [[-208317.881265  201886.609188 -884191.929956]]
prediction is:
 [[-201284.2   192775.12 -846131.8 ]]


real location is:
 [[-208318.314094  200791.54575  -884547.435628]]
prediction is:
 [[-202129.33  190345.27 -833733.56]]


real location is:
 [[-208296.146045  199698.829128 -881471.108252]]
prediction is:
 [[-201097.52  194485.61 -844720.06]]


real location is

real location is:
 [[-208171.990721  135287.866082 -889550.541277]]
prediction is:
 [[-202842.8   132521.58 -865040.44]]


real location is:
 [[-208153.996142  134232.941584 -886979.744115]]
prediction is:
 [[-204343.95  129102.81 -859384.6 ]]


real location is:
 [[-208134.19377   133132.948426 -875958.171285]]
prediction is:
 [[-204341.56  129307.7  -853691.9 ]]


real location is:
 [[-208110.530639  132080.303845 -868205.849444]]
prediction is:
 [[-201636.55  129797.89 -839824.8 ]]


real location is:
 [[-208084.784566  131014.362905 -868635.86551 ]]
prediction is:
 [[-205356.16   127343.914 -843299.44 ]]


real location is:
 [[-208065.487946  129942.140743 -869401.464588]]
prediction is:
 [[-203685.28   129734.914 -843397.06 ]]


real location is:
 [[-208040.112275  128927.437009 -856043.961262]]
prediction is:
 [[-204188.45   124154.125 -833858.8  ]]


real location is:
 [[-207995.600866  127871.412703 -852241.961327]]
prediction is:
 [[-199838.47  124011.22 -820083.1 ]]


real lo

real location is:
 [[-165365.637507    61918.0841743 -425436.706807 ]]
prediction is:
 [[-156956.17    58341.938 -405351.2  ]]


real location is:
 [[-164330.330042    60958.6896009 -415647.048042 ]]
prediction is:
 [[-157801.7     56200.465 -401676.03 ]]


real location is:
 [[-163340.310317    60049.3805892 -411075.489905 ]]
prediction is:
 [[-154733.27    55986.293 -393142.   ]]


real location is:
 [[-162419.722975    59202.9746538 -417238.479966 ]]
prediction is:
 [[-154988.05    53315.766 -392416.   ]]


real location is:
 [[-161380.31897     58256.8201856 -407575.605096 ]]
prediction is:
 [[-150016.7    51469.21 -378928.97]]


real location is:
 [[-160365.689391    57335.5513671 -407804.303409 ]]
prediction is:
 [[-152300.33   51379.37 -385785.5 ]]


real location is:
 [[-159320.854274   56407.602695 -404515.054432]]
prediction is:
 [[-143910.69    51979.895 -383407.4  ]]


real location is:
 [[-158363.085642    55581.4584614 -404387.590056 ]]
prediction is:
 [[-150652.47    479

real location is:
 [[ -95696.5948028     5221.09137662 -154110.785347  ]]
prediction is:
 [[ -86907.41      5129.9185 -137937.34  ]]


real location is:
 [[ -94649.8110019     4962.35250231 -113264.44099   ]]
prediction is:
 [[ -86840.56      7304.5493 -106563.61  ]]


real location is:
 [[-93556.3109099    4776.90701779 -72671.4245231 ]]
prediction is:
 [[-82999.1     3503.998 -72334.04 ]]


real location is:
 [[-92461.5057563    4630.74370395 -47365.5876817 ]]
prediction is:
 [[-83350.98     5144.7197 -39185.047 ]]


real location is:
 [[-91362.7620261    4523.65155871 -36005.6166536 ]]
prediction is:
 [[-83474.3     4668.518 -28380.316]]


real location is:
 [[-90295.2321455    4466.93101753 -28551.3342555 ]]
prediction is:
 [[-78564.29     3104.7039 -25046.469 ]]


real location is:
 [[-89253.5476852    4362.75701575 -29671.1233884 ]]
prediction is:
 [[-80434.6      5702.8057 -24321.535 ]]


real location is:
 [[-88169.5528235    4282.75547242 -16260.1339813 ]]
prediction is:
 [[-8

real location is:
 [[-28267.7421484    1369.41100237 -21478.8048844 ]]
prediction is:
 [[-26195.748    2910.3896 -17235.59  ]]


real location is:
 [[-27243.7450846    1315.71650655 -29791.608355  ]]
prediction is:
 [[-27204.459      319.61166 -25405.225  ]]


real location is:
 [[-26206.5907043    1244.75796339 -34143.5760812 ]]
prediction is:
 [[-24661.541   1249.159 -30724.65 ]]


real location is:
 [[-25148.0170748    1160.77587768 -34433.5040875 ]]
prediction is:
 [[-24884.086     217.3257 -30957.53  ]]


real location is:
 [[-24068.43046      1081.30391383 -33659.5849024 ]]
prediction is:
 [[-22283.596    3388.8208 -32028.842 ]]


real location is:
 [[-23007.9206704    1010.32052689 -32269.214466  ]]
prediction is:
 [[-23706.94     1470.5656 -29348.1   ]]


real location is:
 [[-21954.0807228     939.11837899 -31358.2323155 ]]
prediction is:
 [[-22613.951     441.8946 -29855.34  ]]


real location is:
 [[-20897.7010741     884.63618229 -18379.5981106 ]]
prediction is:
 [[-19436.3

real location is:
 [[-2.51656357e+04 -6.40058976e+02  1.78488777e+06]]
prediction is:
 [[ -24876.207    -3581.2444 1744801.9   ]]


real location is:
 [[-2.62709688e+04 -6.20680979e+02  1.77675788e+06]]
prediction is:
 [[ -26171.686    -3929.2515 1723119.2   ]]


real location is:
 [[-2.73519848e+04 -5.68776886e+02  1.77449908e+06]]
prediction is:
 [[ -29961.564   -4961.584 1740259.5  ]]


real location is:
 [[-2.84053121e+04 -5.18778250e+02  1.77443767e+06]]
prediction is:
 [[ -24565.37     -2516.8337 1704711.1   ]]


real location is:
 [[-2.94807041e+04 -4.62031060e+02  1.75471363e+06]]
prediction is:
 [[ -31120.045   -4432.695 1718808.2  ]]


real location is:
 [[-3.05531977e+04 -3.38428100e+02  1.71502761e+06]]
prediction is:
 [[-2.7507939e+04 -3.2055322e+02  1.6500050e+06]]


real location is:
 [[-3.16277340e+04 -1.72657263e+02  1.71111947e+06]]
prediction is:
 [[-2.7863324e+04 -1.0266049e+03  1.6440299e+06]]


real location is:
 [[-3.26896420e+04  3.60569318e+00  1.71258150e+06]]

real location is:
 [[ -93793.6582236     3883.90715663 1652527.96946   ]]
prediction is:
 [[ -92151.336     1810.8435 1620308.2   ]]


real location is:
 [[ -94753.8115799     4176.91701824 1638330.94766   ]]
prediction is:
 [[ -94748.375     4044.6772 1599568.8   ]]


real location is:
 [[ -95735.4691078     4492.33587992 1612830.60251   ]]
prediction is:
 [[ -95017.016     4021.4968 1573216.5   ]]


real location is:
 [[ -96617.5456029     4839.61948355 1583035.51038   ]]
prediction is:
 [[ -99841.77     3218.352 1555423.1  ]]


real location is:
 [[ -97572.6589072     5246.81782225 1552998.67858   ]]
prediction is:
 [[ -97002.836     3668.7695 1522473.5   ]]


real location is:
 [[ -98491.5865241     5745.39054707 1512397.03716   ]]
prediction is:
 [[-101888.73     5350.747 1500375.8  ]]


real location is:
 [[ -99410.9119378     6298.11871165 1484398.69877   ]]
prediction is:
 [[ -98482.195    5618.244 1452961.8  ]]


real location is:
 [[-100270.961296      6867.32682296 1459511.3

real location is:
 [[-149564.601454    48589.8136707 1382700.15875  ]]
prediction is:
 [[-146935.75    44856.934 1348461.5  ]]


real location is:
 [[-150402.462061    49364.0371152 1381540.96038  ]]
prediction is:
 [[-148451.33    42709.844 1364590.2  ]]


real location is:
 [[-151237.188269    50129.8106905 1383504.13266  ]]
prediction is:
 [[-152295.25    46933.688 1341963.1  ]]


real location is:
 [[-152039.625389    50876.3998706 1389229.63211  ]]
prediction is:
 [[-147400.64    47376.453 1356726.1  ]]


real location is:
 [[-152869.824609    51658.5839607 1389828.09696  ]]
prediction is:
 [[-151841.02    49394.773 1339715.2  ]]


real location is:
 [[-153738.179644    52483.3627421 1384540.62471  ]]
prediction is:
 [[-149433.11   45411.5  1341842.5 ]]


real location is:
 [[-154630.158223   53311.529769 1378536.34864 ]]
prediction is:
 [[-146419.34    45882.754 1335467.9  ]]


real location is:
 [[-155480.856907    54114.0520685 1381324.91525  ]]
prediction is:
 [[-149149.14   5

real location is:
 [[-203532.846728  110903.972026  924118.223866]]
prediction is:
 [[-204136.47  111239.07  894742.6 ]]


real location is:
 [[-203571.508758  112106.511411  928927.270369]]
prediction is:
 [[-198693.78  105788.66  912356.1 ]]


real location is:
 [[-203617.836322  113295.431648  930804.226303]]
prediction is:
 [[-203130.48  106625.71  894204.9 ]]


real location is:
 [[-203675.913554  114445.678507  929729.565711]]
prediction is:
 [[-198910.33  110898.96  907243.7 ]]


real location is:
 [[-203714.387244  115611.668758  931281.692103]]
prediction is:
 [[-199083.75  113645.34  902118.  ]]


real location is:
 [[-203780.287266  116757.737366  934179.518319]]
prediction is:
 [[-200193.36   112132.055  894767.75 ]]


real location is:
 [[-203834.838128  117910.079775  931620.554339]]
prediction is:
 [[-207902.47  114984.06  896302.  ]]


real location is:
 [[-203906.680117  119106.868183  931509.730969]]
prediction is:
 [[-199365.89  116132.63  888160.06]]


real location

real location is:
 [[-205139.270759  194711.396831  932295.689553]]
prediction is:
 [[-200952.83  194428.94  884673.44]]


real location is:
 [[-205198.496754  195958.203458  931711.187872]]
prediction is:
 [[-206186.52  195640.92  899027.25]]


real location is:
 [[-205245.139155  197222.836274  924575.689515]]
prediction is:
 [[-201730.12  192852.    886333.7 ]]


real location is:
 [[-205280.829729  198490.31009   919207.738939]]
prediction is:
 [[-202591.66  195595.8   893453.44]]


real location is:
 [[-205304.827797  199706.891876  924128.764521]]
prediction is:
 [[-201108.58  197037.56  891659.9 ]]


real location is:
 [[-205327.699622  200963.088732  923519.934856]]
prediction is:
 [[-205957.39  194703.73  896155.56]]


real location is:
 [[-205352.706164  202146.515786  919832.584923]]
prediction is:
 [[-199746.3  196610.   898402.8]]


real location is:
 [[-205379.989689  203341.929544  911735.104085]]
prediction is:
 [[-199701.81  199308.3   879395.06]]


real location is:
 

real location is:
 [[-205891.711646  282720.176478  888844.366316]]
prediction is:
 [[-200409.52  273049.9   867176.1 ]]


real location is:
 [[-205826.02292   283893.881323  881894.508479]]
prediction is:
 [[-198815.7   269484.47  837039.5 ]]


real location is:
 [[-205770.011386  285097.953317  887586.511565]]
prediction is:
 [[-202207.89  276566.3   838650.7 ]]


real location is:
 [[-205725.224192  286237.682083  889031.58477 ]]
prediction is:
 [[-202215.34  275358.6   843337.06]]


real location is:
 [[-205681.332033  287408.010031  892820.879155]]
prediction is:
 [[-207335.44  273548.38  882230.1 ]]


real location is:
 [[-205647.525475  288575.78629   897056.596033]]
prediction is:
 [[-207993.36  278815.97  857485.9 ]]


real location is:
 [[-205653.91863   289812.452077  903557.244712]]
prediction is:
 [[-207051.9   279276.88  877101.8 ]]


real location is:
 [[-205655.82548   291010.204099  908001.821529]]
prediction is:
 [[-205895.36  280196.88  886239.6 ]]


real location is

real location is:
 [[-166530.43739   345539.620922  479969.278004]]
prediction is:
 [[-163897.12  335177.75  466603.88]]


real location is:
 [[-165801.591626  346337.632001  479277.514409]]
prediction is:
 [[-162627.44  337173.75  467581.62]]


real location is:
 [[-165068.462739  347116.943503  476577.915141]]
prediction is:
 [[-161560.55  340245.06  465080.4 ]]


real location is:
 [[-164308.284048  347902.724939  473481.024451]]
prediction is:
 [[-162267.97  340567.72  462775.06]]


real location is:
 [[-163598.607212  348646.898066  472724.462984]]
prediction is:
 [[-159284.97  334680.25  463514.06]]


real location is:
 [[-162863.246085  349415.030152  471653.041923]]
prediction is:
 [[-159414.14  349104.6   452593.03]]


real location is:
 [[-162121.153603  350185.52347   475012.915386]]
prediction is:
 [[-159342.03  343672.06  458246.47]]


real location is:
 [[-161382.770787  350961.388802  475456.626116]]
prediction is:
 [[-161267.67  348509.94  463436.7 ]]


real location is

real location is:
 [[-113800.915543  397331.025511  420783.282507]]
prediction is:
 [[-115081.89  389928.06  409840.5 ]]


real location is:
 [[-112986.864405  398046.838078  417162.138244]]
prediction is:
 [[-112778.805  387614.75   405708.22 ]]


real location is:
 [[-112105.822651  398768.782377  413549.932311]]
prediction is:
 [[-111191.66  381185.5   400030.  ]]


real location is:
 [[-111219.772622  399520.683455  417815.774231]]
prediction is:
 [[-112975.55  384467.53  402648.72]]


real location is:
 [[-110357.656379  400250.943542  412807.789566]]
prediction is:
 [[-108155.98  389145.75  398395.1 ]]


real location is:
 [[-109551.235237  400947.959318  413162.906956]]
prediction is:
 [[-103884.22  383042.03  398702.56]]


real location is:
 [[-108698.534856  401675.929625  406269.360971]]
prediction is:
 [[-107442.59  384539.06  391169.56]]


real location is:
 [[-107848.405128  402373.319676  400365.31084 ]]
prediction is:
 [[-110555.36  390386.28  396632.72]]


real location

real location is:
 [[-21262.5009951  407590.36436     -1759.72900308]]
prediction is:
 [[-15325.175   393195.4        821.74023]]


real location is:
 [[-19783.3390754  407577.270766    -3251.24824481]]
prediction is:
 [[-19038.594 393496.2     4940.661]]


real location is:
 [[-18353.6980431  407554.65895      4289.34690417]]
prediction is:
 [[-17646.674 394192.78   10760.801]]


real location is:
 [[-16917.136279  407569.961092   15500.8534837]]
prediction is:
 [[-14530.725 391039.5     8973.1  ]]


real location is:
 [[-15452.7642058 407615.998833   26796.527546 ]]
prediction is:
 [[-12898.4   391390.1    19345.057]]


real location is:
 [[-13968.6451812 407670.02108    22936.0320565]]
prediction is:
 [[-13809.322 395924.25   21205.523]]


real location is:
 [[-12465.6544722 407722.163635   15933.0017569]]
prediction is:
 [[-11207.892 398401.9    14737.865]]


real location is:
 [[-10910.6703402  407743.990901     -464.68580948]]
prediction is:
 [[ -9496.272  391199.2      3623.4216

real location is:
 [[ 79856.9264405 408733.254445   16146.5353343]]
prediction is:
 [[ 74183.97  393749.47   14388.543]]


real location is:
 [[ 81273.5873261 408744.04891    14501.2539379]]
prediction is:
 [[ 76418.81  396724.9    11226.251]]


real location is:
 [[ 82612.8457897 408769.545205   18141.4717422]]
prediction is:
 [[ 80924.01 397424.53  10435.07]]


real location is:
 [[ 83953.0112367 408842.704919   26696.3984165]]
prediction is:
 [[ 81313.37  394124.88   11731.477]]


real location is:
 [[ 85257.5770844 408916.112425   26153.1847145]]
prediction is:
 [[ 81329.45  398784.22   17426.809]]


real location is:
 [[ 86547.3499739 408984.676364   26689.5896619]]
prediction is:
 [[ 81858.625 402399.4    21075.941]]


real location is:
 [[ 87887.6853718 409044.861206   26555.9808927]]
prediction is:
 [[ 82489.12  401393.97   21446.012]]


real location is:
 [[ 89154.6876717 409073.658163   25649.2411252]]
prediction is:
 [[ 85702.26  391437.7    26120.414]]


real location is:
 

real location is:
 [[ 144896.03226   368765.047282 -422534.635894]]
prediction is:
 [[ 144073.75  358456.66 -398552.5 ]]


real location is:
 [[ 145685.955453  368018.601162 -422969.309506]]
prediction is:
 [[ 148262.5   355641.97 -407291.38]]


real location is:
 [[ 146438.842005  367299.407262 -422976.660323]]
prediction is:
 [[ 144057.72  357292.34 -403197.25]]


real location is:
 [[ 147249.844716  366539.325836 -423083.463648]]
prediction is:
 [[ 146091.97  362159.56 -408075.75]]


real location is:
 [[ 148038.540601  365777.238073 -424932.409012]]
prediction is:
 [[ 142275.86  359220.7  -409866.84]]


real location is:
 [[ 148817.236437  365048.652611 -425200.567293]]
prediction is:
 [[ 143384.14  352089.03 -408408.7 ]]


real location is:
 [[ 149582.70029   364306.59942  -424841.808991]]
prediction is:
 [[ 146644.44  352005.88 -406712.47]]


real location is:
 [[ 150362.67877   363576.612363 -425303.347574]]
prediction is:
 [[ 146305.81  354281.   -407341.12]]


real location is

real location is:
 [[ 199061.777291  314126.436139 -458382.022518]]
prediction is:
 [[ 191626.67  305678.84 -435987.9 ]]


real location is:
 [[ 199842.001257  313269.118141 -477755.450669]]
prediction is:
 [[ 191451.78  297863.4  -446697.78]]


real location is:
 [[ 200583.8844    312417.38471  -501937.856432]]
prediction is:
 [[ 189505.3  308551.4 -466738.1]]


real location is:
 [[ 201262.786935  311554.684022 -532358.190736]]
prediction is:
 [[ 185509.28  297332.7  -496678.1 ]]


real location is:
 [[ 201917.622938  310589.438575 -586810.91316 ]]
prediction is:
 [[ 192430.97  303143.5  -557624.44]]


real location is:
 [[ 202437.79792   309618.064339 -643839.538496]]
prediction is:
 [[ 196721.88  304036.06 -612248.4 ]]


real location is:
 [[ 202857.095808  308656.452419 -700858.521366]]
prediction is:
 [[ 200281.69  301516.97 -677945.7 ]]


real location is:
 [[ 203202.373211  307609.459708 -749304.983301]]
prediction is:
 [[ 205191.86  306752.38 -714357.7 ]]


real location is:
 

real location is:
 [[ 205019.285234  225207.088381 -822758.365848]]
prediction is:
 [[ 198606.5   219454.25 -802518.56]]


real location is:
 [[ 205151.376181  224018.776141 -823171.043204]]
prediction is:
 [[ 197543.77  214450.62 -773633.3 ]]


real location is:
 [[ 205281.559231  222815.272652 -831889.463463]]
prediction is:
 [[ 199999.94  211536.78 -803020.8 ]]


real location is:
 [[ 205387.775023  221629.354813 -838375.134598]]
prediction is:
 [[ 198194.02  210655.86 -803336.9 ]]


real location is:
 [[ 205500.714501  220431.49212  -857327.485435]]
prediction is:
 [[ 200191.25  214677.05 -832443.  ]]


real location is:
 [[ 205523.611631  219259.913329 -896891.49248 ]]
prediction is:
 [[ 199046.95  215537.03 -867380.25]]


real location is:
 [[ 205465.607993  217967.057672 -921683.839079]]
prediction is:
 [[ 197719.78  212162.16 -877374.8 ]]


real location is:
 [[ 205414.897075  216659.975645 -916674.284243]]
prediction is:
 [[ 197196.08  209765.84 -868108.3 ]]


real location is

real location is:
 [[ 206569.809724  137977.905614 -882677.930296]]
prediction is:
 [[ 207716.    132805.64 -858889.56]]


real location is:
 [[ 206585.70139   136723.51578  -887276.845143]]
prediction is:
 [[ 202377.12  132722.2  -857234.56]]


real location is:
 [[ 206597.341293  135489.980685 -891008.082099]]
prediction is:
 [[ 205483.62  127843.42 -861013.25]]


real location is:
 [[ 206614.563497  134257.793902 -887685.402752]]
prediction is:
 [[ 202905.67  128319.89 -855889.9 ]]


real location is:
 [[ 206626.557093  133035.936559 -892519.92536 ]]
prediction is:
 [[ 202317.97  129269.2  -863524.44]]


real location is:
 [[ 206616.117724  131878.89494  -902644.566366]]
prediction is:
 [[ 200356.17   128168.266 -869558.1  ]]


real location is:
 [[ 206582.757457  130629.552576 -906336.41084 ]]
prediction is:
 [[ 200747.2    126942.414 -887328.94 ]]


real location is:
 [[ 206544.670925  129536.304132 -901635.778979]]
prediction is:
 [[ 208922.2   125201.47 -876792.1 ]]


real locat

real location is:
 [[  177035.644212     73488.8630697 -1331515.55028  ]]
prediction is:
 [[  173996.5     67411.71 -1299924.6 ]]


real location is:
 [[  176292.596638     72711.2504359 -1328161.91619  ]]
prediction is:
 [[  170388.03     64473.375 -1287751.5  ]]


real location is:
 [[  175513.793145     71925.1756545 -1326387.93735  ]]
prediction is:
 [[  174770.81    67920.3  -1269001.5 ]]


real location is:
 [[  174780.331952     71152.7856984 -1326541.40399  ]]
prediction is:
 [[  167668.2      62606.934 -1287076.2  ]]


real location is:
 [[  173991.137231     70348.9069408 -1322044.29443  ]]
prediction is:
 [[  167006.38    63974.51 -1273174.5 ]]


real location is:
 [[  173205.332523     69498.4382436 -1317898.18357  ]]
prediction is:
 [[  167116.53    58654.5  -1280293.2 ]]


real location is:
 [[  172378.102367    68576.860242 -1311937.92204 ]]
prediction is:
 [[  170374.73    61620.34 -1277645.6 ]]


real location is:
 [[  171611.545486     67742.1650381 -1313331.53211  ]]

real location is:
 [[  125953.50969      21862.1767313 -1359827.97882  ]]
prediction is:
 [[  122325.58     19300.209 -1324239.1  ]]


real location is:
 [[  125080.284861     21060.3387304 -1361123.39662  ]]
prediction is:
 [[  120062.23     23748.625 -1322402.8  ]]


real location is:
 [[  124291.261517     20331.5210734 -1361738.2948   ]]
prediction is:
 [[  122925.6      16896.031 -1331528.6  ]]


real location is:
 [[  123430.217215     19518.0401169 -1361756.92428  ]]
prediction is:
 [[  120469.76     15021.927 -1337207.2  ]]


real location is:
 [[  122603.041919     18729.5151211 -1361298.23096  ]]
prediction is:
 [[  121709.33     19460.129 -1325008.2  ]]


real location is:
 [[  121797.433791     17967.9512934 -1361473.93094  ]]
prediction is:
 [[  118553.62     16644.744 -1316365.   ]]


real location is:
 [[  120912.576241    17126.692143 -1361916.384   ]]
prediction is:
 [[  117898.75     12244.307 -1319775.9  ]]


real location is:
 [[  120043.57728      16309.3448323 -13

real location is:
 [[ 6.60934182e+04  1.54956470e+03 -1.77557710e+06]]
prediction is:
 [[ 6.4516512e+04  1.7088555e+03 -1.7169248e+06]]


real location is:
 [[ 6.50423900e+04  1.51532694e+03 -1.77592629e+06]]
prediction is:
 [[   64907.875      3551.5955 -1726461.1   ]]


real location is:
 [[ 6.39296333e+04  1.47422278e+03 -1.77677746e+06]]
prediction is:
 [[   66064.83       2579.6697 -1724242.2   ]]


real location is:
 [[ 6.28255238e+04  1.44523153e+03 -1.78309454e+06]]
prediction is:
 [[   61170.38       3775.1702 -1740702.4   ]]


real location is:
 [[ 6.16720831e+04  1.42603987e+03 -1.78176408e+06]]
prediction is:
 [[ 6.1378359e+04  6.7476947e+02 -1.7411559e+06]]


real location is:
 [[ 6.05392452e+04  1.39594842e+03 -1.77375515e+06]]
prediction is:
 [[   61073.477     2505.876 -1742452.1  ]]


real location is:
 [[ 5.93807250e+04  1.33258695e+03 -1.76649541e+06]]
prediction is:
 [[   61021.977      3031.4126 -1734459.5   ]]


real location is:
 [[ 5.83324298e+04  1.26236170e+03